### ISSUE TITLE
Any known issues with SQL 2019?

### ISSUE THREAD

**Issue by BrianLawton** [tediousjs/tedious#1003]
I know it's early given SQL 2019 just RTM'd this week, but I was looking for feedback on known issues using Tedious with it. As far as I can tell, there were no changes with respect to SQL 2019 supporting TDS 7.4 so I'm guessing this should be a relatively pain-free migration but I figured I'd float the question in case anyone has a head-start with their testing. Thanks!

**Comment by arthurschreiber** [comment]
I think you should be fine. 👍

I'll see if we can extend our CI coverage to include SQL Server 2019 builds.
