### ISSUE TITLE
Major performance degradation between versions 4.2.0 and 6

### ISSUE THREAD

**Issue by meelash** [tediousjs/tedious#1006]
Using the ms-sql library I noticed a major degradation in performance after they upgraded the tedious version from 4.2.0 in this commit: https://github.com/tediousjs/node-mssql/commit/b63526853e65ffeafc50e6e81bd335d68215ddf2

What I am seeing is that the same benchmark set of inserts to a database takes more than 4.5 times longer to run after that upgrade. (Some information about my performance test is available here: https://github.com/tediousjs/node-mssql/issues/939)

I am attempting to isolate and reproduce this using just the tedious library. So far, I am seeing a  performance hit of approximately the same scale using the benchmarks in tedious/benchmarks, so my guess would be that the issue is the same. I will continue to isolate the exact commit where the performance degrades.

EDIT: It doesn't appear the results I initially reported were related, I will continue investigating this and report back.

**Comment by IanChokS** [comment]
Hi @meelash, can you try to run your performance script against version 5.0.3 and see if it has the same latency time?

**Comment by MichaelSun90** [comment]
Hi  @meelash, I also just try to run the tests against 4.2.0 and 6.6.2(lastest), and I do not see a huge difference between these two performance vise.  There is a proximately average 3-4 ms difference between these two.  Please share any new findings from your side. Thanks :bow:

**Comment by meelash** [comment]
I've definitively identified the commit causing the performance degradation as this one:
https://github.com/tediousjs/tedious/commit/d949dd8fb40dc9e7dec2624ce63bde49158221fd

I am working now to reproduce in a benchmark test and will report back.

**Comment by IanChokS** [comment]
hi @meelash, any progress? :)

**Comment by IanChokS** [comment]
Closing for now, re-open if issue still persists
