### ISSUE TITLE
Database change and language change on SQL Profiler

### ISSUE THREAD

**Issue by mkxml** [tediousjs/tedious#101]
Hello.

I noticed that SQL Profiler throws warnings at database and language changes, that's not necessarily a problem but I want to know what you think about this.

My SQL profiler says that language is always being changed to 'us_english' and database is always being changed to the one I specified at the beginning. I did not changed the database but it prints out that warning nevertheless.

I'm curious about how Tedious handle database connections, does it use the database changed event to check if a connection succeeded or something like that?

The strange thing about SQL Server is that it puts these warnings under SQL_ERROR umbrella when looking at the SQL Profiler.

**Comment by aspaiva** [comment]
Is there any way to avoid showing it in SS profiler while tracking actions? Or do something to avoi the changing without reinstalling the server in the user language when is different from us_english?
