### ISSUE TITLE
exception_ring_buffer_recorded

### ISSUE THREAD

**Issue by KeepITSimpleSolutions** [tediousjs/tedious#1034]
![Capture](https://user-images.githubusercontent.com/13180229/71897773-d1ccd800-3157-11ea-891b-9bc0e4976ebb.PNG)
Getting thousands exception_ring_buffer_recorded...

How to capture...

CREATE EVENT SESSION [ExceptionRingBufferEvents] ON SERVER 
ADD EVENT sqlos.exception_ring_buffer_recorded(
    ACTION(sqlserver.sql_text))
ADD TARGET package0.ring_buffer(SET max_memory=(4096))
WITH (MAX_MEMORY=4096 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=30 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=NONE,TRACK_CAUSALITY=OFF,STARTUP_STATE=ON)
GO

Error Number 3617
Severity 25
SQL Text

set textsize 2147483647
set quoted_identifier on
set arithabort off
set numeric_roundabort off
set ansi_warnings on
set ansi_padding on
set ansi_nulls on
set ansi_null_dflt_on on
set concat_null_yields_null on
set cursor_close_on_commit off
set implicit_transactions off
set language us_english
set dateformat mdy
set datefirst 7

**Comment by KeepITSimpleSolutions** [comment]
The severity of the exception 3617 is 25. Severity levels from 20 through 25 indicate system problems. 
These are fatal errors, which mean that the process (the program code that accomplishes the task specified in the statement) is no longer running. 
The client connection to SQL Server closes.

**Comment by arthurschreiber** [comment]
@KeepITSimpleSolutions Does this only happen if you connect using `tedious`? What about connections made via SQL Server Management Studio?

**Comment by IanChokS** [comment]
@KeepITSimpleSolutions Is this issue still persisting? Closing for now, feel free to re-open if needed.
