### ISSUE TITLE
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds

### ISSUE THREAD

**Issue by arpitgupta2405** [tediousjs/tedious#1035]
I'm getting the "RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds" in my code. The probable cause of this error is that I'm trying to connect MSSQL using port 3306 instead of 1433.

But just want to know, if there is any way that I can catch this error in Backend because port number is something that the end user gives and I really don't want my server to break because of negligence of end user.

Any lead will be appreciated.

**Comment by arthurschreiber** [comment]
Are you sure you're connecting to MS SQL Server, and not MySQL? I'm asking because port 3306 is the one used by MySQL.

Anyway, tedious does not care about which port your SQL Server is listening to, so I don't think that's the issue here. 🤔

**Comment by arpitgupta2405** [comment]
Yes, I'm pretty sure I'm trying to connect to the MS SQL server only.

**Comment by arthurschreiber** [comment]
Can you provide the full stacktrace for the error?

**Comment by arpitgupta2405** [comment]
Please find the stacktrace below:

Uncaught RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
      at boundsError (internal/buffer.js:51:11)
      at Buffer.readUInt8 (internal/buffer.js:141:5)
      at Packet.isLast (node_modules/tedious/lib/packet.js:116:29)
      at ReadablePacketStream.<anonymous> (node_modules/tedious/lib/message-io.js:101:18)
      at ReadablePacketStream.EventEmitter.emit (domain.js:441:20)
      at addChunk (node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:291:12)
      at readableAddChunk (node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:278:11)
      at ReadablePacketStream.Readable.push (node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:245:10)
      at ReadablePacketStream.Transform.push (node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:148:32)
      at ReadablePacketStream._transform (node_modules/tedious/lib/message-io.js:70:16)
      at ReadablePacketStream.Transform._read (node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at ReadablePacketStream.Transform._write (node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:172:83)
      at doWrite (node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:428:64)
      at writeOrBuffer (node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:417:5)
      at ReadablePacketStream.Writable.write (node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:334:11)
      at Socket.ondata (_stream_readable.js:667:20)
      at Socket.EventEmitter.emit (domain.js:441:20)
      at addChunk (_stream_readable.js:284:12)
      at readableAddChunk (_stream_readable.js:265:11)
      at Socket.Readable.push (_stream_readable.js:220:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
      at TCP.onread (node_modules/async-listener/glue.js:188:31)

**Comment by arpitgupta2405** [comment]
Is there any update on this?

**Comment by IanChokS** [comment]
@arpitgupta2405 Do you get the same error if you run the same script on port 1433?

**Comment by arpitgupta2405** [comment]
No, I'm only getting the error if I run script on port 3306.

Since my script is totally dependent on how the end user configures, so I need a way to properly handle the error.

**Comment by IanChokS** [comment]
Hmm do you have a repro script? I don't understand how writing to buffers change based on port difference

**Comment by arpitgupta2405** [comment]
Sorry for the delay in response.

I'll tell you what I think could be the reason behind the issue, the Mssql server is up on port say 1433 but in the code if I gave port 3306 for connecting then this issue is happening.

The only problem with my code is, the port number is something that the end user enters and it is crashing my server.

I have also upgraded tedious from 2.2.3 to 8.0.1 and still facing the issue.

Could you please try the above thing and see if it can be reproduced.

**Comment by arpitgupta2405** [comment]
Or is there any other way to reproduce this issue?

**Comment by arpitgupta2405** [comment]
I encountered this issue by my server logs and reproduced this after reading [#853 ](https://github.com/tediousjs/tedious/issues/853)

**Comment by IanChokS** [comment]
@arpitgupta2405 do you show your config?

**Comment by arpitgupta2405** [comment]
connectionConfig = {
  authentication: { 
    type: 'default',
    options: {
      userName: '<my user name>',
      password: '<my password>'
    }
  },
  server: '<sever host>',
  options: {
    database: '<db>',
    encrypt: true,
    port: 3306,
    packetSize: 32768
  }
}

**Comment by IanChokS** [comment]
Do you also have a repro script I can use on my end to see if I can reproduce the error?

**Comment by arpitgupta2405** [comment]
I don't have any script as such, the code is the part of my application and I'm not authorised to share the code snippet.

**Comment by IanChokS** [comment]
The only thing I can think of for now is the packet size. As stated in the our docs:
`options.packetSize
The size of TDS packets (subject to negotiation with the server). Should be a power of 2. (default: 4096).`

Maybe try a different packet size such as 32761? Beyond that I'm not too sure 🤔

**Comment by arpitgupta2405** [comment]
I have tried with the default packetSize as well and it didn't help. Our application requires packetSize to be 32768.

**Comment by arpitgupta2405** [comment]
Below is the code pattern that we are using in our application:

connectionConfig = {
  authentication: { 
    type: 'default',
    options: {
      userName: '<my user name>',
      password: '<my password>'
    }
  },
  server: '<sever host>',
  options: {
    database: '<db>',
    encrypt: true,
    port: 3306,
    packetSize: 32768
  }
}

const connection = new Connection(connectionConfig)

var query = connection.query({sql: 'some query'})

query.on('error', function (err) {
    // handle error
  })
  .on('result', function (result) {
    // save the result
  })
  .on('end', function () {
    // console.log('\n\t\t+++++++++++End called \n')
  })

**Comment by IanChokS** [comment]
What library are you using for `new Connection`? Tedious doesn't have a `.query` method for the Connection class

**Comment by arpitgupta2405** [comment]
const { Request, Connection } = require('tedious')

**Comment by arpitgupta2405** [comment]
I'm sorry, I just gave you a wrong code. I messed up. Apologies.

**Comment by arpitgupta2405** [comment]
Please ignore the previous code snippet (I have deleted that ).

Below is the code pattern we use:

const { Request, Connection } = require('tedious')

const connectionConfig = {
  authentication: { 
    type: 'default',
    options: {
      userName: '<my user name>',
      password: '<my password>'
    }
  },
  server: '<sever host>',
  options: {
    database: '<db>',
    encrypt: true,
    port: 3306,
    packetSize: 32768
  }
}

const connection = new Connection(connectionConfig)

function rowHandler () {
  // save the result
}

function errorHandler () {
  // handle the error
}

let queryToRun = 'sql query'

let request = new Request(queryToRun, (err, rowCount) => {
  if (err) {
    // handle error
  }
  // cleaning up the connection
})

request.on('error', errorHandler)

request.on('row', rowHandler)

connection.on('error', errorHandler)

connection.execSql(request)

**Comment by arpitgupta2405** [comment]
tedious version: 8.0.1

**Comment by arpitgupta2405** [comment]
Is there any update, on this?

**Comment by MichaelSun90** [comment]
Hi @arpitgupta2405 , one thing that I noticed from your example above is, the connection.execSql(request) should be only called within a call back for handling a 'connect' event. Otherwise, the program will try to execute the request whenever the process reaches the line that calles the exeSql method. At that time, the connection may not yet be successfully conducted. 

``` nodejs

const connected =()=>{
    let request = new Request(queryToRun, (err, rowCount) => {
        if (err) {
            // handle error
        }
            // cleaning up the connection
        })

    request.on('error', errorHandler)
    request.on('row', rowHandler)
    connection.execSql(request)
}
connection.on('connect',connected)

``` 

I am not sure this is relevant to the error, and I will keep trying to reproduce the error.

**Comment by MichaelSun90** [comment]
HI @arpitgupta2405, Can you also try to enable the debug log for connection, so we can have some additional details on the transaction and packets? That will be very helpful for the debugging process as well. 

Under connectionConfig.options, add a key called 
``` nodejs
debug:{
     packet: true,
     data: true,
     payload: true,
     token: true,
}
```
Then add a handler for this event: 
``` nodejs
connection.on('debug', (message)=>{console.log(message)})
```

**Comment by arpitgupta2405** [comment]
Hi @MichaelSun90 , I'll try the above mentioned steps and revert back to you. Thanks for your reply.

**Comment by arpitgupta2405** [comment]
Hi @MichaelSun90 , the above changes does not seem to help. Still getting the same error.

**Comment by arpitgupta2405** [comment]
And there is no log getting printed after adding the debug key and listener.

**Comment by MichaelSun90** [comment]
Hi @arpitgupta2405 ,

I will provide the script that I am using, see if this works for you. 

``` nodejs
const config= {
    server: "server host",
    authentication: {
        type: "default",
        options: {
            userName: "user name",
            password: "password"
        }
    },
    options: {
        database: "db bame",
        encrypt: true,
        port: 3306,
        packetSize: 3000,
        debug:{
            packet: true,
            data: true,
            payload: true,
            token: true,
       }
    }
}
    
const connection = new Connection(config)

const handler = (input)=>{
    {console.log(input)}
}
const connected =(error)=>{
    if(error){
        console.log(err)
    }
    let request = new Request('select * from MyTable', (err, rowCount) => {
        if (err) {
            // handle error
        }
        // cleaning up the connection
        })

    request.on('error',handler)
    request.on('row', handler)
    connection.execSql(request)
    
}

connection.on('error', handler)
connection.on('debug', handler)
connection.on('connect',connected)

```

**Comment by arpitgupta2405** [comment]
Hi @MichaelSun90 , I used the your script pattern to write a test case (in mocha) and it generated the following log:

(the bold lines are printed by debug handle)

2020-03-13T09:25:01.015Z - info:       Simple/Test queries
**2020-03-13T09:25:04.275Z - info: connected to <my-db-name>:3306**
**2020-03-13T09:25:04.982Z - info: State change: Connecting -> SentPrelogin**
2020-03-13T09:25:04.988Z - info:         1) should get some rows
2020-03-13T09:25:04.989Z - info: 
2020-03-13T09:25:04.993Z - info: 
2020-03-13T09:25:04.993Z - info:   0 passing (13s)
2020-03-13T09:25:04.993Z - info:   1 failing
2020-03-13T09:25:04.994Z - info: 
2020-03-13T09:25:04.994Z - info:   1) MSSQL
       Export
         Simple/Test queries
           should get some rows:
     Uncaught RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
      at boundsError (internal/buffer.js:51:11)
      at Buffer.readUInt8 (internal/buffer.js:141:5)
      at Packet.type (node_modules/tedious/lib/packet.js:143:24)
      at IncomingMessageStream.processBufferedData (node_modules/tedious/lib/incoming-message-stream.js:72:26)
      at IncomingMessageStream._transform (node_modules/tedious/lib/incoming-message-stream.js:107:10)
      at IncomingMessageStream.Transform._read (node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:177:10)
      at IncomingMessageStream.Transform._write (node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:164:83)
      at doWrite (node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:409:139)
      at writeOrBuffer (node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:398:5)
      at IncomingMessageStream.Writable.write (node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:307:11)
      at Socket.ondata (_stream_readable.js:667:20)
      at Socket.EventEmitter.emit (domain.js:441:20)
      at addChunk (_stream_readable.js:284:12)
      at readableAddChunk (_stream_readable.js:265:11)
      at Socket.Readable.push (_stream_readable.js:220:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
      at TCP.onread (node_modules/async-listener/glue.js:188:31)

2020-03-13T09:25:04.994Z - info: 
2020-03-13T09:25:04.994Z - info: 
**2020-03-13T09:25:19.056Z - info: Connection lost - read ECONNRESET**
Waiting for the debugger to disconnect...

**Comment by arpitgupta2405** [comment]
Is there any update, on this?

**Comment by IanChokS** [comment]
@arpitgupta2405 Sorry we're still trying to reproduce the issue

**Comment by MichaelSun90** [comment]
Hi @arpitgupta2405, I have tried to reproduce your behavior with the same settings. but I still cannot get the same error. The closest that I get is a buffer index out of range error. I know that you said that you are trying to connect to a MySQL server, but since the error related to a port number that dedicated to MySQL server by default, so I set up a MySQL driver on my machine. Then, I try to form a connection through port  3306. This is where I got the buffer index out of range error. 

Can you help me triple check the status of the port? Just to make sure that we can get rid of this factor entirely. Here is a PowerShell script that you can use for this:  Get-Process -Id (Get-NetTCPConnection -LocalPort 3306).OwningProcess.

**Comment by arpitgupta2405** [comment]
Hi @MichaelSun90 , sorry for the delayed response. I have Mysql running on the port 3306.

Yeah, that could be the possible reason for this error.

**Comment by arpitgupta2405** [comment]
It would be good if tedious provides any way to check that beforehand, as my application takes the connection config from the end user and if the end user gives an incorrect port number (like in this case) my server crashes instantly.

**Comment by IanChokS** [comment]
As @MichaelSun90 mentioned, `Tedious` driver is to be used with Microsoft's SQL Server only, and not MySQL, as these two servers use different protocols. Specifically, MSSQL uses the `Tabular Data Stream` protocol which this driver is built on, whereas MySQL does not. It's also clarified in the description in this project's README page: https://github.com/tediousjs/tedious.

**Comment by arpitgupta2405** [comment]
Hi @IanChokS , I guess you haven't read my issue clearly. 

I'm trying to connect to MSSQL Server only. But if I specify the port number as 3306, I get an uncaught RangeError. How to I catch that error?
