### ISSUE TITLE
SQLServer 2019 socket hang up errors

### ISSUE THREAD

**Issue by ErikJansenIRefact** [tediousjs/tedious#1043]
We know there is no formal support for SQLServer 2019. Nevertheless we are testing with a SQLServer 2019 docker image.

We now often get socket hang up errors.
Any suggestions/ideas?

Kind regards,
Erik

**Comment by arthurschreiber** [comment]
> We know there is no formal support for SQLServer 2019

SQL Server 2019 should be supported just fine by `tedious` - we just don't support all features (like Always Encrypted). But if you don't rely on one of these features, everything should work just fine. 🤔 

> We now often get socket hang up errors.

Did you also test with other versions of the SQL Server? Do you see the same hangups there? Do you see anything weird in the SQL Server log output? Is there any pattern to these lockups?

**Comment by ErikJansenIRefact** [comment]
We've tested with SQLServer 2017. Works fine. We do not use any specific features.
I did not yet check the SQL Server log output.

We use the latest image (updated just recently) from Microsoft. In this CU Microsoft mentions a fix on TDS (something with buffers on V1 and V2).

**Comment by arthurschreiber** [comment]
I ran out unit and integration test against the latest SQLServer 2019 docker container release, and except for one failure caused by a slight change in an error message, the tests all pass just fine.

Could you describe in more detail what sort of testing you are doing? Is there some reliable way to reproduce these disconnects? Are you connecting with encryption enabled or disabled?

I’ll update our CI configuration to run tests against the latest container version (we‘re running against 2017 right now), but I’m at a loss why you’re seeing these issues.

Are you using a connection pool library or node-mssql?

**Comment by ErikJansenIRefact** [comment]
We use the connection pool. But this seems to work fine with the SQL Server 2017 image.
We have around 30 connections in the pool and are executing quite some load with different connections.
We do not use encryption.
Will look into the logs and get back to you.

**Comment by ErikJansenIRefact** [comment]
The error log reports access violations and the used session is killed. We anticipate on errors. But it seems that the connection is not removed from the connection pool? We need to investigate further.

So it seems that SQLServer 2019 docker image has some serious bugs. And probably socket errors do not result in removing the connection from the connection pool.

**Comment by ErikJansenIRefact** [comment]
For some reason the connections same to be unstable. That's all we know for now.

**Comment by ErikJansenIRefact** [comment]
Installed SQLServer 2019, developer edition on Windows. Executed the same tests. Same errors.
So it doesn't seem to be related to the Docker Linux edition.

Out setup:
1. We open 30 connections to the database with tedious-connection-pool package.
2. We start scheduling work to the database (it's kind of ETL), get a connection from the pool, generate a SQL statement, create a request, execute the request, return the connection to the pool. After a while we are getting errors from the database.

When we execute the generated SQL directly (for example in SSMS) I cannot reproduce the errors.
So it's hard to find out what's going on exactly.

**Comment by ErikJansenIRefact** [comment]
Hi Arthur,

We know now for sure the issue is caused by SQLServer. Both the tedious-connection-pool and tedious@next work as expected. So no issues connecting to SQLServer 2019.

I will close this issues.
Thanks for your help.

Kind regards.

**Comment by arthurschreiber** [comment]
> We know now for sure the issue is caused by SQLServer. Both the tedious-connection-pool and tedious@next work as expected. So no issues connecting to SQLServer 2019.

Did you reach out to Microsoft to get this confirmed? Any other information you could share around this issue, in case any other users reach out to us with similar symptoms? Thank you! 🙇

**Comment by ErikJansenIRefact** [comment]
In a single transaction:
1. Insert rows into a table with a TABLOCK hint.
2. In a next step join this table with another table and select some data (this will trigger gathering stats).
3. This sometimes results in an access violation causing a severe error. The socket is closed.

If you gather statistics between step 1 and 2 no access violations anymore. So for some reason and only occasionally the combination of TABLOCK, a single transaction and auto gathering of stats will result in an access violation.

If you remove the transaction at the beginning also no access violation.
It took us 2 days to figure out the root cause of this problem. 

PS: it's not so easy to report a bug to Microsoft. So we need to figure out how to get in touch.

**Comment by David-Engel** [comment]
@ErikJansenIRefact If you have MS Support, you can go through them to report the bug. You can also submit the bug via https://aka.ms/sqlfeedback. If you have a simple T-SQL repro script that can be run via SSMS or sqlcmd to produce the AV, that's probably ideal. I'm curious exactly what the repro looks like.
