### ISSUE TITLE
Clearing parameters ? Or assigning values in a loop

### ISSUE THREAD

**Issue by cAstraea** [tediousjs/tedious#1056]
Is there a method for clearing the parameters in the loop ? 

I tried something like this but couldn't figure it out

```
                   requestSQLInsertWorklog.addParameter('WorklogID', TYPES.BigInt);

                   req.worklogs[0].forEach(wlog => {  
                       console.log(requestSQLInsertWorklog)  
                                           
                    //make update ... 
                   requestSQLInsertWorklog.parametersByName[WorklogID].value =   wlog.id;
```
------------

**Comment by MichaelSun90** [comment]
Hi @cAstraea, I am assuming you are trying to send queries with parameters against multiple value sets for this parameter? I think you can try to prepare a statement for that purpose.  There is a link to the documentation for that function: http://tediousjs.github.io/tedious/api-connection.html#function_prepare. This function needs to be combined with the execute function: http://tediousjs.github.io/tedious/api-connection.html#function_execute. 

with these two functions, you can prepare function once, and execute the function with multiple values set for that parameter.  
 
There is an example in the file called prepared.js under this PR: https://github.com/tediousjs/tedious/pull/1032/files

**Comment by cAstraea** [comment]
Hmm it's not entirely clear :(

My end goal is just to do a simple insert inside a loop. Tried different options, closest I got was using tedious-connection-pool package but it opens too many connections for the azure plan and couldn't figure out how to close them. 
Been trying to make a simple example to work something like this. Also found some information about something called bulk inserting but couldn't find an example for it.

```
const {
    Connection,
    Request,
    TYPES
} = require("tedious");

// Create connection to database
const config = {
    authentication: {
        options: {
            userName: "", // update me
            password: "" // update me
        },
        type: "default"
    },
    server: "testdatabase.database.windows.net", // update me
    options: {
        database: "worklog", //update me
        encrypt: true,
        log: true
    },
    log: true
};

var connection = new Connection(config);
connection.on('connect', function(err) {
    if (err) {
        console.log(err);
    } else {
        for (let i = 0; i < 50; i++) {
            let InsQuery = `
    INSERT dbo.Worklogs(
        WorkLogID
       ,ReqID
       ,WorklogOwner
       ,End_time
       ,Descriere
       ,Created_by
       ,Recorded_time
       ,time_spent_hours
       ,time_spent_minutes
       ,Start_time
     ) VALUES (
        ${i}
       ,738000009683239
       ,'Razvan'
       ,1582273500107
       ,'TEST'
       ,'razvan'
       ,738000009683239
       ,1 
       ,15 
       ,738000009683239          
     )`;
            request = new Request(InsQuery, function(err, rowCount) {
                if (err) {
                    console.log(err);
                } else {
                    console.log('Insert complete.');
                }

                connection.close();
            });


            connection.execSql(request, (err, test) => {
                if (err) throw err

                // connection.close();

                // var connection = new Connection(config);

            });

        }
    }
});
```

**Comment by MichaelSun90** [comment]
Hi @cAstraea, there is a bulk load example in the Tedious driver under the example folder. 
There is a link to that folder. https://github.com/tediousjs/tedious/blob/master/examples/bulkLoad-sample.js
There is a link to the Tedious bulk load feature documentation that you can also check: http://tediousjs.github.io/tedious/bulk-load.html. This may help explain the exmaple better.

**Comment by cAstraea** [comment]
Thanks this is what I'm looking for
