### ISSUE TITLE
Export the TypeScript declaration

### ISSUE THREAD

**Issue by fxalgrain** [tediousjs/tedious#1067]
Hi, 

I m starting a new project written in TypeScript, and, of course, I m using Tedious for SQL queries. 

VS Code has added for me   `"@types/tedious": "4.0.0" ` in my package.json
TypeScript compilator is happy but I m not comfortable to use an outdated type definition

I just take a look into this repository and I discover you have to rewrite it with TypeScrypt. So looks weird for me that we need an external dependency to get type definition. 
A quick search gives me a Medium article that illustrates how to do it. Adding `declaration: true` into the tsconfig.json and `types: "dist/index.d.ts" ` into the package.json should solve the issue. 

Is it possible to do that for the next release?

PS: I m a rookie with TypeScript, sorry if I'm wrong

**Comment by MichaelSun90** [comment]
Hi @fxalgrain, we have definitely planned to release the types as part of the tedious package in the future, so there won’t be a need to install anything else. However, there are still some tricks that we needed within the driver before we actually can do that. 
The one that you currently trying to use is actually a type definition from a public contributor, so you may need to wait a bit to actually use Tedious as a typed library.

**Comment by fxalgrain** [comment]
Thanks @MichaelSun90 for your answer. 

I will wait :)

**Comment by hosseinmd** [comment]
> Hi @fxalgrain, we have definitely planned to release the types as part of the tedious package in the future, so there won’t be a need to install anything else. However, there are still some tricks that we needed within the driver before we actually can do that. The one that you currently trying to use is actually a type definition from a public contributor, so you may need to wait a bit to actually use Tedious as a typed library.

Has anything been done about this? This is so simple to do.

**Comment by MichaelSun90** [comment]
Hi @hosseinmd , @fxalgrain , I think for the latest version of tedious, it does not depend on the public types from @types/tedious": "4.0.0" anymore. Can you guys give it a try, and see if that is the case? 

@arthurschreiber , I think tedious do not count on any external types now, right?

**Comment by fxalgrain** [comment]
Hi @hosseinmd @MichaelSun90 

I opened this ticket 2 years ago ^^. I m not an active user of tedious anymore.

But a quick look on master show me that now tedious has been written in Typescript. The NPMJS page of the package displays that @types/tedious still required. 
It means that the package build does not include the types definition and/or the type property of the package.json is not good.

With TypeScrip already in place, it will be more easy now

**Comment by MichaelSun90** [comment]
Thanks for the feed back. Yes, we have notice the npm page have the type definition mentioned as required as well. However, I remember I have confirm this should not be the case, not sure whey npm page still record it like that. We have discuses this under another issue related to this.  Will try to figure out this , and see if we can do anything for the npm page.

**Comment by IlCallo** [comment]
I can confirm types aren't exported by this package
You have not set any `types` field in the package.json
At a glance, I could not locate where you generate types, so I guess you don't
Usually types are generated via `tsc --declaration`, but you're building the project using Babel, so types are just not produced

**Comment by AndreyBelym** [comment]
I confirm that there are no type definitions in `tedious@16.1.0`.
