### ISSUE TITLE
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds

### ISSUE THREAD

**Issue by arpitgupta2405** [tediousjs/tedious#1074]
Hi @IanChokS , I guess you haven't read my issue clearly (https://github.com/tediousjs/tedious/issues/1035).

I'm trying to connect to MSSQL Server only. But if I specify the port number as 3306, I get an uncaught RangeError. How do I catch that error?

**Comment by IanChokS** [comment]
@arpitgupta2405 You mentioned that 

> I have Mysql running on the port 3306

That's why I closed the issue, because Tedious isn't built for MySQL Server.

**Comment by arpitgupta2405** [comment]
@IanChokS , the problem is we take the connection config from the end user and there are times when end user specifies port as 3306 by mistake for the mssql connection, so in that case my server breaks.

So it will be better if you can add try and catch for this error, so it becomes easy for me to handle this case and my server doesn't break.

Let me know if there is still some confusion.

**Comment by IanChokS** [comment]
Have you implemented error handling in your application to catch errors that tedious throws? 

I think the error is being thrown when establishing a `new connection(config)` in tedious. Maybe try to do a `try catch` around that to see if your able to catch it?

**Comment by arpitgupta2405** [comment]
Hi @IanChokS , I have all the error handlers in place for tedious and even tried using try and catch for new connection(config) but none of those worked.

**Comment by IanChokS** [comment]
Can you show what error handlers you have for tedious?

**Comment by arpitgupta2405** [comment]
const { Request, Connection } = require('tedious')

const connectionConfig = {
  authentication: { 
    type: 'default',
    options: {
      userName: '<my user name>',
      password: '<my password>'
    }
  },
  server: '<sever host>',
  options: {
    database: '<db>',
    encrypt: true,
    port: 3306,
    packetSize: 32768
  }
}

const connection = new Connection(connectionConfig)

function rowHandler () {
  // save the result
}

function errorHandler () {
  // handle the error
}

let queryToRun = 'sql query'

let request = new Request(queryToRun, (err, rowCount) => {
  if (err) {
    // handle error
  }
  // cleaning up the connection
})

request.on('error', errorHandler)

request.on('row', rowHandler)

connection.on('error', errorHandler)

connection.execSql(request)

**Comment by arpitgupta2405** [comment]
Is there any update?

**Comment by arpitgupta2405** [comment]
@IanChokS , is there nay update on this?

**Comment by IanChokS** [comment]
Sorry I don't really know how to solve this. The error handler example you've provided is too vague, and I am unable to reproduce the issue on my end.

**Comment by AndiD82** [comment]
I've the same issue. My app supports both, mssql and mysql databases, too. If the user selects the mssql connection but defines the address of the mysql database as target, the crash occurs.

Here the full stack trace of the error:
```


There's no chance to get the error catched during connect as the app crashes before.

**Comment by arpitgupta2405** [comment]
Hi @IanChokS , I tried the same thing with the database hosted in azure and the result is same.

Could you please give us a way to catch this error?

**Comment by IanChokS** [comment]
Ah thanks for the repo script, it makes things a bit clearer now. I'll see if I can find a way to catch this error.

**Comment by arpitgupta2405** [comment]
Hi @IanChokS , I did some research on the root cause of this issue. I have raised 1 PR as a fix for this issue. Please have a look on it and let me know if this is fine.

https://github.com/tediousjs/tedious/pull/1101

**Comment by IanChokS** [comment]
@AndiD82 @arpitgupta2405 Can you check if PR #1102 will fix your issue? I think you should be able to catch the error now in `connection.on('error', ...)` if tedious tries to connect to MySql server.

**Comment by AndiD82** [comment]
@IanChokS Thanks for that fix! I tested it and it seems to work. The app doesn't crash anymore and I get the new ConnectionError("Unable to process incoming packet") in the error event handler.
