### ISSUE TITLE
 getaddrinfo ENOTFOUND error while connecting to sql database

### ISSUE THREAD

**Issue by 1ds14te050manoj** [tediousjs/tedious#1079]
Hey all;

Trying to connect to my ms sql server .
But I am getting error.

Details below. Would appreciate any help. Thanks a lot.
"Configurations": {
    "Development": 
                        "Data Source=VD101836.ds.dev.accenture.com:1433;
                          User Id=*********userID;
                          Password=********password;
                         Initial Catalog=******initial db;
                           Integrated Security=True"
}
FYI: This works via SQL Server management studio 2014. I used same config as mentioned below.

**Error**
 exception is {"stack":"ConnectionError: Failed to connect to xxxxabcdcom:1433:1433 - getaddrinfo ENOTFOUND xxxxabcd.com:1433\\n    at Connection.tedious.once.err (C:\\\\Users\\\\manoj\\\\Downloads\\\\My Tasks\\\\Secret manager retrieval\\\\People IDOC\\\\node_modules\\\\mssql\\\\lib\\\\tedious.js:244:17)\\n    at Object.onceWrapper (events.js:286:20)\\n    at Connection.emit (events.js:198:13)\\n    at Connection.EventEmitter.emit (domain.js:448:20)\\n    at Connection.socketError (C:\\\\Users\\\\manoj\\\\Downloads\\\\My Tasks\\\\Secret manager retrieval\\\\People IDOC\\\\node_modules\\\\mssql\\\\node_modules\\\\tedious\\\\lib\\\\connection.js:1095:12)\\n    at Connector.execute (C:\\\\Users\\\\manoj\\\\Downloads\\\\My Tasks\\\\Secret manager retrieval\\\\People IDOC\\\\node_modules\\\\mssql\\\\node_modules\\\\tedious\\\\lib\\\\connection.js:961:21)\\n    at GetAddrInfoReqWrap.dns.lookup [as callback] (C:\\\\Users\\\\manoj\\\\Downloads\\\\My Tasks\\\\Secret manager retrieval\\\\People IDOC\\\\node_modules\\\\mssql\\\\node_modules\\\\tedious\\\\lib\\\\connector.js:48:16)\\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:68:17)","message":"Failed to connect to xxxxabcd.com:1433:1433 - getaddrinfo ENOTFOUND xxxxabcd.com:1433","code":"ESOCKET","originalError":{"stack":"ConnectionError: Failed to connect to xxxxabcd.com:1433:1433 - getaddrinfo ENOTFOUND xxxxabcd.com:1433\\n    at ConnectionError (C:\\\\Users\\\\manoj\\\\Downloads\\\\My Tasks\\\\Secret manager retrieval\\\\People IDOC\\\\node_modules\\\\mssql\\\\node_modules\\\\tedious\\\\lib\\\\errors.js:13:12)\\n    at Connection.socketError (C:\\\\Users\\\\manoj\\\\Downloads\\\\My Tasks\\\\Secret manager retrieval\\\\People IDOC\\\\node_modules\\\\mssql\\\\node_modules\\\\tedious\\\\lib\\\\connection.js:1095:28)\\n    at Connector.execute (C:\\\\Users\\\\manoj\\\\Downloads\\\\My Tasks\\\\Secret manager retrieval\\\\People IDOC\\\\node_modules\\\\mssql\\\\node_modules\\\\tedious\\\\lib\\\\connection.js:961:21)\\n    at GetAddrInfoReqWrap.dns.lookup [as callback] (C:\\\\Users\\\\manoj\\\\Downloads\\\\My Tasks\\\\Secret manager retrieval\\\\People IDOC\\\\node_modules\\\\mssql\\\\node_modules\\\\tedious\\\\lib\\\\connector.js:48:16)\\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:68:17)","message":"Failed to connect to xxxxabcd.com:1433:1433 - 
getaddrinfo ENOTFOUND xxxxabcd.com:1433","code":"ESOCKET","name":"ConnectionError"},"name":"ConnectionError"}',

**Comment by arthurschreiber** [comment]
The server name `xxxxabcdcom:1433` is not valid - the server name can not contain the port. You should use just `xxxxabcdcom` as the server name.

**Comment by ctan66** [comment]
> Hey @1ds14te050manoj 👋
> 
> The server name `xxxxabcdcom:1433` is not valid - the server name can not contain the port. You should use just `xxxxabcdcom` as the server name.

how to connect with custom port no instead of the 1433???

**Comment by IanChokS** [comment]
Hi @ctan66,

You can specify the port number in the configuration options like so:

```js
var config = {
  server: 'xxxxabcdcom',
  authentication: {
    type: 'default',
    options: {
      userName: 'test',
      password: 'test'
    }
  },
  options: {
    port: 1433 // Default Port
  }
};
```

You can find more configuration options in our [documentation page](https://tediousjs.github.io/tedious/api-connection.html). Hope this helps!
