### ISSUE TITLE
Hostname/IP does not match certificates when trustServerCertificate=false

### ISSUE THREAD

**Issue by heyjared** [tediousjs/tedious#1081]
As per the recent deprecation notice introduced in #1029, I have made the change to explicitly set this to false. However, when attempting to connect to an Azure SQL Server in an Elastic Pool, tedious reports the following error:

`HostnameIP does not match certificates altnames Host <redacted>.database.windows.net is not in the certs altnames <redacted>.worker.database.windows.net <redacted>.worker.database.windows.net <redacted>.worker.database.windows.net <redacted>.worker.database.windows.net <redacted>.worker.database.windows.net`

The connection string recommended by the Azure portal includes this option which is missing from the available options in connection options in tedious.

`hostNameInCertificate=*.database.windows.net`

**Comment by arthurschreiber** [comment]
@heyjared 👋 

Thanks for letting us know about this!

I think this is an issue with the re-routing code. I think Elastic Pools work by re-routing the connection from the initial server (`*.database.windows.net`) to target hosts (`*.worker.database.windows.net`), but we don't correctly set the target hosts as the expected host name for the TLS connection, which in turn causes the issue you're seeing.

A fix should not be too hard to do, I'll see if I can find some time to fix this!

**Comment by Sebbish** [comment]
I just ran into this issue with Azure SQL not running elastic pool after making the same change. Changing server connection policy from redirect to proxy fixed it, but is slower. The altnames I got was workers as well.

**Comment by arthurschreiber** [comment]
https://github.com/tediousjs/tedious/pull/1116 is running into the same issue. The problem is that when we follow a server redirect, we still expect the initial server name when performing the TLS connection, which then fails, as this does not match the hostname that the redirect points at.

The fix should be straightforward. I'll open a PR soon. 🙇‍♂️

**Comment by clshortfuse** [comment]
I'm on v9.2.1 and I still have to force `trustServerCertificate: true`. The documentation still wrong, it seems.

Without the option set, I get: `unable to get local issuer certificate`, but enabled it works.
