### ISSUE TITLE
New request after callback

### ISSUE THREAD

**Issue by nkrug** [tediousjs/tedious#1082]
Hi,
im trying to send multiple requests reusing the same connection. The first request works fine and the correct data is returned. But after the callback a second request is not processed. There is no error message. I guess I have to reset the connection or something like that.

``` 
let getOkForCurrentHour = (sTime, eTime, callback) => {

  let result
 
  //console.log("here we go!");
  connection.on("connect", function(err) {
    if (err) {
      console.log("Error:", err);
    }
    request = new Request(`select count(*) From [database] where chktime >= @startT and chktime < @endT`, function(err) {
      if (err) {
        console.log(err);
      }
    });
    request.addParameter('startT',TYPES.DateTime, sTime)
    request.addParameter('endT',TYPES.DateTime, eTime)
   
    request.on("row", function(columns) {   
      result = columns[0].value     
    });

    request.on("doneInProc", (rowCount, more) => {
      console.log(callback)
      callback(result)
      result = ""
    });
    connection.execSql(request);    
  });
  */
};
```

I know that it is not possible to send a new request before the previous is finished. If I try to do that I get an error, that only one connection is allowed. I only call the function after "doneInProc" is triggering.

**Comment by IanChokS** [comment]
Hi @nkrug, this is because you're adding the parameter to the request **in** the request callback, as well as running `connection.execSql` inside the `request.on('doneInProc')` call back. It should instead be on the outside:

```js
let getOkForCurrentHour = (sTime, eTime, callback) => {

  let result

  //console.log("here we go!");
  connection.on("connect", function (err) {
    if (err) {
      console.log("Error:", err);
    }
    request = new Request(`select count(*) From [database] where chktime >= @startT and chktime < @endT`, function (err) {
      if (err) {
        console.log(err);
      }
      //Done call back
    });
  });

  request.addParameter('startT', TYPES.DateTime, sTime)
  request.addParameter('endT', TYPES.DateTime, eTime)

  request.on("row", function (columns) {
    result = columns[0].value
  });

  request.on("doneInProc", (rowCount, more) => {
    console.log(callback)
    callback(result)
    result = "";
  });

  connection.execSql(request);
};
```

Having a bunch of call backs like this can be confusing, so be sure to check [our doc page](https://tediousjs.github.io/tedious/) for future guidance.

**Comment by nkrug** [comment]
Hi. Thank you very much for your reply. Unfortunately the propesed changes are not working. My code is derived from this example: [(https://github.com/tediousjs/tedious/blob/master/examples/parameters.js)]

If I try to put the parameters or the execSQL outside of the connection.on callback I get various error  messages. The request gets marked as undefined. If I define the request outside of the connection.on callback I get "TypeError: Cannot read property 'transformIntoExecuteSqlRpc' of undefined". Is there a different solution, or is there some specific information from my side needed? Thank you for your effort. I have tried a lot of stuff for several hours, but my understanding of JS is limited.

**Comment by IanChokS** [comment]
@nkrug Sorry, I've edited my example above. That should work now :)

**Comment by nkrug** [comment]
Thanks! Maybe I don't understand this properly, but if I nest the requests into each other it has to be hardcoded right? Is there a solution for an arbitrary amount of requests?

Here is a example I build with a different library:
```
let tmpctr = 0
function manageCallbacks(res) {
  if (tmpctr <= 10) {
    connect(manageCallbacks)
    console.log(res);
    tmpctr++
  }
}


function connect(cb) {
  console.log("connecting");
  var connStr ="con string to sql server";

  sql.open(connStr, function (err, conn) {
    if (err) {
      console.log(err);
    }
    console.log("connection is opened");
    
      var q = "select count(*) From [DATABASE]";
      conn.query(q, function (err, res) {
        if (err) {
          console.log(err.message);
        }
        cb(res)
      });
  });
}
```
This runs only one request at a time, and repeats until the condition is met. Is there something similar in tedious?

**Comment by IanChokS** [comment]
Yup certainty. What you're showing is a simple recursion. You can do something similar with tedious too: 

```js
connection.on('connect', function (err) {
  // If no error, then good to go...
  executeStatement()
}
);

let i = 3;
function executeStatement() {
  request = new Request("select 42, 'hello world'", function (err, rowCount) {
    if (err) {
      console.log(err);
    } else {
      console.log(rowCount + ' rows');

      if (i > 0) {
        i -= 1;
        executeStatement();
      } else {
        connection.close();
      }
    }
  });

  request.on('row', function (columns) {
    columns.forEach(function (column) {
      if (column.value === null) {
        console.log('NULL');
      } else {
        console.log(column.value);
      }
    });
  });

  request.on('done', function (rowCount, more) {
    console.log(rowCount + ' rows returned');
  });

  // In SQL Server 2000 you may need: connection.execSqlBatch(request);
  connection.execSql(request);
}

```
