### ISSUE TITLE
Login failed for user '' . Tedious 8.3.0 SQL server 2016

### ISSUE THREAD

**Issue by morinrod-cardioscan** [tediousjs/tedious#1110]
Trying to connect to SQL server 2016 with Tedious 8.3.0 gives the error:
Login failed for user '' . 
My code:
```js
  var dbconfig = {
    server: "xxx.xx.xx.xxx",
    authentication: {
        type: "default",
        options: {
            userName: "user",
            password: "password"
            }
        },
    };
connection = new Connection(dbconfig);
```

Tried to upgrade node version from 10 to 14, didn't work.
Also tried to add the encrypt=false option and it didn't work.
Only when I downgraded to **Tedious version 6.1.0** it started working.

**Comment by IanChokS** [comment]
Hi @morinrod-cardioscan can you show the stack trace of the error? I was able to connect to SQL Server 2016 so far

**Comment by morinrod-cardioscan** [comment]
Hi @IanChokS ,
I upgraded to Tedious 8.3.0 again and I don't get the error anymore, everything is working fine.
I added more code to the project since I got the error but haven't changed the code above or any configuration on the server. So not sure what was the cause...
Thanks for your time, I will close the issue.

**Comment by IanChokS** [comment]
Awesome, I’m glad to that you were able to solve it 🙌
