### ISSUE TITLE
insert datetime2 value invalid

### ISSUE THREAD

**Issue by MephistoSunyang** [tediousjs/tedious#1111]
Hi,
I find a question about insert datetime type column.
When i insert some time like the day of end '2020-06-17 23:59:59:00',
but the database column display '2020-06-18 23:59:59:00'.
The code like this:
<pre><code>
await sql.connect(config);
  const request = new sql.Request(config);
  request.input(
    "1",
    sql.DateTime2,
    new Date(moment("2020-06-17").endOf("day").format("YYYY-MM-DD HH:mm:ss"))
  );
  const result = await request.query(
    `INSERT INTO "users" ("testDate") VALUES (@1)`
  );
  return result;
</code></pre>

Then i found what's problem is,
in data-types - datetime2.js line 65
<pre><code>
if (options.useUTC) {
  buffer.writeUInt24LE(Math.floor((+parameter.value - UTC_YEAR_ONE) / 86400000));
} else {
  const dstDiff = -(parameter.value.getTimezoneOffset() - YEAR_ONE.getTimezoneOffset()) * 60 * 1000;
  buffer.writeUInt24LE(Math.floor((+parameter.value - +YEAR_ONE + dstDiff) / 86400000));
}
</code></pre>
I think this code is calculate date without hours but the parameter.value include hours/minutes/seconds,
so when the data like '2020-06-17 23:59:59:00' you calculate the '23:59:59' and dstDiff you will get  one more day!
I think removed the hours/minutes/seconds we can get correct the value.
like this:
<pre><code>
const dailyDate = moment(parameter.value).startOf("day").toDate();
if (options.useUTC) {
  buffer.writeUInt24LE(Math.floor((+dailyDate - UTC_YEAR_ONE) / 86400000));
} else {
  const dstDiff = -(dailyDate.getTimezoneOffset() - YEAR_ONE.getTimezoneOffset()) * 60 * 1000;
  buffer.writeUInt24LE(Math.floor((+dailyDate - +YEAR_ONE + dstDiff) / 86400000));
}
</code></pre>
finally, thank you for your contributions for us and i wish you every success in your career!:smile::smile::smile:

**Comment by arthurschreiber** [comment]
👋 @MephistoSunyang Hello there!

I think the issue you describe was already fixed with https://github.com/tediousjs/tedious/pull/1023, which was part of the `tedious@8.0.0` release. It looks like you're not using `tedious` directly, but via a different library (my guess is via `node-mssql`?).

Newer versions of `node-mssql` should be using the latest version of `tedious` as well, so upgrading should fix this for you.

> finally, thank you for your contributions for us and i wish you every success in your career!

Thanks! Same to you, and thanks for reporting this issue.
