### ISSUE TITLE
ESOCKET Connection Error when connecting to MSSql using nodejs

### ISSUE THREAD

**Issue by achaugule** [tediousjs/tedious#1120]
I'm using versions:
mssql: "^6.2.0",
tedious: "^8.3.0"

I have enabled TCP/IP in configuration manager. Also all my sql services are running. yet am getting following error:

C:\Nodejs\node-sql-conn\Database>node connect.js
tedious deprecated In the next major version of tedious, creating a new Connection instance will no longer establish a connection to the server automatically. Please use the new connect helper function or call the .connect method on the newly created Connection object to silence this message. internal\process\task_queues.js:79:11
Connection Failed

C:\Nodejs\node-sql-conn\Database\connect.js:26
throw err;
^
ConnectionError: Failed to connect to localhost:undefined - Cannot call write after a stream was destroyed
at ConnectionError (C:\Nodejs\node-sql-conn\node_modules\tedious\lib\errors.js:13:12)
at Connection.socketError (C:\Nodejs\node-sql-conn\node_modules\tedious\lib\connection.js:1308:56)
at Socket. (C:\Nodejs\node-sql-conn\node_modules\tedious\lib\connection.js:1143:14)
at Socket.emit (events.js:327:22)
at errorOrDestroy (internal/streams/destroy.js:108:12)
at onwriteError (_stream_writable.js:418:5)
at onwrite (_stream_writable.js:445:5)
at doWrite (_stream_writable.js:399:11)
at writeOrBuffer (_stream_writable.js:387:5)
at Socket.Writable.write (_stream_writable.js:318:11) {
code: 'ESOCKET'
}

This is my Code:
var Connection = require('tedious').Connection;
var config = {
server: 'localhost',
authentication: {
type: 'default',
options: {
userName: 'sa',
password: '####',
port:1433
}
},
options: {
database: 'Company',
instanceName: 'MSSQLSERVER',
rowCollectionOnDone: true,
useColumnNames: false,
trustServerCertificate: false
}
};
var connection = new Connection(config);
connection.on('connect',function(err){
if(err){
console.log('Connection Failed');
throw err;
}
else{
console.log('Connected');
}
});
module.exports = connection;

Please Help!!!

**Comment by IanChokS** [comment]
Hi @achaugule, Just from an initial quick look, it seems like you've got the `port` specified in the wrong options.

E.g., you have it in the authentication options,
```js
var config = {
  server: 'localhost',
  authentication: {
    type: 'default',
    options: {
      userName: 'sa',
      password: '####',
      port: 1433
    }
  },
  options: {
    database: 'Company',
    instanceName: 'MSSQLSERVER',
    rowCollectionOnDone: true,
    useColumnNames: false,
    trustServerCertificate: false
  }
};
```

whereas the port should be specified in the other options:

```js
var config = {
  server: 'localhost',
  authentication: {
    type: 'default',
    options: {
      userName: 'sa',
      password: '####',
    }
  },
  options: {
    port: 1433,
    database: 'Company',
    instanceName: 'MSSQLSERVER',
    rowCollectionOnDone: true,
    useColumnNames: false,
    trustServerCertificate: false
  }
};
```
Sorry for the double `options` , I know it can be confusing sometimes. Hopefully that solves your issue. 
You can also check out our docs with more examples [here](https://tediousjs.github.io/tedious/)

**Comment by achaugule** [comment]
Hi IanChokS ,

I did the necessary changes and got the following error:

C:\Nodejs\node-sql-conn\node_modules\tedious\lib\connection.js:343
        throw new Error('Port and instanceName are mutually exclusive, but ' + config.options.port + ' and ' + config.options.instanceName + ' provided');
        ^
Error: Port and instanceName are mutually exclusive, but 1433 and MSSQLSERVER provided
    at new Connection (C:\Nodejs\node-sql-conn\node_modules\tedious\lib\connection.js:343:15)
    at Object.<anonymous> (C:\Nodejs\node-sql-conn\Database\connect.js:22:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

Removing port number from config object i'm still getting following errror:

tedious deprecated In the next major version of `tedious`, creating a new `Connection` instance will no longer establish a connection to the server automatically. Please use the new `connect` helper function or call the `.connect` method on the newly created `Connection` object to silence this message. internal\process\task_queues.js:79:11
Connection Failed

C:\Nodejs\node-sql-conn\Database\connect.js:26
        throw err;
        ^
ConnectionError: Failed to connect to localhost:undefined - Cannot call write after a stream was destroyed
    at ConnectionError (C:\Nodejs\node-sql-conn\node_modules\tedious\lib\errors.js:13:12)
    at Connection.socketError (C:\Nodejs\node-sql-conn\node_modules\tedious\lib\connection.js:1308:56)
    at Socket.<anonymous> (C:\Nodejs\node-sql-conn\node_modules\tedious\lib\connection.js:1143:14)
    at Socket.emit (events.js:327:22)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at doWrite (_stream_writable.js:399:11)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11) {
  code: 'ESOCKET'
}

**Comment by achaugule** [comment]
Following is the code that worked for me.

const express = require('express');
const sql = require('mssql');
const bodyParser = require('body-parser');
const app =  express();

//const customerRoutes = require('./api/routes/customers');

app.use(bodyParser.urlencoded({extended: false}));
app.use(bodyParser.json());
//CORS Middleware
app.use(function (req, res, next) {
    //Enabling CORS 
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Methods", "GET,HEAD,OPTIONS,POST,PUT");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, contentType,Content-Type, Accept, Authorization");
    next();
});
//Initialising connection string
var dbConfig = {
    user:  "sa",
    password: "techcareerAB20#",
    server: "IN5CG9010BLY",
    database: "Company",
    options: {
        "enableArithAbort": true,
        "encrypt":false
    }
};

//Function to connect to database and execute query
var executeQuery = function(req, res){             
     sql.connect(dbConfig, function (err) {
        if (err) {   
            console.log("Error while connecting database :- " + err);
            res.send(err);
        }
        else {
            console.log('Database Connected');
          // create Request object
          var request = new sql.Request();
          // query to the database
          request.query(req, function (err, response) {
            if (err) {
              console.log("Error while querying database :- " + err);
              res.send(err);
              }
              else {
                console.log(response);
                res.send(response);
              }
          });
        }
    });           
}

**Comment by ramses429** [comment]
![image](https://user-images.githubusercontent.com/33917970/167060202-7e5c31c3-4e1e-450a-beb1-b902e001a646.png)
![image](https://user-images.githubusercontent.com/33917970/167060372-3c85ce8a-e339-4b98-aac8-a21b4b277717.png)
![image](https://user-images.githubusercontent.com/33917970/167060472-dabb7afc-ee40-4c54-b07a-9c27c352b0b1.png)
![image](https://user-images.githubusercontent.com/33917970/167061220-971a070a-c017-4712-8d7e-3af3861dc27e.png)

Use how host your own public ip direction
