### ISSUE TITLE
Connection lost - read ECONNRESET - SQL 2000

### ISSUE THREAD

**Issue by Itayp1** [tediousjs/tedious#1123]
hey 
i have trouble to connecting into sql server 2000

i have the following code
and i get the error 
"Connection lost - read ECONNRESET"

what can be the problem ?

this is the props of the server 
Microsoft SQL Server Standard Edition
Microsoft Windows NT 5.2 (3790)
NT INTEL X86
8.00.2039
server_collation Hebrew_CI_AS

```js
var Connection = require('tedious').Connection;

var config = {
  server: '1.1.1.1',
  options: {
    tdsVersion:"7_1",
  },
  authentication: {
    type: 'default',
    options: {
      userName: 'user1',
      password: 'user2'
    }
  }

};
var connection = new Connection(config);
connection.on('connect', function(err) {
    // If no error, then good to go...
    console.log("connected")
    // executeStatement();
  }
);
connection.on('debug', function(text) {
    console.log(text);
  }
);
```

**Comment by IanChokS** [comment]
Hi @Itayp1, thanks for raising your issue. We'll take a look into this.

**Comment by MichaelSun90** [comment]
Hi @Itayp1, we do not really have a test set up for SQL server 2000 on hand. Is it possible that we use yours for some simple connection tests?

**Comment by MichaelSun90** [comment]
Hi @Itayp1, I just got a SQL server 2000 test environment and figured out the issue. Actually, someone else got a similar issue with you and the solution solves yours as well (https://github.com/tediousjs/tedious/issues/1059). You just need to set the encrypt: false under options which should resolve the issue. 

```nodejs
var config = {
  server: '1.1.1.1',
  options: {
    tdsVersion:"7_1",
    encrypt: false
  },
  authentication: {
    type: 'default',
    options: {
      userName: 'user1',
      password: 'user2'
    }
  }

};
```

**Comment by Itayp1** [comment]
hey
its working great
tnx

‫בתאריך יום ב׳, 13 ביולי 2020 ב-21:50 מאת ‪Michael Sun‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by MichaelSun90** [comment]
Good to know that helps. I will close this for now. If you get anything else, feel free to reopen this.

**Comment by IanChokS** [comment]
Hi @Itayp1 Just to let you know, when you set `encrypt: false` I believe it is turning off SSL/TLS encryption so your data (such as username and password) could be potentially seen.
