### ISSUE TITLE
When outputparameter value exceed limit characters(8000)value got truncated

### ISSUE THREAD

**Issue by Ethan0721** [tediousjs/tedious#1126]
`
request.on('returnValue', (name, value, matadata)=>{ 
  
     result[name] = value; // if value is over 8000 characters value will got truncated
});
`
 
I tired using Text and NText both got error. Using VarChar has only 8000 limit characters. Not sure if there is any solution for this.
I also post this issue in stackoverflow: 
https://stackoverflow.com/questions/62824283/tedious-package-when-outputparameter-value-exceed-limit-characters-8000

**Comment by Ethan0721** [comment]
@IanChokS  @MichaelSun90  @arthurschreiber

**Comment by arthurschreiber** [comment]
I'll see what can be done about getting `Text` and `NText` output parameters working, as that looks like a bug.

Did you try using `VarChar` or `NVarChar` with the `length` option set to `Infinity` / `Number.POSITIVE_INFINITY`? That should toggle the parameter into `varchar(max)` / `nvarchar(max)` and allow value lengths above 8000 bytes.

**Comment by Ethan0721** [comment]
Hi @arthurschreiber  thanks for you reply, I assume this is your suggestion in Node level code change : 
   request.addOutputParameter('JSONOUTPUT1', TYPES.VarChar, {length: Infinity});
    request.addOutputParameter('JSONOUTPUT2', TYPES.VarChar, {length: Infinity});

I tired this way it's still not working, it has the same length as VarChar has.

**Comment by IanChokS** [comment]
@Ethan0721 Are you concatenating two strings that when combined is over 8,000 characters? If so, you need to cast at least one component to varchar(max) to get a string returned with more than 8,000 characters (resource [1](https://bertwagner.com/2018/05/15/why-is-my-varcharmax-variable-getting-truncated/), [2](https://stackoverflow.com/questions/7392161/t-sql-varcharmax-truncated), [3](https://social.msdn.microsoft.com/Forums/en-US/6dc8620f-bb86-438a-8e43-bd44f2eb0377/truncating-varcharmax?forum=transactsql)).

I'll try to replicate this on tedious too.

**Comment by Ethan0721** [comment]
Hi @IanChokS, I have two outputparameters, i am not concatenating these two, I just have big chunk of data returned from SQL Server and each of outputparameter, json1 and json2, will over 8000+for sure.    
 I don't see issue in SQL Server side because when i execute the storeprocedure and display the data I can get correct, without truncated data in the table.  Below is how i run my storeprocedure in sql server. 
`
DECALRE @json2 as varchar(MAX) 
exec MY_STORE_PROCEDURE 
@store_nbr = 'ALL', 
@jsonoutput1 = @json2 output, 
SELECT @json2
`
Again , the issue is happen when i am receiving the data.  Below way jsonout1 and 2 has exactly 8000 limit. value will be truncated above it. 

`
    request.addOutputParameter('JSONOUTPUT1', TYPES.VarChar);
    request.addOutputParameter('JSONOUTPUT2', TYPES.VarChar);
    request.on('returnValue', (name, value, matadata)=>{
      result[name] = value;
    });
`

**Comment by IanChokS** [comment]
@Ethan0721 Can you show a full repo script?

Also if you just need to get this working for now, I was able to get the full length of the text by using a regular sql statement without the use of parameters. 
For e.g.,
Stored procedure on ssms: 
 ```sql
create procedure selectValue (@val varchar(max) OUTPUT, @len int OUTPUT) as 
begin
	select @val = col1, @len = LEN(col1) from table8
end;
```

Tedious code: 
```js
connection.on('connect', function(err) {
  var request = new Request(`
  declare @str varchar(max), @num int;

  exec selectValue @val = @str output, @len = @num OUTPUT;
  
  select @str as 'value', @num as 'length';`,
    function(err) {
      if (err) {
        console.log(err);
      }

      connection.close();
    });

  request.on('row', function(columns) {
    columns.forEach(function(column) {
      if (column.value === null) {
        console.log('NULL');
      } else {
        console.log(column.value);
      }
    });
  });

  connection.execSql(request);
});
```

Result:

```
...aaaab //<-- 8001 a's followed by a b
8001 //<-- the total length of the string returned. 
```

**Comment by Ethan0721** [comment]
Thank you for look deep into this, yes, what you post is not using the input and output parameter and not running the storeprocedure way. We have two methods one is for running the sql query the other one is for running the storeprocedure.  Below is how i implement for storeprocedure. I will try tweek this to running query way. I hope I can also see how your team would handle this in storeprocedure way, because it seems Text and NText is not working as expected in current version, and receiving outputparameter not able to read chunk by chunk. 

`
const spPostExecute = (spName, inputParams, settings, done)=> {
  let result = {};
  let ERROR_HANDLER = null;
  const connection = new Connection(settings);
  connection.on("connect", err => {
    if (err) {
      console.error(err.message);
      ERROR_HANDLER = err;
      ERROR_HANDLER.status = STATUS_CODE.DATABASE_CONNECTION_ERROR;
      done(ERROR_HANDLER);
      return;
    }
    const request = new Request(spName, (err, rowCount) => {
      if (err) {
        ERROR_HANDLER = err;
        ERROR_HANDLER.status = STATUS_CODE.DATABASE_QUERY_ERROR;
        console.error(`Error received from database side ${err.message}`);
      } else {
        console.log(`${rowCount} row(s) returned`);
      }
    });

    if(inputParams){
      inputParams.forEach((param)=>{
        request.addParameter(param.name, param.type, param.val);
      })
    }

    request.addOutputParameter('JSONOUTPUT1', TYPES.VarChar);
    request.addOutputParameter('JSONOUTPUT2', TYPES.VarChar);

    request.on('returnValue', (name, value, matadata)=>{
      result[name] = value;
    });
    request.on('requestCompleted', () => {
      connection.close();
      if(ERROR_HANDLER){
        done(ERROR_HANDLER);
      }else{
        console.log(result);
        done(null, result);
      }
    });
    request.on('error', (err) => {
      connection.close();
      ERROR_HANDLER = err;
      ERROR_HANDLER.status = STATUS_CODE.DATABASE_QUERY_ERROR;
      console.log("error in the request ");
      done(err);
    });
    connection.callProcedure(request);
  })   
}
`

**Comment by IanChokS** [comment]
This looks more like a sqlserver config error than `tedious`, because calling the stored procedure from tedious, the server itself is sending back truncated data (There's a `b` at the 8,001 position in the database but as you can see the `b` has been cutoff). 

![image](https://user-images.githubusercontent.com/53239257/87818996-63f91b80-c820-11ea-9261-5ee04ca6146f.png)


Some work arounds I've seen is to do a `while` loop in the stored procedure ([source](https://stackoverflow.com/questions/7850477/how-to-print-varcharmax-using-print-statement))
```sql
DECLARE @Counter INT
SET @Counter = 0
DECLARE @TotalPrints INT
SET @TotalPrints = (LEN(@script) / 8000) + 1
WHILE @Counter < @TotalPrints 
BEGIN
    -- Do your printing...
    SET @Counter = @Counter + 1
END
```

**Comment by Ethan0721** [comment]
reading by row fixed our current error, thanks for your info i will try the above way as well. Thank you so much for you dig into this.
