### ISSUE TITLE
Data Types missing functions - TypeError: parameter.type.validate is not a function

### ISSUE THREAD

**Issue by itsphil** [tediousjs/tedious#1127]
### Expected behaviour:

It is expected that when using `sql.UniqueIdentifier` or any other typing provided by the `mssql` library that it will execute successfully and not error.

### Actual behaviour:

While calling a stored procedure I received this error;

`TypeError: parameter.type.validate is not a function`

Upon logging out what `sql.UniqueIdentifier` (or any other Type) I am presented with the following object;

```
type: [Function: UniqueIdentifier] {
    declaration: 'uniqueidentifier',
    inspect: [Function]
}
```

This object seems to lack a lot of the functions defined in `node_modules\tedious\lib\data-types\uniqueidentifier.js`. Therefore when this file `node_modules\tedious\lib\request.js` (line 187), runs this code `const value = parameter.type.validate(parameter.value);` it errors because `validate` is not a function.

### Configuration

I am importing the Types from the `mssql` library as below;

`import sql from "mssql";`

and referencing it using;

`sql.UniqueIdentifier`

### Software versions

  * NodeJS: 12.16.1
  * node-mssql: 6.2.0
  * SQL Server: 14

**Comment by IanChokS** [comment]
Hi @itsphil, This issue might best be raised on [mssql ](https://github.com/tediousjs/node-mssql). For Tedious, there is a `validate` [function for the type Uniqueidentifier](https://github.com/tediousjs/tedious/blob/4120817754e91a32d9419093770771df590365ca/src/data-types/uniqueidentifier.ts#L33), so it's most likely that the mssql library needs to import that function from tedious.

**Comment by IanChokS** [comment]
@itsphil Do you have a repro script? I can try to see if there's any possible work arounds

**Comment by itsphil** [comment]
Thanks @IanChokS . I created a reproduction, but alas it worked fine. I believe the issue must be to do with how I have my project(s) setup.

I have a base project (Project A) which is our API framework which utilises `mssql` and does all the heavy lifting.

I then have an API project (Project B) which uses Project A. Project B also uses `mssql`, but only for the types it provides, e.g. `UniqueIdentifier`.

For some reason when I run `console.log(parameter.type);` on line 182 of `node_modules/tedious/lib/request.js` on both Project A and my reproduction project, they output quite different results.

As this seems to be an issue with my implementation, I am happy to close the issue if you have no idea's on what could be going on.

**Comment by IanChokS** [comment]
Ah well glad you were able to figure it out! I'll close this issue then.
