### ISSUE TITLE
Example, storedProcedureWithParameters.js missing DB connection

### ISSUE THREAD

**Issue by Afsarsoft** [tediousjs/tedious#1147]
Great samples, Great job, please add more. Just FYI, looks like DB connection is missing from example storedProcedureWithParameters.js
Following worked for me.
+++++++++++++++++++++++++++++++++++
var connection = new Connection({
  server: 'afsarsoft.database.windows.net',
  **options: {
    database: "DBNAME", //update me
    encrypt: true
  },**
  authentication: {
    type: 'default',
    options: {
      userName: 'USERNAME', //update me
      password: 'PASSWORD'  //update me
    }
  }
});
+++++++++++++++++++++++++++++

**Comment by IanChokS** [comment]
Hi @Afsarsoft Thanks for your feedback! We currently have one PR (#1032) that will hopefully add more clarification and examples.

**Comment by Afsarsoft** [comment]
@IanChokS  thanks, great, looking forward to have more examples specially related with SQL SPs returning multiple rows. Also, it would be great to have more complete examples in getting results from SQL SPs and rendering them all the way to UI/HTML.

**Comment by IanChokS** [comment]
How you display data from the backend to the frontend is totally up to you and is not part of tedoius's domain. But for pointers  you can use [Express](https://www.npmjs.com/package/express) on the backend, and [Axios](https://www.npmjs.com/package/axios) on the front end to communicate data between a client and a server. 

Closing this now as it isn't an issue with tedious driver. 

I hope this all helps!
