### ISSUE TITLE
bulkLoad.setTimeout(timeout) doesn't do anything

### ISSUE THREAD

**Issue by chriseaton** [tediousjs/tedious#1158]
Just noticed that the `bulkLoad.setTimeout(timeout)` function set's a timeout property, but it doesn't appear to be used at all. If I set the value to 1ms, I would expect almost any query to timeout immediately, but they do not. Looking at the tedious Connection object, `execBulkLoad` function looks like it constructs a new `Request` but doesn't seem to do anything with the timeout value.

tedious version 9.2.1

**Comment by IanChokS** [comment]
Yes this looks like an issue. Thanks for raising awareness to this problem! We'll look into fixing this.

**Comment by IanChokS** [comment]
@chriseaton PR #1164 has been created to address this issue!
