### ISSUE TITLE
Get id of inserted item

### ISSUE THREAD

**Issue by ghost** [tediousjs/tedious#117]
I am making an insert and the ID is auto generated in the DB.  I need that auto-generated ID on the callback from the request.  I tried listening to the doneInProc event, but nothing returns from that event.

**Comment by SyRenity** [comment]
Just wanted to add my 2c that it works great with Promise pattern (Q), allowing to use the result via resolve().

**Comment by arthurschreiber** [comment]
Another, and in my opinion better, alternative is to use the `OUTPUT` clause in your `INSERT` statement.

**Comment by lee-houghton** [comment]
Just be careful using @@identity. It will work fine if you don't use triggers, but if you (or your DBA) add a trigger, you may find that @@identity returns what was created by the trigger. You can use `scope_identity()` to refer to the original ID.

**Comment by SyRenity** [comment]
@arthurschreiber @lee-houghton thanks for the tip, scope_identity() is a better choice indeed.

**Comment by Nedlinin** [comment]
@arthurschreiber : Wanting to go the route of the output clause but I can't seem to get it to play nicely with Tedious.

Following statement works in SQL Management Studio:
    
    INSERT INTO dbo.direct(employeeNumber, job,phase, chargeCode)
    OUTPUT INSERTED.ID
    VALUES(1, 2 3, 4)


However, if I try to convert that to a Tedious call with parameters:

        const sqlStatement = "INSERT INTO " +
            "dbo.direct(employeeNumber, job, phase, chargeCode) " +
            "OUTPUT @ID=INSERTED.ID " +
            "VALUES(@employeeNumber, @job, @phase, @chargeCode)";

        const request = db.createReq(sqlStatement, cb);

        request.addParameter("employeeNumber", TYPES.Int, dlInfo.employeeID);
        request.addParameter("job", TYPES.Int, dlInfo.job);
        request.addParameter("phase", TYPES.Int, dlInfo.phase);
        request.addParameter("chargeCode", TYPES.Int, dlInfo.chargeCode);
        request.addOutputParameter("ID", TYPES.UniqueIdentifier);

         request.on("returnValue", function(parameterName, value) {
            console.log(value); // Always returns null?
        });


Mind pointing me at where I'm going wrong?

**Comment by arthurschreiber** [comment]
Is there a reason you're trying to use an output variable?

**Comment by Nedlinin** [comment]
@arthurschreiber : Yes.  Stupidity :smile: 

Went this route using on row and had no issues.

        request.on("row", function(columns) {
            console.log(columns[ 0 ].value);
        });

Sorry to bug ya!
