### ISSUE TITLE
Does Tedious support connections to Sybase?

### ISSUE THREAD

**Issue by rathboma** [tediousjs/tedious#1170]
Sybase and Sybase IQ also implement the TDS protocol. 

Does Tedious work for those databases also? I see no mention in the docs.

**Comment by IanChokS** [comment]
That's interesting, theoretically it should be possible, but tedious is designed solely for MS Sql Server. Give it a try though, and let us know it works!

Closing this as it isn't an issue.

**Comment by rathboma** [comment]
Reading some details online, it seems Sybase only implements version 5.0 of the TDS protocol, so probably no? I'll still try to figure it out though.

**Comment by IanChok** [comment]
Unfortunately `tedious` doesn't support that version of TDS. As [stated in our docs](https://tediousjs.github.io/tedious/api-connection.html):
```
options.tdsVersion
The version of TDS to use. If server doesn't support specified version, negotiated version is used instead. The versions are available from require('tedious').TDS_VERSION.
7_1 (use for SQL Server 2000)
7_2
7_3_A
7_3_B
7_4
(default: 7_4).
```

**Comment by rathboma** [comment]
yep :-/

**Comment by IanChokS** [comment]
Unfortunately `tedious` doesn't support that version of TDS. As[ stated in our docs page](https://tediousjs.github.io/tedious/api-connection.html):
```
options.tdsVersion
The version of TDS to use. If server doesn't support specified version, negotiated version is used instead. The versions are available from require('tedious').TDS_VERSION.
7_1 (use for SQL Server 2000)
7_2
7_3_A
7_3_B
7_4
(default: 7_4).
```
