### ISSUE TITLE
Not passing `domain` value for identifying the tenantId

### ISSUE THREAD

**Issue by carlosjrodriguezp** [tediousjs/tedious#1171]
https://github.com/tediousjs/tedious/blob/69ad8243d400d19fb05230c027ff74648b91a2e8/src/connection.ts#L3539

I've been trying to connect to my mssql DB using Azure AD Auth on `sequelize`, however I get the following message `Security token could not be authenticated or authorized.`. After debugging inside `sequelize`, then `tedious` and finally `ms-rest-nodeauth`, I realized that `ms-rest-nodeauth` does not get the `options.domain` value. The function `loginWithUsernamePassword` from `tedious` login.ts file is not passing that value to the nodeauth function, even when `tedious` does get it from `sequelize`. I wonder if it is due to some specific reason or there may be an issue here. I debugged the Auth process and was able to make the Azure AD Auth connection with my mssql DB if I set up the `options.domain` value manually when the auth process gets to `withUsernamePassword` function (stopping here with a breakpoint). If this is not the correct way for setting this up, I'll need some help from Tedious team. Any one?

Using: 
sequelize@5.22.3
tedious@6.4.0

**Comment by IanChokS** [comment]
`@azure/ms-rest-nodeauth` `loginWithUsernamePassword` method only requires user name and password, which it gets from tedious config: `authentication.options.userName` and `authentication.options.password`.

Not sure why you would need the `options.domain` value for that API since it doesn't call for it.

**Comment by IanChokS** [comment]
Also the tedious version `6.4.0` that you're using has a dependency for an outdated version of `@azure/ms-rest-nodeauth` (2.0.2). The latest version of that package is 3.0.6.

**Comment by carlosjrodriguezp** [comment]
`@azure/ms-rest-nodeauth` `loginWithUsernamePassword` can receive `options`
![image](https://user-images.githubusercontent.com/14138695/98309929-5ca57b80-1f91-11eb-85a8-4d2f73d63220.png)

then, in the following method, it evaluates if `options.domain` is not present to provide a custom `common` value.
![image](https://user-images.githubusercontent.com/14138695/98310101-c7ef4d80-1f91-11eb-8748-71daf5c4d14c.png)

With this `common` value as the tenant Id, I'm not able to make the connection using Azure AD Auth.

If this is not the correct whay to set up Azure AD Auth, how it would be? Since no matter what properties I defin in my Sequelize/Tedious config there are not getting to `@azure/ms-rest-nodeauth`.

I'm trynig to understand how I should set up this connection properly. Nothing in the web has helped me, I had to go myself through the libraries code.

**Comment by IanChokS** [comment]
Ah yes you're right, it doesn't look like tedious has an option to pass in a custom `domain` in the optional config property at the moment. I'll look create a fix for that! Thanks for bringing awareness to this issue! 🙇

**Comment by carlosjrodriguezp** [comment]
Awesome, I'd appreciate this help since we're required for security reasons to change our connection to Azure AD Auth. Thanks! @IanChokS

**Comment by IanChokS** [comment]
Ok you can checkout the branch [Ian/username-pass-domain](loginWithUsernamePassword) and see if this change helps for now. I just quickly passed in the domain option in the options config for `loginWithUsernamePassword` method. Was this the change you did to make it work? I'll be sure to add tests soon too.

**Comment by carlosjrodriguezp** [comment]
Hi @IanChokS Sorry, I believe I missed this when I described what I found in `tedious` `connection.js` file:
When setting up the authentication properties for `azure-active-directory-password` auth method, at the `connection` construct, I don't know why but it only takes options `userName` and `password`. It discards any other property from `authentication.options`.

![image](https://user-images.githubusercontent.com/14138695/98390734-64116700-201b-11eb-8e2a-e5154b7da557.png)

I should have mentioned this before, but it gets to `SENT_LOGIN7_WITH_FEDAUTH` transition the `authentication.options` will only contains `userName` and `password` no matter how many other props there were set up previously. So, having this the modification you did will get the `authentication.options.domain` as undefined.

I assume the change should be done on the construction (in the code of the image above).

**Comment by carlosjrodriguezp** [comment]
And yes, I can confirm after testing it that including the domain attribute in the auth props along with your change in `loginWithUsernamePassword ` , works as expected:
![image](https://user-images.githubusercontent.com/14138695/98393898-91f8aa80-201f-11eb-9ba1-b105d7c478a1.png)

**Comment by IanChokS** [comment]
@carlosjrodriguezp I believe[ I already put ](https://github.com/tediousjs/tedious/compare/ian/username-pass-domain)the `domain: options.domain` in the constructor you described above. Was this what you were referring to, or did I miss another part of the config?

**Comment by carlosjrodriguezp** [comment]
oh yeah, you're totally right. My bad, I hadn't seen it:
![image](https://user-images.githubusercontent.com/14138695/98403344-6f21c280-202e-11eb-9cfa-83a2e5616508.png)

**Comment by carlosjrodriguezp** [comment]
@IanChokS Hi Ian. Just a concern. Is there any estimate date when you guys believe this issue can get fixed and delivery? Thanks!

**Comment by IanChokS** [comment]
Hi yes, I'll try to get this fix merged asap, hopefully by the end of next week 🤞

**Comment by IanChokS** [comment]
@carlosjrodriguezp can you confirm if the changes I've proposed solves your issue?

**Comment by carlosjrodriguezp** [comment]
@IanChokS yes, the changes you proposed were implemented directly in my local environment and they worked.

**Comment by carlosjrodriguezp** [comment]
@IanChokS Hi Ian, is there any update on this? I know the PR was created but don't know when it will be finally merged and released. Thanks!

**Comment by IanChokS** [comment]
Hi sorry I'm not able to merge because one of the core CI tests have been failing. I've just [created a PR](https://github.com/tediousjs/tedious/pull/1185) to update the CI test so hopefully the tests will start passing 🤞

**Comment by IanChokS** [comment]
PR has been merged. Hope this helps!

**Comment by carlosjrodriguezp** [comment]
Awesome, thanks for all the help and support!
