### ISSUE TITLE
ELOGIN despite setting up updated password.

### ISSUE THREAD

**Issue by gautamsamal** [tediousjs/tedious#1173]
I am using `node-mssql` to manage the db connections, however I have a weird requirement that sometimes the password gets updated and I have to reflect the same in the servers otherwise they end up with `ELOGIN` errors. So, basically I update the password in `config.password` of my connection pool.

While this has been working great all the times but yesterday I found a case where it threw `ELOGIN` error even after the said change. The SQL event logs says - wrong password.
`<login_information><error_code>18456</error_code><error_state>65</error_state></login_information>`

I am pretty sure that the password that I set is correct via code. So, is there anything in the library or in `tedious` that tried to connect with old password? Could an open preexisting connection in pool cause this? Or is there a better way to ensure updates of password/user?

Any information will help! Thanks in advance!

Versions:
node-mssql - 6.1.0
tedious - 6.7.0
SQL server - 2016

**Comment by IanChokS** [comment]
Hi @gautamsamal , tedious itself doesn't implement connection pooling yet. If it is caused by connection pooling, it might best to raise this issue on the [node-mssql](https://github.com/tediousjs/node-mssql) side.

**Comment by gautamsamal** [comment]
@IanChokS true! It makes sense. Thanks. 
I'll create the issue on their end. Just to be clear, it doesn't sound like anything to do with tedious, does it? I mean, if I change the user/password in config for a tedious connection, it will immediately use that in the next connection. Correct?
