### ISSUE TITLE
Cannot connect to localhost/sqlexpress

### ISSUE THREAD

**Issue by Cottin** [tediousjs/tedious#118]
When setting the server to sqlexpress on localhost I get the exeption: getaddrinfo ENOTFOUND

``` javascript
var config = {
    userName: 'sa',
    password: 'mypassword',
    server: 'localhost/sqlexpress'
    server: 'LOCALHOST\\sqlexpress'
    server: 'LOCALHOST/SQLEXPRESS'
    server: 'LOCALHOST\\SQLEXPRESS'
    // note: I only use one of these at a time
  };
```

If it helps, when setting the server to just localhost I instead get a ECONNREFUSED.

Is there a problem in the lookup fo localhost\sqlexpress?

**Comment by oscartmxpgit** [comment]
Start your SQL Server Browser service, and don´t forget to enable TCP/IP in sql server configuration manager (configure TCP port under IPAll)
Next, I had to do this https://stackoverflow.com/questions/60226370/certificate-error-when-connecting-to-sql-server
