### ISSUE TITLE
404 Not Found - GET https://registry.npmjs.org/tedius - Not found

### ISSUE THREAD

**Issue by karlgo** [tediousjs/tedious#1183]
I'm getting the following error when I go to install tedius using npm.

    npm ERR! code E404
    npm ERR! 404 Not Found - GET https://registry.npmjs.org/tedius - Not found
    npm ERR! 404
    npm ERR! 404  'tedius@*' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

This is happing on Windows, macOS and Ubuntu.

npm version is 7.0.14

**Comment by IanChokS** [comment]
Try `tedious` with an 'o'

**Comment by karlgo** [comment]
Duh - sorry - thank you for being my eyes!!!

**Comment by IanChokS** [comment]
Yeah no worries :)
