### ISSUE TITLE
Add ORDER as a BulkLoad Option

### ISSUE THREAD

**Issue by dl-eric** [tediousjs/tedious#1197]
It would be really nice to have the BulkLoad option "ORDER" when doing bulk inserts. I'd imagine it's an easy couple-line change 😄 

ORDER is described in the Microsoft Docs [here](https://docs.microsoft.com/en-us/sql/t-sql/statements/bulk-insert-transact-sql?view=sql-server-ver15) and [here](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms177468(v=sql.105)).

I'm looking to use Tedious to run our bulk inserts, and a current Bulk Insert optimization we need to do is specifying ORDER as a way to tell SQL to not sort the data as they're already sorted.

**Comment by IanChokS** [comment]
Sorry for the late reply, but thanks for the suggested feature! When we have a bit more free time, we'll take a look into this.
