### ISSUE TITLE
Can't connect to Heimdall Data proxy

### ISSUE THREAD

**Issue by alferpal** [tediousjs/tedious#1199]
Hello.

We're having some problems with tedious, namely, that when we try to connect to a MS SQL Server DB going through a Heimdall Data proxy, we get an ECONNRESET.

The connection directly to the DB works as expected

We're using:
  * Node: 14.15.x
  * tedious: 9.2.1
  * SQL Server: if I'm not mistaken, it's a 14.x

On the other hand, we can connect to that DB passing through Heimdall using [Microsoft/vscode-mssql](https://github.com/microsoft/vscode-mssql)

From what I can tell by looking at a wireshark capture, is that vscode-mssql opens a secure connection to the proxy. 

Is there any way to do this in tedious?

**Comment by IanChokS** [comment]
Thanks for raising this issue, we'll take a look into it soon!

**Comment by alferpal** [comment]
I also raised an issue in the extension's repo asking how they connect:

https://github.com/microsoft/vscode-mssql/issues/16924#issuecomment-754168389

Hope that helps

**Comment by arthurschreiber** [comment]
I think the extension uses the CLI tools to connect.

There must be some difference between the CLI and tedious when connecting, which is not an issue with SQL Server, but causes some problems with Heimdall.

I've never used Heimdall before. Is there a free version of it available that we could use to test against?

**Comment by alferpal** [comment]
I'm not sure as it's my first time using it as well. I'll try to find something and will let you know

**Comment by alferpal** [comment]
Turns out it was a problem on our heimdall configuration. 

I'll close the issue, this client works fine.
Thank you for the time you put into this, and my apologies for opening an issue that in the end was not this clients fault.

**Comment by IanChokS** [comment]
Glad to hear you figured out the issue!
