### ISSUE TITLE
Possible EventEmitter memory leak

### ISSUE THREAD

**Issue by andrewsensus** [tediousjs/tedious#1201]
I think I'm seeing a memory leak in tedious, although I don't have a working example that is independent of my much larger application. My use pattern is to create a request object, prepare a statement, then run many queries using that prepared statement. I find that if I occasionally reset the connection, throw away the request object, and create a new one, my leak goes away.

I noticed this warning:
```
2021-01-07 05:22:41.060: 7011 (node:7011) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 cancel listeners added to [Request]. Use emitter.setMaxListeners() to increase limit
```

A core dump examined with llnode shows a lot of ReadableState, WritableState, and a few other types:
```
       6603     393232 Promise
      14066    1237808 (ArrayBufferView)
     275604    8819368 (Array)
     858961   48101784 RpcRequestPayload
     858976  109948928 PassThrough
     859216   41242368 CorkedRequest
     859344  185618304 ReadableState
     859348  206245344 WritableState
     859470   41258888 BufferList
    1374337    7734328 (String)
    3408785  189469752 Object
 ---------- ----------
   10246521  840970736
```

`connection.js` calls `makeRequest`. `makeRequest `calls `request.once('cancel', ...)`. I suspect the listener is never getting cleaned up and that the closure captures `message` which probably references a lot of things. I've confirmed with node --trace-warnings that `makeRequest` is the location the event emitter is complaining about.

In v5.0.0 a feature was added, "allow `BulkRequest`s to be canceled" (f78d745cbd79d87fa0de159bb19cf8ccb7c4a1e3). I see the introduction of the cancel listener, but I don't see where it is cleaned up on the non-bulk and non-error path.

**Comment by IanChokS** [comment]
Hi @andrewsensus , what version of tedious are you using? I think we've addressed this problem before but I'm not 100% sure.

**Comment by andrewsensus** [comment]
Hi @IanChokS I just realized I was running some of my tests against 9.2.1 and some against 9.2.3. Prior to that I was on 2-something.

**Comment by arthurschreiber** [comment]
@andrewsensus Prepared statements reuse the same `Request`s, if I remember correctly? 🤔 If that's true, you're right, the `cancel` handlers are never cleared out and will accumulate over time.

Thank you for reporting this!

I can't estimate how involved a fix would be right now. I took a quick look, and I think we'll have to unsubscribe from the 'cancel' event in at least these two cases:
* when a connection is closed with an in-flight request.
* when a request response was fully processed.

Unfortunately, we don't have access to the callback in those two places, so it might require some refactoring beforehand. 🤔

**Comment by arthurschreiber** [comment]
For normal requests, I don't think this is an issue - as soon as the `Request` object is no longer referenced, it (and its callbacks) will be cleaned up.

**Comment by andrewsensus** [comment]
@arthurschreiber Yes, I'm re-using the same `Request` for the many executions of the prepared statement.

Also, I just reran my test-case against 9.2.3. I can confirm that without introducing extra connection resets I'm seeing memory grow. OTOH, if I periodically reset the connection (and thus create a new `Reqeust` and re-prepare the statement), I see the EventEmitter warning repeatedly but memory stops growing.

I think the core dumps I was looking at were against multiple tedious versions -- I know they were against multiple node versions, but the general pattern of the leak looked the same.
