### ISSUE TITLE
RequestError: Connection closed before request completed.

### ISSUE THREAD

**Issue by zebtrijay** [tediousjs/tedious#1220]
So, I have been trying to resolve this error by increasing the packetSize to 16383 which is claimed to be the ideal size w/o interrupting the performance, but certainly cannot upgrade the size and still returns the value as "maximumLength":4000. Can you please let me know where can I change default size?

**Comment by IanChokS** [comment]
Hi @zebtrijay , do you have an repro example?

**Comment by arthurschreiber** [comment]
It sounds like you're mixing up two different things? `nvarchar` columns are limited to 4000 characters, unless you use `nvarchar(max)`. But this has nothing to do with the `packetSize` option.

Can you provide an example that reproduces the error you're running into?
