### ISSUE TITLE
Powershell with MFA

### ISSUE THREAD

**Issue by qgh-lpereira** [tediousjs/tedious#1223]
Hello,
I'm trying to use MFA ID to auto login to O365/Azure but what tried thusfar is not working.
[connecto365-Encrypted .txt](https://github.com/tediousjs/tedious/files/6036140/connecto365-Encrypted.txt)

**Comment by IanChokS** [comment]
Hi @qgh-lpereira , I'm a bit confused on what exactly you are trying to do. It looks like you're trying to use `.NET` instead of `tedious`? If so you can try to raise an issue on their [support page](https://dotnet.microsoft.com/platform/support)

**Comment by qgh-lpereira** [comment]
Thanks for the information.
