### ISSUE TITLE
[DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066

### ISSUE THREAD

**Issue by Komi-wbg** [tediousjs/tedious#1237]
I am using tedious 6.6.2 in one of my projects, it is a GCP cloud function environment, with nodejs 10, and i am getting a warning related to tedious: 
`"severity":"ERROR","message":"(node:6720) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.\n    at Object.connect (_tls_wrap.js:1619:15)\n    at MessageIO.startTls`

Also when i do a `node --trace-deprecation` it shows another warning: `tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message.`
What can/should i do about these warnings?

**Comment by IanChokS** [comment]
Is it possible to update to the latest tedious version `11.0.6`?

**Comment by pawelusfr** [comment]
@IanChokS I'm getting the same error on 11.0.6

**Comment by pawelusfr** [comment]
Looks like `servername` is being set when calling `tls.connect` even though I've set an IP address as server address.

**Comment by IanChokS** [comment]
I think the same issue has risen on the `mssql` library which uses `tedious` under the hood. According[ the last comment](https://github.com/tediousjs/node-mssql/issues/884), it could be "a universal issue with cloud DB service providers with SSL connections, and not a problem with this library. Would recommend investigating configuration options on the cloud DB service provider."

**Comment by IanChokS** [comment]
I think I found the official explanation from  [RFC 6066](https://tools.ietf.org/html/rfc6066), which states:

```
Currently, the only server names supported are DNS hostnames;
...
Literal IPv4 and IPv6 addresses are not permitted in "HostName".

  It is RECOMMENDED that clients include an extension of type
   "server_name" in the client hello whenever they locate a server by a
   supported name type.

   A server that receives a client hello containing the "server_name"
   extension MAY use the information contained in the extension to guide
   its selection of an appropriate certificate to return to the client,
   and/or other aspects of security policy.
```

Sorry you're running into this issue, but I don't think this is an error in `tedious` driver as I've also seen other people post this same error warning when connecting to other databases like MongoDB. I'm not sure how to solve this issue, but I hope I provided some helpful links to further your debugging. 

Closing this for now!
