### ISSUE TITLE
HELP: Unable to connect to SQL Server running locally

### ISSUE THREAD

**Issue by sdtacoma** [tediousjs/tedious#1239]
I am at a loss trying to get connected to a local SQL 2019 Server.  Below are my settings and what I have tried / turned on. I can connect to the DB through SMSS via locahost.

What am I doing wrong?

- TCP/IP is enabled
- SQL Server and Windows Authentication mode is on
- TCP Port 1433 and TCP Dynamic Port is Blank
- Named Pipes is enabled
- SQL Server is running
- SQL Browser is running
- SQL Server Agent is running

**Error:**
ConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)

```
var Connection = require('tedious').Connection;
	var Request = require('tedious').Request;
	var config = {
		server: 'localhost',
		authentication: {
		  type: 'default',
		  options: {
			userName: 'UN',
			password: 'PW'
		  }
		},
		options: {
			database: 'School',
			port: 1433
		}
	  };
	  	  
	  const connection = new Connection(config);
	  
	  connection.on('connect', (err) => {
		if (err) {
		  console.log('Connection Failed', err);
		  throw err;
		}
		executeStatement();
	  });
	  
	  connection.connect();
	  
	  function executeStatement() {
		const request = new Request('select * from Course', (err, rowCount) => {
		  if (err) {
			throw err;
		  }
	  
		  console.log('DONE!');
		  connection.close();
		});
	  
		// Emits a 'DoneInProc' event when completed.
		request.on('row', (columns) => {
		  columns.forEach((column) => {
			if (column.value === null) {
			  console.log('NULL');
			} else {
			  console.log(column.value);
			}
		  });
		});
	  
		request.on('done', (rowCount) => {
		  console.log('Done is called!');
		});
	  
		request.on('doneInProc', (rowCount, more) => {
		  console.log(rowCount + ' rows returned');
		});
	  
		// In SQL Server 2000 you may need: connection.execSqlBatch(request);
		connection.execSql(request);
	  }
```

**Comment by IanChokS** [comment]
> TCP Port 1433 and TCP Dynamic Port is Blank
Can you try explicitly setting the TCP port to be 1433?

**Comment by sdtacoma** [comment]
@IanChokS 

I have done that... 
![image](https://user-images.githubusercontent.com/18173141/111364871-063afe80-864f-11eb-862e-736bc1581a66.png)

**Comment by IanChokS** [comment]
Do you have another service running in the background? Perhaps `localhost` is conflicting with another service. Try explicitly connecting to the server IP address

**Comment by sdtacoma** [comment]
@IanChokS 

Different error when I specify an IP.

ConnectionError: Failed to connect to 192.168.1.42:1433 in 15000ms

**Comment by arthurschreiber** [comment]
@sdtacoma Based on what you describe, this should just work. 🤔 

Have you tried not specifying the port and specifying the instancename instead to connect via a SQL server browser lookup? 🤔

**Comment by sdtacoma** [comment]
@arthurschreiber 

I just tried it and below is the error that is generated. Including the full error in case there is something else going on.  

          connection.on('connect', (err) => {
		if (err) {
		  console.log('Connection Failed', err);
		  throw err; // line 33
           }

![image](https://user-images.githubusercontent.com/18173141/111381049-68512f00-8662-11eb-91dd-f6d4a820b812.png)

**Comment by sdtacoma** [comment]
@arthurschreiber 

When I specify the instance name I get the following error.


```
connection.on('connect', (err) => {
		if (err) {
		  console.log('Connection Failed', err);
		  throw err;     // line 33
		}
	  
		executeStatement();
	  });

```
![image](https://user-images.githubusercontent.com/18173141/111381561-19f06000-8663-11eb-8b5d-08c89693334f.png)

**Comment by IanChokS** [comment]
What version of tedious are you running?

**Comment by sdtacoma** [comment]
@IanChokS  "tedious": "^11.0.6"

**Comment by sdtacoma** [comment]
Does it have anything to do with the SQL Server version I am running? It is 2019.

**Comment by IanChokS** [comment]
I was able to connect and run queries on the SQL Server 2019-latest in a docker image.

**Comment by sdtacoma** [comment]
Hi @IanChokS 

That worked and I got the same output as you did. What does that tell us exactly?

42
hello world
1 rows returned
DONE!

**Comment by IanChokS** [comment]
Np! Glad to hear it worked. I think the original problem was probably something to do with your SQL Server set up 🤷‍♂️ Perhaps try reinstalling again. Are you planning on using the docker instance instead? If so I can close this issue.

**Comment by sdtacoma** [comment]
I can even connect to the docker instance through SMSS. That's great! 

Yes, close the issue I will use the docker image. Thank you for all of your help and guidance.

**Comment by IanChokS** [comment]
Btw I would recommend looking into setting up [volume mounts and database backups ](https://www.darrinbishop.com/blog/2021/02/step-by-step-win10-and-sql-server-with-docker-volumes/)with docker, so that if the docker instance stops or needs to be restarted, you won't lose your data
