### ISSUE TITLE
UnhandledRejection error: The database '<name>' has reached its size quota.

### ISSUE THREAD

**Issue by brsanthu** [tediousjs/tedious#1248]
We are getting this error when trying to insert some data and db storage limit reached. In such cases, the insert call should project reject and not miss out the underlying server error. We noticed that this happens quite a bit and errors are not properly propagated.

```
unhandledRejection error. Stack: RequestError: The database '<name>' has reached its size quota. Partition or delete data, drop indexes, or consult the documentation for possible resolutions.
at handleError (/usr/src/app/dist/node_modules/node-dbext/node_modules/mssql/lib/tedious/request.js:233:15)
at Connection.emit (events.js:315:20)
at Connection.EventEmitter.emit (domain.js:467:12)
at Connection.emit (/usr/src/app/dist/node_modules/node-dbext/node_modules/tedious/lib/connection.js:1045:18)
at Parser.<anonymous> (/usr/src/app/dist/node_modules/node-dbext/node_modules/tedious/lib/connection.js:1149:12)
at Parser.emit (events.js:315:20)
at Parser.EventEmitter.emit (domain.js:467:12)
at Parser.<anonymous> (/usr/src/app/dist/node_modules/node-dbext/node_modules/tedious/lib/token/token-stream-parser.js:35:14)
at Parser.emit (events.js:315:20)
at Parser.EventEmitter.emit (domain.js:467:12)
```

**Comment by MichaelSun90** [comment]
Hi @brsanthu, what is the current behavior when the insert data reaches its size quota? From what you showed here, seems that the server error that you expected has been swallowed? 
One thing I noticed is that you are using mssql on top of the tedious drivers. The mssql project has not been actively maintained for a well, so it may have some problems and it is still using a pretty old version of Tedious driver. If this is not working for you, could you try directly using the latest tedious driver by itself without mssql instead?

**Comment by brsanthu** [comment]
@MichaelSun90 thank you for your response. We are using https://github.com/tediousjs/node-mssql which is well maintained looks like. 

We use that library to get benefits of connection pool. If we have to remove node-mssql, how do we connection pool tedious driver?

**Comment by MichaelSun90** [comment]
Hi @brsanthu, Sorry that my information is maybe outdated, and thank you for letting me know that the owner for mssql decides to start to maintain it again. We were even has a discussion within the team to take over maintenance of mssql. 

As for the issue, if you are using connection pooling, then use tedious by itself is out of the picture. However, you can still help me to try your repo case with the tedious driver itself, see if the tedious propagate the proper error? Just to associated the origin of this problem. Or, you can provide us some repo steps, and we can try it on our side. Thanks!

**Comment by arthurschreiber** [comment]
@brsanthu This looks like a bug in https://github.com/tediousjs/node-mssql, or in the way you are using that library in your application. This does not seem to be a bug in `tedious`. 

When you reach the size quota while running a query, this error is sent back by the server and handled correctly by `tedious`, just like any other error that would happen. Either the wrapping in `node-mssql` or in your code is not handling this correctly and that ends up causing the `unhandledRejection`. `tedious` does not use promises internally (yet), so it's not possible it would end up causing an `unhandledRejection`.
