### ISSUE TITLE
UTC problem and One Day Off

### ISSUE THREAD

**Issue by v1d3rm3** [tediousjs/tedious#1249]
Hello!

**In node-mssql (6.3.1) / Tedious (6.7.0)**:

I'm having problems with not using utc in driver: `setUTC = false`.
If the hour of the date is anything is between `00:00:00 - 00:0:27`, than, in database, it subtracts one day (??????) of the Date.

**For example:**

Using `new Date(2021, 4, 27, 0, 0, 27)` to generate the Date (`2021-05-27T03:00:27.000Z`) (in backend) gives me `2021-05-26 00:00:27`

Using `new Date(2021, 4, 27, 0, 0, 28)` to generate the Date (`2021-05-27T03:00:28.000Z`) (in backend) gives me `2021-05-27 00:00:28`

Using `new Date(2021, 4, 27, 0, 0, 0)` to generate the Date (`2021-05-27T03:00:00.000Z`) (in backend) gives me `2021-05-26 00:00:00`

The code/repro:
```
import * as sql from "mssql";

const pool = new sql.ConnectionPool({
  user: "xxxx",
  password: "xxxxx",
  server: "xxxxx",
  database: "xxxxx",
  options: {
    enableArithAbort: true,
    useUTC: false,
    trustServerCertificate: true,
  },
});

async function start() {
  const conn = await pool.connect();

  let myDate = new Date(2021, 4, 27, 0, 0, 0);
  console.log(myDate);
  

  await conn.request().input("dt", sql.DateTime, myDate).query(`
    UPDATE example
    SET date= @dt
    WHERE id= 1;
  `);

  const res1 = await conn.query(
    "select date from example where id = 1"
  );
  console.log(res1.recordset);

  await pool.close();
}

start();
```

**In node-mssql (7.0.0-beta.5) / Tedious (11.0.5)**:

All things works as expected in same code.

**For example:**

Using `new Date(2021, 4, 27, 0, 0, 0)` to generate the Date (`2021-05-27T03:00:00.000Z`) (in backend) gives me `2021-05-27 00:00:00`

----

But i can't use `mssql 7.0.0-beta.5`. I'm using `typeorm` lib, and it ins't compatible with the mssql 7.x version.

Anyone can help me?

**Comment by IanChokS** [comment]
HI @v1d3rm3, Just curious as to why you're using `node-mssql` and not `tedious` directly? Also I'm not sure if `typeorm` works with `tedious` itself, but if not, you're probably best raising this issue on [node-mssql's](https://github.com/tediousjs/node-mssql#readme) repo directly as that is a separate library. Hopefully they can provide support for `typeorm` in their latest driver version. Since as you've stated it works with `tedious 11.0.5`, I'm not sure what else we can do.

**Comment by v1d3rm3** [comment]
Is `tedious` replacing `node-mssql`? It's just a reproduction of problem, i use here `node-mssql` because `typeorm` uses `node-mssql` and not `tedious` directly.

I think, like other issues, it's not a node-mssql problem, but a tedious problem, or not? How works long support here? There isn't support anymore for old versions of tedious to do a hotfix?

**Comment by arthurschreiber** [comment]
We don't generally backport fixes to old versions, because that's a huge maintenance overhead and we're basically just two people working on `tedious` right now. How do you feel about this?

A new version of `node-mysql` is in the works that updates to the latest version of `tedious`, so that might fix your issue soon? 🙇‍♂️

**Comment by v1d3rm3** [comment]
I understand the context, @arthurschreiber.
Thanks!

**Comment by v1d3rm3** [comment]
@arthurschreiber @IanChokS i'm receiving this error, but i can't discover the origin, it's from tedious? I'm using the 11v.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (0)
    at Function.byteLength (buffer.js:728:11)
    at RpcRequestPayload.generateParameterData (C:\Users\victo\Workspace\legisrh-dev\node_modules\tedious\lib\rpcrequest-payload.js:77:71)
    at generateParameterData.next (<anonymous>)
    at RpcRequestPayload.generateData (C:\Users\victo\Workspace\legisrh-dev\node_modules\tedious\lib\rpcrequest-payload.js:68:19)
    at generateData.next (<anonymous>)
    at C:\Users\victo\Workspace\legisrh-dev\node_modules\tedious\node_modules\readable-stream\lib\internal\streams\from.js:43:35
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\victo\Workspace\legisrh-dev\node_modules\tedious\node_modules\readable-stream\lib\internal\streams\from.js:3:103)
    at _next (C:\Users\victo\Workspace\legisrh-dev\node_modules\tedious\node_modules\readable-stream\lib\internal\streams\from.js:5:194)
    at C:\Users\victo\Workspace\legisrh-dev\node_modules\tedious\node_modules\readable-stream\lib\internal\streams\from.js:5:364
Emitted 'error' event on Readable instance at:
    at emitErrorNT (C:\Users\victo\Workspace\legisrh-dev\node_modules\tedious\node_modules\readable-stream\lib\internal\streams\destroy.js:87:8)
    at emitErrorAndCloseNT (C:\Users\victo\Workspace\legisrh-dev\node_modules\tedious\node_modules\readable-stream\lib\internal\streams\destroy.js:57:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_INVALID_ARG_TYPE'
```

Any tips?

**Comment by v1d3rm3** [comment]
With a little coding, i could make a reproduction of the problem.

```
import { Connection, Request, TYPES } from "tedious";

const conn = new Connection({
  server: "localhost",
  options: {
    trustServerCertificate: true,
    database: "test",
  },
  authentication: {
    type: "default",
    options: {
      userName: "SA",
      password: "devsetic@00",
    },
  },
});

conn.connect((err) => {
  if (err) {
    throw err;
  } else {
    console.log("it was connected");
  }

  const req = new Request(
    `SELECT * FROM [dbo].[Person] WHERE [name] LIKE @0`,
    (err, rows) => {
      if (err) throw err;
    }
  );

  req.on("row", function (columns) {
    console.log(columns);
    conn.close();
  });

  req.addParameter(0 as any, TYPES.VarChar, `%victor%`);

  conn.execSql(req);
});
```

In this line ``req.addParameter(0 as any, TYPES.VarChar, `%victor%`);``, i'm passing a number, and receive the error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (0)
    at Function.byteLength (buffer.js:728:11)
    at RpcRequestPayload.generateParameterData (C:\Users\victo\Workspace\tedious-test\node_modules\tedious\lib\rpcrequest-payload.js:77:71)     
    at generateParameterData.next (<anonymous>)
    at RpcRequestPayload.generateData (C:\Users\victo\Workspace\tedious-test\node_modules\tedious\lib\rpcrequest-payload.js:68:19)
    at generateData.next (<anonymous>)
    at C:\Users\victo\Workspace\tedious-test\node_modules\readable-stream\lib\internal\streams\from.js:43:35
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\victo\Workspace\tedious-test\node_modules\readable-stream\lib\internal\streams\from.js:3:103)
    at _next (C:\Users\victo\Workspace\tedious-test\node_modules\readable-stream\lib\internal\streams\from.js:5:194)
    at C:\Users\victo\Workspace\tedious-test\node_modules\readable-stream\lib\internal\streams\from.js:5:364
```
I think old versions of this driver accept numbers, not only strings, as param of `addParameter` (?), and now, it not accept anymore. It's a bug, or you'll not offer backward compatibility in this case?

**Comment by v1d3rm3** [comment]
With a little coding, i could make a reproduction of the problem.

```
import { Connection, Request, TYPES } from "tedious";

const conn = new Connection({
  server: "localhost",
  options: {
    trustServerCertificate: true,
    database: "test",
  },
  authentication: {
    type: "default",
    options: {
      userName: "SA",
      password: "xxxx",
    },
  },
});

conn.connect((err) => {
  if (err) {
    throw err;
  } else {
    console.log("it was connected");
  }

  const req = new Request(
    `SELECT * FROM [dbo].[Person] WHERE [name] LIKE @0`,
    (err, rows) => {
      if (err) throw err;
    }
  );

  req.on("row", function (columns) {
    console.log(columns);
    conn.close();
  });

  req.addParameter(0 as any, TYPES.VarChar, `%victor%`);

  conn.execSql(req);
});
```

In this line ``req.addParameter(0 as any, TYPES.VarChar, `%victor%`);``, i'm passing a number, and receive the error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (0)
    at Function.byteLength (buffer.js:728:11)
    at RpcRequestPayload.generateParameterData (C:\Users\victo\Workspace\tedious-test\node_modules\tedious\lib\rpcrequest-payload.js:77:71)     
    at generateParameterData.next (<anonymous>)
    at RpcRequestPayload.generateData (C:\Users\victo\Workspace\tedious-test\node_modules\tedious\lib\rpcrequest-payload.js:68:19)
    at generateData.next (<anonymous>)
    at C:\Users\victo\Workspace\tedious-test\node_modules\readable-stream\lib\internal\streams\from.js:43:35
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\victo\Workspace\tedious-test\node_modules\readable-stream\lib\internal\streams\from.js:3:103)
    at _next (C:\Users\victo\Workspace\tedious-test\node_modules\readable-stream\lib\internal\streams\from.js:5:194)
    at C:\Users\victo\Workspace\tedious-test\node_modules\readable-stream\lib\internal\streams\from.js:5:364
```
I think old versions of this driver accept numbers, not only strings, as param of `addParameter` (?), and now, it not accept anymore. It's a bug, or you'll not offer backward compatibility in this case?

**Comment by IanChokS** [comment]
` req.addParameter(0 as any, TYPES.VarChar, `%victor%`);`  The param type states `VarChar` which expects a string. If you want to pass a number, you might have to change `TYPES.VarChar` to `TYPES.Int` or something of a number type.

**Comment by v1d3rm3** [comment]
@IanChokS, sorry, i think i don't understand. Second argument refers to type of value or type of name of parameter.

What i want to say is that in older versions, the name of the parameter (first param of addParameter function -  [number] ``0 as any``)could be a `number`, for example? Or always the name of the parameter was a string?

Because in older version of mssql, at least, i could pass a number as name of parameter, and it worked. This error is from it:

`` The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (0)``
