### ISSUE TITLE
Unsupported Protocol Error

### ISSUE THREAD

**Issue by kagedevelopment** [tediousjs/tedious#1251]
I am seeing the below error when trying to connect to a local sql server database using tedious. I have tried both using the IP address and localhost and it won't connect. TCP/IP is enabled for MSSQLSERVER in sql server configuration manager. I also verified that sql server browser is also running. 

Error:

ConnectionError: Failed to connect to 127.0.0.1:1433 - 22996:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1942:

    at ConnectionError (E:\ExpressServer\kagetruckroutingappServer\node_modules\tedious\lib\errors.js:13:12)
    at Connection.socketError (E:\ExpressServer\kagetruckroutingappServer\node_modules\tedious\lib\connection.js:1641:56)
    at Socket.<anonymous> (E:\ExpressServer\kagetruckroutingappServer\node_modules\tedious\lib\connection.js:1405:14)
    at Socket.emit (events.js:326:22)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ESOCKET'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kagetruckroutingappserver@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kagetruckroutingappserver@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     Redacted

Code:
```
var Connection = require('tedious').Connection; 
var Request = require('tedious').Request;  
console.log('start')
var config = {
  server: 'localhost',
  authentication: {
    type: 'default',
    options: {
      userName: 'redacted', // update me
      password: 'redacted' // update me
    },
    options: {
      encrypt: false, 
      cryptoCredentialsDetails: {
        minVersion: 'TLSv1'
    }
    }
  }
}
    var connection = new Connection(config);  
    console.log('after connection variable')
    connection.connect();
    console.log('after connect')
    connection.on('connect', function(err) { 
      if (err) {
        console.log('Connection Failed');
        throw err;
      } 
        // If no error, then good to proceed.
        console.log("Connected");  
        
    });
```

**Comment by kagedevelopment** [comment]
$ npm tedious -v
6.14.8

**Comment by kagedevelopment** [comment]
I changed the server based on what I saw on Microsofts website and I'm now getting the error failed to login as user 'redacted'

```
var Connection = require('tedious').Connection; 
var Request = require('tedious').Request;  
console.log('start')
var config = {
  server: 'localhost.database.windows.net',  //update me
        authentication: {
            type: 'default',
            options: {
                userName: 'redacted', //update me
                password: 'redacted' //update me
            }
        },
 
}
    var connection = new Connection(config);  
    console.log('after connection variable')
    connection.connect();
    console.log('after connect')
    connection.on('connect', function(err) { 
      if (err) {
        console.log('Connection Failed');
        throw err;
      } 
        // If no error, then good to proceed.
        console.log("Connected");  
        
    });

```

**Comment by IanChokS** [comment]
Are you able to login using the latest version of tedious?

**Comment by kagedevelopment** [comment]
I tried the commands npm install tedious@11.0.8 and npm install tedious@latest and neither of them updated the version when i run the command npm tedious -v I still get 6.14.8

**Comment by IanChokS** [comment]
the latest version is 11.0.7. Try running the commands: `npm uninstall tedious` then `npm i tedious`. That should install the latest one

**Comment by kagedevelopment** [comment]
I am using version 11.0.7 now and I am still seeing the same error. I have verified that TCP/IP is enabled for MSSQLSERVER, SQL Server Browser is running and SQL Server agent is running. I am able to log into SSMS just fine using the credentials I am using in my code. Any idea what the issue is? I have seen people use just localhost or the IP Address for their connection. Why does mine only get to login failed when using  localhost.database.windows.net as the server? When I don't use that as the server it throws the original error that I posted.

**Comment by IanChokS** [comment]
What sql server version are you using?

**Comment by kagedevelopment** [comment]
SQL Server Management Studio						15.0.18206.0
Microsoft Analysis Services Client Tools						15.0.1567.0
Microsoft Data Access Components (MDAC)						6.3.9600.17415
Microsoft MSXML						3.0 5.0 6.0 
Microsoft Internet Explorer						9.11.9600.19963
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.9600

**Comment by IanChokS** [comment]
I mean what[ version of the database](https://sqlserverbuilds.blogspot.com/) are you using? You can [follow these steps](https://sqlserverbuilds.blogspot.com/2019/01/how-do-i-find-sql-server-version.html) to get the exact version

**Comment by kagedevelopment** [comment]
12.0.2269.0

**Comment by kagedevelopment** [comment]
I'm not going to be able to dig into this until Monday. I will let you know the results then. Thank you!

**Comment by kagedevelopment** [comment]
I have a ticket open with Internal IT to update this on our server. I will let you know the results once this is updated.

**Comment by kagedevelopment** [comment]
Updating SQL server fixed the issue. Thank you for your assistance!

**Comment by Estefania-Pichardo-Montes** [comment]
Hi, i have a similar problem, i can't connect to my database althrought the protocol TCP/IP is enabled in my computer, also make sure all the sql services are running, i got this error

ConnectionError: Failed to connect to localhost:1433 - self signed certificate
    at ConnectionError (C:\Users\Lauro\Documents\PruebaConexionSql\node_modules\tedious\lib\errors.js:13:12)
    at Connection.socketError (C:\Users\Lauro\Documents\PruebaConexionSql\node_modules\tedious\lib\connection.js:1641:56)
    at Socket.<anonymous> (C:\Users\Lauro\Documents\PruebaConexionSql\node_modules\tedious\lib\connection.js:1405:14)
    at Socket.emit (events.js:322:22)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'Failed to connect to localhost:1433 - self signed certificate',
  code: 'ESOCKET'
}

my code:

const config = {  
    server: 'localhost', 
    authentication: {
        type: 'default',
        options: {
            userName: 'user', 
            password: ''
        }
    },
    options: {
        encrypt: true,
        database: 'db'
    }
};  

const Connection = require('tedious').Connection;  
const config = require('./dbconfig');

const connection = new Connection(config);  
connection.connect();

connection.on('connect', function(err) {  
    if (err) {
        console.log(err);
    } else {
        console.log('Connected');
    }
});

im using the version of database 15.0.2000.5

SQL Server Management Studio						        15.0.18330.0
SQL Server Management Objects (SMO)						16.100.37971.0
Microsoft Analysis Services Client Tools						15.0.19040.0
Microsoft Data Access Components (MDAC)					10.0.19041.1
Microsoft MSXML						                                3.0 6.0 
Microsoft .NET Framework						                4.0.30319.42000
Operating System						                                10.0.19042

**Comment by kagedevelopment** [comment]
Try adding these options:

options: {
            encrpyt: true,
            trustServerCertificate: true

}

**Comment by IanChokS** [comment]
Try adding  `trustServerCertificate: true` in the config options.

**Comment by IanChokS** [comment]
@kagedevelopment can you open a new issue for this?

**Comment by kagedevelopment** [comment]
@Estefania-Pichardo-Montes If you are still having this issue, can you please create a separate issue for this?

**Comment by Estefania-Pichardo-Montes** [comment]
Hey, i already resolve the issue, adding the suggested option i get another error but i realize that the error was that i was using the user of windows authentication instead of an sql server user, thank you

**Comment by irzelindo** [comment]
> Try adding this options:
> 
> options: { trustServerCertificate: true
> 
> }

I had the same issue and this solution worked for me.

**Comment by kazzi58** [comment]
> Try adding this options:
> 
> options: { trustServerCertificate: true
> 
> }

Where exactly do I have to add this?

**Comment by mShan0** [comment]
Hi @kazzi58, this goes in your config object.

```
const config = {
  ...,
  options: {
      trustServerCertificate: true
  }
}
```

You can find more information here: http://tediousjs.github.io/tedious/api-connection.html

**Comment by ubilrodriguez** [comment]
a mi me sale este error:

ConnectionError: Failed to connect to localhost:1433 - 12864:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1994:
