### ISSUE TITLE
User assigned managed identity configuration cannot authenticate or authorize security token.

### ISSUE THREAD

**Issue by RalphK66** [tediousjs/tedious#1257]
I have tried:

```javascript
const config_MSI = {
  server: process.env.SQL_SERVER_NAME,
  authentication: {
    type: "azure-active-directory-msi-app-service",
    options: {
      clientID: process.env.APP_CLIENT_ID,
    },
  },
  options: {
    database: process.env.SQL_SERVER_DB_NAME,
    encrypt: true,
  },
};

// and...

const config_MSI = {
  server: process.env.SQL_SERVER_NAME,
  authentication: {
    type: "azure-active-directory-msi-app-service",
  },
  options: {
    database: process.env.SQL_SERVER_DB_NAME,
    encrypt: true,
  },
};

**Comment by IanChokS** [comment]
It doesn't look like its in our documentation (sorry), but you can try to add these fields in the authentication:
```js
authentication: {
          type: 'azure-active-directory-msi-app-service',
          options: {
            clientId: options.clientId,
            msiEndpoint: options.msiEndpoint,
            msiSecret: options.msiSecret
          }
        }
```
Also note `clientId` not `clientID`

**Comment by RalphK66** [comment]
In that thread that you lined in your first response, you mention that you had to add the resource for it to work for you... what resource are you referring to?

Also, I am pretty new to Azure, so I am not sure where to find the MSI_ENDPOINT and MSI_SECRET env variables... not sure that is something you might know but figured I may as well ask.

**Comment by IanChokS** [comment]
I found this article to be a very good summary of [how MSI works](https://marczak.io/posts/2019/07/securing-websites-with-msi/). I couldn't find how I tested the MSI changes in the previous MSI issue, so I'm not exactly sure what was required in the config to connect (sorry!). One thing to try is to make sure to enable 'User assigned', in your Azure App Service portal.

**Comment by IanChokS** [comment]
Hi @RalphK66, just wondering if you were able to resolve your issue? Or is this issue still present?

**Comment by IanChokS** [comment]
I was able to confirm that tedious still works with MSI authentication. Closing this for now, feel free to re-open if you're still running into issues.
