### ISSUE TITLE
Keeps defaulting to port eventhough I have specified a port.

### ISSUE THREAD

**Issue by Eratica** [tediousjs/tedious#1259]
`original: ConnectionError: Failed to connect to MyServer\\SQLServerInstance:1433 - getaddrinfo ENOTFOUND MyServer\\SQLServerInstance`

My port is not 1433 and I am not sure why it 1433 is being inserted when it is specified.

Everything worked until I attempt to connect to a remove server.

In Node I am using a .env file for connection properties.

`const dotenv = require('dotenv');
 dotenv.config();

module.exports = {
  development: {
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: "mssql",
  },
};`

I decided to update the version to 11.0.8 but still the same issue.

**Comment by IanChokS** [comment]
Hi @Eratica, it looks like you're trying to use `mssql` config options and not `tedious`. Please take a look at our getting s[tarted page here](https://tediousjs.github.io/tedious/)

**Comment by IanChokS** [comment]
I'm not too sure. Have you tried connecting using `tedious` library directly?
