### ISSUE TITLE
No event 'socketConnect' in state 'SentPrelogin'

### ISSUE THREAD

**Issue by praveenkpatare** [tediousjs/tedious#1263]
Trying to connect to MS SQL Server database using tedious and facing the above issue.

versions - 
Node - 12.18.3
Tedious - 6.14.5
MSSQL Server - 2012

Please help.

 Here is the detailed stack trace -

![image](https://user-images.githubusercontent.com/69985258/118182951-68fe0b80-b3ee-11eb-9076-ac1f23be6f4e.png)

**Comment by IanChokS** [comment]
Hi @praveenkpatare, do you get the same issue using the latest tedious driver 11.0.7?

**Comment by praveenkpatare** [comment]
Hello @IanChokS 

Received the below error after updating tedious

![image](https://user-images.githubusercontent.com/69985258/118192603-3e667f80-b3fb-11eb-9f84-65c5b65093ab.png)

**Comment by IanChokS** [comment]
I believe you're encountering the[ same issue here](https://github.com/tediousjs/tedious/issues/1251).  [Here's how you can fix it](https://github.com/tediousjs/tedious/issues/1251#issuecomment-830421680).

**Comment by praveenkpatare** [comment]
Thanks @IanChokS  it worked.

Although i changed the connection string to Sql Server on Azure.

**Comment by IanChokS** [comment]
Glad to hear it worked!
