### ISSUE TITLE
How to pass in a WHERE IN parameter

### ISSUE THREAD

**Issue by PhilHannent** [tediousjs/tedious#1264]
I am trying to use a WHERE id IN ('', '', '') clause. However, the current documentation does not make it clear how to add a parameter like this. Can someone explain the best way? 

I've coded up building the SQL statement but I'd rather a parameterised query.

https://tediousjs.github.io/tedious/api-request.html#function_addParameter

**Comment by IanChokS** [comment]
(I haven't tested this myself), but I would imagine it might be something like: 
```js
const sql = "... WHERE id IN ('@p1', '@p2')";
const request = new Request(sql, (err) => {...});
request.addParameter('p1', TYPES.VarChar, 'clientId1');
request.addParameter('p2', TYPES.VarChar, 'clientId2');
```

**Comment by arthurschreiber** [comment]
There's a few different approaches you could take (and none of them are really specific to `tedious`).

You can find some discussion and further links around this topic over at https://dba.stackexchange.com/questions/629/passing-array-parameters-to-a-stored-procedure.

Unfortunately, `tedious` does not support TVP parameters (yet!) - there's an open PR for that #1180 but it requires some more work.

Depending on the size of the ids that you want to pass in, either a temporary table or building the statement dynamically (like @IanChokS suggested) will be probably the best option right now.

Please let us know what approach you've taken! 🙇‍♂️

**Comment by PhilHannent** [comment]
For the record I went with a solution I am not happy with but is easy to understand:

````		
let ids = ''
for (let i = 0, len = deviceIDs.length; i < len; i++) {
	ids += `@p${i},`
}
// Remove the last comma
ids = ids.substring(0, ids.length - 1)
const sql = `SELECT * FROM tblDevices
		WHERE deviceId IN (${ids}) AND authorised = 1`

const request = pool.request()

for (let i = 0, len = deviceIDs.length; i < len; i++) {
	request.input(`p${i}`, sqlP.VarChar(sqlP.MAX), deviceIDs[i])
}

const result = await request.query<DeviceModel>(sql)
````

**Comment by arthurschreiber** [comment]
One small suggestion I'd have is to use `Array.join` instead to skip the last comma removal:

```js
let ids = []
for (let i = 0, len = deviceIDs.length; i < len; i++) {
	ids.push(`@p${i}`);
}
const sql = `SELECT * FROM tblDevices
		WHERE deviceId IN (${ids.join(', ')}) AND authorised = 1`
```

Another suggestion would also be to replace the `for` loop with `Array.map`, which calls the given function with the index as the second argument:

```js
const ids = deviceIDs.map((_, i) => `@p${i}`);
const sql = `SELECT * FROM tblDevices WHERE deviceId IN (${ids.join(', ')}) AND authorised = 1`
```

**Comment by PhilHannent** [comment]
@arthurschreiber Thanks for the feedback, I implemented it.
