### ISSUE TITLE
Authentication with Azure CLI

### ISSUE THREAD

**Issue by architshukla** [tediousjs/tedious#1284]
Feature request to add support for getting AAD access tokens using Azure CLI.

**Justification**
The tedious library supports Azure Managed Identity, which removes the need to manage credentials in production applications and moves that responsibility to the platform. This feature request would extend this "credential-less" access to a developer's local environment.
Typically, developers are logged in with Azure CLI and libraries like `@azure/ms-rest-nodeauth` and `@azure/identity` can use it to retrieve access tokens instead of having their application manage credentials.

**Proposed changes**
1. Add a new authentication type `azure-active-directory-azure-cli`.
2. Use an appropriate library function to get credentials from Azure CLI. As tedious is using `@azure/ms-rest-nodeauth` right now,  `AzureCliCredentials` will be used ([sample usage](https://github.com/Azure/ms-rest-nodeauth#getting-credentials-via-azure-cli)).

I have got it to work and I'm willing to contribute this functionality if the justification makes sense.

**Challenges**
1. I noticed that there is a plan for a [major refactor for authentication](https://github.com/tediousjs/tedious/issues/1144#issuecomment-803571215) with the end goal or removing a direct dependency on an authentication library. This seems like a long-term plan so this feature could be added in the interim.
2. The [first PR to refactor authentication types](https://github.com/tediousjs/tedious/pull/1242) has been open for a bit so it would be helpful to understand how this change should be prioritized against that. If that is planned to be merged soon, this change can wait for it. Otherwise, this can go in first.

**Comment by MichaelSun90** [comment]
Hi @architshukla, Thanks for this suggestion. We are also looking into migrating from the current ADD authentication lib to @azure/identity. Will have a discussion with the team.  Hi Arthur @arthurschreiber, do you have any thoughts on this.

**Comment by pgraham** [comment]
Hi,  now that v13 is release and has migrated to @azure/identity, being able to authenticate with AzureCliCredentials or DefaultAzureCredentials would be helpful in enabling credential-less auth for development tasks such as running tests against a database locally.

**Comment by aangelisc** [comment]
Hey @architshukla, how did you get this to work? Would you be able to provide a gist?
