### ISSUE TITLE
bulkLoad.addRow not adding rows to bulkLoad object

### ISSUE THREAD

**Issue by dozienwankwoh** [tediousjs/tedious#1322]
I am testing the bulk load functionality and I am not able to add rows to the bulkLoad object. I am not getting an error, but the "rows" item in the bulkLoad obect remains empty after my bulkLoad.addRow line. Please see code below. Has anyone experienced this?
---------------------------------------------------------------------------------------
const { Connection, Request, TYPES } = require("tedious");

const bulkInsertColumns = [
    {columnName: "column1",
    type: TYPES.Int,
    nullable:{nullable : true}
    },
    {columnName: "column2",
    type: TYPES.Int,
    nullable:{nullable : true}
    },
    {columnName: "column3",
    type: TYPES.Int,
    nullable:{nullable : true}
    },
    {columnName: "column4",
    type: TYPES.Int,
    nullable:{nullable : true}
    }
];

const bulkInsertRows = [
    {column1: 123,
     column2: 456,
     column3: 678,
     column4: 123,
    },
    {column1: 456,
     column2: 868,
     column3: 184,
     column4: 825,
    },
    {column1: 592,
     column2: 275,
     column3: 136886,
     column4: 68466,
    }
];

var options = { keepNulls: true };
const writeTable = 'results_test';

const conn = new Connection({
    authentication: {
        options: {
        userName: "test", // update me
        password: "test" // update me
        },
        type: "default"
    },
    server: "test", // update me
    options: {
        database: "test", //update me
        encrypt: true,
        rowCollectionOnDone: true
    }
});
            
var bulkLoad = conn.newBulkLoad(writeTable, options, function(error, rowCount){
if (error){
    context.log("hit bulk insert error:"+error)
}else{
    context.log(`inserted ${rowCount} rows`);
    }
        });

for (i in bulkInsertColumns){
    thisColObject` = bulkInsertColumns[i]
    bulkLoad.addColumn(thisColObject.columnName, thisColObject.type, thisColObject.nullable);
}

for (var row in bulkInsertRows){
    `bulkLoad.addRow(bulkInsertRows[row]);`
}

**Comment by arthurschreiber** [comment]
You need to call `connection.execBulkLoad` to actually execute the BulkLoad.

If you are on the most recent version of `tedious` you can also pass the list of row objects to the `connection.execBulkLoad` method instead of calling `bulkLoad.addRow`.

**Comment by dozienwankwoh** [comment]
@arthurschreiber thank you for your answer. This is just a snippet of the full code. 

My issue is with populating the `bulkInsert` obj before it is actually executed. I am debugging my code and watching variables and noticed that the `.addColumn` block works fine and populates the bulkInsert object. But the `.addRow` block does not populate the bulkInsert object. 

I am using tedious version 11.4.0.

**Comment by dozienwankwoh** [comment]
I've also tried running the sample code for Bulk Insert attached to this repo. I have a screenshot here of my variable window after the 2 `bulkLoad.addColumn` and 2 `bulkLoad.addRow` lines have been executed. The columns have been added to the bulkLoad object, but the rows were not. Has anyone else experienced this issue? thank you.

![Screen Shot 2021-08-14 at 11 29 11 AM](https://user-images.githubusercontent.com/53310162/129453053-d85ad2df-7494-4e32-8df6-7060403a1fd2.png)

**Comment by arthurschreiber** [comment]
> The columns have been added to the bulkLoad object, but the rows were not. Has anyone else experienced this issue?

This is working as intended. 😬 When you call `bulkLoad.addRow`, the row is not collected inside the `rows` property on the `BulkLoad`. (That property is internal on `BulkLoad` objects and is actually unused.) Instead, rows are written to the internal `RowTransform` (`rowToPacketTransform`) stream.

**Comment by dozienwankwoh** [comment]
Thank you @arthurschreiber. I had another issue in my code that was causing the rows not to write to the SQL table. It is working now.

Thanks for tending to these issues!
