### ISSUE TITLE
Execute raw query with parameters

### ISSUE THREAD

**Issue by lroal** [tediousjs/tedious#1326]
How can I execute a plain query with parameters ? The docs only refers to prepared queries explicitly type checked parameters.
And is it possible to do it without named parameters ?
Something like this:
connect.query('select id, name from _customer where id=?', ['someId']);

You can do this easiliy with other libs like https://www.npmjs.com/package/msnodesqlv8 or https://www.npmjs.com/package/pg

**Comment by arthurschreiber** [comment]
> How can I execute a plain query with parameters ?

I think `Connection.execSql` is the API method you're looking for.

> The docs only refers to prepared queries explicitly type checked parameters.

If you want to specify parameters, you need to specify the parameter types as well when you use `tedious`. There is no sensible way for us to deduce what parameter type should be used. E.g. `varchar`/`char`/`nvarchar`/`nchar`/`text`/`ntext` can all be used to send string parameters, but you need to decide which one is the correct one to use based on your application and database.

> And is it possible to do it without named parameters ?

Not really, not. Queries are executed via `sp_executesql`, which only supports named parameters. Other libraries might support this by internally transforming your query to use named parameters, but it's not something that I want to add to tedious. You are free to build a layer on top to do this for you, or use an existing library that builds on top of `tedious` and supports this.

**Comment by lroal** [comment]
Thanks for quick reply
