### ISSUE TITLE
Spurious `ReturnValue` event being issued

### ISSUE THREAD

**Issue by akc42** [tediousjs/tedious#1344]
I have just tried to upgrade from tedious 2.0.1 to tedious 12.2.0  

I went through all the breaking changes release notes and thought I had fixed everything (there are some bugs in the documentation, but I'll address those in another issue)

However I am getting a spurious `ReturnValue` event.  I checked (with some debug) that I had never called `request.addOutputParameter`  but I am still receiving the event.   The `parameterName` passed into this event is "handle"

I am not 100% when it occurs, I am inside a transaction with a series of `SELECT` statements that all return a single row, and it occurs after the `row` event, but since there is only one row event per (prepared) request I am not sure if its the end of the request.

**Comment by arthurschreiber** [comment]
@akc42 Thank you for reporting this issue!

I'm glad that the deprecation messages have been helpful, and it sounds like the upgrade process has been quite smooth for you, all things considered. 😅 

This `returnValue` event you're getting is stemming from this line here, I think: https://github.com/tediousjs/tedious/blob/7aea4fa207c053dc78b7f9586098cd1c1361958d/src/connection.ts#L3040

Just changing this to `output: false` should fix the issue you're seeing. Can you see if this works for you?

**Comment by akc42** [comment]
@arthurschreiber Well I don't use it very much, but I do use it.  are you saying its not working?
It certainly worked in the previous version I was using - haven't really checked it recently as its just a bunch of random counters that I update to tell me which part of my application has been accessed.

I include a snippet of code that I use, although I wrap tedious in a whole layer that lets me handle it it what I deem a much more convenient way for me.  I'll present to snippet and then how my code wrapper relates that to the tedious api

```
     try {
        debug('Snapshot function counters');
        let n;
        await database.connect(async connection => {
          debug('got a connection')
          await connection.transaction(async () => {
            debug('in transaction')
            const sql = `UPDATE FunctionCounts SET noOfCalls = NoOfCalls + @count WHERE FunctionName = @name
              IF @@rowcount = 0
              BEGIN
                INSERT INTO FunctionCounts(functionName,NoOfCalls) VALUES(@name,@count)
              END`;
            await connection.request(sql, async request => {
              debug('in request')
              request.addParameter('name', database.TYPES.NVarChar);
              request.addParameter('count', database.TYPES.Int);

              n = 0;
              debug('about to prepare SQL to update counters');
              await request.prepare(async () => {

                debug('created prepared request');
                for (let counter in counters) {
                  n++;
                  debug('Updating counter(', chalk.rgb(255, 136, 0).bold(counter), ') With ', counters[counter]);
                  await request.exec({ name: counter, count: counters[counter] }, null);
                }
                debug('Done all updates');

              });
            });
          });
```

Most of it can be obvious from the code above but
database is a constant that I set up in any module that want to use the database namely
```
const database = require('./common/database')
```
and its module exports a couple of values

```
  const  connections = new Map();
  module.exports = {
    ISOLATION_LEVEL: ISOLATION_LEVEL,
    TYPES: TYPES,
    connect: async function (callback) {
      const connection = new Connection()
      const id = uuidV4();
      connections.set(id, connection);
      debug('before callback in db.connect, connection id = ',chalk.redBright(id));
      const count = await callback(connection);
      debug('after callback in db.connect');
      await connection.close();
      connections.delete(id);
      return count;
    },
    close: async function() {
      for await (const [id,connection] of connections.entries()) {
        debug('closing connection id', id);
        await connection.close();
      } 
      connections.clear();
    }
  };
```

I have two classes `Connection` and `Request` that are wrappers to tedious `connection` and `request` objects

`connection.transaction` is essentially a wrapper function around three steps

1. Call tedious `connection.beginTransaction()`
2. Await the completion of the callback
3. Call tedious `connection.commitTransaction()`

Obviously there is error handling if callback throws and error to rollback the transaction

`connection.request` returns a new instance on its callback of a my wrapper `request` object

`request.prepare` is similar to `connection transaction` in that it is a wrapper function around 3 steps

1. Call tedious `connection.prepare(request)`
2. Await the completion of the callback
3. Call tedious `connection.unprepare(request)`

Again with error handling


My `request.addParameter` pretty well just hands this straight off to tedious `request.addParameter`, so as you can see in my usage snippet I am adding a generic two parameters to the request before calling prepare.

The request has two other calls `exec` executes the tedious `connection.execute` or tedious `connection.execSql` and `call` calls the tedious `connection.callProcedure`

When my `request.exec` has two parameters (as in the above snippet) is calls tedious `connection execute` otherwise its calling 
tedious `connection.execSql`

You will the notice that the second parameter in my `request.exec` call is null.  That is because its an in  UPDATE/INSERT statement not returning any rows.  However I can instead have an async callback, in which each raw row is passed to the callback (and we await its completion).  As tedious can be throwing new row events and any time, there is a whole hidden code of buffering of these rows (up to a limit).  At the limit I call tedious `request.pause` and request.resume` is called.

I wrote all this wrapper library in February of this year after using tedious through a more traditional non `async\await` structure for about 4 years before that.  That had the above snippet in its old form so I have been using prepared statements like that for a long time.

**Comment by arthurschreiber** [comment]
@akc42 I totally missed that `execute` takes a `params` argument (which is what allows reusing the prepared statements). 🙈 I mixed it up with `execSql`/`execSqlBatch`.

Anyway, thank you for the long explanation and code examples about how you're using `tedious`, and the layer you have built on top to make it easier to use with `async`/`await`. I really want to bring something similar into `tedious` itself, to make it easier to use (and maintain), but I'm still not 100% sure about how to best make this work, especially with the sort of "streaming" nature that responses. I'll try to ping you if any development happens in that area.

On another note, where you able to see if https://github.com/tediousjs/tedious/pull/1347 solves the issue you've been running into?
