### ISSUE TITLE
No collation was set by the server for the current connection

### ISSUE THREAD

**Issue by frandominguez03** [tediousjs/tedious#1349]
I'm following [BulkLoad](https://tediousjs.github.io/tedious/bulk-load.html) docs to insert multiple rows at once in my database. I'm getting this error:

> No collation was set by the server for the current connection in TediousJS

When my script tries to execute the following line:

```js
bulkLoad.addRow(TYPES.Null, col2, col3, col4, col5, TYPES.Null, col7, 
                                col8, col9, TYPES.Null, TYPES.Null, TYPES.Null);
```

What does this error mean? Why I haven't gotten it before using `bulkLoad`? How do I solve this?

Thanks!

**Comment by arthurschreiber** [comment]
Interesting. 🤔

We recently fixed a bug where `varchar` parameters sent from the client to the server could end up as garbage on the serverside because `tedious` did not respect the database's collation. This was fixed by taking the collation sent back by the server during the login phase and sending all future data encoded according to this collation.

I'm pretty sure that all recent versions of SQL Server always send back a collation value during log in, so the code has an assertionwhen sending `varchar` to ensure a collation was set, that's where the error you're seeing is coming from.

Which version of SQL Server are you running against?

**Comment by frandominguez03** [comment]
Thanks for the fast answer!

My current version is Microsoft SQL Azure (RTM) - 12.0.2000.8.

**Comment by arthurschreiber** [comment]
Do you know what the collation is set to, by chance? You can look it up in the Azure Portal, or using a SQL statement like:

```
SELECT DATABASEPROPERTYEX('<your database name here>', 'Collation')
```

**Comment by frandominguez03** [comment]
Apparently, that query is returning `NULL`. Is that even possible?

Should I try [this](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-database-collation?view=sql-server-ver15#TsqlProcedure) to set a Collation?

**Comment by arthurschreiber** [comment]
I don't think you can set a collation for an azure database using an sql statement. Actually, I think azure database collation can't be changed at all after creation.

I assume you don't have access to the Azure Portal to check what collation is specified there?

This is really confusing (and unexpected!). Sorry for the trouble here. The easiest workaround for you would be to use an older version of tedious for the time being. Still, if you could help me troubleshoot what's going on here, I'd be very thankful! ❤️

**Comment by frandominguez03** [comment]
Yes, I do have access to the Azure Portal. Let me investigate where the collation is and I will report back.

And no worries, I'll try to help as much as I can. Thanks a lot for the support!

**Comment by arthurschreiber** [comment]
You can find the collation under "Settings" -> "Properties" if you view the database.

**Comment by frandominguez03** [comment]
Found! It is `SQL_Latin1_General_CP1_CI_AS`.

**Comment by arthurschreiber** [comment]
So the server has a collation set, but your database does not? 😕

**Comment by frandominguez03** [comment]
Well, turns out I was typoing the database command. Now both return the same `SQL_Latin1_General_CP1_CI_AS`. Sorry about that!

**Comment by arthurschreiber** [comment]
Okay. 😅 That at least makes sense now! I'm going to try and reproduce this (I have a Azure SQL instance with the same collation settings). I'll let you know if I can find something!

**Comment by arthurschreiber** [comment]
Can you check `connection.databaseCollation` after connecting (but before sending your bulk load?)

```
console.log(connection.databaseCollation);
```

gives me the following:

```
Collation {
  lcid: 1033,
  flags: 13,
  version: 0,
  sortId: 52,
  codepage: 'CP1252',
  buffer: undefined
}
```

**Comment by frandominguez03** [comment]
It says `undefined` for me

**Comment by arthurschreiber** [comment]
Do you specify the database name in the connection options? 🤔

**Comment by frandominguez03** [comment]
I create the connection like this:

```js
const connection = new Connection(db_config);
connection.connect();
```

With `db_config` being: 
```json
{"authentication": {"options": {"userName":"XXX","password":"YYY"},
"type":"default"},
"server":"ZZZ.windows.net",
"options":{"database":"myDB","encrypt":true}}
```

I believe it's correct since I've previously inserted rows in the database, without the `bulkLoad`.

**Comment by arthurschreiber** [comment]
Are you waiting on the callback from `connection.connect();` before you create the bulk load / access `connection.databaseCollation`?

The connection is not fully set up before that, and there's currently a bit of a quirk around collations with bulk loads in that the collation is copied in the bulk load from the connection at the time the bulk load is created.

So, if you do:

```js
const connection = new Connection(db_config);
connection.connect((err) => {
  if (err) {
    // handle error
  }

  console.log(connection.databaseCollation);
});
```

Do you still get `undefined` back?

**Comment by frandominguez03** [comment]
Nope, I wasn't waiting for it. It now says:

```json
Collation {
    lcid: 1033,
    flags: 13,
    version: 0,
    sortId: 52,
    codepage: 'CP1252',
    buffer: undefined}
```

**Comment by arthurschreiber** [comment]
Perfect. As a general rule, you should wait for the `connect` callback to be called before you do anything with the connection. The specific bug you've encountered here will probably be fixed in some future version of `tedious`, but it will never be safe to use the connection before it was fully set up. 👍 

I guess this can be closed now? 🤔

**Comment by frandominguez03** [comment]
So what's the workaround here? I'm adding rows to the `bulkLoad` instance inside a for loop. Am I supposed to instantiate `bulkLoad` in the callback of the connection and then add the rows in the loop? Or am I supposed to do everything in the callback of the connection?

**Comment by arthurschreiber** [comment]
You're right, you need to do all your work inside the callback. It's also not a workaround in that case, but the "proper way of doing things". 😅 

That's nothing specific to `tedious` really, but a fundamental part of the callback style programming in Node.js. Whether you open a file, a network socket or perform any other asynchronous task, you need to wait for the results to be communicated via the callback before you can do any work that relies on the previous steps having happened.

See https://nodejs.dev/learn/javascript-asynchronous-programming-and-callbacks as a general introduction to this concept.

**Comment by frandominguez03** [comment]
Got it. Thanks for your help!

**Comment by arthurschreiber** [comment]
Thanks for being so helpful in getting down to the root cause of this issue! I'll make sure that we really highlight this better in our documentation that the connection is in a half-baked state if you don't wait for the `.connect` callback to fire. 🙇‍♂️
