### ISSUE TITLE
Connection error - Connect.js

### ISSUE THREAD

**Issue by naushadck** [tediousjs/tedious#1354]
By referring this https://www.microsoft.com/en-us/sql-server/developer-get-started/node/windows/step/2.html, 
the connection.js giving error. 

Error screen shot.
![image](https://user-images.githubusercontent.com/70026286/135803433-59762280-5a79-40ca-a5bd-b70bda028f06.png)

**Comment by arthurschreiber** [comment]
I don't think this error has anything to do with `tedious`. It looks like the `uuid` module you're using uses `import`/`export` statements, but your Node.js version does not support those.

**Comment by arthurschreiber** [comment]
The sample you posted here includes no reference to `uuid`. 🤔 

Which version of Node.js are you using? You need to be using at least version 12.x for the latest version of `tedious`.

**Comment by naushadck** [comment]
1. The sample you posted here includes no reference to uuid. 

         The sample is refereed in the "Getting Started" Section. (Node.js + Windows) in https://github.com/tediousjs/tedious 
               (readme.md)       
         How can i include uuid in the sample script similar one ?. 
         

2.  Which version of Node.js are you using? You need to be using at least version 12.x for the latest version of tedious.
            Node.js version 13.x 
            tedious version  - Installed using   npm install tedious 
                (described in the installation section of readme.md)
