### ISSUE TITLE
@azure/identity 2.0 - removed python dependency & security fixes

### ISSUE THREAD

**Issue by tamusjroyce** [tediousjs/tedious#1360]
When might this be updated to use https://www.npmjs.com/package/@azure/identity 2.0 (released two days ago)? I'm excited as python isn't supported in all our environments. And this will speed our pipelines up quite a bit. Thank you for this great project!

**Comment by MichaelSun90** [comment]
We will definitely look into this migration to identity 2.0. Just did a brief check of their changes log, and seems the changes are mainly related to error handling and browser interactive auth. What do you think Arthur @arthurschreiber?  Do you think this is something that we can quickly absorb into tedious? 
By the way, @tamusjroyce, just curious, is this the part "Identity v2 no longer includes native dependencies (neither ordinary, peer, nor optional dependencies). Previous distributions of @azure/identity included an optional dependency on keytar, which caused issues for some users in restrictive environments."(copied from their changelog) that causes you to want to have version identity 2.0?

**Comment by tamusjroyce** [comment]
That is correct

**Comment by vineelgarimella** [comment]
Hi @MichaelSun90  , do you have an ETA on which can we have the  https://www.npmjs.com/package/@azure/identity dependency updated to 2.x.x as stated above? We are currently waiting for the migration to resolve some of our security issues . Thanks

**Comment by MichaelSun90** [comment]
Hi @vineelgarimella, unfortunately, we do not have an exact ETA yet for this. We are definitely considering making this upgrade soon. If we got an ETA or made this upgrade, we will definitely put an update here.

**Comment by tamusjroyce** [comment]
Opps. Forgot to close this after I saw this had been done. Thank you for this!!!
