### ISSUE TITLE
server responded with unknown TDS version

### ISSUE THREAD

**Issue by j535158420** [tediousjs/tedious#1362]
tdsVersion:"7_1"

**Comment by v-mabarw** [comment]
Hi @j535158420, what version of SQL Server are you attempting to connect to?

**Comment by MichaelSun90** [comment]
Hi @j535158420 , Can you provide us with a bit more detail on your issue?

**Comment by arthurschreiber** [comment]
@j535158420 without more details on this issue, there's no way we can provide help. I'm going to close this issue. If you can provide further information, we can re-open this. 🙇‍♂️
