### ISSUE TITLE
Connection to named instance

### ISSUE THREAD

**Issue by terror2012** [tediousjs/tedious#1364]
I'm trying to connect to a named instance on the VPN network, using hostname\instancename as provided by the documentation, but I'm getting socket hang up. I have this issue with both sequelize and mssql, since both use tedious as their driver.

As a side-note, I can successfully connect to this instance using Heidisql with the TCP/IP MSSQL connection (using the same configuration, server as hostname, and user/pass combination), but nodejs won't connect to the instance, and I'm not sure what's the issue

Expected behaviour:
Connect to the instance successfully.

Actual behaviour:
ConnectionError: Failed to connect to SQLHOST2:undefined - socket hang up

Configuration:
const config = {
user: test1,
password: testPass,
server: "SQLHOST2\Instance",
database: TestDB,
}

Software versions
NodeJS: 17.0.1
node-mssql: 7.2.1 or sequelize: 6.7.0 (config variable changed to accommodate sequelize mssql connection schema, but the same details)
tedious: 14.0.0
SQL Server: Microsoft SQL Server 2014 (v12)

**Comment by MichaelSun90** [comment]
Hi @terror2012 ,

I have set a quick test locally, and the connection sees works for me. 

this is what my test looks like: 
``` node
const sql = require('mssql')
const sqlConfig = {
  database:'master',
  user: `<windows user name>`,
  domain:'<windows user domain>',
  password: `<windows password>`,
  server: `machinename\instancename`,
  port: 1433,
  options: {
    encrypt: false, // for azure
    trustServerCertificate: false // change to true for local dev / self-signed certs
  }
}

let test = async () => {
 try {
  await sql.connect(sqlConfig)
  const result = await sql.query`select @@servername`
  console.dir(result)
 } catch (err) {
    console.dir(err)
 }
}
test()
```

The only thing I think that I modified is I set " encrypt: false, " in the option.  You can try that, see if it helps.

**Comment by terror2012** [comment]
> Hi @terror2012 ,
> 
> I have set a quick test locally, and the connection sees works for me.
> 
> this is what my test looks like:
> 
> ```js
> const sql = require('mssql')
> const sqlConfig = {
>   database:'master',
>   user: `<windows user name>`,
>   domain:'<windows user domain>',
>   password: `<windows password>`,
>   server: `machinename\instancename`,
>   port: 1433,
>   options: {
>     encrypt: false, // for azure
>     trustServerCertificate: false // change to true for local dev / self-signed certs
>   }
> }
> 
> let test = async () => {
>  try {
>   await sql.connect(sqlConfig)
>   const result = await sql.query`select @@servername`
>   console.dir(result)
>  } catch (err) {
>     console.dir(err)
>  }
> }
> test()
> ```
> 
> The only thing I think that I modified is I set " encrypt: false, " in the option. You can try that, see if it helps.

The solution was encrypt: false
Apparently leaving it empty or setting it to true gives the socket hang up error, setting it to false makes everything work perfectly. Thanks a lot for the help!
