### ISSUE TITLE
Data type of returnValue

### ISSUE THREAD

**Issue by anton-johansson** [tediousjs/tedious#1366]
Hi!

I'm using the `mssql` node package, which depends on this package. I'm using TypeScript, and my dependencies look like this:

```json
{
  "dependencies": {
    "mssql": "7.2.1"
  },
  "devDependencies": {
    "@types/mssql": "7.1.4"
  }
}
```

I know this is not directly related to this repository. However, since the source property (`returnValue`) comes from this repository, I thought I'd start here. From the `@types/mssql` package, the `returnValue` property is typed as `any`. I would love to treat this as a `number`. Can anyone where verify to me whether or not the contents of this property can be anything other than a `number`?

Thanks in advance!

**Comment by MichaelSun90** [comment]
Hi @anton-johansson, can you point me to where this returnValue property is?  I have not used mssql, but if you point me where the resurnValue is, I could help you verify whether it is can be restricted to a number type on the tedious side.

**Comment by anton-johansson** [comment]
Hey @MichaelSun90!

The TypeScript defintion for `returnValue` can be found here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mssql/index.d.ts#L148

I'm assuming it's these lines (mostly guessing here):
https://github.com/tediousjs/node-mssql/blob/master/lib/tedious/request.js#L955-L957

**Comment by MichaelSun90** [comment]
Hi @anton-johansson , just checked. On tedious, there is a "procReturnStatusValue: undefined | any;" which should be corresponding to "returnStatus" here: 
```node
req.on('doneProc', (rowCount, more, returnStatus) => {
          returnValue = returnStatus
        })
```
I have searched around and seems "procReturnStatusValue"  is only treated like a "number" type. From this, I think it should be safe to treat it as a number type. However, I can only confirm this from the tedious side, on mssql side, there could be other things that rely on this and they are not restricted to just number type. 

We can check with the project owners. @arthurschreiber  and @dhensby, what do you guys think?

**Comment by dhensby** [comment]
It's treated as an int in `node-mssql`

**Comment by anton-johansson** [comment]
That's awesome! Thanks a bunch for looking it up. I assume this means that we could change the data type in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mssql/index.d.ts#L148.

**Comment by dhensby** [comment]
certainly looks that way

**Comment by dhensby** [comment]
NB: but if tedious is declaring it as undefined|any then we probably should too

**Comment by arthurschreiber** [comment]
👋 @anton-johansson,

`number` is the correct type here. Unforunately, this is not typed correctly in `tedious`, and changing the type information would require us to be a bit more strict about verifying that the server is sending data in the correct order. `tedious` is a bit lax about this right now.

I don't think there's much harm to type this differently than the way it's typed in `tedious` - as long as the server is sending "correct" response data this value will always be a `number`.
