### ISSUE TITLE
Connection failed by logon trigger

### ISSUE THREAD

**Issue by ramgee-da** [tediousjs/tedious#1370]
![image](https://user-images.githubusercontent.com/74703845/144786482-8a98d266-ade7-49d0-b1b5-f5842a8c4c1d.png)

I'm testing server trigger on my production server. 
tedious connection fails when CRUD command exists on logon tirigger. 
here's my logon trigger

USE [master]
GO

/****** Object:  DdlTrigger [block_ipaddress]    Script Date: 2021-12-02 ¿ÀÀü 10:40:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER TRIGGER [block_ipaddress] ON ALL SERVER FOR LOGON 
AS
BEGIN 
			SET ANSI_PADDING ON
			DECLARE @capturedip NVARCHAR(15)
			SELECT  @capturedip

END

GO

it technically do nothing but declaere and select variable, '@capturedip' . 
The strange thing is when I commented out 'SELECT  @capturedip', tedious connection successed and works perfectly. 
As production DB server must be protected by multiple secrity processes, I cannot remove logon trigger. 
Can anybody solve this problem?

**Comment by MichaelSun90** [comment]
Hi @ramgee-da, I found someone who asked the same question at the Microsoft Q&A: https://docs.microsoft.com/en-us/answers/questions/652299/tedious-cannot-be-authenticated-logon-trigger.html. 
I think DanGuzman' s under this link will be helpful to you. Let me know if that helps.

**Comment by ramgee-da** [comment]
I still need help
