### ISSUE TITLE
How to use mssql connection using ip/instance?

### ISSUE THREAD

**Issue by marcelodelta** [tediousjs/tedious#1377]
I'm trying to connect to a production MSSQL instance but it fails to connect.

Could anyone help?

I'm grateful for the community's attention.

.env
MSSQL_SERVER=ip/instance
MSSQL_PORT=1433
MSSQL_USER=sa
MSSQL_PASSWORD=password
MSSQL_DB_NAME=database

"message": "Failed to connect to ip/instance:1433 - getaddrinfo ENOTFOUND ip/instance",

**Comment by MichaelSun90** [comment]
Hi @marcelodelta , I saw you have closed the issue. Did you get it resolved on your side?  If you got it resolved, may I ask what was the issue, and how did you get it resolved?
