### ISSUE TITLE
Error: Requests can only be made in the LoggedIn state, not the LoggedInSendingInitialSql state . Error: Requests can only be made in the LoggedIn state, not the SentLogin7WithStandardLogin state.

### ISSUE THREAD

**Issue by martnjf** [tediousjs/tedious#1391]
Hello everyone, a few days ago I asked about an issue, that wasn't really an issue, but I was helped by MichaelSun90, [here it is](https://github.com/tediousjs/tedious/issues/1375).
To resume the problem is that, I need to insert multiple objects into a DB in SQLServer, so I was told here that I needed to change my code to make multiple request, so I did it.

## My issue
The issue is that when I run my code in my PC, with the corrections I was told here, it runs perfectly, not a single error, but when I try to run it in the PC of my job, I get the following errors:

````
Error: Requests can only be made in the LoggedIn state, not the LoggedInSendingInitialSql state
Error: Requests can only be made in the LoggedIn state, not the SentLogin7WithStandardLogin state
```` 
I have 69 objects, my code sometimes inserts 50, sometimes 40, sometimes 30... and showing this message error.

## What I expect
I'm expecting to know why it doesn't work perfectly in the other PC, as it does in mine, I would like to know if I need to change something in the config of something or if it's just a hardware issue or something about the server (As you can see, I am not an expert in this things)

## My Code
This is my code, the same as the last time but corrected:
```
var config = {
   ...
};

function insertOffice(index) {
    var connection = new Connection(config);
    connection.on("connect", function (err) {
        console.log("Successful connection");
    });
    connection.connect();
    
    let url = `https://api.openweathermap.org/data/2.5/weather?lat=${offices[index].latjson}&lon=${offices[index].lonjson}&appid=${api_key}&units=metric&lang=sp`;
    fetch(url)
        .then((response) => { return response.json(); })
        .then(function (data) {
            var myObject = {
                Id_Oficina: offices[index].IdOficina,
                ...
            };

            const request = new Request(
                "EXEC USP_BI_CSL_insert_reg_RegistroTemperaturaXidOdicina @IdOficina, ...",
                function (err) {
                    if (err) {
                        console.log("Couldnt insert data (" + index + "), " + err);
                    } else {
                        console.log("Data with ID: " + myObject.Id_Oficina +" inserted succesfully(" + index + ").")
                    }
                }
            );
            request.addParameter("IdOficina", TYPES.SmallInt, myObject.Id_Oficina);
            ...
            request.on("row", function (columns) {
                columns.forEach(function (column) {
                    if (column.value === null) {
                        console.log("NULL");
                    } else {
                        console.log("Product id of inserted item is " + column.value);
                    }
                });
            });
            request.on("requestCompleted", function () {
                connection.close();
            });
            connection.execSql(request);
        });
}

function functionLooper() {
    for (let i = 0; i < offices.length; i++) {
        let response = insertOffice(i);
    }
}

functionLooper();
```

## What I believe
I believe the server I'm trying to reach have some security stuff that doesn't let me send this multiple times, so I thought it was a good idea to add a delay, just doing:
1. Run ```functionLooper()``` 
2. Open the connection.
3. Make a request and insert the object.
4. Close the connection.
5. Delay.
6. Repeat.

Is this something about the server config? I tried googling the message Error but I didn't find anything about it and [here](http://tediousjs.github.io/tedious/frequently-encountered-problems.html) there are some errors, but not mines.
Thank you, anything you want me to clarify let me know.

Here's my [stackoverflow post](https://stackoverflow.com/questions/70872413/how-can-i-add-a-settimeout-to-run-a-function-and-insert-data-multiple-times) with a little more details.

## Edit
The idea of using a delay worked, but I still would like to know why without it doesn't in the other PC, thank you :)

**Comment by MichaelSun90** [comment]
Hi @martnjf , we have discuses within the teams. From what you have provided. it seems you are trying to send request when the corresponding connection has not been full formed. Your code works for you own PC but not work PC could because that these two PCs has different performances. The performance difference may cause a delay during the run time which allows the connection to be fully formed before request has been sent our. This also explains why add a delay manually helps with the problem. 

One thing you could try with you current code is put everything from line `let url = https://api.openweathermap.org/data/2.5/weather?` to
 `connection.execSql(request);
        });` in to a call back function for `.connect`
        
The code will looks something like: 
` connection.connect(()=>
{
let url = https://api.openweathermap.org/data/2.5/weather?
...
connection.execSql(request);
        });
});`        
The call back function will only be called when the connection is fully formed, so this should prevent that request to be sent before connection is fully formed. 

Hope this helps you.

**Comment by martnjf** [comment]
Once again, thank you so much for your answer and your time @MichaelSun90! It helped me alot :)
