### ISSUE TITLE
Github reporting a high severity security issue with simple-get

### ISSUE THREAD

**Issue by akc42** [tediousjs/tedious#1392]
I am getting a high severity security issue from `simple-get`.  As far as I can work out it comes from tedious use of @azure/identity which is currently shown in your package.json as v 1.5.2

npm does show a v2 of this package, although it appears to have breaking changes,

**Comment by clshortfuse** [comment]
````
node_modules/simple-get
  prebuild-install  <=6.1.4
  Depends on vulnerable versions of simple-get
  node_modules/prebuild-install
    keytar  4.2.0 - 4.3.1 || 4.4.1 - 7.0.0 || >=7.2.0
    Depends on vulnerable versions of prebuild-install
    node_modules/keytar
      @azure/identity  1.1.0-dev.20200310.1 - 2.0.0-beta.6
      Depends on vulnerable versions of keytar
      node_modules/@azure/identity
        tedious  >=11.0.9
        Depends on vulnerable versions of @azure/identity
        node_modules/tedious
```

https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/migration-v1-v2.md

>If you use the VisualStudioCodeCredential, you likely have keytar in your dependencies. keytar is a popular native machine-code dependency in the Node.js ecosystem. NMC dependencies were removed from @azure/identity and put into individual packages. To use the VisualStudioCodeCredential with Identity v2, complete the following steps:

**Comment by michaelpinnell** [comment]
curious as to the timeline of releasing a new version of tedious with this bump in it

**Comment by debasis-mondal** [comment]
@pekim Can we please have the new version of tedious with bumped up @azure/identity soon?

**Comment by debasis-mondal** [comment]
thanks @clshortfuse, your suggestion is working for me. But, as you mention we only need the dependency on certain condition, can we mark that as peer dependency?

**Comment by clshortfuse** [comment]
@debasis-mondal I'm not sure of the consequences in using `peer-dependency`, but I know `override` was specifically created for this situation:

>If you need to make specific changes to dependencies of your dependencies, for example replacing the version of a dependency with a known security issue, replacing an existing dependency with a fork, or making sure that the same version of a package is used everywhere, then you may add an override.

Using a `peer-dependency` makes all packages use that version. We know forcing `tedious` to use `@azure/identity@2.0.1` is safe without any code changes, but if you had another package that also uses `@azure/identity` v1, it might crash when forcing it to use v2.
