### ISSUE TITLE
RequestError: Requests can only be made in the LoggedIn state, not the Connecting state

### ISSUE THREAD

**Issue by ANTGOMEZ** [tediousjs/tedious#1397]
I see this error was talked about here: [https://github.com/tediousjs/tedious/issues/458](url) and I tried the suggested solution, but it didn't work for me.

Here is my code:

`

        exports.exec_sql_cmd = async function(cmd)

        {

        var config = {  

            server: 'xx.xx.xx.xx',

            authentication: {

                type: 'ntlm',

                options: {

                    userName: 'master',

                    password: 'masterp',

		   domain: 'the.domain.com'

                }

            },

            options: {            

                encrypt: false,

                database: 'tblTest'

            }

        };  

        var connection = new Connection(config);

        connection.on('connect', function(err) { 

            console.log("Connected");  

            executeStatement();

        });
    
     connection.connect();
          
    function executeStatement() {  
        var request = new Request(cmd, function(err) {  
         if (err) {  
            console.log(err);}  
        });  
        
        request.on('row', function(columns) {  
            columns.forEach(function(column) {  
              if (column.value === null) {  
                console.log('NULL');  
              } else {  
                console.log("Row Inserted");  
              }  
            });  
        });
       
        request.on("requestCompleted", function (rowCount, more) {
            connection.close();
        });
        connection.execSql(request);  
    }

    }
`

I do get connected (this line runs: _console.log("Connected");_ ), but then this error is thrown:
`RequestError: Requests can only be made in the LoggedIn state, not the Connecting state`

The context of all this is: I'm trying to perform an INSERT from AWS Lambda back down to an On-Prem MS SQL database.

Thanks in advance.

**Comment by mShan0** [comment]
Hi @ANTGOMEZ, 

I've noticed that `connection.on` is not handling the error parameter in the callback function. Could you try handling it in a similar fashion to `executeStatement`? I.e. print the error if it exists. The connection function could be missing an error coming from the database side with more details.

**Comment by ANTGOMEZ** [comment]
Hi,

This is the code I am using now, below. When I run it, it doesn't throw any errors, but it doesn't do anything.

The function lives in a separate file. But that's not an issue, it does get called and the method is invoked. Now I'm getting the config from ParamStore in AWS, I have verified that that's good. It's the same as the prior code I submitted, so that's not an issue.

I put the error catch like you asked, but this has no effect. No error is thrown, but the record is never inserted in the DB, I did print out the record being inserted by this method and I manually ran that insert command in the DB and it works as expected.

I should mention that it did work for a little while, then it didn't any more.

exports.exec_sql_cmd = async function(conn_store, cmd)
  {
    let config = await exports.get_parameter(conn_store)

    const connection = new Connection(JSON.parse(config));
    connection.on('connect', function(err) {
    if (err) {
        console.log("CONNECTION ERROR: "+err);
    }
    // If no error, then good to proceed.
    console.log("Connected");
    executeStatement();
    });

    function executeStatement() {
    let request = new Request("select top 1 RoleID from Roles;", function (err) {
        if (err) {
            console.log("REQUEST ERROR: "+err);
        }
    });
    let result = "";
    request.on('row', function(columns) {
        columns.forEach(function(column) {
        if (column.value === null) {
            console.log('NULL');
        } else {
            result+= column.value + " ";
        }
        });
        console.log(result);
        result ="";
    });

    request.on('done', function(rowCount, more) {
        console.log(rowCount + ' rows returned');
    });

    // Close the connection after the final event emitted by the request, after the callback passes
    request.on("requestCompleted", function (rowCount, more) {
        connection.close();
    });
    connection.execSql(request);
    }
}

**Comment by mShan0** [comment]
I've noticed that your new code block is missing a `connection.connect()` call. Could you add that in and try it again?

**Comment by ANTGOMEZ** [comment]
Oops, missed that, but after adding that back in, now I'm back to this error:

CONNECTION ERROR: Error: Failed to connect to xx.xx.xx.xx:1433 in 15000ms
Connected
REQUEST ERROR: Error: Requests can only be made in the LoggedIn state, not the Connecting state

So the Connection event is at least fired, but ...

**Comment by mShan0** [comment]
Thanks for doing that. Will take a look into this. Can I get the Node version and Tedious version you are using?

**Comment by ANTGOMEZ** [comment]
Thanks for your kind help.

Node: v17.1.0
Tedious: 14.1.0

**Comment by mShan0** [comment]
I'm not 100% sure if this is the same issue you have, but there has been an issue with NTLM authentication when using Node 17 (as Tedious does not officially support Node 17 currently). If you throw the error inside of this block: 
```    
if (err) {
    console.log("CONNECTION ERROR: "+err);
    throw err;
}
```
and you see an error message similar to this one: [https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported](url), Node 17 may be the issue since Node upgraded to OpenSSL v3 and there are some compatibility issues. If it is possible to downgrade to Node 16, try that.

If that does not fix your issue, can you enable debugging to see a more detailed log?

```
 var config = {  
        server: 'xx.xx.xx.xx',
        authentication: {
            type: 'ntlm',
            options: {
                userName: 'master',
                password: 'masterp',
	   domain: 'the.domain.com'
            }
        },
        options: {            
            encrypt: false,
            database: 'tblTest'
            // Add this to your configuration file. You can pick and choose which ones to enable. 
            debug: {
                packet: true,
                data: true,
                payload: true,
                token: true
            }
        }

    };  
```
Then add this event listener to output the debug messages:
```
  connection.on('debug', (msg) => {
    console.log(msg);
  });
```

**Comment by ANTGOMEZ** [comment]
Sorry for the late response. But I did switch back to Node 16 and it worked.

Thank you for your help!
