### ISSUE TITLE
azure-active-directory-password not working passed v12.3.0

### ISSUE THREAD

**Issue by joelvarty** [tediousjs/tedious#1398]
When I attempt to use tedious greater than v12.3.0 with azure active directory password, I get a weird warning, and an error.  

Warning is this:
```
DeprecationWarning: When using the `azure-active-directory-password` authentication method, please provide a value for the `clientId` option. This option will be required in a future release.
```

Error is this:
```
Security token could not be authenticated or authorized.
```

When I run the code with v12.3.0, it works just fine.

Here's my example code (based on a tutorial from Microsoft Docs...)
````

const { Connection, Request } = require("tedious");

// Create connection to database
const config = {
  authentication: {
    options: {
      userName: "username", // update me
      password: "password" // update me
    },
    type: "azure-active-directory-password"
  },
  server: "your_server.database.windows.net", // update me
  options: {
    database: "your_database", //update me
    encrypt: true
  }
};

/* 
    //Use Azure VM Managed Identity to connect to the SQL database
    const config = {
        server: process.env["db_server"],
        authentication: {
            type: 'azure-active-directory-msi-vm',
        },
        options: {
            database: process.env["db_database"],
            encrypt: true,
            port: 1433
        }
    };

    //Use Azure App Service Managed Identity to connect to the SQL database
    const config = {
        server: process.env["db_server"],
        authentication: {
            type: 'azure-active-directory-msi-app-service',
        },
        options: {
            database: process.env["db_database"],
            encrypt: true,
            port: 1433
        }
    });

*/

const connection = new Connection(config);

// Attempt to connect and execute queries if connection goes through
connection.on("connect", err => {
  if (err) {
    console.error(err.message);
  } else {
    queryDatabase();
  }
});

connection.connect();

function queryDatabase() {
  console.log("Reading rows from the Table...");

  // Read all rows from table
  const request = new Request(
    `SELECT TOP 20 pc.Name as CategoryName,
                   p.name as ProductName
     FROM [SalesLT].[ProductCategory] pc
     JOIN [SalesLT].[Product] p ON pc.productcategoryid = p.productcategoryid`,
    (err, rowCount) => {
      if (err) {
        console.error(err.message);
      } else {
        console.log(`${rowCount} row(s) returned`);
      }
    }
  );

  request.on("row", columns => {
    columns.forEach(column => {
      console.log("%s\t%s", column.metadata.colName, column.value);
    });
  });

  connection.execSql(request);
}


```

**Comment by MichaelSun90** [comment]
Hi @joelvarty , for using 'azure-active-directory-password' an azure registered application client id is required. In tedious, we used to provide a clientId within the driver internally which is not really good practice. The proper way to do this is to allow users to pass in their clients. That's is why we rise the warning here. Here is a [link ](https://docs.microsoft.com/en-us/graph/auth-register-app-v2)to the Microsoft side doc for registering the app and getting the client id.  

If the clientID is not provided, tedious will still work with the clinetID that we hard-coded inside the driver during this transition period. However, the hard code clientId will be removed entirely in the future. 

Also, another part is, for using 'azure-active-directory-password', a 'tendetID' is needed. Here is a [link ](http://tediousjs.github.io/tedious/api-connection.html)to tedious side doc. You can search "azure-active-directory-password" under that page, and you will find corresponding details. 

We will see if we can do an update for the Microsoft side doc to represent these changes, so it will not cause further confusion. 

The connection config will be like this: 
`const config = {
  authentication: {
    options: {
            userName: "user name" //update me,
            password: "password" //update me,
            tenantId: "tenantId" //update me,
            clientId: "clinetId" // This one is optional for now because we still have the hard code one: "7f98cb04-cd1e-40df-9140-3bf7e2cea4db" to smooth the transition period. This will be required in the future which is why we provide the warning. 
    },
    type: "azure-active-directory-password"
  },
  server: "your_server.database.windows.net", // update me
  options: {
    database: "your_database", //update me
    encrypt: true
  }
};`

**Comment by joelvarty** [comment]
Thanks so much for the clarification, @MichaelSun90 !  

I already had an Azure Enterprise Application setup, and when I plugged in those values, it worked perfectly!
