### ISSUE TITLE
Tedious connector to SQL DB works when called locally, but when deployed to AWS Lambda, it does not work.

### ISSUE THREAD

**Issue by ANTGOMEZ** [tediousjs/tedious#1401]
Originally, I was using the example code that's "out there" in the wild to connect to SQL with NodeJS, and that worked fine.

However, I had to write unit tests for it with Jest and I could not do it in that form, so I re-wrote the function by breaking it up into pieces to make it easier to write tests for. I was then able to write and run tests, and the code also works when I run it from my local machine (Windows 10.) The DB is on-prem on a network Windows server.

When I deploy this code to AWS Lambda, however, the code will not work, I get the following errors:

CONNECTION ERROR: Error: Failed to connect to xx.xx.xx.xx:1433 in 15000ms
REQUEST ERROR: Error: Requests can only be made in the LoggedIn state, not the Connecting state

The Lambda has full access back to our on-prem network, I know this because that same lambda works in the original code form.

Here is the newly written code:

`       

       exports.execSQLCmd = async function (conn_store, cmd) {  
  	
    	let config = await exports.getParameter(conn_store)
    	let conn_cfg = JSON.parse(config)
    
    	//connect
    	exports.connect_exec(conn_cfg, cmd);	
    
    	return result;
    }
    
    function connect_exec(conn_cfg, cmd) {
    	const connection = exports.get_connection(conn_cfg);
    	exports.on_connect(connection, cmd);
    	connection.connect();
    	return connection;
    }
    
    function on_connect(connection, cmd) {
    	connection.on('connect', function (err) {
    		if (err) {
    			console.log('CONNECTION ERROR: ' + err);
    		}
    		console.log('CONNECTED');
    		exports.execute_statement(connection, cmd);
    	});
    }
    
    function get_connection(conn_cfg) {
    	return new Connection(conn_cfg);
    }
    
    function execute_statement(connection, cmd) {
    	let request = exports.get_request(connection, cmd);
    
    	connection.execSql(request);
    }
    
    function get_request(connection, cmd) {	
    	let request = new Request(cmd, function (err) {
    		if (err) {
    			console.log('REQUEST ERROR: ' + err);
    		}
    	});
    	//add three event hooks to the request
    	request.on('row', function (columns) {
    		columns.forEach(function (column) {
    			result += (column.value === null ? '' : column.value) + ',';
    		});
    		result = result.replace(/,$/, '\r\n');
    	});
    	request.on('done', function (rowCount, more) {
    		console.log('SQL COMMAND COMPLETED: ' + rowCount + ' rows returned');
    	});
    	request.on('requestCompleted', function (rowCount, more) {
    		connection.close();
    		console.log('CONNECTION TO SERVER CLOSED');
    	});
    	return request;
    }
`

here is the config I am using:
`{"authentication":{"options":{"userName":"user","password":"yyy","domain":"my.domain.com"},"type":"ntlm"},"server":"xx.xx.xx.xx","options":{"encrypt":false,"database":"mydb", "trustServerCertificate": false}}`

The Lambda is using NodeJS Runtimes 12.x/14.x. 14 is the highest they go.

My local NodeJS version is 16.3.

Not sure if that is an issue. And I don't think I can go back to down to 14, or I'm not sure.

If you can see why this form of the code would work on my local network but not in AWS Lambda, please advise.

Thank you!

**Comment by ANTGOMEZ** [comment]
UPDATE:

Set type to default and removed the domain, then also called the main function `exports.execSQLCmd`  with `await`. Now it works as expected!

**Comment by mShan0** [comment]
Hi @ANTGOMEZ, glad you got it working. If you aren't using NTLM anymore, you can feel free to use Node 17 with your project.
