### ISSUE TITLE
SSL routines:ssl_choose_client_version:unsupported protocol

### ISSUE THREAD

**Issue by komtalekar** [tediousjs/tedious#1407]
I ma facing below issue when connecting to  SQL 2008R2 SP3 GDR

code:'ESOCKET'
message:'Failed to connect to testsqlserver:undefined - 30128:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1947:\n'
name:'ConnectionError'
originalError:ConnectionError {message: 'Failed to connect to testsqlserver.…enssl\openssl\ssl\statem\statem_lib.c:1947:\n', code: 'ESOCKET', stack: 'ConnectionError: Failed to connect to LN_MS_F…tions (internal/process/task_queues.js:80:21)'}
stack:'ConnectionError: Failed to connect to testsqlserver:undefined - 30128:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1947:\n\n    at Connection.<anonymous> (C:\Temp\Code\GitLab\testsqlserver\node_modules\mssql\lib\tedious\connection-pool.js:68:17)\n    at Object.onceWrapper (events.js:422:26)\n    at Connection.emit (events.js:315:20)\n …rchaserequest\service\node_modules\tedious\lib\connection.js:1290:12)\n    at Socket.<anonymous> (C:\Temp\Code\GitLab\testsqlserver\node_modules\tedious\lib\connection.js:1125:14)\n    at Socket.emit (events.js:327:22)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)'
__proto__:MSSQLError

**Comment by arthurschreiber** [comment]
Which version of Node.js are you using?

**Comment by komtalekar** [comment]
> Which version of Node.js are you using?

v14.15.5

**Comment by komtalekar** [comment]
> Hi @komtalekar , I found this issue #914 , and @arthurschreiber has a explanation [there ](https://github.com/tediousjs/tedious/issues/914#issuecomment-517011077), You can check this , see if it helps. Basiclly the required tls version is not meet and may cause this issue.

hi @MichaelSun90  Thanks a lot . It worked for me with TypeOrmModule.forRoot({ but I am struggling to put cryptoCredentialsDetails options in TypeOrmModule.forRootAsync(

**Comment by MichaelSun90** [comment]
Hi @komtalekar , is TypeOrmModule a nestjs side function. I am not really fimilar with this function. You may need to consult with their side.  Also, I have a link to a [doc](https://nodejs.org/docs/latest/api/tls.html#tls_tls_createsecurepair_credentials_isserver_requestcert_rejectunauthorized) for cryptoCredentialsDetails, hope that helps.

**Comment by komtalekar** [comment]
Thanks a lot @MichaelSun90 . I changed my nodejs version from 14 to 10 then it worked as per below comments in issue [#914 ]

For those that run into a similar error, this is because since Node.js 12, the default TLS settings were tightened. Most likely your SQL Server does not support TLS 1.2, but it's required by default in Node.js 12. You can change this either via a command line flag when starting node (e.g. --tls-min-v1.0), or by passing a custom cryptoCredentialsDetails option to the Connection constructor that specifies minVersion: 'TLSv1' or whatever TLS version you need to use.
