### ISSUE TITLE
Unable to connect to Azure SQL with `azure-active-directory-access-token` with "Login failed for user '<token-identified principal>'. The server is not currently configured to accept this token."

### ISSUE THREAD

**Issue by kuldea-franta** [tediousjs/tedious#1418]
Hello,
I'm having trouble while connection to Azure SQL database with `azure-active-directory-access-token`. The token is generated with library [@azure/identity](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/README.md). I have tried `InteractiveBrowserCredential`, `DeviceCodeCredential`, `DefaultAzureCredential`.

The error is:
> ConnectionError: Login failed for user '&lt;token-identified principal&gt;'. The server is not currently configured to accept this token.

Code to reproduce:

### index.js
```js
const {InteractiveBrowserCredential, DeviceCodeCredential, DefaultAzureCredential} = require('@azure/identity');
const Connection = require('tedious').Connection;

const tenantId = 'TENANT_ID'; // <- change
const server = 'SERVER.database.windows.net'; // <- change
const database = 'DATABASE'; // <- change

const scopes = ['https://database.windows.net/.default'];

const credential = new InteractiveBrowserCredential({tenantId, redirectUri: 'http://localhost:1337'});
// const credential = new DeviceCodeCredential({tenantId});
// const credential = new DefaultAzureCredential({tenantId});

credential.getToken(scopes).then(x => {
  const config = {
    server,
    options: {
      database,
      trustServerCertificate: true,
      enableArithAbort: true,
    },
    authentication: {
      type: 'azure-active-directory-access-token',
      options: {
        token: x.token
      },
    }
  };

  const connection = new Connection(config);
  connection.connect((err) => {
    if (err) {
      throw err;
    }
    console.log('SUCCESS');
  });
}).catch(e => console.error(e));
```

### package.json
```json
{
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "@azure/identity": "^2.0.4",
    "async": "^3.2.3",
    "tedious": "^14.3.0"
  }
}

```

EDIT: I'm able to connect to the same SQL Server, using all three flows, by tools like MSSQL Management Studio, ItelliJ Idea, even with .net core `Microsoft.Data.SqlClient` (tried `ActiveDirectoryPassword` only).

**Comment by jamesderrick** [comment]
Major difference between my code and yours is having `encrypt: true` in your config options, that's definitely needed for connecting to Azure SQL but not for a local SQL Server

**Comment by IanMoroney** [comment]
Same error when adding `encrypt: true`.
I actually think our scenario is complicated by the fact that our AD users are guest users in the tenant.
Although this scenario works fine in other applications such as SSMS and Azure Data Studio.

Tenant 1 authenticates the user, as the user is natively located there
Tenant 2 is where the Azure SQL server is.
Tenant 2 has the user configured as a guest user.

**Comment by kuldea-franta** [comment]
@jamesderrick `encrypt` is set to `true` by default

**Comment by jamesderrick** [comment]
Fair point, didn't know that was the case

**Comment by kuldea-franta** [comment]
Ok, problem fixed. As @IanMoroney explained in his post, we do have two subscription somehow connected together. So I just tried a tenant i of the second subscription and connection is successful. Anyways, thank you @jamesderrick for you time.

**Comment by IanMoroney** [comment]
For anyone experiencing this issue in a multi-tenant or cross-tenant scenario, pay attention to the tenant ID which is associated with the bearer token.
It should be the same as the tenant ID in which your Azure SQL Server is in.

**Comment by MichaelSun90** [comment]
> Same error when adding `encrypt: true`. I actually think our scenario is complicated by the fact that our AD users are guest users in the tenant. Although this scenario works fine in other applications such as SSMS and Azure Data Studio.
> 
> Tenant 1 authenticates the user, as the user is natively located there Tenant 2 is where the Azure SQL server is. Tenant 2 has the user configured as a guest user.

Hi Ian, just want to learn a bit more about this. You mentioned," Although this scenario works fine in other applications such as SSMS and Azure Data Studio". Is the scenario here mean that generating a token using Tenant 1 from your example will also work for SSMA and Azure Data Studio but not be tedious? If I am wrong, can you explain a bit more about this scenario? Thanks!:bow:
