### ISSUE TITLE
Connection database option doesn't work

### ISSUE THREAD

**Issue by ShaneK** [tediousjs/tedious#144]
Whenever I connect to a database I pass in a configurations object that looks something like this:

```
var config = {
    userName: 'root',
    password: 'password123',
    server: 'localhost',
    database: 'foobar'
};
```

but whenever I execute a query like this:

```
var request = new Request("SELECT COUNT(*) FROM Bar", function(err, rowCount){
```

I get an error like this:

```
{ name: 'RequestError',
  message: 'Invalid object name \'Bar\'.',
  code: 'EREQUEST' }
```

However, if I instead execute my statement like this:

```
var request = new Request("USE foobar; SELECT COUNT(*) FROM Bar", function(err, rowCount){
```

It works correctly. This must mean that the configuration option for database isn't being handled properly.

**Comment by Zivpp** [comment]
A huge thanks to you! This solves my problem!
