### ISSUE TITLE
Replace md4 implementation

### ISSUE THREAD

**Issue by arthurschreiber** [tediousjs/tedious#1447]
NTLM support requires the use of `md4` hashing. Unfortunately, never Node.js versions hide `md4` hashing behind an environment variable / command line flag.

Maybe we should think about using a different library to provide `md4` hashing? I'm not super happy about it, but the way `md4` is used in NTLM is not really a security issue I guess? I mean, if someone decides to use NTLM auth, I assume they know what they're doing.

**Comment by mShan0** [comment]
I agree, will look into alternate libraries that can handle `md4` hashing.

**Comment by mShan0** [comment]
Two library candidates:

1. [js-md4](https://github.com/emn178/js-md4), library creator has created individual libraries for each hashing algorithm, many of which are widely used. However, there is no TypeScript support. Some of the owner's other hashing libraries have TypeScript support (e.g. [https://github.com/emn178/js-sha3/blob/master/index.d.ts](url)).

2. [hash-wasm](https://github.com/Daninet/hash-wasm), includes many algorithms. However, library works with async/await, need to convert NTLM payload to async/await to accomodate it. I have a potential working solution using this library.
