### ISSUE TITLE
Error: Requests can only be made in the LoggedIn state, not the Connecting state

### ISSUE THREAD

**Issue by Teengamer37** [tediousjs/tedious#1454]
When I'm trying to connect, the connection works fine. When I make a request and send an SQL command, it will generate this error.

I'm using the latest version of Node.js and tedious. I also temporarly disable the firewall for this issue. The server is on a local machine in my network.

script.js

```
var Connection = require('tedious').Connection; 
var Request = require('tedious').Request;  
var TYPES = require('tedious').TYPES; 
var connection;


function executeSQL([SQL command], callback) {
  connection = new Connection({
    userName: 'xxx',
    password: 'xxx',
    server: 'xxx', 
    database: 'xxx',
    options: {
      encrypt: false,
      enableArithAbort: true,
      trustServerCertificate: true
    }
  });

  connection.connect((err) => {
    if (err) {
      console.log(err);
    }
  });

  requestSql(sql);
}

function requestSql(sql) {
  request = new Request(sql, function(err, rowCount) {
    if (err) {
      console.log(err);
    } else {
      console.log(rowCount + ' rows');
      connection.close();
    }
  });

  request.on('row', function(columns) {
    columns.forEach(function(column) {
      console.log(column.value);
    });
  });

  connection.execSql(request); //<-- error generated
}
```

In the requestSql() function, I have copied the sample code on the documentation page

**Comment by lpelicioli** [comment]
I think that you must move the request function:
```
var Connection = require('tedious').Connection; 
var Request = require('tedious').Request;  
var TYPES = require('tedious').TYPES; 
var connection;


function executeSQL([SQL command], callback) {
  connection = new Connection({
    userName: 'xxx',
    password: 'xxx',
    server: 'xxx', 
    database: 'xxx',
    options: {
      encrypt: false,
      enableArithAbort: true,
      trustServerCertificate: true
    }
  });

  connection.connect((err) => {
    if (err) {
      console.log(err);
    }
    else
      requestSql(sql); //<------------------------------------------------------------ HERE
  });

  
}

function requestSql(sql) {
  request = new Request(sql, function(err, rowCount) {
    if (err) {
      console.log(err);
    } else {
      console.log(rowCount + ' rows');
      connection.close();
    }
  });

  request.on('row', function(columns) {
    columns.forEach(function(column) {
      console.log(column.value);
    });
  });

  connection.execSql(request); //<-- error generated
}
```

**Comment by Teengamer37** [comment]
> I think that you must move the request function:
> 
> ```
> var Connection = require('tedious').Connection; 
> var Request = require('tedious').Request;  
> var TYPES = require('tedious').TYPES; 
> var connection;
> 
> 
> function executeSQL([SQL command], callback) {
>   connection = new Connection({
>     userName: 'xxx',
>     password: 'xxx',
>     server: 'xxx', 
>     database: 'xxx',
>     options: {
>       encrypt: false,
>       enableArithAbort: true,
>       trustServerCertificate: true
>     }
>   });
> 
>   connection.connect((err) => {
>     if (err) {
>       console.log(err);
>     }
>     else
>       requestSql(sql); //<------------------------------------------------------------ HERE
>   });
> 
>   
> }
> 
> function requestSql(sql) {
>   request = new Request(sql, function(err, rowCount) {
>     if (err) {
>       console.log(err);
>     } else {
>       console.log(rowCount + ' rows');
>       connection.close();
>     }
>   });
> 
>   request.on('row', function(columns) {
>     columns.forEach(function(column) {
>       console.log(column.value);
>     });
>   });
> 
>   connection.execSql(request); //<-- error generated
> }
> ```

Sorry for late response. Thanks for the answer, it worked.
