### ISSUE TITLE
Correct Row count returned, but rows is an empty array

### ISSUE THREAD

**Issue by MowglyOrizon** [tediousjs/tedious#1458]
As per the title, the row count being returned is 1 but the row array being returned is empty
`SELECT` statements work fine, but on `INSERT` statements there is no row.
Here is my code:
```
  export const dbPromise = (connection, request) => {

  const con = connection();

  return new Promise((resolve, reject) => {
    let response;

    request.on('row', (columns) => {
      console.log({columns});
      response = mapDBRowToJSON(columns);
    });

    request.on('done', () => {
      resolve(response);
    });
    request.on('doneProc', () => {
      resolve(response);
    });
    request.on('doneInProc', (rowCount, more, rows) => {
      console.log({rowCount, more, rows})
      resolve(response);
    });

    request.on('error', (err) => {reject(err)});

    con.on('connect', () => {con.execSql(request)});
  });
};
```

the console logs:
```
{ rowCount: 1, more: true, rows: [] }
```
the console log from the `row` callback is never fired

I need the response for an insert statement
Again, this works correctly when the request is a select, only the insert is a problem

EDIT:
Here is my config:
```
const config = {
  server: '***.database.windows.net',
  authentication: {
    type: 'default',
    options: {
      userName: '***', 
      password: '***',
    }
  },
  options: {
    database: '***',
    encrypt: true,
    rowCollectionOnRequestCompletion: true,
  }
}
```

**Comment by arthurschreiber** [comment]
I think this is not a bug in `tedious`, but a misunderstanding on your side. 🤔 

`INSERT` statements don't return any data, unless you use [the `OUTPUT` clause](https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?view=sql-server-ver16). If you don't use the `OUTPUT` clause, you only get the number of rows inserted and that's it.

**Comment by MowglyOrizon** [comment]
Thank you @arthurschreiber you were correct- the bug was between the keyboard and the chair
