### ISSUE TITLE
npm start fails with tedious

### ISSUE THREAD

**Issue by Alejandro742** [tediousjs/tedious#1497]
**Software versions**
* Tedious: ^15.1.1
* SQL Server: Microsoft SQL Server 2019
* Node.js: v14.13.0
* npm: 6.14.8
* ubuntu: 16.04.7 LTS

**Additional Libraries Used and Versions**
* mssql: ^9.0.1

**Connection configuration**
`
const sqlConfig = {
  user: process.env.USER,
  password: process.env.PASS,
  database: process.env.DB,
  server: process.env.HOST,
  pool: {
    max: 10,
    min: 0,
    idleTimeoutMillis: 30000,
  },
  options: {
    encrypt: false,
    trustServerCertificate: true,
  },
};
`

**Problem description**
When I try to run my nodejs/express project I get one of the errors below. Sometimes is the first and sometimes is the second and I don't know why

**Error message/stack trace**

* 
`
  await this.messageIo.startTls(this.secureContextOptions, ((_this$routingData = this.routingData) === null || _this$routingData === void 0 ? void 0 : _this$routingData.server) ?? this.config.server, this.config.options.trustServerCertificate); 
  SyntaxError: Unexpected token ?
`
*
`
 tedious npm const [, major, minor, build] = /^(\d+)\.(\d+)\.(\d+)/.exec(_package.version) ?? ['0.0.0', '0', '0', '0']; SyntaxError: Unexpected token ?
`

**Comment by MichaelSun90** [comment]
Thanks for the information, we will see if we can reproduce the behavior.  Seems that the environment does not recognize the nullish coalescing operator(??) used in the code.

**Comment by Alejandro742** [comment]
@MichaelSun90 exactly, I think the same. I downgrade mssql from 9.0.1 to 8.1.4 and it works
