### ISSUE TITLE
Sequelize & Azure SQL Encrypt Error

### ISSUE THREAD

**Issue by MrBlackBrain** [tediousjs/tedious#1500]
**Software versions**
* Tedious: 15.1.2
* SQL Server: Azure SQL Single Database
* Node.js: 16.18.1 & 18

**Additional Libraries Used and Versions**

* Sequelize:  6.25.7

**Table schema**

No schema for this issue.
**Connection configuration**
`
const sequelize = new Sequelize(dbConfig.DB, dbConfig.USER, dbConfig.PASSWORD, {
	host: dbConfig.HOST,
	dialect: 'mssql',
	logging: false,
	dialectOptions: {
		options: {
			encrypt: true,
		},
		requestTimeout: 60000,
		connectTimeout: 30000,
	},

	pool: {
		max: 3,
		min: 0,
		acquire: 30000,
		idle: 30000,
	},
});
`

**Problem description**

Even though encrypt option is set correctly by both sequelize and tedious documents, "true" value for encrypt is ignored.

**Expected behavior**

Set encrypt value to true for Azure SQL connection because Azure SQL does not allow unencrypted connections

**Actual behavior**

Encrypt value is first set to "true"i however on prelogin value changes to "false".

**Error message/stack trace**

ConnectionError: Server requires encryption, set 'encrypt' config option to true.
 code: 'EENCRYPT',
  isTransient: undefined

**Any other details that can be helpful**

Relevant Sequelize Issue : https://github.com/sequelize/sequelize/issues/15204

**Comment by arthurschreiber** [comment]
The default value for `encrypt` is `true`:

https://github.com/tediousjs/tedious/blob/e43e9c912d05f1d9a359960a02afafb118f30a6f/src/connection.ts#L1246

Tedious just uses the value passed in from the client, as long as it's not `undefined` and a `boolean` value:

https://github.com/tediousjs/tedious/blob/e43e9c912d05f1d9a359960a02afafb118f30a6f/src/connection.ts#L1483-L1489

It is passed to the prelogin message here:

https://github.com/tediousjs/tedious/blob/e43e9c912d05f1d9a359960a02afafb118f30a6f/src/connection.ts#L2236-L2239

and from there, it's used directly when building the prelogin message:

https://github.com/tediousjs/tedious/blob/e43e9c912d05f1d9a359960a02afafb118f30a6f/src/prelogin-payload.ts#L134-L145

The option does not get modified by tedious. Something else must be going on.

**Comment by MrBlackBrain** [comment]
Issue was with "winston-sql-transport" library. Thaks for your effort
