### ISSUE TITLE
Custom Parsing Functions for different datatypes

### ISSUE THREAD

**Issue by khkiley** [tediousjs/tedious#1505]
@arthurschreiber suggested in this issue https://github.com/tediousjs/tedious/pull/973#issuecomment-536230895 a new feature that would allow custom parsing functions.

This would be handy for situations where the JavaScript representation of the data type could result in a loss of precision, i.e. Decimal and DateType2

To be able to hook in a function, or at the least have tedious return the raw TDS representation of the column as a buffer would be very convenient.

Currently to achieve this I need to manipulate the SQL select statement to cast as a buffer or varchar, but this becomes impractical if the result set comes from a stored procedure.

Has there been any progress on this? I've looked but haven't found any other reference to it.

Thank you,

Kurt

**Comment by MichaelSun90** [comment]
Hi @khkiley , unfortunately, we have not got a chance to fully working on this yet. But this definitely a important refactor that we  planed for future. If we make any progress in the future, we will definitely notify you and people interesting in this change.

**Comment by khkiley** [comment]
Thank you for the update @MichaelSun90.

Kurt
