### ISSUE TITLE
Network socket not correctly cleaned up when connection timeout fires during TDS8.0 TLS negotiation

### ISSUE THREAD

**Issue by arthurschreiber** [tediousjs/tedious#1558]
The recently added `Connection#wrapWithTls` method does not behave correctly if the connection timeout fires during the TLS negotiation.

When the connect timeout fires, we dispatch a [`ConnectionError` to the `connect` event](https://github.com/tediousjs/tedious/blob/b78df149fd55d11125a35af7e2366c0a36ed4c74/src/connection.ts#L2132-L2143) and move the internal state over to the `FINAL` state. Because we haven't fully connected yet, the network socket does not get cleaned up when moving to the `FINAL` state.

When the connection timeout fires between the call to [`connect`](https://github.com/tediousjs/tedious/blob/b78df149fd55d11125a35af7e2366c0a36ed4c74/src/connection.ts#L2045C7-L2045C67) and before [`wrapWithTls`](https://github.com/tediousjs/tedious/blob/b78df149fd55d11125a35af7e2366c0a36ed4c74/src/connection.ts#L2050C11-L2050C51) returns, we never clean up the socket correctly, because `wrapWithTls` doesn't return an error if the connection timeout fires.

I think this can be fixed by making `wrapWithTls` take the `signal` passed to `connectOnPort`, and handle it correctly (i.e. call `signal.throwIfError` at the beginning of the function, and set the correct event handlers to reject the promise if the signal is aborted).

**Comment by MichaelSun90** [comment]
Hi @arthurschreiberm, I will look into this 👍
