### ISSUE TITLE
Need to update @azure/msal-node to 2.0 for NodeJs 20 compatability

### ISSUE THREAD

**Issue by ahkelly** [tediousjs/tedious#1585]
**Software versions**
* Tedious:
* SQL Server:
* Node.js:

**Additional Libraries Used and Versions**

NodeJs 20
Latest version of node-mssql and this library

**Problem description**

Installing node-mssql or this package directly still fails on NodeJs 20 (now LTS) due to the outdated msal-node package used. Any guidance on when this may be updated?

**Error message/stack trace**

Below is output from attempting to install using Node 20 (18 is fine)

npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @azure/msal-node@1.18.2
npm ERR! notsup Not compatible with your version of node/npm: @azure/msal-node@1.18.2

**Any other details that can be helpful**

**Comment by MichaelSun90** [comment]
Hi @ahkelly , we do have a PR #1575 from @esetnik that does bump up the versions. Will definitely look into this and, see if we can merge that and release.

**Comment by ahkelly** [comment]
Thank you kindly

**Comment by eikaramba** [comment]
this ticket currently prevents me from installing directus on node 20, so would highly appreciate pumping the versions

**Comment by UTLogicLabs** [comment]
This is currently preventing me from jumping to Node 20 LTS are later.

**Comment by sergiubcn** [comment]
Upvoting ⬆️

**Comment by tnowak3000** [comment]
Upvoting!

**Comment by tuxpoldo** [comment]
Upvoting!

**Comment by arthurschreiber** [comment]
This has been fixed and is available in v16.6.1. That release has not been tagged as `latest` yet, but will be in a few days. You can install it explicitly in the meantime.
