### ISSUE TITLE
https://salla.sa//bero-2030.com

### ISSUE THREAD

**Issue by Berro8** [tediousjs/tedious#1593]
**Software versions**
* Tedious:
* SQL Server:
* Node.js:

**Additional Libraries Used and Versions**

**Table schema**

**Connection configuration**
`
// Paste your connection config here.
`

**Problem description**

**Expected behavior**

**Actual behavior**

**Error message/stack trace**

**Any other details that can be helpful**

**Comment by MichaelSun90** [comment]
Hi @Berro8 , I am not quite sure what is your issue here.
