### ISSUE TITLE
Cannot find name 'AggregateError'.

### ISSUE THREAD

**Issue by martijnimhoff** [tediousjs/tedious#1612]
**Software versions**
* Tedious: 18.1.0
* @types/node: 18.19.8
* Node.js: 18.19.1
* Typescript: 5.3.3

**Problem description**
When I install this library in my project. I'm getting the following type error in the library:
```
> eslint .; tsc --noemit

node_modules/tedious/lib/connection.d.ts:748:29 - error TS2304: Cannot find name 'AggregateError'.

748     loginError: undefined | AggregateError | ConnectionError;
                                ~~~~~~~~~~~~~~

Found 1 error in node_modules/tedious/lib/connection.d.ts:748
```

**Expected behavior**
It looks like AggregateError should be available, but it is not found. I can't reproduce this type error when just running the linter in the library itself.

**Comment by wy193777** [comment]
I have the same error, can you be detailed on how did you fixed it?

**Comment by lroal** [comment]
How do I solve this ?
I am using pure javascript with typescript definition files.
Have no tsconfig.json

**Comment by martijnimhoff** [comment]
> I have the same error, can you be detailed on how did you fixed it?

In my tsconfig.json, I changed the target to `es2022`.

> How do I solve this ?
> I am using pure javascript with typescript definition files.
> Have no tsconfig.json

Are you building a library yourself?

**Comment by lroal** [comment]
target es2022 solved it
```bash
tsc ./src/index.d.ts --module commonjs --target es2022 --noEmit true --strict true --esModuleInterop true
```
I use tsc to check that my typescript definitions are correct:
https://github.com/alfateam/rdb/blob/master/package.json#L44
