### ISSUE TITLE
Upgrade @azure/identity to resolve vulnerability

### ISSUE THREAD

**Issue by oliverbock** [tediousjs/tedious#1633]
According to [this advisory](https://github.com/advisories/GHSA-m5vv-6r4h-3vj9), [@azure/identity](https://www.npmjs.com/package/@azure/identity/v/4.0.0-alpha.20231106.4) versions prior to 4.2.1 include a vulnerability.  Package.json specifies [`"@azure/identity": "^3.4.1"`](https://github.com/tediousjs/tedious/blob/934e98e965994580dacff756ca7972f19f60a761/package.json#L44C5-L44C33) which cannot be quietly upgraded because the hat (`^`) does not allow major version upgrades.

Please adopt the invulnerable release version.

Apologies if my limited understanding of npm dependencies means that this isn't necessary.

**Comment by MichaelSun90** [comment]
Hi @oliverbock , the change has been merged and released. Closing this one for now.

**Comment by olibos** [comment]
Hello @MichaelSun90  do you know when it will be released on NPM?
