### ISSUE TITLE
[QUESTION] Error: Cannot read properties of null (reading 'lookup')

### ISSUE THREAD

**Issue by ModuleHunter** [tediousjs/tedious#1648]
**Question**
No matter what settings I use, tedious outputs the above error message when I want to connect to a MS SQL Server. It does not matter whether it is a remote server or a local server. I checked all possible connection settings (TCP/IP) in Sql Server Configuration Manager and experimented with various values (and restarted the server), but no luck. SQL Logins are also enabled. I installed NodeJS (20.16.0.0) only a few days ago on a fresh Windows 10. I also tried the 'mssql' extension but it outputs the same error message, too. I even added NodeJS as exception to Windows' firewall. I tried 'msnodesqlv8' as driver and started MS SQL Server Browser service, but just nothing helps.

This is my current connection code:

    import { Connection, Request, TYPES } from 'tedious';

    var config = {
        server: 'localhost', // <- also tried ::1 and 127.0.0.1
        authentication: {
            type: 'default',
            options: {
                userName: 'test',
                password: '<HIDDEN>'
            }
        },
        options: {
            //port: 1433, <- also tried instead of instanceName
            instanceName: 'SQLEXPRESS',
            encrypt: true, // <- does not affect anything
            database: 'master',
            trustServerCertificate: true, // <- does not affect anything when I use encrypt option
            debug: {
                packet: true,
                data: true,
                payload: true,
                token: true
            }
        }
    };  
    var connection = new Connection(config);
    connection.on('debug', function(value) {
        console.log(value)
    });
    connection.on('connect', function(err) {
        console.log(err);
    });
    connection.connect();

Console output:

    State change: Initialized -> Connecting
    DocumentsView.vue:213 Error: Cannot read properties of null (reading 'lookup')
        at connection.ts:1966:32
        at Item.run (browser.js:153:14)
        at drainQueue (browser.js:123:42)

It should be noted that I can connect to the servers without problems in SQL Server Management Studio by using SQL Logins. I use Vue with Vite for a web application if that helps.

My package.json:

    {
        "name": "eservices",
        "version": "0.0.0",
        "private": true,
        "type": "module",
        "scripts": {
             "dev": "vite",
             "build": "vite build",
             "preview": "vite preview"
        },
        "dependencies": {
          "@primevue/themes": "^4.0.3",
          "@types/node": "^22.1.0",
          "msnodesqlv8": "^4.2.1",
          "openai": "^4.54.0",
          "pinia": "^2.1.7",
          "primeicons": "^7.0.0",
          "primevue": "^4.0.3",
          "tailwindcss-primeui": "^0.3.4",
          "tedious": "^18.3.0",
          "vue": "^3.4.29",
          "vue-router": "^4.3.3"
        },
        "devDependencies": {
          "@vitejs/plugin-vue": "^5.0.5",
          "autoprefixer": "^10.4.20",
          "postcss": "^8.4.40",
          "tailwindcss": "^3.4.7",
          "vite": "^5.3.1",
          "vite-plugin-node-polyfills": "^0.22.0"
        }
    }

**Comment by mShan0** [comment]
Can you try running your connection code independently without going through Vue to see what happens? The error message is from Vue and not Tedious

**Comment by mShan0** [comment]
My best guess is that you're trying to read from the database before the connection is fully established in your Vue application

**Comment by arthurschreiber** [comment]
Isn't vue a front end framework? Tedious only works on Node.js, not in the browser.

**Comment by mShan0** [comment]
`connection.connect()` initiates the connection asynchronously. You need to put the code that runs after the connection is established inside 
```
connection.on('connect', function(err) {
    // Insert calls here
});
```

**Comment by MichaelSun90** [comment]
Hi @ModuleHunter, thanks for confirming that it is working now. Will close this one for now.
