### ISSUE TITLE
Unable to connect System assigned Managed Identity to Azure SQL

### ISSUE THREAD

**Issue by mlechler** [tediousjs/tedious#1650]
Hi, I'm trying to connect from a system assigned Managed Identity to an Azure SQL database. I tried several solutions, but I'm always getting the error `Security token could not be authenticated or authorized`.

I'm using `typeorm@0.3.20` with `mssql@10.0.4` and `tedious@16.7.1`.

My current (typeorm) configurationlooks like the following. I guess it shouldn't be a problem to extract the tedious configuration out of this.
`{
  "authentication": {
    "type": "azure-active-directory-msi-app-service",
    "options": {
      "clientId": "XXX"
    }
  },
  "type": "mssql",
  "host": "XXX",
  "port": 1433,
  "database": "XXX",
  "synchronize": false,
  "logging": false,
  "migrationsRun": true,
  "entities": [
    "dist/entity/**/*.js"
  ],
  "migrations": [
    "dist/migration/**/*.js"
  ],
  "subscribers": [
    "dist/subscriber/**/*.js"
  ]
}`

For my understanding `clientId` is just needed for user assigned Managed Identity, right? If I remove it, I get another error `Login failed for user '<token-identified principal>'` which seems to be an authentication issue between the Managed identity and the Azure SQL, right?

maybe the solution is, to remove the `clientId` and get the other error fixed?

**Comment by MichaelSun90** [comment]
Hi @mlechler , have you give some other azure auth types a try with your credential?
azure-active-directory-default is a pretty forgiven auth type that will take suer input and try to match a auth process to approach. 
```
authentication: {
        type: 'azure-active-directory-default',
        options: {
               clientId: process.env.AZURE_CLIENT_ID  // <----- user-assigned managed identity        
        }
    },
```
I am not an expert on azure side, I think there are also power shell script that can test if the identities are properly setup. here is a [page ](azure-active-directory-default) from Microsoft side.

**Comment by mlechler** [comment]
Hi @MichaelSun90, I tried the whole day a lot of different methods to get the auth flow working. I'm out of ideas...

We only have the possibility to use the system assigned Managed Identity, nothing else.

As far as I understand, I have to use my example without the clientId, as this is for the user assigned Managed Identity, which I don't have. I guess this is why typeorm/mssql gives me the error `CredentialUnavailableError: ManagedIdentityCredential: The managed identity endpoint is indicating there's no available identity. Message: undefined Status code: 400`.

Maybe the system assigned Managed Identity is missing permissions which results in the error... I will check tomorrow.

**Comment by mlechler** [comment]
I just found the error. My database user was partly "destroyed" by my terraform script.

The library works like a charm, with `azure-active-directory-msi-app-service` and without `clientId` as it is system assigned :)

Thanks, I will close.
