### ISSUE TITLE
Cannot connect to SQL Azure database

### ISSUE THREAD

**Issue by mcartoixa** [tediousjs/tedious#188]
I have used tedious succesfully in the past to connect to various stanadrd SQL Server instances. I have spent the whole day to try and connect to an database hosted on Azure, to no avail.

At this point I have activated the debug options ([available here](https://gist.github.com/mcartoixa/c32db3279510775c8ce4)) and it seems that it fact a connection is established, but is closed right after the login has been sent. The _encrypt_ option is set to true, and I can connect to the database with the same credentials by other means (SSMS).

I am using the latest 1.5.1 version.

Any idea?

**Comment by vvo** [comment]
@rossipedia Should we automatically put encrypt:true when windows.net in the hostname?

**Comment by bretcope** [comment]
I don't think inferring configuration is the road we want to go down. What might be a good idea is to include a section in the documentation about connecting to Azure.

**Comment by arthurschreiber** [comment]
Like this? :trollface: https://github.com/pekim/tedious/commit/ccf8573112e946b3363132fc063002b64debbd5e

**Comment by bretcope** [comment]
yes... like that.

**Comment by TyrionLanister** [comment]
Can Anyone help me with this error. I am connecting to an Azure database.

I am receiving connnection error with code: Elogin

===============================================================

{ name: 'ConnectionError',
  message: 'Login failed for user \'d*******\'.',
  code: 'ELOGIN' }

===========================================================

Detailed log

============================================================
connected to abcd.database.windows.net:1433
Connected to Database sensorData
Sent
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x002F, spid:0x0000, packetId:0x01, window:0x00
  0000  00001A00 06010020 00010200 21000103 00220004 04002600 01FF0000 00010001  ....... ....!... ."....&. ........
  0020  01000000 000000  .......
  PreLogin - version:0.0.0.1 1, encryption:0x01(ON), instopt:0x00, threadId:0x00000000, mars:0x00(OFF)
State change: Connecting -> SentPrelogin
Connected to Database sensorData
Received
  type:0x04(TABULAR_RESULT), status:0x01(EOM), length:0x002B, spid:0x0000, packetId:0x01, window:0x00
  0000  00001A00 06010020 00010200 21000103 00220000 04002200 01FF0B00 04DF0002  ....... ....!... ."....". ........
  0020  010000  ...
  PreLogin - version:11.0.4.223 2, encryption:0x01(ON), instopt:0x00, threadId:0x00000000, mars:0x00(OFF)
Connected to Database sensorData

  Login7 - TDS:0x74000004, PacketSize:0x00001000, ClientProgVer:0x00000000, ClientPID:0x0000340C, ConnectionID:0x00000000
           Flags1:0xE0, Flags2:0x00, TypeFlags:0x00, Flags3:0x08, ClientTimezone:-120, ClientLCID:0x00000409
           Hostname:'*******', Username:'********', Password:'******', AppName:'Tedious', ServerName:'******.database.windows.net', LibraryName:'Tedious'
           Language:'undefined', Database:'sensorData', SSPI:'', AttachDbFile:'', ChangePassword:''
State change: SentPrelogin -> SentTLSSSLNegotiation
Connected to Database sensorData
Sent
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x0145, spid:0x0000, packetId:0x01, window:0x00
  0000  16030101 38010001 340303D3 A99408C2 982E5C46 72845675 E121889A F38C1EBB  ....8... 4....... ..\Fr.Vu.!......
  0020  D444BC4D 5BD62AC4 72DBE200 0088C030 C02CC028 C024C014 C00A00A3 009F006B  .D.M[.*. r......0.,.(.$.. .......k
  0040  006A0039 00380088 0087C032 C02EC02A C026C00F C005009D 003D0035 0084C012  .j.9.8.. ...2...*.&...... .=.5....
  0060  C0080016 0013C00D C003000A C02FC02B C027C023 C013C009 00A2009E 00670040  ........ ...../.+.'.#.... .....g.@
  0080  00330032 009A0099 00450044 C031C02D C029C025 C00EC004 009C003C 002F0096  .3.2.... .E.D.1.-.).%.... ...<./..
  00A0  0041C011 C007C00C C0020005 00040015 00120009 00FF0100 00830000 000E000C  .A...... ........ ........ ........
  00C0  00000975 6E646566 696E6564 000B0004 03000102 000A0034 0032000E 000D0019  ...undefined.... .......4.2......
  00E0  000B000C 00180009 000A0016 00170008 00060007 00140015 00040005 00120013  ........ ........ ........ ........
  0100  00010002 0003000F 00100011 00230000 000D0020 001E0601 06020603 05010502  ........ .....#.. ... .... ........
  0120  05030401 04020403 03010302 03030201 02020203 000F0001 01337400 00  ........ ........ ........ .3t..
Connected to Database sensorData
Received
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x0DED, spid:0x0000, packetId:0x01, window:0x00
  0000  1603010D E0020000 4D030155 BF8C0722 541B0AA6 6B63B669 06914AE0 BF84E1E6  ........ M..U..."T...kc.i..J.....
  0020  3EF863CB 811F9C30 202FEE20 0A280000 40FAB04A CC95B06F 7623CF02 373FC527  >.c....0 /. .(.. @..J...ov#..7?.'
  0040  691EFC79 AF11BB7E 74B748E6 C0140000 05FF0100 01000B00 0C1C000C 19000689  i..y...~t.H..... ........ ........
  0060  30820685 3082046D A0030201 0202135A 000047DC C28BA701 EFDE5388 00010000  0...0..m.......Z..G..... ..S.....
  0080  47DC300D 06092A86 4886F70D 01010B05 0030818B 310B3009 06035504 06130255  G.0...*. H....... .0..1.0. ..U....U
  00A0  53311330 11060355 0408130A 57617368 696E6774 6F6E3110 300E0603 55040713  S1.0...U....Washington1. 0...U...
  00C0  07526564 6D6F6E64 311E301C 06035504 0A13154D 6963726F 736F6674 20436F72  .Redmond1.0...U. ...Microsoft Cor
  00E0  706F7261 74696F6E 31153013 06035504 0B130C4D 6963726F 736F6674 20495431  poration1.0...U. ...Microsoft IT1
  0100  1E301C06 03550403 13154D69 63726F73 6F667420 49542053 534C2053 48413230  .0...U.. ..Microsoft IT SSL SHA20
  0120  1E170D31 34313030 37313034 3434355A 170D3136 31303036 31303434 34355A30  ...141007104445Z..161006104445Z0
  0140  2A312830 26060355 0403131F 64617461 2E646234 2D342E64 61746162 6173652E  *1(0&..U....data.db4-4.database.
  0160  77696E64 6F77732E 6E657430 82012230 0D06092A 864886F7 0D010101 05000382  windows.net0.."0...*.H.. ........
  0180  010F0030 82010A02 82010100 96BDB48F D97B4834 9E60A8A3 9473ED0B C6BD237C  ...0.... ........ .{H4.`.. .s....#|
  01A0  12DE4142 9AA4BA18 03EE7A13 BE776F83 F469986D A3D070AA FD4BAD6C 20BC37D5  ..AB.... ..z..wo. .i.m..p. .K.l .7.
  01C0  147795C2 DFFB72BB 19497A7E 9BB7901B D3ADD995 5530D24E 0D81AE67 DBB11A98  .w....r. .Iz~.... ....U0.N...g....
  01E0  1290FED8 81E98106 D5F83CE3 48A97A0E B50564BB 56203C71 1DD9DB71 6655BA92  ........ ..<.H.z. ..d.V <q...qfU..
  0200  9DA7CEDD 8E531C75 DD24ABE9 5C67345D ECD008FD A5616889 A046B0C7 B6B23A50  .....S.u.$..\g4].....ah. .F....:P
  0220  AE9F7D0A AEBEB635 748A788F 9D49F03A 2A536F80 BF93F1DF 2257E44D F05769E9  ..}....5t.x..I.:*So..... "W.M.Wi.
  0240  204A7197 F4039DA4 C0F837FB 43096019 AB2A4074 CA2445A9 08F17AC8 59AE1276   Jq..... ..7.C.`. .*@t.$E. ..z.Y..v
  0260  9880452C 6095948F 5294400C EE738FEA 6DDC6A62 D976F8C4 38D0919E 06A26E3D  ..E,`... R.@..s.. m.jb.v.. 8.....n=
  0280  4748E203 2F370071 D76A7247 02030100 01A38202 40308202 3C300B06 03551D0F  GH../7.q.jrG.... ....@0.. <0...U..
  02A0  04040302 04B0301D 0603551D 25041630 1406082B 06010505 07030106 082B0601  ......0. ..U.%..0...+.... .....+..
  02C0  05050703 02301D06 03551D0E 04160414 CF6DB045 81370367 4D0CE377 7A1CB128  .....0.. .U...... .m.E.7.gM..wz..(
  02E0  84011496 30640603 551D1104 5D305B82 1F646174 612E6462 342D342E 64617461  ....0d.. U...]0[. .data.db4-4.data
  0300  62617365 2E77696E 646F7773 2E6E6574 82162A2E 64617461 62617365 2E77696E  base.windows.net..*.database.win
  0320  646F7773 2E6E6574 82202A2E 7365636F 6E646172 792E6461 74616261 73652E77  dows.net. *.secondary.database.w
  0340  696E646F 77732E6E 6574301F 0603551D 23041830 16801451 AF24269C F4682257  indows.net0...U. #..0...Q.$&..h"W
  0360  80262B3B 4662157B 1ECCA530 7D060355 1D1F0476 30743072 A070A06E 86366874  .&+;Fb.{...0}..U...v0t0r.p.n.6ht
  0380  74703A2F 2F6D7363 726C2E6D 6963726F 736F6674 2E636F6D 2F706B69 2F6D7363  tp://mscrl.microsoft.com/pki/msc
  03A0  6F72702F 63726C2F 6D736974 77777732 2E63726C 86346874 74703A2F 2F63726C  orp/crl/msitwww2.crl.4http://crl
  03C0  2E6D6963 726F736F 66742E63 6F6D2F70 6B692F6D 73636F72 702F6372 6C2F6D73  .microsoft.com/pki/mscorp/crl/ms
  03E0  69747777 77322E63 726C3070 06082B06 01050507 01010464 3062303C 06082B06  itwww2.crl0p..+. .......d0b0<..+.
  0400  01050507 30028630 68747470 3A2F2F77 77772E6D 6963726F 736F6674 2E636F6D  ....0..0http://www.microsoft.com
  0420  2F706B69 2F6D7363 6F72702F 6D736974 77777732 2E637274 30220608 2B060105  /pki/mscorp/msitwww2.crt0"..+...
  0440  05073001 86166874 74703A2F 2F6F6373 702E6D73 6F637370 2E636F6D 304E0603  ..0...http://ocsp.msocsp.com0N..
  0460  551D2004 47304530 4306092B 06010401 82372A01 30363034 06082B06 01050507  U. .G0E0C..+.... .7*.0604..+.....
  0480  02011628 68747470 3A2F2F77 77772E6D 6963726F 736F6674 2E636F6D 2F706B69  ...(http://www.microsoft.com/pki
  04A0  2F6D7363 6F72702F 63707300 30270609 2B060104 01823715 0A041A30 18300A06  /mscorp/cps.0'.. +.....7. ...0.0..
  04C0  082B0601 05050703 01300A06 082B0601 05050703 02300D06 092A8648 86F70D01  .+...... .0...+.. .....0.. .*.H....
  04E0  010B0500 03820201 001669E4 7195F000 62272E14 8FA840C6 30AC7029 F6E2EAFF  ........ ..i.q... b'....@. 0.p)....
  0500  F3171F73 C2C631D1 62339B16 3C9E854F 90AFD1FB 6615B636 0F570995 C4E80B10  ...s..1. b3..<..O....f..6.W......
  0520  79EFE4BF 5F7FCA65 B3A7F3B7 17E989F1 E924A516 F183E4B6 58F115CA 11D81A13  y..._..e........ .$...... X.......
  0540  B1BFB2D8 D9B72661 89B93409 9BA70BDE B455FD43 3BDBCB37 1EE7FEBD F15D4A4B  ......&a..4..... .U.C;..7.....]JK
  0560  1CB3C1B2 E72AE735 F7A2639D 9ED4AEEF D40B968D A062B5C1 41B202F7 80175C72  .....*.5..c..... .....b.. A.....\r
  0580  ED2819BC 4E9D5E7A 0A30CB9C 34702791 E5775386 60F31DB2 659954C7 6E12A732  .(..N.^z.0..4p'. .wS.`... e.T.n..2
  05A0  2161F448 96ADFC36 D80F6910 0396910B 3C19D2B6 B0EE05AC A94CB756 9FBCFC04  !a.H...6..i..... <....... .L.V....
  05C0  B26B66DA 037A79ED 66ADFB06 A487723B 55DD79B3 2BAF88C9 578CCFE6 3B762755  .kf..zy. f.....r;U.y.+... W...;v'U
  05E0  0C8EAB0F 61030A4D E5E59605 C2DA3BD4 1BF561FA 25FD6737 12DE34C4 853634EF  ....a..M......;. ..a.%.g7..4..64.
  0600  7EBEC1FE 5337B252 CE322624 D3115387 35300F45 99045512 DD038642 4E1C30E2  ~...S7.R.2&$..S. 50.E..U. ...BN.0.
  0620  92968B38 AE8A5C66 AC03C598 14886975 D84A3E92 E663B9E9 4F7C120B 9B8FAD17  ...8..\f......iu.J>..c.. O|......
  0640  37E26036 4FCBEB36 9A001ED0 2171B206 5B7951BD 67FBEED4 A08B1CBF 9B8BF4F2  7.`6O..6....!q.. [yQ.g... ........
  0660  D8A13732 D934E914 2E7CCDF8 24BD42E4 7E766C3E F9676447 3122293D E51A110A  ..72.4.. .|..$.B. ~vl>.gdG1")=....
  0680  2CA8B6BA DEBC3C8F 6A37904C 5340DCA0 6B76A4E7 32B8D4EC BBB1FB32 2DE66EA8  ,.....<. j7.LS@.. kv..2... ...2-.n.
  06A0  79AEF352 ACF58252 C39A5DD7 19B73E8B F07F82B0 F13C49D3 CBC3A866 E2869A1F  y..R...R..]...>. .....<I. ...f....
  06C0  834508E2 528BF75E E929B40D EEBDDEC0 F34C87CC 27FB2F5B DF1323D3 9C289BE4  .E..R..^.)...... .L..'./[..#..(..
  06E0  E17BEC8B FCB153FD F000058A 30820586 3082046E A0030201 02020407 279AA930  .{....S. ....0... 0..n.... ....'..0
  0700  0D06092A 864886F7 0D01010B 0500305A 310B3009 06035504 06130249 45311230  ...*.H.. ......0Z1.0...U. ...IE1.0
  0720  10060355 040A1309 42616C74 696D6F72 65311330 11060355 040B130A 43796265  ...U.... Baltimore1.0...U....Cybe
  0740  72547275 73743122 30200603 55040313 1942616C 74696D6F 72652043 79626572  rTrust1"0 ..U... .Baltimore Cyber
  0760  54727573 7420526F 6F74301E 170D3133 31323139 32303037 33325A17 0D313731  Trust Root0...131219200732Z..171
  0780  32313932 30303635 355A3081 8B310B30 09060355 04061302 55533113 30110603  219200655Z0..1.0...U.... US1.0...
  07A0  55040813 0A576173 68696E67 746F6E31 10300E06 03550407 13075265 646D6F6E  U....Washington1.0...U.. ..Redmon
  07C0  64311E30 1C060355 040A1315 4D696372 6F736F66 7420436F 72706F72 6174696F  d1.0...U....Microsoft Corporatio
  07E0  6E311530 13060355 040B130C 4D696372 6F736F66 74204954 311E301C 06035504  n1.0...U....Microsoft IT1.0...U.
  0800  0313154D 6963726F 736F6674 20495420 53534C20 53484132 30820222 300D0609  ...Microsoft IT SSL SHA20.."0...
  0820  2A864886 F70D0101 01050003 82020F00 3082020A 02820201 00D1E837 A7768A70  *.H..... ........ 0....... ...7.v.p
  0840  4B19F020 37092437 7FEAFB78 E605BA6A AD4E270D FC726AD9 6C21C464 11957310  K.. 7.$7...x...j.N'..rj. l!.d..s.
  0860  0A5C257B 886C9404 FDC7DBAE 7BDC4A08 B33E16F1 D0ADDB30 6DD71A1E 52B53DF0  .\%{.l.. ....{.J. .>.....0m...R.=.
  0880  471903E2 7DA6BD57 133F54EA 3AA3B177 FC42F063 496A9180 2E3049C0 8AEB2BAF  G...}..W.?T.:..w.B.cIj.. .0I...+.
  08A0  FE3AEB07 5D06F7E9 FD840E91 BD092029 E86E5D09 CE15D3E7 EFDB50EB 44EF1857  .:..]... ...... ).n]..... ..P.D..W
  08C0  AB041DBC 31F9F77B 2A13CFD1 3D51AF1B C5B57BE7 B0FC53BB 9AE763DE 4133B647  ....1..{*...=Q.. ..{...S. ..c.A3.G
  08E0  24695DB8 46A7FFAD ABDF4F7A 78252721 2634CA02 6E3751F0 ED581A60 94F6C493  $i].F... ..Ozx%'!&4..n7Q. .X.`....
  0900  D8DD3024 25D71CEB 1994355D 93B2AEAA 298373C4 74590552 679DDA67 5139053A  ..0$%... ..5].... ).s.tY.Rg..gQ9.:
  0920  36EAF21E 762B14AE EC3DF914 998B076E BCE70C56 DEACBEAE DB753290 9E63BD74  6...v+.. .=.....n...V.... .u2..c.t
  0940  BFE00ACA F8349667 84CDD142 3878C799 B60CCEB6 0FE91BCB F459BE11 0ECB2C32  .....4.g...B8x.. ........ .Y....,2
  0960  C8FA8329 64793C8B 4BF03274 6CF393B8 966B5D57 5A68C1CC 0C798A19 DEF54902  ...)dy<. K.2tl... .k]WZh.. .y....I.
  0980  5E088001 890C32CD D2D696D5 4BA0F3EC BFABF47D B3A1B97C DA4ED7E5 B7ACB9F2  ^.....2. ....K... ...}...|.N......
  09A0  255F01CB 8C96A828 AEC1335A F63F0890 DCEBFF39 D826C812 9D1C9AAA A9C0168E  %_.....(..3Z.?.. ...9.&.. ........
  09C0  86ED6752 96007F0D 923D3DD9 7036E5EA 426F1FAE 95E55B5D F8D03AC7 D4DE7786  ..gR.... .==.p6.. Bo....[]..:...w.
  09E0  D0FC9E4E E2E2B8A9 683709C4 39E385B8 89F31F6E B76D1F4A 2F18096F DE4A018F  ...N.... h7..9... ...n.m.J/..o.J..
  0A00  14C9B7A6 EEA7639F 33A4547C 428368B8 A5DFBFEC B91A5D13 3BD9AD68 FD200A55  ......c. 3.T|B.h. ......]. ;..h. .U
  0A20  912164F9 D71301A0 085D5989 1B44AFA4 ACC70510 FA414AA8 FB020301 0001A382  .!d..... .]Y..D.. .....AJ. ........
  0A40  01203082 011C3012 0603551D 130101FF 04083006 0101FF02 01003053 0603551D  . 0...0. ..U..... ..0..... ..0S..U.
  0A60  20044C30 4A304806 092B0601 0401B13E 0100303B 30390608 2B060105 05070201   .L0J0H. .+.....>..0;09.. +.......
  0A80  162D6874 74703A2F 2F637962 65727472 7573742E 6F6D6E69 726F6F74 2E636F6D  .-http://cybertrust.omniroot.com
  0AA0  2F726570 6F736974 6F72792E 63666D30 0E060355 1D0F0101 FF040403 02018630  /repository.cfm0...U.... .......0
  0AC0  1D060355 1D250416 30140608 2B060105 05070301 06082B06 01050507 0302301F  ...U.%.. 0...+... ......+. ......0.
  0AE0  0603551D 23041830 168014E5 9D593082 4758CCAC FA085436 867B3AB5 044DF030  ..U.#..0.....Y0. GX....T6.{:..M.0
  0B00  42060355 1D1F043B 30393037 A035A033 86316874 74703A2F 2F636470 312E7075  B..U...;0907.5.3.1http://cdp1.pu
  0B20  626C6963 2D747275 73742E63 6F6D2F43 524C2F4F 6D6E6972 6F6F7432 3032352E  blic-trust.com/CRL/Omniroot2025.
  0B40  63726C30 1D060355 1D0E0416 041451AF 24269CF4 68225780 262B3B46 62157B1E  crl0...U......Q. $&..h"W. &+;Fb.{.
  0B60  CCA5300D 06092A86 4886F70D 01010B05 00038201 01007685 C523311F B473EAA0  ..0...*. H....... ......v. .#1..s..
  0B80  BCA5EDDF 45436A7F 69201B80 B2FB1CDD AA7F88D3 314136F7 FBFB6BAD 988C781F  ....ECj. i ...... ....1A6. ..k...x.
  0BA0  9D11673A CD4BECA8 BC9D1519 C43B0BA7 93CEE8FC 9D5BE81F CB56AE76 432BC713  ..g:.K.. .....;.. .....[.. .V.vC+..
  0BC0  517741A8 664C5FA7 D1D7AA75 C51B294C C9F46DA1 5EA18593 16C2CB3B AB147D44  QwA.fL_. ...u..)L..m.^... ...;..}D
  0BE0  FDDA2529 862AFE63 20CAD20B C23415BB AF5B7F8A E0AAED45 A6EA79DB D8356654  ..%).*.c ....4.. .[.....E..y..5fT
  0C00  43DE3733 D1E4E0CD 57CA71B0 7DE91677 64E85997 B9D52ED1 B491DA77 71F34A0F  C.73.... W.q.}..wd.Y..... ...wq.J.
  0C20  48D23499 609537AC 1F01CD10 9DE82AA5 20C7509B B36C4978 2B589264 89B89536  H.4.`.7. ......*.  .P..lIx+X.d...6
  0C40  A834AAF0 41D2955A 2454974D 6E05C495 ADC47AA3 39FB7906 8A9BA64F D922FA44  .4..A..Z$T.Mn... ..z.9.y. ...O.".D
  0C60  4E36F3C9 0FA639E7 80B25EBF BD39D146 E55547DB BC6E0C00 01670300 186104B8  N6....9. ..^..9.F.UG..n.. .g...a..
  0C80  987AFCB2 751E1427 9C4E6DFF 7796B262 AECC1E50 B495CF5A A633D02D 702D60F1  .z..u..'.Nm.w..b...P...Z.3.-p-`.
  0CA0  0663BB8B 5FE62FC6 062EC87A DB746D2A 8349D62E E84FB3BC 3669F80F 55CD076E  .c.._./. ...z.tm*.I...O.. 6i..U..n
  0CC0  2BA28701 60DF3053 C2665E9A 46E49992 3593B8FD B262A987 1789D045 8F7B5D01  +...`.0S.f^.F... 5....b.. ...E.{].
  0CE0  0015CAFF C9564D4F A61FE8E8 AEB6F784 EBBF598C DBD68241 4B1AD930 9782C43E  .....VMO........ ..Y....AK..0...>
  0D00  31F1138B D2E19CAA 9FD7F06A 50D77057 12C533D5 37482276 486F3371 1F4900F6  1....... ...jP.pW..3.7H"vHo3q.I..
  0D20  13558A6A 7176CD1B F1D2D4E6 5EBB4F2B 2A0FA7E3 2934ADF7 F4A7A957 E2F084B4  .U.jqv.. ....^.O+*...)4.. ...W....
  0D40  0E5C5F1B 4452E3EB 510DF126 260B71F1 41D3BA54 8630351C 3E66EEFF 76319E58  .\_.DR.. Q..&&.q. A..T.05. >f..v1.X
  0D60  CD137829 A4783E92 70672AD5 E956EF74 129523F8 ADAA2944 696C5DB0 BF5231CA  ..x).x>. pg*..V.t..#...)Dil]..R1.
  0D80  9F2F3C73 6FE98DE7 18F554B3 E7CD9E8F 3E059894 96C1ED13 B8A472D0 7442260F  ./<so... ..T..... >....... ..r.tB&.
  0DA0  17FB2E4F C443F444 07A5274F E44E219A 430C0678 4A569FF7 09024F3A F3B99D2C  ...O.C.D..'O.N!. C..xJV.. ..O:...,
  0DC0  6AD20D75 9D6D29C9 8E9CC039 C34EF615 2B067D09 477D3E98 99A8E02B E84A83F3  j..u.m). ...9.N.. +.}.G}>. ...+.J..
  0DE0  FE0E0000 00  .....
Connected to Database sensorData
Sent
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x00AE, spid:0x0000, packetId:0x01, window:0x00
  0000  16030100 66100000 62610404 89529B89 5A209E37 B1443BD0 BF9FDA0B 5B6BED84  ....f... ba...R.. Z .7.D;. ....[k..
  0020  85D42CD3 05686E90 8FC18968 C3DCB1E4 39ECB53F 118F49CE C652876B 2B99DC35  ..,..hn. ...h.... 9..?..I. .R.k+..5
  0040  A547C90F 9201D64C 4EADD5A8 3ABB1377 FC87F4CE 062DA2B9 DC9BA02D C926B803  .G.....LN...:..w.....-.. ...-.&..
  0060  27CBC849 82831957 5CAACF14 03010001 01160301 00306417 065D1796 B0DDDF77  '..I...W\....... .....0d. .].....w
  0080  CA62DEDF AF8AFE52 547172C0 51BB58E9 BD252B64 753D415D FDEB513D DA848499  .b.....RTqr.Q.X. .%+du=A]..Q=....
  00A0  29925000 6787  ).P.g.
Connected to Database sensorData
Received
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x0043, spid:0x0000, packetId:0x01, window:0x00
  0000  14030100 01011603 010030F9 2601E838 5261DD93 4A950896 B55E959F BA78B84F  ........ ..0.&..8Ra..J... .^...x.O
  0020  4FEA6B22 92265B0C A01687B1 F6154ECB 42438F60 C01D0022 B33334  O.k".&[. ......N. BC.`...".34
TLS negotiated (ECDHE-RSA-AES256-SHA, TLSv1/SSLv3)
State change: SentTLSSSLNegotiation -> SentLogin7WithStandardLogin
Connected to Database sensorData
Received
  
{ number: 18456,
  state: 1,
  class: 14,
  message: 'Login failed for user \'*****\'.',
  serverName: '****',
  procName: '',
  lineNumber: 1,
  name: 'ERROR',
  event: 'errorMessage' }
{ number: 40608,
  state: 1,
  class: 10,
  message: 'This session has been assigned a tracing ID of \'89796195-3696-42c1-a1ae-2bec2f258328\'.  Provide this tracing ID to customer support when you need assistance.',
  serverName: '***',
  procName: '',
  lineNumber: 1,
  name: 'INFO',
  event: 'infoMessage' }
{ name: 'DONE',
  event: 'done',
  more: false,
  sqlError: true,
  attention: false,
  serverError: false,
  rowCount: undefined,
  curCmd: 0 }
State change: SentLogin7WithStandardLogin -> Final
connection to ****.database.windows.net:1433 closed
State is already Final

============================================================================

I am new to tedious. Any help will be greatly appreciated.

**Comment by ReadySoftTeam** [comment]
Prueba esto

const sequelize = new Sequelize('DB Name', 'Username', 'Password', {
    host: 'Host',
    dialect: 'mssql',
    dialectOptions: {
        options: {
            encrypt: true,
        }
    }
  });

**Comment by ReadySoftTeam** [comment]
A mi me funciono de esta forma:

const sequelize = new Sequelize('DB Name', 'Username', 'Password', {
    host: 'Host',
    dialect: 'mssql',
    dialectOptions: {
        options: {
            encrypt: true,
        }
    }
  });
