### ISSUE TITLE
Invalid state; requests can only be made in the LoggedIn state, not the SentClientRequest state

### ISSUE THREAD

**Issue by rgarrison3** [tediousjs/tedious#19]
This issue arises when calling one request then refreshing the page. I have the code that I have wrote for this if anyone is interested in duplicating it.

http://c9754731.r31.cf2.rackcdn.com/WebServicesServlet_Exam.zip

All you have to do to set this up (I built it and use it on windows so I dont know how it will work on linux lol). You just need to setup the ConnectionConfig.js file in the lib folder with your connection info and then modify the gateway test method.

Any help with this would be greatly appreciated!!!

**Comment by hasan3ysf** [comment]
Hi,
I understood the above clearly, and tried to stick to it in my application.
The code below, do the following:
1. Every 1 second, fetsh the data from the server (fetchStock function) and save it in temporary array, 
2. Every 1 second, send the data saved in the temporary array to the client using the Server-Sent Events (SSE) API.

It looks the 1 second, is not enough, so I got getting the error mentioned here, many times, so i increased it to 5 second, but still git it from time to time.

Is there a way to use Promise().then to be sure the fetchStock  function is not re-called before the first call be completely executed.

    var Request = require('tedious').Request;
    var Connection = require('tedious').Connection;
    var config = {
         userName: 'sa',
         password: 'pswd',
        server: 'xx.xxx.xx.xxx',
        options: {
        	database: 'DB',
                 rowCollectionOnRequestCompletion: 'true',
                 rowCollectionOnDone: 'true'
	     },
     };
    var sql = new Connection(config);
    
    var addElem = (obj, elem)=> [].push.call(obj, elem);
    var result = {}, tmpCol = {}, tmpRow = {};
    module.exports = {

      displayStock: function (es) {
		  var dloop = setInterval(function() {
		  if(result.error !== null)
		        if (es) es.send(JSON.stringify(result), {event: 'rmSoH', id: (new Date()).toLocaleTimeString()});
		  if(result.error === null)
		        if (es) es.send('connection is closed');
	      }, 1000);
      },

      fetchStock: function () {
                request = new Request("SELECT ItemCode, WhsCode, OnHand FROM OITW where OnHand > 0 and (WhsCode ='RM' or WhsCode ='FG');", function(err, rowCount, rows) {
			    if (err) {
				result = {'error': err};
				console.log((new Date()).toLocaleTimeString()+' err : '+err);
			     }
                 if(rows)
			     rows.forEach(function(row){
					 row.forEach(function(column){
					     var colName = column.metadata.colName;
					     var value = column.value;
					     addElem(tmpCol, {colName: value})
					 });
				 addElem(tmpRow,{'item': tmpCol[0].colName, 'Whs': tmpCol[1].colName, 'Qty': tmpCol[2].colName});
				 tmpCol = {};
			   });
			   result = tmpRow;
			   tmpRow={}
		   });
	    sql.execSql(request);
      }
    }

**Comment by swapnilkadu** [comment]
I am still getting the same issue, please look at the code below:
```javascript
var Connection = require('tedious').Connection;
var Request = require('tedious').Request;
var TYPES = require('tedious').TYPES;

var config2 = {
    userName: 'dbuser',
    password: 'dbpass',
    server: 'mysqlserver.com',
    options: {
        database: 'msdb'
    }
};

var connection = new Connection(config2);
    connection.on('connect', function(err) {
        if(err) {
            console.log("Database connection is not established: \n"+err);
            process.exit(0);
        } else {
            console.log("Connected");  // If no error, then good to proceed.
            createTableOperation();
        }
    });  

function createTableOperation() {
    var query = "CREATE TABLE ClientDetailsTest(CLIENT_ID CHAR(5) PRIMARY KEY, CLIENT_NAME VARCHAR(25), CLIENT_CHANNEL VARCHAR(25))";
        
    request = new Request(query, function(err){
        if(err) {
            console.log("Error while creating table: "+err);
            process.exit(0);
        }
    });
    connection.execSql(request);
}
```

**Comment by arthurschreiber** [comment]
@swapnilkadu What error are you seeing exactly? Do you see any of the `console.log` statements?

**Comment by parths3an** [comment]
I am wondering how the above issue of @swapnilkadu fixed? I am having the same issue. Any pointers?

**Comment by LakMoore** [comment]
Comment out the 
`connection.execSql(request);`
as it will probably be masking the true error (which in my case was bad credentials).
