### ISSUE TITLE
using Windows Authentication

### ISSUE THREAD

**Issue by leijing7** [tediousjs/tedious#214]
I read the doc says support domain login, but I still got message: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.

I used the same config with another module [odbc](https://www.npmjs.org/package/odbc). It did not have any problems. 

Do I have to switch to ODBC to use windows authentication?

**Comment by bretcope** [comment]
@russj would you mind giving the fix presented in pull request #228 a try and see if it works for you?
