### ISSUE TITLE
new Request(fn) releases zalgo

### ISSUE THREAD

**Issue by vvo** [tediousjs/tedious#234]
We came up on a bug in sequelize because of this: https://github.com/pekim/tedious/blob/935d698f484f5a326ebadf30159315af77c65f70/src/request.coffee#L20

Callback is called synchronously and thus it can lead to very strange behavior in other people code like this: https://github.com/sequelize/sequelize/blob/6a0912ad82915fd7bf20bd71ad7707abd473a137/lib/dialects/mssql/query.js#L68

promise === undefined at this point because the implementer thought that the callback to new Request was asynchronous.

This is called as releasing zalgo: http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

Do you think you could make it fully asynchronous by default? Would it be a good idea?

Thanks.

**Comment by arthurschreiber** [comment]
Yes. I'll look into it.

**Comment by IanChokS** [comment]
Since the bug lies in a .coffee script and tedious no longer uses .coffee, I'm going to assume this particular type of issue has been resolved.
