### ISSUE TITLE
Serialize Results

### ISSUE THREAD

**Issue by tracker1** [tediousjs/tedious#257]
Related to #181, although a true pause/resume would be nice, I would be happy if the cursor could be put into a mode that only returned a single row at a time, with a `next` callback to fetch/return the next row when ready.

I'm trying to export/dump a several million records to a CSV with additional processing that has to happen per record, and am running out of memory (hitting node/v8's limits) before the process can complete.  A simple serialization against a cursor, while less beneficial than actual stream/backpressure support, would be sufficient for my needs, and I can only guess I am not the only one that can use this.

TIA.

**Comment by v-suhame** [comment]
Done in https://github.com/tediousjs/tedious/pull/518.
