### ISSUE TITLE
Internal Error: No event 'attention' in state 'Final'

### ISSUE THREAD

**Issue by bitsoflogic** [tediousjs/tedious#260]
This was triggered by the connection event, 'error':

```
Error: No event 'attention' in state 'Final'
    at Connection.dispatchEvent (.../node_modules/tedious/lib/connection.js:754:26)
    at Parser.<anonymous> (.../node_modules/tedious/lib/connection.js:615:19)
    at Parser.emit (events.js:95:17)
    at Parser.nextToken (.../node_modules/tedious/lib/token/token-stream-parser.js:91:18)
    at Parser.addBuffer (.../node_modules/tedious/lib/token/token-stream-parser.js:68:17)
    at Connection.sendDataToTokenStreamParser (.../node_modules/tedious/lib/connection.js:891:35)
    at Connection.STATE.SENT_ATTENTION.events.data (.../node_modules/tedious/lib/connection.js:297:23)
    at Connection.dispatchEvent (.../node_modules/tedious/lib/connection.js:752:59)
    at MessageIO.<anonymous> (.../node_modules/tedious/lib/connection.js:680:22)
    at MessageIO.emit (events.js:95:17)
```

I've been using `tedious` in production on a cron that runs every 5 minutes for about a week and then this event was triggered 284 times over a 4 second period with the same error message.

**Comment by bretcope** [comment]
@arthurschreiber would you mind taking a look at this? I believe you're the one who wrote the attention event.

**Comment by bitsoflogic** [comment]
If helpful, this is for connections made to SQL Server 10.0.5520.  Looking at this again, I would guess the 4 second window mentioned in the earlier post was probably the entire duration of the cron job.  By the time it ran again 5 minutes later, the problem was resolved.

**Comment by arthurschreiber** [comment]
This is weird. I can't really debug this without more information, but it looks like `tedious` switched into the `Final` state and *then* received a bunch of `done` tokens with the `attention` bit event set.

**Comment by bitsoflogic** [comment]
@arthurschreiber Do you think this is truly an error?  Or, should Tedious simply have an `attention` event in the `Final` state?  If it is an error, is there anything I can provide to help troubleshoot it?

**Comment by arthurschreiber** [comment]
I'd guess it is an error. IIRC, the TDS spec does not allow `attention` events to happen in the FINAL state (as the FINAL state means you're already disconnected from the server). It might be some weird ordering issue causing this.

**Comment by bitsoflogic** [comment]
I've been researching this for awhile however my knowledge of TDS is limited.  It seems like this is a race condition, which I'm thinking I may be creating.  I am using the `tedious-connection-pool`, then do this:

```
request.on('doneProc', function(...) {
   ...
   connection.close();
   ... 
});
```

I need to research more later, but I believe that `connection.close()` was created before I found the `tedious-connection-pool` library and was attempting to implement a very basic version of it.

**Comment by lee-houghton** [comment]
I'm seeing a lot of "no event 'data' in state 'final'"... Should I raise a
separate issue for it? I haven't yet had time to look into it.

**Comment by arthurschreiber** [comment]
> It seems like this is a race condition, which I'm thinking I may be creating.

You're spot on. The issue here is that the `doneProc` is emitted asynchronously, and before a done token was completely processed by tedious. So basically, you're `close`ing the connection before tedious has handled potential `attention` events stemming from a `done` token.

if you wrap `connection.close` in `setImmediate/process.nextTick`, the issue should go away.

We still should investigate a proper fix for this in tedious.

**Comment by bitsoflogic** [comment]
Thanks for the feedback.  I'll make that change.

To add some context, I am using `doneProc` as a way to determine when any SQL statement is done (not just stored procedures).  When `doneProc` is fired, I assume all `row` events have been fired and I send the data gathered from those `row` events back via a callback.  Just before calling the callback, I execute `connection.close` to free up the connection.
