### ISSUE TITLE
immediately get "end" event

### ISSUE THREAD

**Issue by mvolkmann** [tediousjs/tedious#279]
After creating a connection and registering for the "connect", "error", and "end" events, I immediately get an "end" event and the program exits. A simple example is below. Any idea what I'm missing?

``` js
var Connection = require('tedious').Connection;

var config = {
  userName: 'some-name',
  password: 'some-password',
  server: 'some-ip-address'
};

var connection = new Connection(config);
connection.on('connect', function (err) {
  console.log('got connect');
});

connection.on('end', function () {
  console.log('got end');
});

connection.on('error', function (err) {
  console.log('got err =', err);
});
```

**Comment by arthurschreiber** [comment]
Nope, no idea what's wrong - your example code looks fine. You could try to enable more verbose debug output and post it in a gist so we can better understand what is happening.
