### ISSUE TITLE
Reading and writing LOBs in streaming mode

### ISSUE THREAD

**Issue by bjouhier** [tediousjs/tedious#316]
Is it possible to read large objects (BLOBs and CLOBs) in streaming mode?

**Comment by IanChokS** [comment]
@bjouhier In Sql Server, [BLOBs ](https://stackoverflow.com/questions/8240858/how-to-declare-a-blob-in-sql-server) are equivalent to data type `VARBINARY(MAX)`, and [CLOBs](http://www.sqlines.com/oracle/datatypes/clob) are equivalent to `VARCHAR(max)` in Sql Server.
