### ISSUE TITLE
Cannot return values after INSERT

### ISSUE THREAD

**Issue by jeremyalan** [tediousjs/tedious#343]
I've been chasing this one for a few days, and not sure what I'm doing wrong... I'm connecting to a DB instance on SQL Azure from Node.js running locally on my MacBook.

Basically, I want to be able to INSERT a record, grab the SCOPE_IDENTITY(), and use that to select a generated `uniqueidentifier`, and return it via output parameter.

So, for example...

```
CREATE TABLE [Sample].[SampleTable]
(
   [SampleTableId] int NOT NULL IDENTITY(1, 1),
   [UniqueId] uniqueidentifier NOT NULL
         CONSTRAINT [DF_Sample_SampleTable_UniqueId] DEFAULT (NEWID()),

   ...

   CONSTRAINT [PK_Sample_SampleTable_SampleTableId] PRIMARY KEY CLUSTERED
   (
      [SampleTableId] ASC
   ),

   CONSTRAINT [UK_Sample_SampleTable_UniqueId] UNIQUE NONCLUSTERED
   (
      [UniqueId] ASC
   )
);
```

... then, I invoke this stored procedure ...

```
CREATE PROCEDURE [Sample].[CreateSampleRow]
   ...

   -- Output parameters.
   @UniqueId uniqueidentifier = NULL OUTPUT
AS

SET NOCOUNT ON;

INSERT INTO [Sample].[SampleTable](...)
VALUES (...);

DECLARE @NewId int = SCOPE_IDENTITY();

SET @UniqueId = (
   SELECT S.[UniqueId]
   FROM [Sample].[SampleTable] S
   WHERE S.[SampleTableId] = @NewId
);
```

When I run this query, it emits a 'returnValue' event, but the value is always null.

I've also tried just using the SELECT at the end of the query to select the UniqueId value instead of using the output parameter (not my preference, but I could switch it if I had to), but again, the query seems to run fine, and I receive 'columnMetadata' and 'doneInProc' events, but the 'row' event never fires for my final SELECT so I can't retrieve the newly created UniqueId from my Node.js function.

It may also be worth noting, if I run my procedure inside of SQLPRO for MSSQL, everything appears to work exactly as expected.  It only fails when running inside of Node.js using the tedious driver.

**Comment by lee-houghton** [comment]
What values are you passing to `request.addOutputParameter`?

**Comment by IanChokS** [comment]
@jeremyalan Were you able to figure out your issue? Since it's been a while, i'll close this for now, but in the off chance that you're still encountering this problem, feel free to re-open this issue.

**Comment by jeremyalan** [comment]
Yep, that's fine, I honestly don't remember what the resolution was. :)
