### ISSUE TITLE
Tedious crash when inputing credentials from another DB

### ISSUE THREAD

**Issue by arkihillel** [tediousjs/tedious#353]
Discussed here https://github.com/pekim/tedious/issues/132#issuecomment-162495422

Still having the same issue

**Comment by IanChokS** [comment]
@arkihillel I know it's been sometime, but with the latest tedious version, are you still getting a crashing error? For a different server, the expected behaviour should should output a `Failed to connect to ....`

**Comment by arkihillel** [comment]
@IanChokS it's been quite some time since I had any use for Tedious. I don't even have access to my then DBs and code so I cannot really test it again. I guess you can close this one
