### ISSUE TITLE
Tedious modifies passed in `config` object

### ISSUE THREAD

**Issue by arthurschreiber** [tediousjs/tedious#363]
Tedious currently modifies the `config` object that is passed into the `Connection` constructor. This is bad practice and causes a lot of problems, as this is quite unexpected.

See #356 for one such problem.

The simplest fix for this would be if `tedious` would create a deep copy of the passed in `config` object.

**Comment by arthurschreiber** [comment]
@tvrprasad The "correct" way to fix this would be to create a copy of the config object (and any nested objects) using `Object.create`. This is also the pattern that Node.js core code is using as a solution for the same problem.

**Comment by tvrprasad** [comment]
@arthurschreiber Submitted pull request - https://github.com/tediousjs/tedious/pull/445.
