### ISSUE TITLE
Debug messages emitted despite connection config having them off

### ISSUE THREAD

**Issue by akc42** [tediousjs/tedious#364]
A short while ago I turned on debugging to find out what was happening with a problem I was having (its a connection pool problem).  This involved be switching debugging on in the connection config and creating a listener elsewhere in my code for the emitted debug event on the connection.

I turned debugging off again but forgot I had left the listener in my code.  I was still getting token debug messages coming, despite the default in the documentation that it was false.

**Comment by arthurschreiber** [comment]
Hey @akc42 

Thank you for your issue. :heart: Can you provide a simple reproducible test case for this issue you're seeing?

**Comment by akc42** [comment]
@arthurschreiber  I am not sure what form you want this in. The way I am using it is in a library I built which wraps round some of the connection and request functions, and its way too complicated to give you that.  

I'll try and mock up a simple node file that does what I am doing and see if I can reproduce it with that.  They we can discuss how you want to see given the database I am using here.

**Comment by akc42** [comment]
The following is a simple node file that I created which demonstrates the problem.
```
  var TYPES = require('tedious').TYPES;
  var Request = require('tedious').Request;
  var Pool = require('tedious-connection-pool');

  var poolConfig = {
    min: 2,
    max: 4,
    log: false
  };

  var DBHOST = 'xxxxx';
  var DBUSER = 'xxxxx';
  var DBPASS = 'xxxxx';
  var DBNAME = 'xxxxx';


  var pool = new Pool(poolConfig, {
    server: DBHOST,
    userName: DBUSER,
    password: DBPASS,
    options: {
      port: 1433,
      database: DBNAME,
      useColumnNames: true,
      connectTimeout: 15000,
      requestTimeout: 15000
    }
  });
  pool.on('error', (err) => {
    pool.drain();
    process.kill(process.pid,'SIGINT'); //tells us to shutdown gracefully
  });

  pool.acquire(function(err, conn) {
    console.log('acquired connection');
    conn.on('debug', function(message) {
      console.log('DEBUG MESSAGE: '  + message);
    });
    var sql = 'SELECT SourceName FROM MarketingSource WHERE isInUse = 1 ORDER BY Priority DESC';
    var request = new Request(sql,function(err,rowCount) {
      console.log('request completed');
      conn.release();
      pool.drain();
      setTimeout(function() {
        console.log('SHUTTING DOWN');
      },300);
    });
    request.on('row', function(columns) {
      console.log('request row received');
    })
    conn.execSql(request);
  });

```
The following is the output from running that.  You will see I get debug messages but nothing sets debug on.

```
acquired connection
DEBUG MESSAGE: State change: LoggedIn -> SentClientRequest
request row received
request row received
request row received
request row received
request row received
request row received
request row received
request row received
request row received
request row received
request row received
request row received
DEBUG MESSAGE: State change: SentClientRequest -> LoggedIn
request completed
DEBUG MESSAGE: State change: LoggedIn -> SentClientRequest
DEBUG MESSAGE: State change: SentClientRequest -> Final
DEBUG MESSAGE: connection to DBHOST:1433 closed
DEBUG MESSAGE: State is already Final
SHUTTING DOWN
```

**Comment by IanChokS** [comment]
@akc42  I don't think is a bug, but rather the design. Connection object will always emit state change messages in the 'debug' event but you don't necessarily have to capture them. The config.options.debug simply allows you to capture more detailed events if you desired to do so (such as data, packet, payload or token). 

Closing this for now, but @arthurschreiber if I'm wrong, please re-open this issue.
