### ISSUE TITLE
Failed to connect message doesn't take into account default port

### ISSUE THREAD

**Issue by jcollum** [tediousjs/tedious#373]
src/connection.js line 430

`const message = 'Failed to connect to ' + this.config.server + ':' + this.config.options.port + ' in ' + this.config.options.connectTimeout + 'ms';`

I'm using the default port, which doesn't seem to have made it into to the config.options. Results in an error that is misleading: `Failed to connect to DEF.abc.xyz.com:undefined in 15000ms (err.code=ETIMEOUT)` -- note the 'undefined'.

**Comment by tvrprasad** [comment]
Can you share the full script where you're running into the issue?

**Comment by Anthropic** [comment]
I run the following and get the same error, hope it helps.
node: 5.1.0
npm: 3.3.12
tedious: 1.14.0
tedious-connection-pool: 1.0.5
@jcollum are you using tedious-connection-pool too?

I use **instance name** so port isn't required, if I add port I get a mutual exclusivity error.

There are two separate issues here, the error message could be cleaned up, I have added PR #535 to tackle that issue.

However the main issue is the connection error which is something different, it appears to work for a while **then the timeout occurs**, so it seems like it may be failing even after successful connection.

```bash
ConnectionError: Failed to connect to UMELDT03.corp.uecomm.com.au:undefined in 15000ms
    at ConnectionError (/media/sf_ue/hg/PTN/node/node_modules/tedious/lib/errors.js:12:12)
    at Connection.connectTimeout (/media/sf_ue/hg/PTN/node/node_modules/tedious/lib/connection.js:467:28)
    at Timer.listOnTimeout (timers.js:92:15)
```

Here is my connection script:
```js
  function MssqlDataAccess(config) {
    var mssqlCon = {
      'userName': config.username,
      'password': config.password,
      'server': config.host,
      'options': { 'instanceName': config.instanceName }
    };

    var mssqlPool = { max: config.max, idelTimeOutMills: config.timeout };

    this.pool = new ConnectionPool(mssqlPool, mssqlCon);
    this.sqlLinkedServerName = config.linkServer;
  };

  MssqlDataAccess.prototype._execProc = function(name, params, callback) {
    var self = this;

    this.pool.acquire(function(err, connection) {
      if (err) { return callback(err); }

      var result = {};
      result.records = [];
      result.parameters = {};
      var request = new Request(name, function(err /*, rowCount*/) {
        if (err) { return callback(err); }
        callback(null, result);
        connection.release();
      });

      for (var i = 0; i < params.length; i++) {
        if (params[i].isOut) {
          request.addOutputParameter(params[i].name, params[i].type);
        }
        else {
          var def = params[i].type === TYPES.Bit ? false : null;
          request.addParameter(params[i].name, params[i].type, params[i].value || def);
        };
      };

      request.on('row', function(columns) {
        var record = {};
        columns.forEach(function(column) {
          record[self._convertCol(column.metadata.colName)] = column.value;
        });
        result.records.push(record);
      });

      connection.callProcedure(request);
    });
  };
```

**Comment by tvrprasad** [comment]
> ConnectionError: Failed to connect to UMELDT03.corp.uecomm.com.au:undefined in 15000ms

@Anthropic Your timeout looks like just a case of slow network. You may want to set config.options.connectTimeout to a higher value, say 60000.

> Results in an error that is misleading: Failed to connect to DEF.abc.xyz.com:undefined in 15000ms (err.code=ETIMEOUT) -- note the 'undefined'.

@jcollum This works fine in the latest bits of Tedious and will make it in the next release. From a test I ran on my machine where I didn't specify the port:
__ConnectionError: Failed to connect to localhost:1433 in 10ms__

I'm closing this. Feel free to re-activate if I missed something.

**Comment by jcollum** [comment]
Good deal, fhanks
