### ISSUE TITLE
No event 'socketConnect' in state 'SentPrelogin'

### ISSUE THREAD

**Issue by fantasywind** [tediousjs/tedious#377]
Try to initial connection will throw error `No event 'socketConnect' in state 'SentPrelogin'` on SQL Server 2000

I already try to set tdsVersion to **7_1**, but still not work.

Node.js Environment: 
v5.10.1 on Windows Server 2008 32bit

tedious@1.13.2

Thank you for help

**Comment by gingters** [comment]
I have the exact same issue when trying to connect to a SQL Azure db.

**Comment by arthurschreiber** [comment]
Looks like this is specific to SQL Server 2000. We don't run SQL Server 2000 during our CI builds on AppVeyor (it's not available by default), so this issue must have been introduced without anyone noticing.

**Comment by IanChokS** [comment]
@fantasywind @gingters did you encounter the same issue also with newer SQL Server's?

**Comment by IanChokS** [comment]
@fantasywind @gingters, if your connecting to SQL Server 2000, you need to specify tds version to 7_1 in your config like so:

```js
   var config = {
            options: {		
                ...,
                tdsVersion: '7_1'
            }
          };
```

If this doesn't help, please re-open this issue.

**Comment by norogoth** [comment]
I am getting
`Error: No event 'socketConnect' in state 'SentPrelogin'`
for
```js
var Connection = tedious.Connection;
var config = {
    server: 'localhost',
    authentication: {
        type: 'default',
        options: {
            userName: username,
            password: password,
        }
    },
    options: {
        port: 1433,
        //encrypt: false,
    }
};
```
