### ISSUE TITLE
Notification of update query

### ISSUE THREAD

**Issue by WolfieWerewolf** [tediousjs/tedious#384]
I'm sorry to ask such a basic question but I can't find this.  If I listen for request.on('row')... I get the results for select queries however when I do an update query I haven't been able to figure out how to listen for confirmation / error when the operation is complete.  I'm sure this is a simple one and again I'm sorry for such a basic question.  Any advice is greatly appreciated.
Thanks
/W

**Comment by IanChokS** [comment]
Based on the TDS Docs, "`The DONE token marks the end of the response for each executed SQL statement. Based on the SQL statement and the context in which it is executed, the server MAY generate a DONEPROC or DONEINPROC token instead.`" 

To capture these events, you can use `request.on('done')`, `request.on('doneInProc')`, or `request.on('doneProc')`;

Re-open this issue if this doesn't help!

**Comment by WerewolFox** [comment]
Thanks for the response... I opened this in 2016 :-)

**Comment by IanChokS** [comment]
Yeah sorry about 🙈 I didn't join tedious until a few months ago. Out of curiosity, were you able to figure our your original issue?

**Comment by WolfieWerewolf** [comment]
Unfortunately it was so long ago I don't remember.... There has been a lot of code written between now and then...
