### ISSUE TITLE
tedious vs msnodesqlv8 perf comparison

### ISSUE THREAD

**Issue by csucla2015** [tediousjs/tedious#385]
Hello @pekim 
Thanks for all your work on tedious. We truly appreciate it. We are doing some investigation around the performance and stress comparisons between [tedious](https://github.com/pekim/tedious) and [msnodesqlv8](https://github.com/TimelordUK/node-sqlserver-v8). What are your thoughts around it? Have you done any testing? 

Thanks!

**Comment by IanChokS** [comment]
@csucla2015 if you find tedious lacking in either performance or stress comparisons, lets us know and how we may improve :)
