### ISSUE TITLE
Adding a function to Object.prototype breaks Request.validateParameters

### ISSUE THREAD

**Issue by kcsampson** [tediousjs/tedious#386]
I created a simple function and added it to Object.prototype.myFunc = function(){...}

Now I get a "TypeError: unkn..." in the middle of validateParameters.   For some reason, an extra "empty" parameter gets added to "this.parameters".  Here is some code I tried as a workaround that fixes my problem.

`

```
value: function validateParameters() {

   // I added this reduce call to get rid of the extra empty parameter(s)
    this.parameters = this.parameters.reduce(function( parms,parm, i){
        if ( parm.name ) parms.push(parm);
        return parms;
    },[]);



 for (var i = 0, len = this.parameters.length; i < len; i++) {
    var parameter = this.parameters[i];
    var value = parameter.type.validate(parameter.value);
    if (value instanceof TypeError) {
        console.log("uh oh, on tedious");
      return this.error = new _errors.RequestError("Validation failed for parameter '" + parameter.name + "'. " + value.message, "EPARAM");
    }
    parameter.value = value;
  } 

  return null;
}
```

  }]);

`

**Comment by lee-houghton** [comment]
What you're doing is called duck punching and is bad for many reasons. The
best way to fix this is just don't do it.

If that's really not an option, you may need to use Object.defineProperty
to make the property non-enumerable. That way, when tedious does its for-in
loop or Object.keys() or whatever it does, it won't see your property.
