### ISSUE TITLE
DateTime millisecond precision

### ISSUE THREAD

**Issue by symi** [tediousjs/tedious#391]
I've noticed the DateTime millisecond precision seems to be losing the thousandth of a second figure. If I create a param (for a stored sproc request), with type DateTime and set the value to be 2016-05-27 11:05:06.763 (as a JS Date object). The actual value present in sqlserver seems to be 2016-05-27 11:05:06.760. 

I've tracked it down to this code in data-type.js 

``` javascript
threeHundredthsOfSecond = milliseconds / (3 + (1 / 3));
threeHundredthsOfSecond = Math.floor(threeHundredthsOfSecond);
```

I assume this has something to do with the 3 millisecond precision of DateTime ( .000, .003, or .007) however it shouldn't be rounding 003 to 000.

As a quick fix I've changed `Math.floor` to `Math.round` [see commit on my fork](https://github.com/symi/tedious/commit/7d00214232cbb79e9e7f6c96e92952c2f5102ae6) which _seems_ to work... however I'm no expert in this area and not 100% sure if it's the correct fix, so waiting on advice before PR'ing.

**Comment by frikkievb** [comment]
I've tried your suggestion but with no success.  Also struggling with this problem.
