### ISSUE TITLE
Requests with multiple statements

### ISSUE THREAD

**Issue by nvsoares** [tediousjs/tedious#395]
HI.
I'm trying to execute a set of instructions cycle. the probelma is that whenever I get the following error: Requests can only be made in the LoggedIn state, not the SentClientRequest state.
Here is a small example:

``` javascript
'use strict';
const Connection = require('tedious').Connection
const Request = require('tedious').Request;

const config = {
    userName: 'your-username',
    password: 'your-password',
    server: 'your-server',

    options: {
        instanceName: 'your-instance',
        database: 'your-database',
        rowCollectionOnRequestCompletion: true
    }
};

let connection = new Connection(config);
let commands = ["select 1", "select 2"];

connection.on('connect', function (err) {
    if (err) {
        console.log(err);
    } else {
        commands.forEach((cmd) => {
            execute(cmd);
        });
    }
}
);

function execute(cmd) {
    var request = new Request(cmd, function (err, rowCount) {
        if (err) {
            console.log('Request error: ' + err);
        } 

        connection.close();
    });

    connection.execSql(request);
}

// connection.on('debug', function (text) {
//     console.log(text);
// }
// );

```

How to overcome?

**Comment by Kamill90** [comment]
it has been a while, but has anybody dealt with it?

**Comment by arthurschreiber** [comment]
There can only ever be one request active on a single connection. There's two solutions to the issue encountered with the code above: wait for the current request to finish before executing a new request (e.g via the callback passed to the Request constructor), or open multiple connections (e.g. Via the tedious connection pool library).

Both solutions have different advantages and disadvantages (and in some cases you might actually apply both together), but this is a solved problem.
