### ISSUE TITLE
Tedious headline should point to the updated GitHub Pages site

### ISSUE THREAD

**Issue by chuck-knox** [tediousjs/tedious#406]
Hey guys, it looks like you started migrating to an organization for Tedious. Good move! 

I wanted to point out that the headline for the Tedious repo needs to be updated to include a link to the new GitHub pages URL: http://tediousjs.github.io/tedious/

![tedious_outofdate](https://cloud.githubusercontent.com/assets/8022749/16779995/7ec37562-4829-11e6-8a56-c4912b38bfec.png)

This should be a super easy and quick fix for anyone that controls the repo.

**Comment by arthurschreiber** [comment]
Done and thanks for the report! ❤️

**Comment by chuck-knox** [comment]
You're welcome,  thanks for taking care of it so quickly!
