### ISSUE TITLE
request emits two undocumented events

### ISSUE THREAD

**Issue by akc42** [tediousjs/tedious#413]
Trying to find out how to know that a `connection.prepare(request)` had completed I have been looking at the request.callback code.

Firstly, when preparing a request the request callback is NOT called, but also 'prepared' event is emitted (at least when the preparation is succesfull).. I am not sure, but I think an error in the prepared statement (such as parameters not defined) does call the callback.  This seems a little wierd and is making handling of prepared statements a bit complicated.  Why is it set this way?

Secondly, just after the request callback is called the 'requestCompleted' event is emitted.

Neither of these two events are documented under request.

**Comment by v-suhame** [comment]
github.io is updated with the missing events.
