### ISSUE TITLE
No console output with minimal.js sample?

### ISSUE THREAD

**Issue by ScottBeeson** [tediousjs/tedious#418]
I copied the contents of https://github.com/tediousjs/tedious/blob/master/examples/minimal.js and changed the connection information.  At first I was getting console output that said "Failed to connect..." until I realized that the port has to be specified in the options object.  Now that I have the proper port, I'm not getting _any_ output.

I'm trying to access an Intersystems Cache.  Is this a compatibility issue or am I doing something wrong?

**Comment by IanChokS** [comment]
Hi @ScottBeeson,

Were you able to find what was wrong? Could you show what your config looks like? 

Since it's been a while, I'll assume you've figured it out, but if you still have issues connecting, feel free to re-open this issue!
