### ISSUE TITLE
Transaction Management

### ISSUE THREAD

**Issue by mehtaekta** [tediousjs/tedious#42]
Hey,

As per the readme v0.0.8 will support transaction. When will v0.0.8 be released?

**Comment by mikermcneil** [comment]
For others finding this issue in search engines, you might want to instead check out https://github.com/tediousjs/tedious/issues/412


@pekim @arthurschreiber Since this issue is kinda prominent in search, reckon it makes sense to lock it to prevent it being zombied further?
