### ISSUE TITLE
verifyError emits error code ESOCKET which node-mssql silently ignores

### ISSUE THREAD

**Issue by SimonHooker** [tediousjs/tedious#426]
Relating to issue #423 it turns out the actual issue is that if the error emitted is of type code === ESOCKET, node-mssql then mostly sidesteps it instead of reporting the issue.

As such will adapt the error code to be something different for verify errors.

**Comment by IanChokS** [comment]
@SimonHooker Sorry I'm having a hard time understanding what the issue is. If node-mssql is sidestepping an error emitted from Tedious, then perhaps it would be more appropriate to open an issue in node-mssql :)
