### ISSUE TITLE
DateTime Millisecond Precision not correct

### ISSUE THREAD

**Issue by frikkievb** [tediousjs/tedious#428]
I am trying to get a DATETIME (not DATETIME2) from a MSSQL database. We need this accuracy for our concurrency checks.

I wanted what was in the database. The value is =2016-08-02 12:42:11.087
But I am getting: 2016-08-02T12:42:11.086Z

**Comment by tvrprasad** [comment]
How did you verify what's in the database? Does SSMS give you the right answer on the query?
If you can share your code, I'd be curious to take a look.

**Comment by tvrprasad** [comment]
Fixed by https://github.com/tediousjs/tedious/pull/517
