### ISSUE TITLE
why does arrayToGuid use toUpperCase?

### ISSUE THREAD

**Issue by jdanyow** [tediousjs/tedious#429]
Code:  https://github.com/tediousjs/tedious/blob/master/src/guid-parser.js#L12-L35

Excerpt from [RFC 4122](https://tools.ietf.org/html/rfc4122#section-3) (emphasis mine):

>Declaration of syntactic structure:
  A UUID is an identifier that is unique across both space and time,
  with respect to the space of all UUIDs.  Since a UUID is a fixed
  size and contains a time field, it is possible for values to
  rollover (around A.D. 3400, depending on the specific algorithm
  used).  A UUID can be used for multiple purposes, from tagging
  objects with an extremely short lifetime, to reliably identifying
  very persistent objects across a network.
>
>  The internal representation of a UUID is a specific sequence of
  bits in memory, as described in Section 4.  To accurately
  represent a UUID as a URN, it is necessary to convert the bit
  sequence to a string representation.
>
>  Each field is treated as an integer and has its value printed as a
  zero-filled hexadecimal digit string with the most significant
  digit first.  **The hexadecimal values "a" through "f" are output as
  lower case characters** and are case insensitive on input.

An implementation without `toUpperCase` is approximately 400 times faster in my testing (chrome 51, windows 10, benchmark.js):  https://gist.run/?id=f3e57d94770c6e7f8d2f783e9ac67c6c .  I think we could fix the perf by improving the `formatHex` algorithm but that's a separate issue.

I'm guessing the `toUpperCase` call exists for a reason... would be great to know why. Changing the behavior would break many apps.  Maybe an option could be added to turn it off?

Looks like node-mssql copied the implementation:  https://github.com/patriksimek/node-mssql/blob/v3.3.0/src/tds.coffee#L103-L131

**Comment by jdanyow** [comment]
faster formatHex/arrayToGuid: https://gist.run/?id=d568ef501492644130ef3ba30a9d8274

**Comment by arthurschreiber** [comment]
I just merged a patch for this based on your suggestion! Many thanks! ❤️

**Comment by jdanyow** [comment]
@arthurschreiber nice! glad it was helpful.

Any chance this issue could be re-opened- still wondering why the Guids are uppercased.

If no one knows or there's no reason, it's totally fine, just wondering if there was a reason because I was hoping they'd be lowercased and the code deliberately uppercases them for some reason.
