### ISSUE TITLE
guidToArray performance tuning

### ISSUE THREAD

**Issue by jdanyow** [tediousjs/tedious#441]
@arthurschreiber this is the counterpart to https://github.com/tediousjs/tedious/pull/440

https://gist.run/?id=72ba5c3588d6375fee052fc8358a4606

I can send a PR if it looks good.

**Comment by arthurschreiber** [comment]
These numbers look great! If you can create a PR for this, I'd be happy to merge it! Thanks! :heart:

**Comment by jdanyow** [comment]
cool- will do
