### ISSUE TITLE
Is this repository really maintained?

### ISSUE THREAD

**Issue by sant123** [tediousjs/tedious#446]
Hi, I've done a pull request some time ago and I have not received any answer from it.... The pull request is here:

https://github.com/tediousjs/tedious/pull/403

**Comment by arthurschreiber** [comment]
Tedious is still maintained.

At my previous company we used tedious extensively as a core component of the application that we built, and I was allowed to spend time maintaining it. I was able to add a lot of useful functionality like transactions and fix some other bugs and performance bottlenecks.

I moved to another company, where I don't use tedious nor do any Node.js development at all, so maintenance of tedious itself now only happens in my free time, and I'm afraid I had a lot less of that than needed for tedious.

Recently, @tvrprasad and @SaloniSonpal have shown interest to become more active in the development of tedious, but things like that don't happen over night and need some ramp up time (again limited by much time I can afford to spend).

I'm sorry I've not replied earlier to your PR. I'll be taking a look now.

Thanks!

**Comment by sant123** [comment]
I really appreciate ur answer @arthurschreiber, for a moment a thought I should research for another library, but Tedious is the most stable I know. Now that I know the story, I'll be more patient in order to make PR. :smile: 

Thank you!!!
