### ISSUE TITLE
Internationalized Domain Names for server names

### ISSUE THREAD

**Issue by SaloniSonpal** [tediousjs/tedious#448]
How do I leverage internationalization and localization features for SQL Server? Can you please point me as to how I can handle international domain names? Can someone please help me with documentation pointers if this is supported?

**Comment by arthurschreiber** [comment]
> How do I leverage internationalization and localization features for SQL Server?

Can you be a bit more specific on what these features are?

> Can you please point me as to how I can handle international domain names?

I've not tried this, but the way it's implemented right now depends on whether the Node.js core components handle international domain names automatically or not (and I believe they do not).

For users, the simplest "fix" would be to specify the punycode variant of their server domain name in the configuration they pass to tedious.

> Can someone please help me with documentation pointers if this is supported?

As mentioned below, I don't think this is supported out of the box, but if a user specifies the punycode version of their domain name, it should just work ™.

**Comment by SaloniSonpal** [comment]
Agree @arthurschreiber. Most software written for non-Windows platforms follows the Internet DSN standards and most likely uses the Punycode format for IDNs, while a Windows-based DNS Server on a private network can be configured to allow the use of UTF-8 characters. It'll be good to convert a Unicode serverName to ASCII compatible encoding (Punycode) when required during a connection.

Some more about Collation and Unicode Support[](https://msdn.microsoft.com/en-us/library/ms143726.aspx) and Windows Collation Names[](https://msdn.microsoft.com/en-us/library/ms188046.aspx) on MSDN.

**Comment by arthurschreiber** [comment]
That's okay. We can use the punycode library to do this automatically when doing the dns lookup. 👍🏻

**Comment by v-suhame** [comment]
Servers with IDN works as it is with tedious 😄 `dns.lookup` already takes care of it.

**Comment by v-suhame** [comment]
IDN support added in #705.
