### ISSUE TITLE
Redirection logic not implemented

### ISSUE THREAD

**Issue by SaloniSonpal** [tediousjs/tedious#449]
This doc https://blogs.msdn.microsoft.com/sqlcat/2016/09/08/connect-to-azure-sql-database-v12-via-redirection/ specifically calls out that Tedious for Node.js does not implement redirection. @arthurschreiber, @pekim, @ben-page, other committers and active members - is this something that should be looked into?

Scanning through the code I do see some re-routing/ redirection logic in connection.js.

**Comment by arthurschreiber** [comment]
I believe this is supported, and support for this was added quite a while ago! (I think for v1.8.0).

I have not tested this feature specifically - @SaloniSonpal @tvrprasad can you verify whether this works as supposed on the Azure Platform?

**Comment by arthurschreiber** [comment]
@SaloniSonpal @tvrprasad ping?

**Comment by tvrprasad** [comment]
I'll take a look at this and let you know.

**Comment by tvrprasad** [comment]
@arthurschreiber You're right. Redirection works as it's supposed to. Here is what I did to verify:

- Created a Azure Windows VM and Azure SQL DB.
- Added some logging to tedious and ran a simple query from the VM.
- I see the following:
  1. Create Socket.
  2. Routing Change.
  3. Destroy Socket.
  4. Create Socket.
  5. Logged In.
  6. Destroy Socket.

From a non-Azure Windows VM where Redirection does not take effect, I see:
1. Create Socket.
2. Logged In.
3. Destroy Socket.
