### ISSUE TITLE
Add support for Extended Events Log

### ISSUE THREAD

**Issue by SaloniSonpal** [tediousjs/tedious#451]
To be able to access diagnostic information in the server's extended events log will be really helpful to trace driver operations and understand connection failures. Thank you!

**Comment by arthurschreiber** [comment]
I'm not exactly sure what you are referring to, and I could not find "Extended Events Log" specified anywhere in the latest `MS-TDS` specification. Could you provide a bit more context for this?

**Comment by IanChokS** [comment]
You can access debugging information via connection events: 

```js
connection.on('debug', cb);
connection.on('infoMessage', cb);
```

[Refer to documentation under Connection](https://tediousjs.github.io/tedious/api-connection.html#event_infoMessage)
