### ISSUE TITLE
Potential bug when encoding password

### ISSUE THREAD

**Issue by SteveShe** [tediousjs/tedious#453]
I was having trouble logging into my Azure DB and I think I have tracked it down to the password being misinterpreted by Tedious. I use a password generator for my passwords and they contain special characters, all of which are support by Azure SQL. I have found that when I login using Tedious with this password configuration the login fails:

```
var config = {
    server  : "server001.database.windows.net",
    userName: "admin",
    password: "\3sYAU{YH88u4i^",
    /* password: "Password00", this one works fine. */
    options: { 
        encrypt: true, 
        database: 'database001',
    }
};
```

Even when I encode the backslash character () by doubling it up `password: "\\3sYAU{YH88u4i^"` it still doesn't seem to encode correctly. However, if I remove the backslash character altogether it works just fine. 

I traced it into this code in the login7-payload.js function:

```
key: 'createPasswordBuffer',
    value: function createPasswordBuffer() {
        var password = this.loginData.password || '';
        password = new Buffer(password, 'ucs2');
        for (var b = 0, len = password.length; b < len; b++) {
        var byte = password[b];
        var lowNibble = byte & 0x0f;
        var highNibble = byte >> 4;
        byte = lowNibble << 4 | highNibble;
        byte = byte ^ 0xa5;
       password[b] = byte;
  }
 return password;
}
```

At the beginning the password variable seems to be correct as long as I have escaped the backslash in my password declaration, `password: "\\3sYAU{YH88u4i^"`, but I still can't login. I don;t know enough about big/little endian encoding to know if the code above is working correctly with the backslash regardless of whether i escape it or not. 

My workaround is to avoid the backslash in my password strings for now, but it feels like this is a bug.

**Comment by cshettar** [comment]
Not only for backslash. Log in does not work for passwords with other special characters such as % and # as well. This is indeed a bug and needs to be solved or atleast mentioned in the documentation.

**Comment by arthurschreiber** [comment]
@cshettar Thanks for confirming the issue!

@tvrprasad Is this something you could look into?

**Comment by tvrprasad** [comment]
I'll take a look at this.

**Comment by tvrprasad** [comment]
@SteveShe This is odd. I tried the exact password you got, "\\3sYAU{YH88u4i^", and it worked fine for me!
@cshettar I tried a password with all special characters !@#$%^&*()\1Aa (with escaping in JS it'll be "!@#$%^&*()\\1Aa" and that worked too.

Can you try with the current bits of Tedious and latest version of node?

**Comment by tvrprasad** [comment]
Closing the issue as everything seems to work as expected. Re-open if you still notice problems.
