### ISSUE TITLE
Add tests, documentation and sample for nanosecondDelta

### ISSUE THREAD

**Issue by tvrprasad** [tediousjs/tedious#454]
Tedious allows for 'nanosecondDelta' to be the specified on 'value' of type 'Date' passed in to Request.addParameter() method. This is not currently tested or documented.

**Comment by LuisBosquez** [comment]
@arthurschreiber hello! I am a Program Manager in Microsoft now working with @tvrprasad to contribute to tediousjs. I wanted to start helping right away with some of the docs issues. Is there a public GitHub repository for the documentation where I can submit PRs to?

**Comment by IanChokS** [comment]
Fix in #600
