### ISSUE TITLE
Tedious releases

### ISSUE THREAD

**Issue by tvrprasad** [tediousjs/tedious#455]
@arthurschreiber @pekim  I see on https://www.npmjs.com/package/tedious that last release for Tedious was 6 months back. Any thoughts on if we should do a new release?

**Comment by tvrprasad** [comment]
@patriksimek @bretcope 
For more thoughts.

**Comment by arthurschreiber** [comment]
Let's plan for a release soon. There is still the issue highlighted by https://github.com/tediousjs/tedious/pull/420, where connecting to SQLServer using older versions of the TDS protocol is basically completely broken (this mainly affects people trying to use tedious with older SQL Server versions).

**Comment by tvrprasad** [comment]
I looked into #420 a bit. I'll update the issue with findings and we can discuss how to move forward there. I'll try and squeeze in some time to spend on the issue.

**Comment by tvrprasad** [comment]
We should also close https://github.com/tediousjs/tedious/pull/362 for the release. Hopefully we're pretty close on that one.

**Comment by tvrprasad** [comment]
> Let's plan for a release soon. There is still the issue highlighted by #420,

We're now closed on #420.

> We should also close #362 (Multi Subnet Failover) for the release. Hopefully we're pretty close on that one.

I have a PR out https://github.com/tediousjs/tedious/pull/444 waiting to help close #362.

You think we can close #362 (Multi Subnet Failover) and do a release?

**Comment by arthurschreiber** [comment]
I've opened #477 for the upcoming 1.15.0 release. I'll close this now!
