### ISSUE TITLE
Connection issue connecting to sql server

### ISSUE THREAD

**Issue by venkatavijay** [tediousjs/tedious#457]
Hi all,

I am facing below connectivity issue when connecting to my sql instance.
Any pointers highly appreciated!

app.get('/getpackages', function (req, res) {
    var retval;
    var conn = new TDS.Connection({
        domain: 'mydomain', userName: 'username', password: 'password', server: 'server.mydomain.com',
        options: { database: 'test', requestTimeout: 0, connectTimeout: 30000, rowCollectionOnRequestCompletion: true },
        debug: { log: true }
    });
    function debug(message) {  
        console.log('debug=> ' + message);
    }
    conn.on('debug', debug);
    conn.on('connect', function (err) {
        if (err) {
            console.log('Error');
            conn.close();
        } else {
            // If no error, then good to go...
            let request = new TDS.Request("select \* from employee", function (err, rowCount, rows) {
                if (err) {
                    console.log('Error');
                    conn.close();
                } else {
                    conn.close();
                    //res.contentType('application/json');
                    retval = JSON.stringify(rows);
                    res.jsonp(retval);
                }

```
        });

        conn.execSql(request);
    }
});
```

});

debug=> connected to server.mydomain.com:1433
debug=> State change: Connecting -> SentPrelogin
debug=> State change: SentPrelogin -> SentLogin7WithNTLMLogin
debug=> State change: SentLogin7WithNTLMLogin -> SentNTLMResponse
Error
debug=> State change: SentNTLMResponse -> Final
debug=> connection to server.mydomain.com:1433 closed
debug=> State is already Final

**Comment by tvrprasad** [comment]
@venkatavijay I'm able to repro your error when I specify 'domain' in config and my 'username'/'password' are Database users. I suspect that's what's happening in your case.

Specifying 'domain' triggers NTLM code path and I suspect your user is a Database user. Remove 'domain' setting from your connection config and see if that fixes the issue.

Couple of other things:
1) In your 'connect' listener, print the 'err' passed in, it'll give you useful debug information.
2) Please use ```JavaScript block around your the script code in your post. Makes it easier to read.

**Comment by tvrprasad** [comment]
Closing the issue as there is nothing here to fix in Tedious. Please re-open if there is still an issue.
