### ISSUE TITLE
Socket is not a constructor

### ISSUE THREAD

**Issue by Nokel81** [tediousjs/tedious#462]
Hello, I am trying to connect to a SQL database on the same network as I but when I try and create a connection object I get a `Socket is not a constructor: TypeError` error.

This is practically my code:

```
var Connection = require('tedious').Connection;
var dbConfig = require("./dbConfig.json");

module.exports = function ($scope, $location, SQLService, AlertService) {
    $scope.Submit = function () {
        var connection = new Connection(dbConfig);
    };
};
```

I get the error on the `new Connection` line and my config looks something like this, the values have been changed.

```
{
    "userName": "nokel81",
    "password": "nl4vsc54ykpPurt",
    "server": "10.10.6.6",
    "options": {
        "port": 52581,
        "database": "E1Q_API",
        "instancename": "sql2k12"
    }
}
```

Version of Tedious: 1.14.0

**Comment by Nokel81** [comment]
Some more information, this connection is being made in an Angular 1 Controller. I do not get that error when in a test file.

**Comment by arthurschreiber** [comment]
> Some more information, this connection is being made in an Angular 1 Controller. I do not get that error when in a test file.

Are you trying to connect from a browser to your SQL Server? I don't think that will work. Tedious is written for Node.JS.

**Comment by Nokel81** [comment]
Ok, thanks. I will then create a backend services using node for the connections to the SQL server.

**Comment by arthurschreiber** [comment]
> Ok, thanks. I will then create a backend services using node for the connections to the SQL server.

👍 Cool! Let us know if you run into any other issues with tedious.
