### ISSUE TITLE
Bad link on npm

### ISSUE THREAD

**Issue by zeg-io** [tediousjs/tedious#468]
The link to the changelog is broken on npm page.

The current (broken) one is: `http://pekim.github.io/tedious/changelog.html`

This one works: `http://tediousjs.github.io/tedious/changelog.html`

**Comment by tvrprasad** [comment]
This has been fixed -https://github.com/tediousjs/tedious/commit/50c8001ad3fb98bf052a39248215cb649cc2b6fc

This'll show up when we do the next release.
