### ISSUE TITLE
No event 'data' in state 'Final'

### ISSUE THREAD

**Issue by mcrummey** [tediousjs/tedious#470]
I get this error intermittently when running.  I am using tedious-connection-pool if that matters.  (If I release on process.nextTick() I get memory leak errors on the event emitter.)

Here is my code.  Attached it the stacktrace

```js
runStoredProc = function (storedprocedure, parameters) {
	return new Promise((resolve, reject) => {
		const results = [];
		pool.acquire((err, mscon) => {
			if (err) {
				logger.error(err);
			} else {
				const request = new Request(storedprocedure, function (err) {
					if (err) {
						logger.error("Request Error" + err);
						reject(err);
					}
				});
				_.each(parameters, function (value, key) {
					request.addParameter(key, value[1], value[0]);
				});
				request.on("doneInProc", function (rowCount, more, rows) {
					results.push(rows);
				});
				request.on("doneProc", function (rowCount, more, returnStatus, rows) {
					resolve({
						returnStatus: returnStatus,
						rows: results
					});
					// process.nextTick(mscon.release.bind(mscon));
					mscon.release();
				});
				mscon.callProcedure(request);
			}
		});
	});
}
```

error: Connection Pool error: Error: No event 'data' in state 'Final'
error:    Server Error {"message":"No event 'data' in state 'Final'","stack":"Error: No event 'data' in state 'Final'\n    at Connection.dispatchEvent

Full stack trace.
[tediousStackTrace.txt](https://github.com/tediousjs/tedious/files/549043/tediousStackTrace.txt)

**Comment by mcrummey** [comment]
#260 Similar error but different event.

**Comment by arthurschreiber** [comment]
I checked your example and it looks like you are releasing the connection while it's still in use. If you move `mscon.release();` to the end of the callback passed to `new Request`, this issue should get fixed.

Closing a connection while still in use causes undefined behaviour in tedious right now, we might fix this in the future (cc @tvrprasad).

**Comment by mcrummey** [comment]
That was the issue.  Thanks for your help.
