### ISSUE TITLE
Generate documentation using `documentation.js`

### ISSUE THREAD

**Issue by arthurschreiber** [tediousjs/tedious#471]
Currently, documentation for tedious is maintained in a seperate `gh-pages` (see https://github.com/tediousjs/tedious/tree/gh-pages) branch.

This makes maintenance of the documentation a lot more complex than it should be. Documentation often becomes outdated because we need to ask contributors to open a second PR to add documentation for any feature they propose. Also, it causes a lot of drift in the docs, as sometimes documentation updates are simply forgotten when the corresponding code gets changed.

I propose to move all documentation to live next to the source code, and generate a documentation website based on that.

I'd suggest to use `documentation.js` (http://documentation.js.org/).

@tvrprasad @SaloniSonpal What do you think?

**Comment by IanChokS** [comment]
We've moved to use TypeDocs
