### ISSUE TITLE
Release 1.15.0

### ISSUE THREAD

**Issue by arthurschreiber** [tediousjs/tedious#477]
I plan to release the next version of `tedious`, `1.15.0` "Alive and Kicking" soon.

Here's the changelog so far:

---

### What's New

* #362 `tedious` now has better support for SQLServer instances configured for High Availability! If the DNS name for the SQLServer instance you're connecting to resolves to multiple IP addresses, `tedious` will now sequentially try to connect to each of them, and will stop after the first successful connection. There's now also support for the `multiSubnetFailover` connection option, which allows to connect to all resolved IP addresses in parallel and will use whichever connection was established first. Thanks @chrislukkk!

* #419 When establishing an encrypted connection to a server, `tedious` never actually verified the certificate presented by the server. As this is probably not a good idea from a security standpoint, there is a new `trustServerCertificate` connection option that you can set to `false` to enforce certificate verification. The default behaviour did not change, but will in a future release. Thanks @SimonHooker!

### Fixed

* #461 We accidentally broke support for TDS 7.1 (used by SQLServer 2000) a few versions ago. If you're still running software from the year 2000, rejoice - TDS 7.1 support is back! Thanks @tvrprasad!

* #367 Encrypted connections and NTLM authentication didn't work together, at all - but now they do! Thanks @leerlemoniii and @mcrummey!

* #417 When authenticating via NTLM, the domain name was sent to the server as provided in the connection options. As it turns out, NTLM prefers domain names to be specified in upper case, so that's what we're doing now. Thanks @tvrprasad!

* #440 #443 Parsing and writing the contents of GUID columns was pretty slow. Now it's many times faster! Thanks @jdanyow!

* #445 The configuration object that was passed to the `Connection` constructor was modified in multiple places. That was pretty careless and unexpected, so `tedious` now will keep an internal copy of the configuration. Thanks @tvrprasad!

---

Did I miss anything important?

/cc @tvrprasad @SaloniSonpal @patriksimek

**Comment by patriksimek** [comment]
Great contributions! Thanks for all your efforts.

**Comment by tvrprasad** [comment]
This is great @arthurschreiber!
> Did I miss anything important?

Can we merge the unit tests for Multi Subnet Failover Feature (#362)
https://github.com/tediousjs/tedious/pull/444

**Comment by jjg1914** [comment]
@arthurschreiber Is there any ETA on this being released? Would love to have the multiSubnetFailover feature!

**Comment by arthurschreiber** [comment]
> @arthurschreiber Is there any ETA on this being released? Would love to have the multiSubnetFailover feature!

There is one last thing missing before we can push out a release, and that's compatibility between `multiSubnetFailover` and connecting via a instance lookup (https://github.com/tediousjs/tedious/blob/master/src/instance-lookup.js).

Once that is resolved, I#ll push the new tedious release ASAP.

**Comment by jjg1914** [comment]
@arthurschreiber Just want to check up on this again, real excited for this feature!

Is there anything I could do to help move this along?

**Comment by carlosman** [comment]
@arthurschreiber Please, consider reviewing #501 for this release. It is simple. It works and should be an available option.

**Comment by tvrprasad** [comment]
@jjg1914 PR is in code review - https://github.com/tediousjs/tedious/pull/502. Any time now :-)

**Comment by ariskemper** [comment]
Any progress on new release ?
