### ISSUE TITLE
Closing connection while still in use causes undefined behavior

### ISSUE THREAD

**Issue by tvrprasad** [tediousjs/tedious#482]
@arthurschreiber You mentioned this in https://github.com/tediousjs/tedious/issues/470#issuecomment-255947375. Do you have a fix in mind? I can take a crack at it some time.

**Comment by arthurschreiber** [comment]
I think closing a connection with open requests should pass down some sort of error down the request's callback, so that user-defined code can take the appropriate steps of handling it.

**Comment by tvrprasad** [comment]
@arthurschreiber Sent PR to address this - https://github.com/tediousjs/tedious/pull/505
