### ISSUE TITLE
Windows authentication recognized as SQL auth by sql server

### ISSUE THREAD

**Issue by MrJoeXu** [tediousjs/tedious#484]
I am trying to get windows auth working on SQL Server 2008 with Tedious, Here is config:
```
var config = {
userName: "username",
password: "password",
server: "server",
domain: "domain",
options: {
database: "db"
}
};
```

But all I get is the "Unable to login in for user " error. I checked the error log of SQL server and getting this:
```
Login failed for user ***. Reason: An attempt to login using SQL authentication failed. Server is configured for Windows authentication only.
```

I only want to authentication through windows instead of sql server so I did not turn on the mix mode for authentication in SQL Server. Why is sql server recognized my login attempt as SQL authentication instead of Windows authentication?

Thanks!

**Comment by tvrprasad** [comment]
I copied pasted your config and tweaked values and I'm able to connect using my windows account.
Can you share what the complete error output you're getting on the client?

Also, check if the version of Tedious you're using is very old. You would get this behavior if your version of Tedious does not have support for NTLM. You can check that by seeing if you have the file ntlm-payload.js in your Tedious installation.

If none of the above works, try enabling debug output and see if that gives you pointers. You can turn on debugging in your options and then listen to the 'debug' event as below:

```JavaScript
var config = {
  userName: "username",
  password: "password",
  server: "server",
  domain: "domain",
  options: {
    database: "db",
    debug: { data: true, payload: true, packet: true, token: true }
  }
};

connection.on('debug', function (message) {
  console.log(message);
});
```

**Comment by MrJoeXu** [comment]
I turned on the debug node and found out the problem is from my SQL server settings. I changed my port number of server and it connected now. 
THANKS!!!

**Comment by tvrprasad** [comment]
That's great :-)
