### ISSUE TITLE
Returns null for empty aggregate

### ISSUE THREAD

**Issue by max-vogler** [tediousjs/tedious#492]
When executing the aggregate function `COUNT` in a query that would return no rows (because of a `WHERE` block without matching rows), the returned value is `null` instead of an expected `0`.

Example query:
```sql
SELECT SUM(column1) FROM Table WHERE column2 = 'nonexistent'
```

Response:
```js
[ { '':
   { value: null,
     metadata:
      { userType: 0,
        flags: 1,
        type: [Object],
        colName: '',
        collation: undefined,
        precision: undefined,
        scale: undefined,
        udtInfo: undefined,
        dataLength: 4,
        tableName: undefined } } } ]
```

Expected response:
```js
[ { '':
   { value: 0,
// ...
```

Using tedious 1.14.0 and SQL Server V12 on Azure.

**Comment by tvrprasad** [comment]
I get NULL in SSMS also, that's the expected behavior. If you change SUM to COUNT, you'll get 0.
