### ISSUE TITLE
Connecting to remote Sql Server with backslash in password

### ISSUE THREAD

**Issue by geskill** [tediousjs/tedious#499]
The password of the remote Sql Server contains a backslash. However, to connect with tedious i had to type every backslash twice (escape the backslash).

i.e. password: `test\123` must be `test\\123` in order to connect

using tedious 1.14.0

**Comment by arthurschreiber** [comment]
Backslashes in JavaScript strings need to be escaped, I don't think this is specific to tedious in any way. Maybe I'm misunderstanding your issue?

**Comment by geskill** [comment]
you're correct, sorry

**Comment by arthurschreiber** [comment]
No worries! 👍
