### ISSUE TITLE
Dateformat mdy is forced on connection.

### ISSUE THREAD

**Issue by ariskemper** [tediousjs/tedious#507]
Dateformat mdy is forced on connection, which introduces errors like:

RequestError: The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.

if there is different dateformat setled for login user. I recommend dateFormat config option.

**Comment by sebwe** [comment]
This config option is a **must have** for users from other countries. 
Right now every Data or DataType parameter throws conversion errors. 

Is there any workaround to set connection dateformat before executing a procedure?
