### ISSUE TITLE
Change default value for 'arithabort' to ON in v2.0

### ISSUE THREAD

**Issue by tvrprasad** [tediousjs/tedious#509]
Based on the recommendation on MSDN page, perhaps we should change the default value for 'arithabort' to 'on' for 2.0 release. It'll be a breaking change. From the MSDN link https://msdn.microsoft.com/en-us/library/ms190306.aspx:
"
The default ARITHABORT setting for SQL Server Management Studio is ON. Client applications setting ARITHABORT to OFF can receive different query plans making it difficult to troubleshoot poorly performing queries. That is, the same query can execute fast in management studio but slow in the application. When troubleshooting queries with Management Studio always match the client ARITHABORT setting.
"

**Comment by ariskemper** [comment]
#508 I think this don't need to be setled to ON for production environments?. If you want to troubleshoot you could turn it on via options.

**Comment by tvrprasad** [comment]
From the MSDN page https://msdn.microsoft.com/en-us/library/ms190306.aspx:
"You should always set ARITHABORT to ON in your logon sessions. Setting ARITHABORT to OFF can negatively impact query optimization leading to performance issues."

Seems like ON gives better performance. Is there a downside to making it the default? The client can turn it off via options with your PR.

**Comment by ariskemper** [comment]
@tvrprasad i havent read that paper before, i was in doubt because is breaking change, now i agree with you that we could make this default ON.

**Comment by arthurschreiber** [comment]
https://github.com/tediousjs/tedious/pull/1025 adds a deprecation message when opening a new `Connection` without specifying an explicit value for `enableArithAbort`. The next major version will then switch from the default being `false` to the default being `true`.
