### ISSUE TITLE
No error emitted on failed connection

### ISSUE THREAD

**Issue by MatthewPhinney** [tediousjs/tedious#513]
If a SQL Server database is configured to use encrypted connections, the client must specify `encrypt: true` in the tedious connection config. If the client does not specify `encrypt: true`, the connection to the database fails, but the connection object does not emit an error event. 
The connection should emit an error, so the client can handle it appropriately.

Here is sample output from a connection attempt:
```
Debug event:  connected to <db-using-encrypted-connections>
Debug event:  State change: Connecting -> SentPrelogin
Debug event:  State change: SentPrelogin -> SentTLSSSLNegotiation
Debug event:  socket ended
Debug event:  State change: SentTLSSSLNegotiation -> Final
End event:    undefined
Debug event:  State is already Final
Debug event:  socket ended
Debug event:  connection to <db-using-encrypted-connections> closed
```

Incidentally, [TLS.createSecurePair](https://github.com/tediousjs/tedious/blob/65e0b2017be616fb8bcb16ed6b0185534a3c1c3b/src/message-io.js#L91) is [deprecated](https://nodejs.org/api/tls.html#tls_tls_createsecurepair_context_isserver_requestcert_rejectunauthorized_options). Is there any plan to update this code?

**Comment by tvrprasad** [comment]
Thanks for reporting.
Sent pull request to address this: https://github.com/tediousjs/tedious/pull/514

**Comment by tvrprasad** [comment]
About the deprecated createSecurePair, there is a open issue for that - https://github.com/tediousjs/tedious/issues/135. Need someone inspired to take it on :-)

**Comment by MatthewPhinney** [comment]
Thanks for the quick response -- please let me know when a new version (including the changes in #514) is published on npm.

**Comment by tvrprasad** [comment]
Stay tuned :-)

**Comment by tvrprasad** [comment]
The PR is merged. Closing the issue.
