### ISSUE TITLE
Unable to use tedious with Azure database.

### ISSUE THREAD

**Issue by gauravgupta0305** [tediousjs/tedious#516]
I've a node application which do have a connection to SQL Server.
Also, I'm using database as a service from Azure.

Code Snippet : 
----------------------------------------------------------------------------------
import { Connection } from 'tedious'; 
import { Request } from 'tedious';

var config = {
    userName: 'dbuser',
    password: 'dbpassword',
    server: 'mydatabase.database.windows.net',
    options: {
        instanceName: 'SQLEXPRESS', // Removed this line while deploying it on server as it has no instance.
        database: 'dbname'
    }
}; 
connection = new Connection(config);  
connection.on('connect', function(err) {
    if (err) {
        console.log('error : '+err);
    } else {
        console.log("Connected to Database");
    }
}); 
--------------------------------------------------------------------------------------------

It has a successful connection, if done, locally. 
Console Output => Connected to Database.

------------------------------------------------------------------------------------------

Deep dive done using console log : 
-> Connection object is being created, but, the event ".on" is not being able to establish.
-> The connection gets established when deployed locally, while, when deployed on server, it doesn't works.

**Comment by tvrprasad** [comment]
This looks like IIS configuration and/or application level issue. You may have better luck with the question on stackoverflow.com.

**Comment by gauravgupta0305** [comment]
Answered at this link :  http://stackoverflow.com/questions/42505548/unable-to-use-tedious-with-azure-database

**Comment by tvrprasad** [comment]
Oh cool. Didn't notice you didn't have encrypt: true which is required for connection to Azure SQL DB.
