### ISSUE TITLE
Implement options.cancelTimeout

### ISSUE THREAD

**Issue by chdh** [tediousjs/tedious#519]
Options.cancelTimeout is documented in the API docs but has no effect and no test case.
(Or if the cancelTimeout option is not needed, it should be removed from the documentation)

**Comment by arthurschreiber** [comment]
I think this option is supposed to allow specifying the maximum amount of time that we will wait for the server to send an acknowledgement of an attention package before forcefully terminating the connection.

**Comment by tvrprasad** [comment]
https://github.com/tediousjs/tedious/pull/566, in progress, addresses this.
