### ISSUE TITLE
Upgrade SQL version for integration tests

### ISSUE THREAD

**Issue by tvrprasad** [tediousjs/tedious#524]
Had to disable two tests (dateTimePrecision_9_day_flip and outputDatePrecision_9_day_flip) in PR https://github.com/tediousjs/tedious/pull/521/files due to what seems like a corner case bug in the version of SQL Server running on AppVeyor.

@arthurschreiber How do we upgrade the SQL Server version for the integration tests?

**Comment by arthurschreiber** [comment]
This is part of the AppVeyor setup - installing new SQL Server versions on every build is really not feasible. But we could ask them nicely if they could just upgrade their images to contain the latest SQL Server patches.

**Comment by tvrprasad** [comment]
Would you be sending them mail? Let me know if there is something I can help with.

**Comment by Hadis-Fard** [comment]
related to #762
