### ISSUE TITLE
Integration tests should run against Azure SQL DB also

### ISSUE THREAD

**Issue by tvrprasad** [tediousjs/tedious#525]
Currently integration tests only run against local DB. We should have the tests running against Azure SQL DB also as some of the code paths are different and currently not exercised by the current tests.

@arthurschreiber Appreciate any thoughts. I'm happy to help with setting this up.

**Comment by arthurschreiber** [comment]
@tvrprasad I remember that Meet send me the credentials for quite a large SQL Server instance running inside Azure - but I cant find them. Is he still working at Microsoft? Can we get a new instance?

**Comment by tvrprasad** [comment]
Yes, @meet-Bhagdev still works here. Let's see if he'll responsd :-)
Also, @LuisBosquez will have more time to help with Tedious stuff going forward. Keeping him in the loop.

**Comment by v-suhame** [comment]
@meet-bhagdev Bumping up the issue.

**Comment by meet-bhagdev** [comment]
@arthurschreiber so sorry for dropping the ball on this thread. 
@v-suhame I still have the sub

Can you and @arthurschreiber share your Azure/live email id's? I will add you as admins on the Azure subscription. Then you can login and create Azure resources as you like

**Comment by v-suhame** [comment]
@arthurschreiber I'm setting up an Azure VM and AAD domain in the Azure subscription for Tedious. We can use it for ad-hoc testing now, and later extended it to run CI. 

It should be ideal for testing NTLM, windows int, Kerberos and AAD auth. I've started with the setup, and hope it will help in testing #624 :) We can add you to the subscription if you share your Azure id.

**Comment by v-suhame** [comment]
Done in https://github.com/tediousjs/tedious/pull/754.
