### ISSUE TITLE
Docker image with tedious and nodejs

### ISSUE THREAD

**Issue by LuisBosquez** [tediousjs/tedious#526]
I created a Docker image that implements tedious in an ubuntu layer with the Node.js runtime: https://hub.docker.com/r/lbosqmsft/mssql-nodejs-tedious/ 

I would like to know if this is helpful, as we're trying to publish it to the official Microsoft. Is there any feedback on this? 

The Dockerfile can be found here: https://github.com/Microsoft/mssql-docker/tree/master/oss-drivers/tedious

**Comment by arthurschreiber** [comment]
I think this looks good - but I'm not so sure how useful this is. How do you envision people are going to use this?

**Comment by LuisBosquez** [comment]
@arthurschreiber It's used to easily run Node.js app containers with the connectors prepackaged and configured in the environment. This would be a quick example of creating an app Docker image with your Node.js code:

```
FROM lbosqmsft/mssql-nodejs-tedious
ADD myCode /app
CMD node app.js
``` 

After that, you can build an image from this template with:
```
docker build .
```
This will return an image ID.

Assuming that app.js uses `tedious` and that there's a database instance ready for it to connect to, you can run an instance of the application by running:

```
docker run <Image ID> 
```

One of the advantages of Docker is that you can create multiple instances of the application by running the command multiple times.

**Comment by IanChokS** [comment]
This sounds like a great idea! 👍
