### ISSUE TITLE
Add 'cancel' function on Request class

### ISSUE THREAD

**Issue by tvrprasad** [tediousjs/tedious#534]
Currently 'cancel' is on Connection. This works fine since we only have a single Request per connection right now. It belongs on Request class logically though as it's the Request that's being cancelled.

We should mark the cancel function on Connection class deprecated so we can remove it in a later release.

**Comment by chdh** [comment]
Some additional info to justify this:

-  In the upper level driver node-mssql, the [cancel()](https://github.com/patriksimek/node-mssql#cancel) method is a member of the Request class.
-  In the .NET API, the [Cancel()](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlcommand.cancel.aspx) method ist a member of the SqlCommand class.

**Comment by arthurschreiber** [comment]
Yeah, this definately feels like it should be on the Request and not the Connection, long term.

We can deprecate this somewhere in the 2.x releases and drop it in 3.0.

**Comment by arthurschreiber** [comment]
This will be added via https://github.com/tediousjs/tedious/pull/846. 😬
