### ISSUE TITLE
Are there any places we use SHA-1 for crypto?

### ISSUE THREAD

**Issue by tvrprasad** [tediousjs/tedious#544]
@arthurschreiber @chdh I see some news flying around SHA-1 being broken - https://shattered.io/. The only crypto operation I see in the code is tls.createSecureContext() and the documentation does not mention SHA-1 in that context. Just sharing to ask if there is any vulnerability in Tedious that we need to fix. Thanks!

**Comment by ariskemper** [comment]
Crypto is used for NTLM in ntlm-payload.js. There are 2 hashes used MD4 and MD5. NTLM doesn't support cryptographic methods like AES or SHA-256. NTLM has many security issues. In tedious crypto is used to generate random name with Crypto randomBytes method, message-io and ntlm.   tls.createSecureContext() doesn't have anything to do with cryptographic has SHA-1 and its used to create secure context.

**Comment by arthurschreiber** [comment]
@tvrprasad To your original question -  `tedious` does not use SHA-1 anywhere, really.

@ariskemper You're right, NTLM is pretty weak, but there is nothing we can do about it - strenghtening security is on the operators of the SQL Server instance a user might want to connect to, and if the only supported authentication mechanism is NTLM, there's nothing we can do in tedious to help in that situation.

We're working on providing kerberos support, but the SQL Server instance will also have to be set up with kerberos support to make any use of that.
