### ISSUE TITLE
Add request.hasNext()

### ISSUE THREAD

**Issue by ManhQLe** [tediousjs/tedious#549]
Hi,
Is there a similar function where I can manually control the loop through all records in my code like the one they did in mongodb?

**Comment by tvrprasad** [comment]
If you set:
config.options.rowCollectionOnRequestCompletion = true

you'll get rowCount, rows as parameters to the user callback passed to Request constructor, like below:

new Request('select 1 as a; select 2 as b;',  function(err, rowCount, rows) {
  // Loop over rows here.
});

This is not particularly memory efficient, especially if your query returns a lot of rows.
