### ISSUE TITLE
Connect fails for subdivided server spec

### ISSUE THREAD

**Issue by ChrisMiami** [tediousjs/tedious#561]
I don't know what this is, exactly, but the server spec I have to work with is as follows:

`devsql.mycom.com\LATINBIN`

Using `/usr/local/bin/mssql`, I am able to connect using that spec.  Both parts of the spec above are required - the server is only listening on the full spec, not on the host itself.  Within Node, tedious doesn't seem to be able to separate the hostname from the subdirectory (I added the host to my hosts file to make mssql work because the resolution seemed to happen in 2 stages).  The error I get from node/tedious is fairly generic:

```
{ [ConnectionError: Failed to connect to devsql.mycom.com\LATINBIN:1433 - getaddrinfo ENOTFOUND devsql.mycom.com\LATINBIN]
  message: 'Failed to connect to devsql.mycom.com\LATINBIN:1433 - getaddrinfo ENOTFOUND devsql.mycom.com\LATINBIN',
  code: 'ESOCKET' }
```

If I can add info to make this a better report, or execute additional tests I am happy to do so.

**Comment by ChrisMiami** [comment]
Actually, the part after the backslash appears to be an "Instance Name" and, looking at the code for connection.js, may be supported if one sets options.instanceName (which basically resolves to a port lookup).  I will give that a try. Assuming it works, I think the issue, then, is that the expected parsing of the format <host>\<instance> is not done, making existing connection strings invalid.

**Comment by arthurschreiber** [comment]
Hey @ChrisMiami,

as you might have already found out, we don't support the generic server specs as used e.g. by SQL Server Management Studio. When creating a connection via `tedious`, there's a set of options you need to specify instead.

You can find a listing of all available options over at http://tediousjs.github.io/tedious/api-connection.html#function_newConnection

In your case, `devsql.mycom.com` would be the value for the `server` option, and `LATINBIN` would be the value for `instanceName`.

**Comment by tvrprasad** [comment]
Closing this as this is not a Tedious issue, just some house cleaning :-)
