### ISSUE TITLE
Connect requires SQLServer credentials - not Windows auth?

### ISSUE THREAD

**Issue by ChrisMiami** [tediousjs/tedious#562]
My database admins have specified that the login to SQLServer utilize Windows authorization, which means the logged-in OS user will connect without supplying additional credentials.  This is a security measure to avoid username/password in connection strings and source code.

I cannot seem to see any possibility of using this connection method with tedious.  There is no options setting that directs the servers to talk amongst themselves.

Is this possible in tedious?

**Comment by arthurschreiber** [comment]
Integrated Windows authentication is not implemented in `tedious` yet. There is an experimental pull request submitted by @tvrprasad from Microsoft over at https://github.com/tediousjs/tedious/pull/497 that implements integrated Windows authentication which you might want to take a closer look at.
