### ISSUE TITLE
Improvement for connection script example

### ISSUE THREAD

**Issue by SanderPs** [tediousjs/tedious#569]
I think it would probably be a good thing if the following line was added to the Connection-script at 'Getting started' [http://tediousjs.github.io/tedious/getting-started.html](http://tediousjs.github.io/tedious/getting-started.html) :

```
connection.on('debug', function(err) { console.log('debug:', err);});
```

As proposed by @johnwrightsman in: https://github.com/tediousjs/tedious/issues/352

Because if a connection can not be made, due to SQL Server not being set up the right way, it will give you an understandable error message, for instance:

```
debug: Failed to connect to localhost:1433 - Could not connect (sequence)
```

Which is a lot better than (when you combine the two scripts):
```
RequestError: Requests can only be made in the LoggedIn state, not the Connecting state
```

Btw: finding the real problem also lead me to the solution, which i found here:
http://stackoverflow.com/questions/32315817/cannot-connect-to-sql-server-with-node-js-and-tedious

But there is no example script for connecting to SQL Server using dynamic ports on the site. An example script for this might also prevent some frustration for first time users.

**Comment by v-suhame** [comment]
@SanderPs If you can update the [documentation](https://github.com/tediousjs/tedious/tree/gh-pages) and submit a PR, I can review it.

**Comment by IanChokS** [comment]
I've updated the docs to be more clear 
```js
  var connection = new Connection(config);

  connection.on('connect', function(err) {
    if(err) {
      console.log('Error: ', err)
    }
    // If no error, then good to go...
    executeStatement();
  });
```
