### ISSUE TITLE
Improvement to connection API documention

### ISSUE THREAD

**Issue by ltemme** [tediousjs/tedious#570]
API docs:
http://tediousjs.github.io/tedious/api-connection.html

Connection:
There is no mention of the appName config options ... this controls the value in sysprocesses program_name ... helpful when tracing SQL Server side ...

This is a valid connection string for example:
  //Connection string.
  var connectionConfig = {
    userName: config.sqlserver.userName,
    password: config.sqlserver.password,
    server: config.sqlserver.server,
    options: {
            port: config.sqlserver.port,
            appName: "blahblah"
    }
};

**Comment by IanChokS** [comment]
[The Documentation ](https://tediousjs.github.io/tedious/ )should be updated now, please feel free to open a new issue if things are still unclear.
