### ISSUE TITLE
Not connecting to SQL server

### ISSUE THREAD

**Issue by jwasserman1** [tediousjs/tedious#571]
I'm attempting to connect to a database in an instance of SQL Server 2014 using tedious and am getting the following output (I've omitted most of the debug code to make this readable, but let me know if including more would be helpful):
```
debug: connected to localhost:53802
debug: State change: Connecting -> SentPrelogin
debug: State change: SentPrelogin -> SentLogin7WithStandardLogin
Connected
debug: State change: SentLogin7WithStandardLogin -> Final
debug: connection to localhost:53802 closed
debug: State is already Final
```
When I attempt to query the database, I get the following error: 

```
error: RequestError: Requests can only be made in the LoggedIn state, not the SentLogin7WithStandardLogin state
```

My connection code is as follows:

```javascript
var config = {
     username: 'sa',
     password: '******',
     server: 'localhost',
     options: {
          database: 'testdb',
          port: 53802,
          debug: {
	      packet: true,
	      data: true,
	      payload: true,
	      token: true,
	      log: true
          }
    }
}

var connection = new Connection(config);

connection.on('debug', function(message) { 
    console.log('debug:', message);
});

connection.on('connect', function(err) {
    console.log("Connected");
});
```

I looked at previous related issues and realized I hadn't been specifying the correct dynamic port in the config options, which I changed, but I can't seem to figure out what the problem is now. TCP/IP is enabled. Any idea what the issue might be?

**Comment by chdh** [comment]
Try this:

```
connection.on('connect', function(err) {
   if (err) {
      console.error('Connection error', err);
   } else {
      console.log('Connected');
});
```

**Comment by jwasserman1** [comment]
Oh, wow. I had been including that error handling previously, but had removed it because the error message was clogging my terminal and I thought I knew what it was, but turns out I had been using the wrong option for my username. It has to be 'userName' and I was using 'username'. Thanks!
