### ISSUE TITLE
Type Real returns incorrect value

### ISSUE THREAD

**Issue by iba-jsykes** [tediousjs/tedious#572]
If you have a TYPE Real column and a value of say 3.0303  ,  always 4 decimal places. 
Tedious driver appears to be parsing the int to 15 decimal places.  Floats are working fine, just Real does this.

**Comment by chdh** [comment]
As Real and Float data types encode numbers with a binary exponential base, they can only store approximations of some decimal fractional numbers.

**Comment by arthurschreiber** [comment]
As pointed out by @chdh, not all values that are stored in different SQLServer types can be represented as JavaScript scalar values without a loss of precision.

I'm working on a new parser for `tedious` which will allow you to plug into the value parsing and convert binary tds values into whatever representation is required for your application. This is not ready yet, but hopefully will be some time in the future and should fix all these precision issues.

**Comment by chdh** [comment]
The precision is already lost when you store a decimal fractional number as a binary floating point number in the database. It's an inherent problem of binary floating point numbers.

Try e.g. `alert(0.1 * 0.2)` in JavaScript.

**Comment by iba-jsykes** [comment]
All true.  But A != B when it comes to database value and what I present to the user as the database value.    So when I say incorrect, I mean they do not match.

**Comment by chdh** [comment]
Try `select cast(cast(3.0303 as real) as float)` in SQL Server Management Studio.

The output is: `3.03029990196228`

**Comment by iba-jsykes** [comment]
Oh i got around it by using a CONVERT to decimal in my SQL passed.  Just pointing it out, I don't think that's going to hold up to heavy traffic.

**Comment by chdh** [comment]
You can use e.g. `Number.toFixed(n)` in JavaScript to have the same effect.

**Comment by iba-jsykes** [comment]
oh really? Can I put that in the data-types for tedious, or would this have to be in my app code?  Not obvious to me looking at source where to try it.
