### ISSUE TITLE
Tedious FIPS compliance

### ISSUE THREAD

**Issue by dexdexdex** [tediousjs/tedious#573]
Hello friends-
Is there any ODBC configuration stuff you have to do with tedious to make it be FIPS complaint and talk to FIPS enabled SQL Servers? My cursory glance at the codebase seems to indicate we're just using underlying node libraries like crypto and request to do heavy lifting. 

Sooo, if the underlying node binary is FIPS complaint is that all that's required?

**Comment by arthurschreiber** [comment]
Yeah, that's pretty much it. As long as your node binary was built with FIPS support and you run node in FIPS mode, everything should be compliant. 😄
