### ISSUE TITLE
tedious query not retrieving correct data from db

### ISSUE THREAD

**Issue by tromboneamafone** [tediousjs/tedious#58]
Using the provided code I test my sql query. The results are different than running the query in SQL Server Management Studio.

The data from the tedious query does not find any data after july  6, 2012, which is inconsistent with the actual database that I am getting the data from.

``` javascript
function 
   executeStatement() {
      request = new Request("select top 5 data, date from realTime where date > '2012-11-10'", function(err, rowCount) {
         if (err) {
            console.log(err);
         } 
         else {
            console.log(rowCount + ' rows');
         }
      });

      request.on('row', function(columns) {
         columns.forEach(function(column) {
            console.log(column.value);
         });
      });

      connection.execSql(request);
   }
```

I am at a loss to why the query is not executing correctly.

**Comment by Karsenh** [comment]
I'm getting this exact same issue - the working SQL query I copy over from SSMS and send through is returning different data than SSMS and sometimes nothing at all? It's using the correct db but acting as if it's not.

**Comment by mShan0** [comment]
Hi @Karsenh, can you open a new issue? We can assist you from there.
