### ISSUE TITLE
Developer Survey

### ISSUE THREAD

**Issue by LuisBosquez** [tediousjs/tedious#581]
Hello tedious users!

I'd like to learn more about how people use Tedious against SQL Server, so I created this developer survey: https://www.surveybuilder.com/s/eoZzN 

This will help us get to know you better and improve our contributions to tedious. I can post the results as well to satisfy your curiosity 😄

**Comment by LuisBosquez** [comment]
@arthurschreiber @tvrprasad Would adding this link to the README.md be ok?

**Comment by tvrprasad** [comment]
I like the idea of getting feedback from user community!
