### ISSUE TITLE
Error with transform-runtime

### ISSUE THREAD

**Issue by darklilium** [tediousjs/tedious#583]
Hello, 
I have made some code for connecting my ms sql database with mssql lib in a file called server.js
The files i have u can find them here: https://gist.github.com/darklilium/a4dafd836b623488bd0a5085678b4054

When i run 
```
$ node other.js
```
My code works and i have the response that i want.
If i want to import the "sqlQuery" function that i have made to call it in a React App, at exporting, im having the following error:

![image](https://cloud.githubusercontent.com/assets/8507515/26225236/3486b9cc-3bf4-11e7-8b79-9ad46fb19d85.png)

the code im doing for that is:

``` 
import sql from '../services/server.js';
```
And i want to do something that i have in "others.js" file showed in my gist.

Thanks in advice for ur help!

**Comment by v-suhame** [comment]
@darklilium this bug is fixed in React, you can follow it in https://github.com/facebook/react-native/issues/14530
