### ISSUE TITLE
bulkLoad and Foreign Key

### ISSUE THREAD

**Issue by jllunell** [tediousjs/tedious#589]
Hi, I'm trying to load data to Azure SQL Server, and when i use bulkLoad non of the Foreign Keys violations are fired, so i'm able to load corrupted data to the database.

When i use Request, the exception is fired and i can't load the same data that BulkLoad can. So Request is working fine with foreign keys, but I don't know why BulkLoad doesn't.

Anybody knows if it's my misconfiguration or something is wrong with this?
Thank you.

Edited:

I think here is an explanation:
https://dba.stackexchange.com/questions/103095/foreign-keys-become-untrusted-after-bulk-insert

Seems like when you do a bulkLoad the foreign keys are disabled unless you mark an option called CHECK_CONSTRAINTS.

**Comment by v-suhame** [comment]
Fixed in #637
