### ISSUE TITLE
Include table name in column's metadata

### ISSUE THREAD

**Issue by kevinresol** [tediousjs/tedious#591]
Currently it is not distinguishable where the column is from.

In contrast, in mysql, this query `SELECT * FROM tbl1 LEFT JOIN tbl2 ON tbl1.name = tbl2.name`
[with the nestTables option](https://github.com/mysqljs/mysql#joins-with-overlapping-column-names), results in:

```js
{
  tbl1: {name: 'Doe', age: 12},
  tbl2: {name: 'Doe', age: 23}
}
```

The output format isn't really important, but at least we know the name of the table where a column is from.

Not sure if this is limited by the TDS protocol though.

**Comment by v-suhame** [comment]
@kevinresol you are right, it is due to TDS limitation. The TDS response received from Server doesn't have tableName-column mapping for select queries, so it's not possible retrieve origin of column.
