### ISSUE TITLE
Not able to connect to Azure Sql DB

### ISSUE THREAD

**Issue by krishna-velamuri** [tediousjs/tedious#592]
var Connection = require('tedious').Connection;
var Request = require('tedious').Request;
var config = {
  userName: 'username', 
  password: 'password', 
  server: 'test.database.windows.net', 
  options: {
	 database: 'mydatabase'
    ,encrypt: true
    ,useUTC: true
    ,connectTimeout: 10000
    ,debug:{
      packet:true
      ,data:true
      ,payload:true
      ,token:true
    }
  }
};

var connection = new Connection(config);

connection.on('debug',function(message){
  if (!message) return;
  console.error("DEBUG: " + message);
});
// Attempt to connect and execute queries if connection goes through
connection.on('connect', function(err) {
    if (err) {
        console.log(err)
    }
    else{
        insertIntoDatabase()
    }
});

Error Info:

DEBUG: Failed to connect to block-chain.database.windows.net:1433 in 10000ms
{ ConnectionError: Failed to connect to block-chain.database.windows.net:1433 in
 10000ms
    at ConnectionError (C:\Personal\BlockChainAD\node_modules\tedious\lib\errors
.js:12:12)
    at Connection.connectTimeout (C:\Personal\BlockChainAD\node_modules\tedious\
lib\connection.js:634:28)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
  message: 'Failed to connect to block-chain.database.windows.net:1433 in 10000m
s',
  code: 'ETIMEOUT' }
DEBUG: State change: Connecting -> Final
DEBUG: Connection lost - Could not connect (sequence)

events.js:160
      throw er; // Unhandled 'error' event
      ^
ConnectionError: Connection lost - Could not connect (sequence)
    at ConnectionError (C:\Personal\BlockChainAD\node_modules\tedious\lib\errors
.js:12:12)
    at Connection.socketError (C:\Personal\BlockChainAD\node_modules\tedious\lib
\connection.js:703:28)
    at C:\Personal\BlockChainAD\node_modules\tedious\lib\connection.js:590:25
    at SequentialConnectionStrategy.connect (C:\Personal\BlockChainAD\node_modul
es\tedious\lib\connector.js:153:9)
    at Socket.onError (C:\Personal\BlockChainAD\node_modules\tedious\lib\connect
or.js:169:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchainad@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blockchainad@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blockchainad package,

npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blockchainad
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blockchainad
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Personal\BlockChainAD\npm-debug.log

**Comment by v-suhame** [comment]
Looks like a network delay. I'm able to connect to Azure without error. Does increasing connectionTimeout help?

**Comment by v-suhame** [comment]
Closing this issue as it has been inactive. Feel free to reopen if you still encounter it :)

**Comment by yss14** [comment]
@krishna-velamuri Have you fixed it somehow? :) I encounter the same issue with my Azure SQL -.-

**Comment by v-suhame** [comment]
@yss14 Are you able to [connect to Azure SQL Server via command line](https://docs.microsoft.com/en-us/azure/sql-data-warehouse/sql-data-warehouse-get-started-connect-sqlcmd#1-connect)? 

If you are running into the same error as @krishna-velamuri , `Connection lost - Could not connect (sequence)` is a generic message, so it is hard to suggest a solution. We can weed out the possibility of network delay, firewall issue or Server being shutdown, if you are able to connect from command prompt.

**Comment by yss14** [comment]
@v-suhame Yes, connecting via command line or other database management tools like data grip works like a charm.

The weird thing is, that the web app (hosted on an azure app service) is running fine for like 3-4 days. Than the log is spammed with `Failed to connect to xxx.database.windows.net:1433 in 15000ms` errors and the app stops working because there is no connection to the database possible. If I stop the app for like 2, it again works for like 3-4 days.
Btw. I'm using the `mssql` library on top of tedious, so I guess this issue occurs when over time too much connections of the pool time out and than reconnecting is not possible because of the error above.

**Comment by v-suhame** [comment]
`mssql` points to older version of `tedious` driver, we had #574 that addresses intermittent ConnectionError in Azure DB, it would be great if you can use the latest version of tedious driver to test 😄

**Comment by yss14** [comment]
@v-suhame Thanks for that information! :) How do I force mssql to use the newest tedious version?

**Comment by v-suhame** [comment]
`npm-shrinkwrap` might help (I haven't personally tried it), you can check the solution in https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions
