### ISSUE TITLE
Performance Issue using Blobs (Image)  Starting with versions >= 1.13.0

### ISSUE THREAD

**Issue by egandro** [tediousjs/tedious#594]
Hello,

I can confirm that "something" happened between the 1.12.x and 1.13.0 Tag that has a massive impact on performance when querying a column with an image colum.

Getting a 10mb image takes 1 sec with 1.12 and 10 sec with 1.13.

I checking this.

**Comment by arthurschreiber** [comment]
I've been working on a new parser over at https://github.com/tediousjs/node-tds-token-stream. The parser is not based on callbacks nor generators, making it extremely fast, with very low memory consumption, which are the two reasons that are causing the abysmal performance you're experiencing.

Unfortunately, I've not had a lot of time to work on it, so it's in a very early stage. Any help would be highly appreciated!

**Comment by egandro** [comment]
You are currently using som Yacc/Lex like grammar for the Parser?

**Comment by arthurschreiber** [comment]
@egandro No, we don't. 😄 The parser we have is for parsing binary data, and last time I checked Yacc/Lex is not really good at that.

I'm aware that performance is an issue when parsing large sets of data, but there is no "quick" fix here, unfortunately. 😞

I'll close this issue as fixing this is on our roadmap, but it will take some while till we get there.
