### ISSUE TITLE
Request timeout error

### ISSUE THREAD

**Issue by konekred** [tediousjs/tedious#598]
im getting this error
```
Unhandled rejection TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (C:\Users\Office6-1\Desktop\every-matrix\node_modules\generic-pool\lib\ResourceRequest.js:58:17)
    at Timeout.bound [as _onTimeout] (C:\Users\Office6-1\Desktop\every-matrix\node_modules\generic-pool\lib\ResourceRequest.js:8:15)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
```

config
```
    "username": "sa",
    "password": "somepassword",
    "database": "SampleDB",
    "host": "SAMPLE",
    "dialect": "mssql",
    "dialectOptions": {
      "requestTimeout": 0
    },
    "pool":{
      "maxConnections": 100,
      "minConnections": 1,
      "maxIdleTime": 10000
    }
```

code
```
let fs = require('fs')
let db = require('../models/index')

for (let i = 0; i < 100000; i++) {
  db.Test.create({ data: 'this is a test data ('+ i +')' })
}

```

**Comment by jeremyklein** [comment]
I believe I am running into a similar issue. That config option looks like one from Sequelize. Is this the case? One thing that worked for me was upping the max connections. Do you have the same issue if it is set to 100000?

**Comment by konekred** [comment]
did'nt try yet to set the maxConnection to a large number.. i temporarily use async/await to fix the issue.. cause when running many queries asynchronously hangs my database and throwing a request timeout error... thanks for your answer will try it later..

**Comment by arthurschreiber** [comment]
@konekred @jeremyklein Heya! 👋 

Sorry to hear you're running into issues using `tedious`. 😞

I read through the issue description here, but I'm not quite sure what is going on here. The code you pasted does not look like it's using tedious directly, but some other library instead. To understand what's going on, it would be great if you could provide an example that uses tedious directly. 🙇

**Comment by catcher-in-the-try** [comment]
this is a bug in mssql/tedious described here  
https://github.com/sequelize/sequelize/issues/8014

and fixed here
https://github.com/sequelize/sequelize/pull/8815

**Comment by v-suhame** [comment]
Hey @konekred, hope the fix in sequelize referenced by @catcher-in-the-try solves this issue. Feel free to reopen the issue and and provide a repro that uses tedious directly, if problem exists.
