### ISSUE TITLE
Rounding error on nanosecondDelta

### ISSUE THREAD

**Issue by peter-int-veld** [tediousjs/tedious#599]
NanosecondDelta  is rounded incorrect sometimes for the date/time datatype. For example with this date/time: ‘2017-06-29 17:20:03.5036264’. This is caused multiplication rounding errors.

**Comment by peter-int-veld** [comment]
I added a pull request with a fix.

**Comment by LuisBosquez** [comment]
@peter-int-veld, can you open a PR against this project? I think you linked to a commit on your fork and I can't find the request on this project

**Comment by tvrprasad** [comment]
@LuisBosquez There are actually 2 links. https://github.com/tediousjs/tedious/issues/599 is the link to the PR.

**Comment by tvrprasad** [comment]
Never mind :-) Here is the link to the PR - https://github.com/tediousjs/tedious/pull/600

**Comment by arthurschreiber** [comment]
This was fixed by #600. `tedious@2.1.3` was released on the `next` channel containing the fix for this. You can install this version via `npm install tedious@2.1.3` or `npm install tedious@next`. Could you double check and let me know if that solves your problem?
