### ISSUE TITLE
Connect to an open but invalid port (not an SQL instance) does not emits error

### ISSUE THREAD

**Issue by jacargentina** [tediousjs/tedious#601]
Using this simple code i was hoping to receive an error, as the port is a web server, not an MSSQL server.

```javascript
var Connection = require('./src/connection');

var connection = new Connection(
{
        "userName": "anything",  
        "password": "none",  
        "server": "localhost",
        "options": {
            "port": 80
        }
});

connection.on('connect', function(err) {
    console.log('connect', err);
  });

connection.on('end', function(info) {
    console.log('end', info);
  });

connection.on('error', function(info) {
    console.log('error', info)
  });

connection.on('debug', function(text) {
    //console.log('debug', text)
  });
```

On the console i simply get: `end undefined`, but i need tedious tells me "hey, this is not an mssql server!"

Any advice?

**Comment by tvrprasad** [comment]
The HTTP server is returning an invalid verb error message which the code is parsing as pre login response. On my machine, the packet length came out as 21584, so the message-io code kept waiting for the complete packet. In the meantime, the web server closed the connection after sending the error message.

In connection.js, the socket end handler, socketEnded, simply transitions to FINAL state which just closes the connection.

There needs to be more logic in socketEnded to see what the current state and then generate an appropriate error.

If you're able to put together a patch, I'll review.

**Comment by IanChokS** [comment]
If the tedious can't make a connection, it will throw an error after a few seconds or so, e.g.,

```
{ ConnectionError: Failed to connect to blah:1433 - getaddrinfo ENOTFOUND blah
```
