### ISSUE TITLE
angular 4 issue

### ISSUE THREAD

**Issue by Granaat** [tediousjs/tedious#604]
When initializing the connection I get a webpack error stating:

Module not found: Error: Can't resolve 'dns' in ...
same for 'dgram'

anyone knows how to resolve this?

used code:

import { OnInit } from '@angular/core';
import { Connection } from 'tedious';

const DBCONFIG = {
        userName: 'myusr',
        password: 'mypass',
        server: 'myserver',
        options: {
            database: 'mydb',
            tdsVersion: '7_1',        // sql 2000
            encrypt: false,
            rowCollectionOnDone: true
        }
};

export class DatabaseService implements OnInit {

    ngOnInit() {
        const DBconnection = new Connection(DBCONFIG);
    }
}

**Comment by walberglez** [comment]
Same thing is happening to me. Any ideas?

**Comment by arthurschreiber** [comment]
Tedious is not a javascript module for client-side use, it's intended to be used from Node.JS.

**Comment by WynneAnalytics** [comment]
Same issue here
