### ISSUE TITLE
object is not a funcion

### ISSUE THREAD

**Issue by victoreich1** [tediousjs/tedious#609]
When i try to connect, appears an error (object is not a function) because the function Connection is empty, then i printed the connection to saw the functions and parameters, 

![image](https://user-images.githubusercontent.com/31457212/29848443-cf639214-8cdd-11e7-83a2-d6747807ee16.png)

And yes, the Connection function is empty 

![image](https://user-images.githubusercontent.com/31457212/29848458-fa04830c-8cdd-11e7-8bb6-1c59502bae37.png)

why happened this?

**Comment by v-suhame** [comment]
that is unusual! can you clean the `tedious` package under node_modules and try installing it again?

**Comment by victoreich1** [comment]
i will try it tnks

**Comment by chdh** [comment]
In your case, `Connection` is the module exports object and not a function. The console.log() output is perfectly normal. 

You probably wanted to write:

     var Connection = require('tedious').Connection;
