### ISSUE TITLE
'Done' event not firing when request is complete

### ISSUE THREAD

**Issue by englishmatt** [tediousjs/tedious#61]
Per the title, the 'done' event is not being fired when the request returns all rows. I have something like the following, which _is_ retrieving row data:

```
request = new Request(statement, function (err, rowCount) {
    // Check for errors etc.
    connection.close();
});

request.on("row", function (fields) {
    // Do stuff with row data
});

request.on("done", function (rowCount, more) {
    console.log(rowCount + " rows returned.");   // <-- This is never executed.
});
```

More details available upon request, thanks.

Matt

**Comment by PhilTheAir** [comment]
I'm using execSql and there is nothing when listening to 'done', can console.log but no rowCount in  event of 'doneProc', can console.log in conjunction with the correct rowCount in event of 'doneInProc' !!

**Comment by deanvlue** [comment]
same problem here, i'm using execSql, although  doneProc and doneInProc get triggered i'm not getting any data from rows even when rowsCount is greater that 0 (in my case only one row)

**Comment by arthurschreiber** [comment]
@deanvlue I really can not reproduce this issue. What version of SQL Server are your running against? Which version of `tedious`? Can you come up with a minimal reproducible test case?

I believe that people misunderstand how and when the `done`, `doneProc` and `doneInProc` events fire, so understanding your issues will allow me to clarify the docs.

**Comment by waterfallbay** [comment]
I have exactlty the same issue.

```
connection.on('connect', function(err) {  
	// If no error, then good to proceed.  
		if (err) return console.error(err);
		else console.log("Connected");
		
		var rq = new TRequest("SELECT * FROM mytable;", function(err, rowCount) {
			
        if (err) {  
            console.log(err);}  
			
			console.log("Row Count: " + rowCount);
        });
		
        var result = "";
		
        rq.on('row', function(columns) {  
            columns.forEach(function(column) {  
              if (column.value === null) {  
                console.log('NULL');  
              } else {  
                result+= column.value + " ";  
              }  
            });  
            console.log(result);  
            result ="";
        });
  
        rq.on('doneProc', function(rowCount, more) {
			console.log("lallalla");
			console.log(rowCount + ' rows returned');  
        });
		
        connection.execSql(rq);
	});
```
The done event cannot be fired in execSql, doneProc could be fired, however, rowCount returns as undefined.

I am on the latest Azure V12 sql server DB.

**Comment by SteveShe** [comment]
Same problem here as well on Azure v12 DB. 'done' event never fires but 'doneproc' and 'doneInProc' both fire. 'doneInProc' seems to be the one handling the actual results as evidenced by the output at the bottom of this post. The other weird, and more annoying thing that may or may not be related, is that my script never stop executing. I have to kill it. This makes me think that Node is still doing something, but I have no idea what.   
-----------
var Connection = require('tedious').Connection;  
var config = require('./connection.json');

var connection = new Connection(config);  
connection.on('connect', function(err) {  
    if (err) {  
        console.log(err);
    }else {  
        console.log("Connected");
    }  

    var data = [];

    getData(data, function(err, rows) {
        if (err) {
            // Handle the error
            console.log(err);
        } else if (rows) {
            // Process the rows returned from the database
            console.log(rows);            
        } else {
            // No rows returns; handle appropriately
            console.log('no rows returned');            
        }
    });  
});

function getData(data, callback){
    console.log('Entered getData');
    var connection = new Connection(config);
    var newdata = [];
    var dataset = [];
    connection.on('connect', function(err) {

    var sql = "select * from bugs;";

         var Request = require('tedious').Request;
        var request = new Request(sql, function (err, rowCount) {
            console.log('made it to the callback...');
            
            if (err) {
                callback(err);
            } else {
                if (rowCount < 1) {
                    callback(null, false);
                } else {
                    callback(null, newdata);
                }
            }
        });
        //Package the returned data and send it back to the caller. 
        request.on('row', function(columns) {
            columns.forEach(function(column) {
                dataset.push({
                    col: column.metadata.colName,
                    val: column.value
                });
            });
            newdata.push(dataset);
        });
        request.on('done', function (rowCount, more, rows) { 
            console.log('I am done in done');
            console.log(rowCount);
            console.log(rows);
        });
        request.on('doneInProc', function (rowCount, more, rows) { 
            console.log('I am done in doneInProc');
            console.log(rowCount);
            console.log(rows);
        });
        request.on('doneProc', function (rowCount, more, rows) { 
            console.log('I am done in doneProc');
            console.log(rowCount);
            console.log(rows);                   
        });
        connection.execSql(request);
    });
}
------ results -------
node --debug-brk=10174 --nolazy index.js 
Debugger listening on port 10174
Connected
Entered getData
I am done in doneInProc
2
[]
I am done in doneProc
undefined
0
made it to the callback...
[ [ { col: '....

**Comment by SaloniSonpal** [comment]
I'm seeing the same issue. For my `execSql` request:

- `done` doesn't fire, 
- `doneProc` fires but `rowCount` is returned as undefined, 
- `doneInProc` fires first with correct `rowCount`. 

Is that expected? Should we be updating the docs to reflect this? @arthurschreiber @pekim, can you please help confirm this?

Repro code:

```
var Connection = require('tedious').Connection;  
var Request = require('tedious').Request;  
var TYPES = require('tedious').TYPES;  

// Create connection to database
var config = {
		userName: 'mylogin',  
		password: 'mypassword',  
		server: 'localhost',
		options: {
			database: 'testdb'
		}
	}
var connection = new Connection(config);  

// Attempt to connect and execute queries if connection goes through
connection.on('connect', function(err) {  
	if (err) {
		console.log(err);
		return;
	}  
	console.log("Reading rows from the Table...");
	
	// Read all rows from table
	request = new Request("SELECT * FROM dbo.employees;", function(err) {  
		if (err) {
			console.log(err);
		}  
	});  
	
	// Print the rows read
	var result = "";  
	request.on('row', function(columns) {  
		columns.forEach(function(column) {  
		  if (column.value === null) {  
			console.log('NULL');  
		  } else {  
			result+= column.value + " ";  
		  }  
		});  
		console.log(result);  
		result ="";  
	});  
	
	// Output the number of rows read
	request.on('done', function (rowCount, more, rows) {  
		console.log('done: '+ rowCount + ' row(s) returned');  
	});  
	
	request.on('doneProc', function (rowCount, more, returnStatus, rows) {  
		console.log('doneProc: '+ rowCount + ' row(s) returned');  
	});  

	request.on('doneInProc', function (rowCount, more, rows) {  
		console.log('doneInProc: '+ rowCount + ' row(s) returned');  
	});  		
	
	connection.execSql(request);  
});
```

Here's the output:
```
Reading rows from the Table...
2 Sunil India
3 Tom Germany
4 Jake United States
doneInProc: 3 row(s) returned
doneProc: undefined row(s) returned
```

**Comment by tvrprasad** [comment]
There is a 'callback' property you can set on Request and there is a 'requestCompleted' event on Request, both seem work. And those are the two things we didn't try :)

There may be some cleanup and documentation needed on this.

Try these and see if it works.

Using 'callback':
```JavaScript
  request.callback = function (err, rowCount, rows) {
      // rows is not being set but rowCount is. May be a bug.
      if (err) {
        // Error handling.
      } else {
        // Next SQL statement.
      }
  };
```
Using 'requestCompleted':
```JavaScript
  request.on('requestCompleted', function () {
    if (runAgain) {
      // Next SQL statement.
    }
  });
```

**Comment by SaloniSonpal** [comment]
@tvrprasad - Not sure I understand the response. All I'm saying is that `done`, `doneProc` and `doneInProc` are behaving differently than stated in the [documentation](http://tediousjs.github.io/tedious/api-request.html#event_done) :)

**Comment by tvrprasad** [comment]
oops. I mixed up issues there :-(
Sorry about that. Ignore my comment please.

**Comment by SaloniSonpal** [comment]
No worries! @tvrprasad - do you have permissions to fix the documentation?

**Comment by SaloniSonpal** [comment]
@arthurschreiber can we please update the docs for `done`, `doneProc` and `doneInProc`. They are behaving differently than stated in the [documentation](http://tediousjs.github.io/tedious/api-request.html#event_done)

**Comment by techmurphy** [comment]
var Request = require('tedious').Request;
var request = new Request(
        "SELECT * FROM table", function(err, rowCount, rows) {
		....
		response.render('pages/landingPage.ejs', {results: rows}

I read in the tedious API documentation that we need to set the Connection's config.options.rowCollectionOnRequestCompletion is true in order to get rows to fetch the value in the response.render

- However inspite of doing so my rows do not show any value on the browser.
- executing request.on('row', function(columns) however displays the values in the console.log

Anyone faced similar scenario

**Comment by v-suhame** [comment]
Documentation updated in #607, thanks to @veleek.
