### ISSUE TITLE
Cannot connect via encrypted connection to SQL Server 2008 SP2

### ISSUE THREAD

**Issue by eplowe** [tediousjs/tedious#610]
My app is trying to connect to SQL Server 2008 SP2. The connections are configured to be encrypted. The connection always times out at the configured connectionTimeout. I've talked to the DBA, and he's seeing the following error:

"The prelogin packet used to open the connection is structurally invalid; the connection has been closed. Please contact the vendor of the client library. [CLIENT: *.*.*.*]" 

Any ideas?

**Comment by slmmm** [comment]
Have you set your connection options for encrypted before attempting to connect?
**options: {
  encrypt: true
}**

**Comment by eplowe** [comment]
I have. When it's false I get a fast fail telling me that the server is
configured only to accept encrypted connections.

**Comment by eplowe** [comment]
I made a switch over to mssqlnodev8, it connects fine. But, this locks me to using windows boxes only.

**Comment by v-suhame** [comment]
@eplowe try enabling the debug log in driver to get more details. If you need assistance, you can share the logs either in github or via email. 

```
options: {
    debug: {
      packet: true,
      data: true,
      payload: true,
      token: true,
      log: true
    }
}
```

**Comment by eplowe** [comment]
connected to *.*.*.*:1433

Sent
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x002F, spid:0x0000, packetId:0x
01, window:0x00
  0000  00001A00 06010020 00010200 21000103 00220004 04002600 01FF0000 00010001
 ....... ....!... ."....&. ........
  0020  01000000 000000  .......
  PreLogin - version:0.0.0.1 1, encryption:0x01(ON), instopt:0x00, threadId:0x00
000000, mars:0x00(OFF)
State change: Connecting -> SentPrelogin

Received
  type:0x04(TABULAR_RESULT), status:0x01(EOM), length:0x002B, spid:0x0000, packe
tId:0x01, window:0x00
  0000  00001A00 06010020 00010200 21000103 00220000 04002200 01FF0A00 0FA00000
 ....... ....!... ."....". ........
  0020  010000  ...
  PreLogin - version:10.0.15.160 0, encryption:0x01(ON), instopt:0x00, threadId:
0x00000000, mars:0x00(OFF)
State change: SentPrelogin -> SentTLSSSLNegotiation

Sent
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x00FC, spid:0x0000, packetId:0x
01, window:0x00
  0000  16030100 EF010000 EB030369 0223084A 630A25D6 FEBC7699 D339956E 72068ACE
 ........ ...i.#.Jc.%...v. .9.nr...
  0020  A2B52A8A 5F9B8DF0 602D2000 006EC02F C02BC030 C02C009E C0270067 C028006B
 ..*._... `- ..n./.+.0.,.. .'.g.(.k
  0040  C024C014 C00A00A5 00A300A1 009F006A 00690068 00390038 00370036 C032C02E
 .$...... .......j.i.h.9.8.7.6.2..
  0060  C02AC026 C00FC005 009D003D 0035C023 C013C009 00A400A2 00A00040 003F003E
 .*.&.... ...=.5.#........ ...@.?.>
  0080  00330032 00310030 C031C02D C029C025 C00EC004 009C003C 002F00FF 01000054
 .3.2.1.0.1.-.).%.......<./.....T
  00A0  000B0004 03000102 000A001C 001A0017 0019001C 001B0018 001A0016 000E000D
 ........ ........ ........ ........
  00C0  000B000C 0009000A 00230000 000D0020 001E0601 06020603 05010502 05030401
 ........ .#..... ........ ........
  00E0  04020403 03010302 03030201 02020203 33740000   ........ ........ 3t..

Received
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x0269, spid:0x0000, packetId:0x
00, window:0x00
  0000  16030102 5C020000 4D030159 A880118F A3B71A1A A972EE56 B9498A2D B5364E7F
 ....\... M..Y.... .....r.V.I.-.6N.
  0020  CC86CF92 03DE55F7 7055B420 5D150000 DD08F8D4 B4E2C90F 220A315B EFDA1BE3
 ......U. pU. ]... ........ ".1[....
  0040  7D28158D EFB20768 34071571 002F0000 05FF0100 01000B00 02030002 000001FD
 }(.....h4..q./.. ........ ........
  0060  308201F9 30820162 A0030201 02021030 19550C7F E0F1A847 B710F7BB 0EEB1A30
 0...0..b.......0.U.....G.......0
  0080  0D06092A 864886F7 0D010105 0500303B 31393037 06035504 031E3000 53005300
 ...*.H.. ......0;1907..U. ..0.S.S.
  00A0  4C005F00 53006500 6C006600 5F005300 69006700 6E006500 64005F00 46006100
 L._.S.e. l.f._.S. i.g.n.e. d._.F.a.
  00C0  6C006C00 62006100 63006B30 1E170D31 37303431 35303531 3235335A 170D3437
 l.l.b.a. c.k0...170415051253Z..47
  00E0  30343135 30353132 35335A30 3B313930 37060355 04031E30 00530053 004C005F
 0415051253Z0;1907..U...0.S.S.L._
  0100  00530065 006C0066 005F0053 00690067 006E0065 0064005F 00460061 006C006C
 .S.e.l.f._.S.i.g.n.e.d._.F.a.l.l
  0120  00620061 0063006B 30819F30 0D06092A 864886F7 0D010101 05000381 8D003081
 .b.a.c.k0..0...*.H...... ......0.
  0140  89028181 00E37EC1 07803290 47F6347E C6573E54 E576A32F 19C52B7D 2945245E
 ......~. ..2.G.4~.W>T.v./..+})E$^
  0160  9AFD41CA 3BC2CA11 5FAFD06B A76826D7 1B5DFA1C 86CB8072 8B8470FF 555165D3
 ..A.;... _..k.h&. .].....r..p.UQe.
  0180  6085B133 F9E8DBEE D7743292 245F779F 7C469A6A E9190F9A 47C25026 C4642FE2
 `..3.... .t2.$_w. |F.j.... G.P&.d/.
  01A0  EFE66C83 996A95C0 8C74B396 25D7ECFD 2C15FF1D 76A90B5E 8F372960 DE96ECDD
 ..l..j.. .t..%... ,...v..^.7)`....
  01C0  D5DF02E2 DD020301 0001300D 06092A86 4886F70D 01010505 00038181 00CF6B74
 ........ ..0...*. H....... ......kt
  01E0  ED71C4FC BF45D1F3 DD4DA9B6 AE91F547 AE60AC79 8BF8A3FB FE6A7F35 1329CB94
 .q...E.. .M.....G.`.y.... .j.5.)..
  0200  AD74A664 3D3ED248 04148D83 6C9A8952 6A0FF900 CDA0B7DE 04ED40C4 B096907F
 .t.d=>.H....l..Rj....... ..@.....
  0220  460E9E80 2AB6ABEF FCBD098B 5CB8C0AD AC1BB0B5 E6FB3596 E18C02B2 BA8FF899
 F...*... ....\... ......5. ........
  0240  77756440 C486DD3C F1855FA6 7C93FF68 4C21A6C7 3F8E9B52 FAEB21C2 D80E0000
 wud@...<.._.|..hL!..?..R..!.....
  0260  00  .

Sent
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x00CE, spid:0x0000, packetId:0x
01, window:0x00
  0000  16030100 86100000 82008053 A50E887A F04D93E6 B9335113 F55FF951 F48457B2
 ........ ...S...z.M...3Q. ._.Q..W.
  0020  D808D397 2D89CA08 88E10AB8 965CBF6E 7D0DCF60 B8BA80DD A5DAC065 2304D240
 ....-... .....\.n}..`.... ...e#..@
  0040  5B4CD22B 9AD4EEE0 1CD4B774 66D49252 E1BDCB63 BDFFAA06 5557939F 26F71541
 [L.+.... ...tf..R...c.... UW..&..A
  0060  B9D5DFC6 27D30471 70A660D4 D53174E8 84A48E99 E1A86714 414BE507 A1578BF1
 ....'..qp.`..1t. ......g. AK...W..
  0080  AEBE9F57 138CA262 31096414 03010001 01160301 0030785B C5F9A164 6B3DA4C6
 ...W...b1.d..... .....0x[...dk=..
  00A0  F4A04309 B05B18B4 D67AD219 4DC69125 A1BEA6EE 9869C129 501422AA F581E0C5
 ..C..[.. .z..M..%.....i.)P.".....
  00C0  13012814 4BE9  ..(.K.

Received
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x0043, spid:0x0000, packetId:0x
00, window:0x00
  0000  14030100 01011603 0100309D 45443EDD 936F5A91 3242418A C7138DF2 D272F0D3
 ........ ..0.ED>. .oZ.2BA. .....r..
  0020  C96DE4AF DB3E77F1 6F38CF57 1F9DDABA ADFE79EE A9EDCBAD 27DF07  .m...>w. o
8.W.... ..y..... '..
TLS negotiated (AES128-SHA, TLSv1/SSLv3)

Sent
  type:0x10(LOGIN7), status:0x01(EOM), length:0x0102, spid:0x0000, packetId:0x01
, window:0x00
  /* Ommited due to sensitive info */
  Login7 - TDS:0x730B0003, PacketSize:0x00001000, ClientProgVer:0x00000000, Clie
ntPID:0x00000AB4, ConnectionID:0x00000000
           Flags1:0xE0, Flags2:0x00, TypeFlags:0x00, Flags3:0x08, ClientTimezone
:240, ClientLCID:0x00000409
           Hostname:'HOST', Username:'user', Password:'pass'
, AppName:'node-mssql', ServerName:'*.*.*.*', LibraryName:'Tedious'
           Language:'undefined', Database:'DB', SSPI:'', AttachDbFi
le:'', ChangePassword:''
State change: SentTLSSSLNegotiation -> SentLogin7WithStandardLogin
connection to *.*.*.*:1433 closed
State is already Final

**Comment by eplowe** [comment]
Sure thing. See attached. 

[debug_output.txt](https://github.com/tediousjs/tedious/files/1268577/debug_output.txt)

**Comment by ferm10n** [comment]
I'm also experiencing this exact issue. Any assistance for this would be greatly appreciated.

**Comment by v-suhame** [comment]
SQL Server doesn't respond after successful handshake 😞 One odd thing I noticed while looking at this issue is during Login7, a single packet shows 2 TLS exchange in wireshark, for SQL Server 2008. This would need more investigation.

**Comment by ferm10n** [comment]
@v-suhame the server not responding after the handshake seemed to be happening to me too. I also saw 2 TLS exchanges in wireshark. This makes me think that's what is causing the "structurally invalid" error, since it's only supposed to be sending a single Login7 packet.

How did you gather this from looking at debug_output.txt referenced above?

I found Microsoft Message Analyzer to be more helpful than wireshark with better parsing of TDS messages. https://technet.microsoft.com/en-us/library/dn727244.aspx

**Comment by v-suhame** [comment]
@ferm10n I couldn't gather much from the debug_output.txt. I had an instance of SQL Server 2008 in internal test lab, I was able to repro it there 😉 
After some digging, I found that cipher suite negotiated during handshake is not supported in SQL Server 2008, possibly for versions < SQL Server 2008 SP4, as they only support TLSv1.0, details [here](
https://support.microsoft.com/en-ca/help/3135244/tls-1-2-support-for-microsoft-sql-server).

Specifying proper cipher suite in config does the trick, e.g.
```
    options: {
      cryptoCredentialsDetails: { ciphers: 'RC4-MD5' }
    }
```
List of supported suites:
https://msdn.microsoft.com/en-us/library/aa380512.aspx
https://msdn.microsoft.com/en-us/library/aa380124.aspx

**Comment by v-suhame** [comment]
@eplowe @ferm10n can you test the solution suggested?

**Comment by ferm10n** [comment]
@v-suhame Thank you very much! That did the trick.
It's interesting that it negotiates to use a cipher suite that isn't supported. Any idea why that happens?

**Comment by v-suhame** [comment]
Yes, it is weird! I couldn't dig much as it was taken care by the `tls` package and SQL Server, nothing to do with Tedious directly.

**Comment by v-suhame** [comment]
Thanks for testing @ferm10n the solution, I'll close this issue :)

**Comment by eplowe** [comment]
This worked for me! Thank you!
