### ISSUE TITLE
Cannot establish a connection to a public SQL Server

### ISSUE THREAD

**Issue by Samvherck** [tediousjs/tedious#611]
When trying to connect to a SQL Server 2014 database using tedious (and auth0) I receive a timeout error message: 

timeout : failed to connect to 192.168.0....:1433 in 15000ms

I've already asked a question on Stackoverflow about this issue and I was informed that the problem hasn't got anything to do with the server or firewall because the server is publicly available on other computers using SSMS and the firewall is disabled, the TCP protocol is also enabled and the IPAll port is set to 1433. https://stackoverflow.com/questions/45937297/auth0-tedious-unable-to-connect-to-a-public-sql-server

How come tedious cannot establish a connection to a public SQL Server? 

```
var connection = sqlserver.connect({
    userName:  'userName',
    password:  'passWord',
    server:    'serverIp',
    options:  {
        database: 'databaseName',
    }
});
```

**Comment by chdh** [comment]
I assume that the Auth0 sandbox does not allow direct outgoing TCP connections. Did you try your code as a normal Node program?

**Comment by Samvherck** [comment]
It seems that it establishes a connection when using a normal Node program. The last message 'connectundefined' confuses me but the server and login information seems to be recognized and handled correctly (for example, wrong userName results in an error).

```
debugconnected to 192.168.0....:1433
debugState change: Connecting -> SentPrelogin
debugState change: SentPrelogin -> SentLogin7WithStandardLogin
debugPacket size changed from 4096 to 4096
debugState change: SentLogin7WithStandardLogin -> LoggedInSendingInitialSql
debugState change: LoggedInSendingInitialSql -> LoggedIn
connectundefined
```

**Comment by arthurschreiber** [comment]
I guess this is resolved then?

`connectundefined` seems to be part of the debug log output, I don't think there's anything wrong with it - I think `undefined` here means there was no error passed to the `connect` callback.

I'll go ahead and close this, but let me know if there's still an issue here.
