### ISSUE TITLE
config.options.rowCollectionOnRequestCompletion not fetching row count

### ISSUE THREAD

**Issue by v-suhame** [tediousjs/tedious#615]
> var Request = require('tedious').Request;
> var request = new Request(
> "SELECT * FROM table", function(err, rowCount, rows) {
> ....
> response.render('pages/landingPage.ejs', {results: rows}
> 
> I read in the tedious API documentation that we need to set the Connection's config.options.rowCollectionOnRequestCompletion is true in order to get rows to fetch the value in the response.render
> 
> - However inspite of doing so my rows do not show any value on the browser.
> - executing request.on('row', function(columns) however displays the values in the console.log
> 
> Anyone faced similar scenario

@techmurphy Opening an issue to track https://github.com/tediousjs/tedious/issues/61#issuecomment-308722245

**Comment by v-suhame** [comment]
@techmurphy Can you give more details on this issue? What do you get on consoling the rowCount/row from Request callback? I tried with single row of data, it is working, are you trying to fetch huge data?

**Comment by chdh** [comment]
`rowCollectionOnRequestCompletion` is not about the row count, it's about the row data.

When `rowCollectionOnRequestCompletion` is set, the `row` events are still emitted.
This can be seen in the following code sequence in [connection.js](https://github.com/tediousjs/tedious/blob/master/src/connection.js#L574):

        if (this.config.options.rowCollectionOnRequestCompletion) {
          this.request.rows.push(token.columns);
        }
        if (this.config.options.rowCollectionOnDone) {
          this.request.rst.push(token.columns);
        }
        return this.request.emit('row', token.columns);

When `rowCollectionOnRequestCompletion` is set, the row data is stored in `request.rows`.
`request.rows` is then passed to the callback function as the third parameter:

     return sqlRequest.callback(sqlRequest.error, sqlRequest.rowCount, sqlRequest.rows);

**Comment by Hadis-Fard** [comment]
@v-suhame @techmurphy I was not able to reproduce this issue using `rowCollectionOnRequestCompletion` and `rowCollectionOnDone`, both work as expected, could you elaborate more?

**Comment by v-suhame** [comment]
@Hadis-Fard yes, it works as expected :) I'll close this issue.
@techmurphy please reopen it if you have questions.
