### ISSUE TITLE
Deprecation warning: tls.createSecurePair() is deprecated since 0.11.3

### ISSUE THREAD

**Issue by cjthompson** [tediousjs/tedious#616]
`lib/message-io` uses `tls.createSecurePair()` which has been [deprecated since node v0.11.3](https://nodejs.org/dist/latest-v8.x/docs/api/tls.html#tls_tls_createsecurepair_context_isserver_requestcert_rejectunauthorized_options).

As of node v8, this generates warnings:
```
(node:72548) [DEP0064] DeprecationWarning: tls.createSecurePair() is deprecated. Please use tls.Socket instead.
```

**Comment by v-suhame** [comment]
Duplicate of #515
