### ISSUE TITLE
Azure Illegal Token

### ISSUE THREAD

**Issue by TSUDev** [tediousjs/tedious#617]
I am using tedious v2.0.0 and hosted my node app on Azure.
Whenever I try to connect to the SQL Server database I keep getting the following error:
this.emit('error', new Error(`No event '${eventName}' in state '${this
                                     ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\tedious\lib\tedious.js:4:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

It seems that the node server running on Azure has some trouble parsing the ES6 syntax (ex: "`" character)

This is my connection config:
`var config = {
server: '*****.database.windows.net',
userName: "*****",
password: "*****",
options: {
            database: 'TestDB',
            rowCollectionOnDone: true,
            rowCollectionOnRequestCompletion: true,
            encrypt: true
        }
}`

Please advise

**Comment by chdh** [comment]
According to [node.green](http://node.green/#ES2015-syntax-template-literals), template literals (strings between backticks) are supported since Node 4. The current Tedious version requires a Node version >= 4 ("engines"/"node" field in package.json).

What Node version do you have?

**Comment by v-suhame** [comment]
If your node app runs on local server without issue, it would essentially run on Azure too. Update your node version as @chdh suggested.

**Comment by arthurschreiber** [comment]
You need to specify a Node version greater than or equal to version 4 in your application's `package.json` file for Azure to pick up the correct version.

See https://stackoverflow.com/questions/34746480/upgrading-node-on-an-azure-website.
