### ISSUE TITLE
Intermittent "ConnectionError: Failed to connect to XYZ"

### ISSUE THREAD

**Issue by jpalo** [tediousjs/tedious#626]
As per suggestions in #300, I implemented SELECT 1 polling to workaround ECONNRESET errors. However, looking at the success rate of the polling makes me a bit concerned. There is no clear pattern, but every now and then, the simple SELECT doesn't go through and I get error "ConnectionError: Failed to connect to myazuresql.database.windows.net:1433 in 10000ms" I poll every 5 minutes.

I'd love to be more specific about the "every now and then", but sometimes it works hours without issues, sometimes there are two subsequent polls that fail.

I'm new to NodeJS and Tedious so have I even done it in the right place, in the main JS of the application (app.js in our case)?

```
// ping to prevent ECONNRESET errors 
// details: https://github.com/tediousjs/tedious/issues/300
setInterval(function () {
    //Ping the database constantly
    var connection = new Connection(config);
    connection.on('connect', function (err) {
        if (err) {
            logger.log('error in DB ping connection ' + err);
        } else {
            var request = new Request(
            "SELECT 1",
            function (err, rowCount, rows) {
                if (err) {
                    logger.log('error in DB ping ' + err);
                }
                else {
                    logger.log('DB ping OK');
                }
                connection.close();
            });
        
            connection.execSql(request);        
        }
    });   
    
}, 300000); // 5 mins
```

Configuration being, please note that I just increased connectTimeout from 10 secs to 20 secs, so I cannot yet say if it has any effect, would be surprised if it did, though.

```
module.exports = {
    userName: '...', 
    password: '...', 
    server: '....database.windows.net', 
    options: {
        database: '...',
        encrypt: true,
        rowCollectionOnRequestCompletion: true,
        connectTimeout: 20000
    }
}
```

**Comment by arthurschreiber** [comment]
Heya @jpalo!

Thanks for explaining the issue you're encountering. ❤️ 

Is there some way you could verify whether this is specific to `tedious` or if other tools also fail to connect to the database in the same time frames? This would help narrow down whether this is an issue with your network or the connection to Azure, or an issue in `tedious` itself.

**Comment by jpalo** [comment]
I will see how I could rule out some variables. App is running on Azure App Services so if it is network/connection related, it is something inside Azure.

**Comment by v-suhame** [comment]
@jpalo #574 must have fixed this issue. Feels free to reopen the issue if you notice intermittent failure with latest version of driver.
