### ISSUE TITLE
i cant get the value of fetched data from db

### ISSUE THREAD

**Issue by moedeveloper** [tediousjs/tedious#627]
I am trying to use promises and deferred to return fetched data from db, i do as following:

>     request = new Request("SELECT * FROM Details ")
>     request.callback = function (err, rowCount, rows) {
>         // rows is not being set but rowCount is. May be a bug.
>         if (err) {
>           console.log(err)
>         } else {
>           //console.log(rows)
>           deferred.resolve(rows)
>           console.log(deferred.promise)
>           process.exit()
>         }
>     };
>     connection.execSql(request)
>     return deferred.promise 

in the confugration i have  `rowCollectionOnRequestCompletion: true`, and 
        `useColumnNames: true`

The problem is that i dont get the return if i use it somewhere else in the js file and when i console.log the result it looks as bellow:

![image](https://user-images.githubusercontent.com/16238332/31737162-eaca5886-b446-11e7-8d2a-bd25486e907b.png)

I cant see the values, i just see it like this?

Please help :/

**Comment by arthurschreiber** [comment]
According to your `console.log` output, the promise was `fulfilled` and the value it was fulfilled with was the `rows` result you got back from `tedious`.

It looks like you're having trouble with using your promise library correctly, and this is not an issue with `tedious`? 🤔

Here's an example of using `tedious` with native ES6 promises:

```js
let promise = new Promise(function(resolve, reject) {
  // This assumes `rowCollectionOnRequestCompletion: true` and `useColumnNames: true`
  const request = new Request("SELECT * FROM Details ", function(err, rowCount, rows) {
    if (err) {
      return reject(err);
    }

    resolve(rows);
  });

  connection.execSql(request);
});

promise.then(function(result) {
  console.log(result);
});
```

I'll close this as I don't see anything actionable from the `tedious` side.

**Comment by moedeveloper** [comment]
alright, i am new to nodejs, you example helped me but i think we still need to close the connection before we make resolve or am i misstaking it?

**Comment by arthurschreiber** [comment]
It depends on whether you want to reuse the connection or not. Opening a new connection is quite expensive (in terms of time), so people usually keep the connections open as long as possible. 

There's even a library for managing connection pools - see https://github.com/tediousjs/tedious-connection-pool.

**Comment by moedeveloper** [comment]
i wonder why i dont get the value of each column please see bellow picture
![image](https://user-images.githubusercontent.com/16238332/31759866-0e08b722-b4b3-11e7-8ba7-beabcba31278.png)
and thats how i try to get the data

>     var promises = [];
>     promises.push(getSqlData().then(function (data) {
>         return data;
>     }));
>     Promise.all(promises).then(function (values) {
>         console.log(values)
>         var json = JSON.stringify({
>             
>         });
>         //res.end(json);
>     });

**Comment by moedeveloper** [comment]
ohh !! thank you i was really looking for something similar i used this once with mysql but i couldnt find how to do this with tedious.. !! I really appriciate your help!!!
