### ISSUE TITLE
Synchronous mode

### ISSUE THREAD

**Issue by rok-star** [tediousjs/tedious#629]
Greetings!

Is it possible and how long it would take to add synchronous mode?

--
Best regards.

**Comment by arthurschreiber** [comment]
Adding a synchronous mode would be going against any of the design principles of Node.JS. 😞 

As this is quite a peculiar request, may I ask what use you would have for a synchronous mode?

**Comment by rok-star** [comment]
For now in our project we have very complicated backend logic, that consits of kinda several levels of abstraction.
Now we are suppsed to add support of MSSQL, all our logic is sync way, and adding async stuff is not acceptable, or we have to reengineer everything.
Well, if it's impossible we will consider using something like deasync.
Thanks for quick response!

**Comment by arthurschreiber** [comment]
That sounds interesting.

I agree that moving synchronous code over to be asynchronous is not an easy task. `deasync` sounds like it might be able to help you here. Good luck! 😄
