### ISSUE TITLE
request emits prepared even on error (sometimes multiple times)

### ISSUE THREAD

**Issue by andrewsensus** [tediousjs/tedious#632]
When connection.prepare(request) encounters an error, the request emits the 'prepared' event rather than emitting an error. If the event-handler responds to the false 'prepared' event by calling connection.execute(request, params) and that also encounters an error, then a second 'prepared' event is emitted rather than calling the request callback (even though connection.prepare(request) was only called once).

steps to reproduce:
1. configure tedious to connect to the db via an ssh forwarded port (surely there are other ways, but ssh port forwarding provides an easy way to interrupt the tcp-connection)
2. setup ssh to forward a port, such as "ssh -L 1433:db-host:1433 localhost"
3. cause tedious to connect and perform some queries to verify the connection is working
4. stop/background ssh (example: enter, ~, control-Z; send it the corresponding signal if you prefer)
5. at this point tedious is still connected at the TCP level, but ssh is no longer forwarding bytes to/from the server
6. prepare a request
7. kill ssh (I used kill -KILL on the ssh pid)
8. observe that 'prepare' is emitted
9. in the handler for the 'prepare' event, attempt to execute the request
10. observe that the 'prepare' event is emitted a second time

**Comment by v-suhame** [comment]
@andrewsensus Thanks for the detailed repro steps 👍 [ `errorMessage`](http://tediousjs.github.io/tedious/api-connection.html#event_errorMessage) event is emitted for all Server Errors. 
For the scenario you described, `errorMessage` will be emitted before `prepared`, application should listen to it and decide on how to handle further listeners.
That would be the generic solution to handle Server error any point in time during connection:)

**Comment by andrewsensus** [comment]
@v-suhame so far my application has avoided handling connection events. It handles calls to the request callback and events emitted by the request but leaves tedious-connection-pool to handle connection events. Perhaps I need to look into that.
How do you feel about the pull request to avoid emitting a 'prepared' event when the prepare wasn't successful?

**Comment by v-suhame** [comment]
I'm skeptical about that, driver already has a generic way to handle error, it would be inconvenient to handle individual cases. 
Do look into tedious-connection-pool and let us know how that goes.

**Comment by andrewsensus** [comment]
@v-suhame I tested this, and I don't see an [errorMessage](http://tediousjs.github.io/tedious/api-connection.html#event_errorMessage) event, but I do see an [error](http://tediousjs.github.io/tedious/api-connection.html#event_error) event. It should be possible for the application to hook into the error event on the connection.

It still leaves tedious emitting (sometimes multiple) prepared events on error.

**Comment by v-suhame** [comment]
Thanks for trying that :) I haven't tested it by actually killing the SSH, so my recommendation was off, sorry.
 
Can you share the error message thrown in your [PR](https://github.com/tediousjs/tedious/pull/633/files#diff-aab1e3f14ac4fa89a7ece88d240d7a6eR18)?

In general, after `tedious` sends the SQL to prepare, the Server responds either with one of done packet (ie.., `DONE`/ `DONEPROC`/`DONEINPROC`)  or `ERROR`. In the case you described, Server doesn't respond as SQL doesn't reach it.
One approach to deal with this would be to fire `prepared` only after receiving the `DONE`, else to Timeout. What do you think about this approach?

**Comment by andrewsensus** [comment]
With the change in the pull request in place, code like this:
```
    preparedRequestState.request.on('error', function(err) {
      console.error('got error on request:', util.inspect(err, {depth: null}));
    });
```

results in output look this (logging configured to prefix lines with PID):
```
22489 got error on request: { Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

@v-suhame What would the application see if `tedious` hit the Timeout? An error event from the request (like in the PR)? A call to the request callback with an error?

How would the Timeout be configured? A new option passed to the `Connection` constructor? An additional argument passed to [prepare](http://tediousjs.github.io/tedious/api-connection.html#function_prepare)?

**Comment by v-suhame** [comment]
For Timeout, driver throws `RequestError: Timeout: Request failed to complete in <value>ms` , since we are getting `ECONNRESET`, which is a valid error, we can throw the same.

Can you update your PR to throw an instance of `RequestError`, you can use errors thrown in `request.js` as reference. And also, lets have the condition to check error at the beginning, like
```node
  this.callback = function(err) {
  if(err)
    // throw err via RequestError
  if (this.preparing) {
   ...
  } else {
    ...
  }
};
```
