### ISSUE TITLE
[Feedback] Tedious v2.1.0 release

### ISSUE THREAD

**Issue by arthurschreiber** [tediousjs/tedious#636]
`tedious@2.1.0` was released to the `tedious@next` pre-release channel.

If you want to test this new version, you can install it via `npm install tedious@next` or `npm install tedious@2.1.0`.

We plan to keep this new release in the `next` channel for at least a week, to gather feedback and gain confidence, before releasing this version to the `latest` channel. Please let us know if you run into any issues.

---

#### Bug Fixes

* Do not send username and password via LOGIN7 when a domain is set. (#630) ([c9b3fdb2](https://github.com/tediousjs/tedious/commit/c9b3fdb2))

#### Features

* Allow requests to be paused and resumed. (#518) ([9ef0d58d](https://github.com/tediousjs/tedious/commit/9ef0d58d))

---

### Known Issues

* Deployments to Azure fail because of the `sspi-client` dependency.

**Comment by arthurschreiber** [comment]
As we already know that deployments to Azure for applications using `tedious@2.1.0` will fail, we will push a new version that fixes this shortly to the `next` release channel.

**Comment by jdownhower** [comment]
Is there an issue with using Tedious on a table with more than 130 columns?  When Tedious 2.1.1 is being used via Sequelize, I am getting "RangeError: Maximum call stack size exceeded".

**Comment by v-suhame** [comment]
@jdownhower Do you get RangeError with `tedious@2.0.1` too? or is it just with `tedious@2.1.1`? Can you share some detail on what operation is being performed? which API or function triggers this?

**Comment by jdownhower** [comment]
@v-suhame I created an isolated test case and put it in this [repository](https://github.com/jdownhower/test-sequelize), so hopefully it is reproducible.  It also includes the detailed error ([output.txt](https://github.com/jdownhower/test-sequelize/blob/master/output.txt)).  Hope this is helpful.

**Comment by v-suhame** [comment]
@jdownhower Thanks for the repo! 
To sum up the issue, on reading a row with 130+ column, `RangeError: Maximum call stack size exceeded` is thrown.

This issue is due to nested callbacks in the driver, it is a known one (#512), @arthurschreiber was working on a fix, maybe he can give more details.

Workaround for now would be to decrease the packet-size of message, default packet size is `4 * 1024`, you can set it with `config.options.packetSize`.

**Comment by jdownhower** [comment]
@v-suhame Thank you!  I was able to use the Sequelize dialectOptions to pass the new packetSize value to Tedious as a workaround.

**Comment by arthurschreiber** [comment]
@jdownhower As @v-suhame correctly said, the issue is with a recursive code path in the current TDS packet parser. We hope to tackle this issue in the future! 😄

**Comment by arthurschreiber** [comment]
I just tagged `tedious@2.1.1` as `latest` to mark it as stable! 🎉
