### ISSUE TITLE
Date datatype does not work

### ISSUE THREAD

**Issue by niwsa** [tediousjs/tedious#638]
I am trying to input date columns with the value being set with below code snippet
`new Date('13-Sep-2005').toLocaleDateString({ timeZone: "Asia/Kolkata" })`
which should be stored in DB as YYYY-MM-DD format, but no matter what I try it gets stored as "0001-01-01".I am using Azure SQL DB.Appreciate any help.
PS: I tried the tedious latest build 2.1.1 but issue still exists

**Comment by arthurschreiber** [comment]
Hey @niwsa,

thank you for reaching out to us! ❤️ Unfortunately, your bug report does not contain enough information for us to reproduce your issue. 😞 Could you provide a code snippet that shows how you try to insert this value into your database? This will allow us to better understand what is going wrong.

Thank you! 💖

**Comment by niwsa** [comment]
@arthurschreiber   Have found a workaround.
I was trying to bulk insert rows and one of the fields was a Date datatype as shown below
 ```
bulkLoad.addColumn('BirthDay', TYPES.Date, { nullable: false });
...................
bulkLoad.addRow({'BirthDay': '13-Aug-1979'})
```

On changing the addColumn to TYPES.VarChar the date field was properly inserted.
