### ISSUE TITLE
SQL 2017 support

### ISSUE THREAD

**Issue by MickelSierra85** [tediousjs/tedious#639]
Hi, 
Is there an SQL 2017 support planned?

**Comment by v-suhame** [comment]
@MickelSierra85 the driver does work with SQL Server 2017. Are referring to some specific feature in 2017?

**Comment by MickelSierra85** [comment]
Actually I haven't tried it, just read the spec.
I am interested in using JSON columns and MATCH queries.

**Comment by v-suhame** [comment]
I haven't tested these features with `tedious`. But `MATCH` queries should work as the computation is done on Server side and client only accesses them via T-SQL.
Let us know the result if you get to test them 😃

**Comment by v-suhame** [comment]
`JSON` data must be accessible via `tedious`, as that too doesn't need any new additions to driver. I'll close this issue, feel free to open it if you have questions.
