### ISSUE TITLE
Feature: Support JSON data type

### ISSUE THREAD

**Issue by tomipaul** [tediousjs/tedious#663]
Is there a plan to support JSON data type anytime soon?
Thanks

**Comment by v-suhame** [comment]
JSON data should work with the existing driver, without needing to change anything, as all changes are on Server side. 
Data retrieved would be `NVarChar`, you just need to parse them into JSON.

**Comment by tomipaul** [comment]
Thanks :)
And I'm sorry for replying late; was on vacation.
