### ISSUE TITLE
Version inconsistencies.

### ISSUE THREAD

**Issue by dashmug** [tediousjs/tedious#668]
There seems to be an inconsistency between the versions in npm.

`npm outdated` yields...

```
Package  Current  Wanted  Latest  Location
tedious    2.2.3   2.2.3   2.1.5  db-diff
```

Why is the `latest` still at 2.1.5 when we already have v2.2.3?

**Comment by arthurschreiber** [comment]
Hey there! 👋

We have 2 release streams, `next` and `latest`. New versions are always released on `next` first, and then later also released on `stable`, once we don't hear about any issues.

I hope this explains the output you see via `npm outdated`. 🙇
