### ISSUE TITLE
Requests can only be made in the LoggedIn state, not the SentLogin7WithStandardLogin state

### ISSUE THREAD

**Issue by edelCustodio** [tediousjs/tedious#671]
Hi guys!

When I initialize my Electron app, and I try to get some data from the database using Tedious, I don't know why but when I'm sending a query to the database, the connection is ok but when the Request is fired I'm getting an error:

Requests can only be made in the LoggedIn state, not the SentLogin7WithStandardLogin state

here my code:

` getDesktop: function (localAddress) {
        SQLHelper.createConnection();
        var query = 'cliente.ObtenerIdComputadora'
        SQLHelper.clearSqlParameters();
        SQLHelper.addSqlParameter(SQLHelper.sqlParameter('ipCliente', localAddress, TYPES.VarChar));
        SQLHelper.addSqlParameter(SQLHelper.sqlParameter('nombreCliente', os.hostname(), TYPES.VarChar));
        return SQLHelper.executeStatement(query, true);
    },`

I created a generic SQL Helper class to handle all my queries:

`
//SQL Objects
const SqlConnection = require("tedious").Connection;
const Request = require("tedious").Request;
const { ipcMain, BrowserWindow } = require('electron');

//SQL Connection
let connection = null;

//SQL Parameter class
class Parameter {
    constructor(paramName, paramValue, paramType) {
        this.name = paramName;
        this.value = paramValue;
        this.type = paramType;
    }
}

//SQL Parameters array
let parameters = [];
let arrObj = []

//Main SQLHelper object
var SQLHelper = {
    
    //Create SQL Parameter
    sqlParameter: function (paramName, paramValue, paramType) {
        return new Parameter(paramName, paramValue, paramType);
    },
    
    //Add SQL Parameter to the array
    addSqlParameter: function(parameter) {
        parameters.push(parameter);
    },

    //Get the SQL Parameters array
    sqlParameters: function(){
        return parameters;
    },

    //Clear the SQL Parameters array
    clearSqlParameters: function(){
        parameters = [];
    },

    //Get the IP Server
    getIPServer: function() {
        return "SERVER";
    },
  
    getConfig() {
        return config = {
            userName: 'userName',
            password: 'password',
            instanceName: 'SQLEXPRESS',
            server: this.getIPServer(),
            port: "1433",
            options: {
                database: 'MyDatabaseName',
                useUTC: false,
                rowCollectionOnDone: true
            },
            debug: {
                packet: true,
                data: true,
                payload: true,
                token: true,
                log: true
            }
        }
    },
  
    //Open the SQL connection
    createConnection: function() {
        connection = new SqlConnection(this.getConfig());

        connection.on('infoMessage', infoError);
        connection.on('errorMessage', infoError);
        connection.on('end', end);
        connection.on('debug', debug);
    },

    //Execute any SQL statement, simple SELECT statement or stored procedure.
    executeStatement: function(query, isProcedure) {
        var $this = this;
        var parameters = $this.sqlParameters();
        arrObj = []

        return new Promise((resolve, reject) => {

            connection.on('connect', function (errConnection) {
                
                if (errConnection) {
                    console.log(errConnection);
                } else {
                    var request = new Request(query, function(errRequest, rowCount, rows) {
                        
                        if (errRequest) {
                            console.log(errRequest);
                        } else {
                            resolve(arrObj);
                        }                   
    
                        connection.close();
                    });
    
                    //Adding sql parameters
                    for(var i = 0; i < parameters.length; i++) {
                        request.addParameter(parameters[i].name, parameters[i].type, parameters[i].value);
                    }
                    
                    request.on('row', function(columns) {
                        var item = {}
                        columns.forEach(function(column) {
                            item[column.metadata.colName] = column.value; 
                        });
                        
                        arrObj.push(item);
                    });
                    
                    if (isProcedure) {
                        connection.callProcedure(request);
                    } else {
                        connection.execSql(request);
                    }     
                }                           
            });
        }); 
    },
  }

  function infoError(info) {
    var dd = info;
    console.log('infoError=> ' + info);
  }
  
  function debug(message) {
    var dd = message;
    console.log('debug=> ' + message);
  }
  
  function end() {
    var dd = '';
  }

module.exports = SQLHelper;
`

and here is what I'm getting using `connection.on('debug')` call.

debug=> connected to SERVER:1433
debug=> State change: Connecting -> SentPrelogin
debug=> State change: SentPrelogin -> SentLogin7WithStandardLogin
debug=> connected to SERVER:1433
debug=> State change: Connecting -> SentPrelogin
infoError=> {"number":5701,"state":2,"class":0,"message":"Changed database context to 'MyDatabaseName'.","serverName":"MyServerName","procName":"","lineNumber":1,"name":"INFO","event":"infoMessage"}
infoError=> {"number":5703,"state":1,"class":0,"message":"Changed language setting to us_english.","serverName":"MyServerName","procName":"","lineNumber":1,"name":"INFO","event":"infoMessage"}
debug=> Packet size changed from 4096 to 4096
debug=> State change: SentLogin7WithStandardLogin -> LoggedInSendingInitialSql
debug=> State change: SentPrelogin -> SentLogin7WithStandardLogin
infoError=> {"number":5703,"state":1,"class":0,"message":"Changed language setting to us_english.","serverName":"MyServerName","procName":"","lineNumber":21,"name":"INFO","event":"infoMessage"}
debug=> State change: LoggedInSendingInitialSql -> LoggedIn
debug=> Requests can only be made in the LoggedIn state, not the SentLogin7WithStandardLogin state
{ RequestError: Requests can only be made in the LoggedIn state, not the SentLogin7WithStandardLogin state
    at RequestError (C:\Users\Edel Custodio Frias\Documents\Electron\cyber-client-app\app\node_modules\tedious\lib\errors.js:34:12)
    at Connection.makeRequest (C:\Users\Edel Custodio Frias\Documents\Electron\cyber-client-app\app\node_modules\tedious\lib\connection.js:1353:33)
    at Connection.execSql (C:\Users\Edel Custodio Frias\Documents\Electron\cyber-client-app\app\node_modules\tedious\lib\connection.js:1143:19)
    at Connection.<anonymous> (C:\Users\Edel Custodio Frias\Documents\Electron\cyber-client-app\app\assets\js\server_side\sql-helper.js:123:36)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:188:7)
    at Connection.processedInitialSql (C:\Users\Edel Custodio Frias\Documents\Electron\cyber-client-app\app\node_modules\tedious\lib\connection.js:1082:19)
    at Connection.message (C:\Users\Edel Custodio Frias\Documents\Electron\cyber-client-app\app\node_modules\tedious\lib\connection.js:1640:21)
    at Connection.dispatchEvent (C:\Users\Edel Custodio Frias\Documents\Electron\cyber-client-app\app\node_modules\tedious\lib\connection.js:857:45)
    at MessageIO.<anonymous> (C:\Users\Edel Custodio Frias\Documents\Electron\cyber-client-app\app\node_modules\tedious\lib\connection.js:751:18)
    at emitNone (events.js:86:13)
    at MessageIO.emit (events.js:188:7)
    at ReadablePacketStream.<anonymous> (C:\Users\Edel Custodio Frias\Documents\Electron\cyber-client-app\app\node_modules\tedious\lib\message-io.js:102:16)
    at emitOne (events.js:96:13)
    at ReadablePacketStream.emit (events.js:191:7)
    at addChunk (C:\Users\Edel Custodio Frias\Documents\Electron\cyber-client-app\app\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:284:12)
  message: 'Requests can only be made in the LoggedIn state, not the SentLogin7WithStandardLogin state',
  code: 'EINVALIDSTATE' }
debug=> State change: SentLogin7WithStandardLogin -> Final
debug=> connection to SERVER:1433 closed
debug=> State is already Final

I hope someone can help me.

thanks in advance.

**Comment by v-suhame** [comment]
The failure is likely due to the way electron handles events. Running the code you shared without electron would works as expected without triggering error.

Quote from #604 
>Tedious is not a javascript module for client-side use, it's intended to be used from Node.JS.

**Comment by edelCustodio** [comment]
thanks for your answer @v-suhame 

so, any idea how can I solve this?

**Comment by v-suhame** [comment]
I don't see any direct way to use Tedious with Electron. Tedious needs Node.js runtime, and Electron doesn't match that requirement.

**Comment by MartinMa** [comment]
I used tedious with electron in the past. It worked for me. You can pass the database result via asynchronous inter process communication (ipc) to the browser process. The Tedious "business" needs to happen in the backend (Node.js environment).
