### ISSUE TITLE
Add type checking for config options

### ISSUE THREAD

**Issue by Hadis-Fard** [tediousjs/tedious#673]
Some of the config options could be set to anything, there should be a type checking before passing it on to the connection. For example, [abortTransactionOnError](https://github.com/tediousjs/tedious/blob/master/src/connection.js#L113) is checked to be boolean and [ColumnReplacer ](https://github.com/tediousjs/tedious/blob/master/src/connection.js#L133) is checked to be function.

**Comment by arthurschreiber** [comment]
👍 Yup, ideally we would type check all fields passed in by our users to conform to what we expect them to pass in. This is related, but orthogonal to the work of adding flow type annotations to the source.

**Comment by IanChokS** [comment]
This has been done now that the project is in TypeScript
