### ISSUE TITLE
Timezone is being ignored for datetimes

### ISSUE THREAD

**Issue by mnboos** [tediousjs/tedious#675]
Hi

I'm currently having the problem, that values of type datetime2 are returned as UTC, but the actual value has an offset of 1 hour (our timezone is Europe/Vienna (i.e. +1h)).

The value in the database is ```2017-09-12T10:33:00.190``` in timezone +1 (i.e. UTC time would be ```2017-09-12T09:33:00.190```.
However, tedious actually returns  ```2017-09-12T10:33:00.190Z``` which is ```2017-09-12T11:33:00.190``` in local time and that's wrong.

Either I'm wrong and there is some misunderstanding, or there is a problem in the driver.

We're using MSSQL2012 and Tedious 7.4

**Comment by sharpart555** [comment]
I have same problem too.

I 'm using MSSQL 2012 and node-mssql 4.1.0

**Comment by joshstevens19** [comment]
is this still a ongoing issue? i can take a look if so..

**Comment by leeahoward** [comment]
Was having the same issue.  Seems to be fixed by setting useUTC option.
options.useUTC
A boolean determining whether to pass time values in UTC or local time. (default: true).

**Comment by v-suhame** [comment]
@mnboos @sharpart555 Setting `useUTC: false` as mentioned by @leeahoward should do the trick. Feel free to reopen the issue if it didn't work.

**Comment by RevealedFrom** [comment]
I am using the latest 5.1.0 node-mssql (tediousjs/node-mssql).

My SQL Server is version 2014.12.500 and the time zone is:

    select sysdatetimeoffset()
    2019-07-25 10:41:08.4667360 +08:00

and sample test data:

    select Date from cdrs where id=22
    2019-07-24 23:20:00.000

My Node machine is on UTC+8 also, and my Node code is:

      const id = 22;
      POOL.request().query`SELECT Date from cdrs where id=${id}`.then(
        (results) => {
          console.log(results.recordset[0]);
      });

That log statement gives:

    Thu Jul 25 2019 07:20:00 GMT+0800 (Singapore Standard Time)

I get the same results whether `useUTC` is set to false or not.  (I set `useUTC` in the configuration option to open a database connection. I hope this is the right place.)

How do I get the same time when both my SQL Server and Node server are in the same time zone?
