### ISSUE TITLE
tedious connection with backslash

### ISSUE THREAD

**Issue by nicktackes** [tediousjs/tedious#68]
In my tedious connection configuration, 

I have a server structured like...

192.168.4.64\SERVER1

{
    "userName":"aaaa",
    "password":"bbbb",
    "server":"192.168.4.64\SERVER1",
    "database":"Audit",
    "options":{
        "database":"Audit",
        "debug":{
            "packet":true,
            "data":true,
            "payload":true,
            "token":true
        }
    }
}

I have tried double backslash thinking its a json parsing issue, but am unable to connect.  Can you advise?
thanks

**Comment by pmacca** [comment]
For anyone arriving from Google like I did, you can resolve this error by using `options.instanceName` as per the docs http://tediousjs.github.io/tedious/api-connection.html#function_newConnection.

So the initial example would change to
```
{
  "userName":"aaaa",
  "password":"bbbb",
  "server":"192.168.4.64",
  "database":"Audit",
  "options":{
  "database":"Audit",
  "instanceName:" "SERVER1"
  }
}
```

**Comment by pranayusg** [comment]
For sequalise users to connect from nodejs to mssql with hostname containing instanceName

const Sequelize = require('sequelize');
const sequelize = new Sequelize('Audit', 'aaaa', 'bbbb', {
  host: "192.168.4.64",
  dialect: 'mssql',
  dialectOptions: {
    options: {
      instanceName: 'SERVER1'
    }
  }
});

sequelize
  .authenticate()
  .then(() => {
    console.log('Connection has been established successfully.');
  })
  .catch(err => {
    console.error('Unable to connect to the database:', err);
  });
