### ISSUE TITLE
NPM warning: sprintf package is deprecated in favor of sprintf-js

### ISSUE THREAD

**Issue by megastef** [tediousjs/tedious#701]
When installing tedious npm shows a warning: 

```
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
```

Please update package.json to use sprintf-js.

**Comment by arthurschreiber** [comment]
Thanks! Fixed via c22ed1866fafca127f7cf844f65b022380cfd7e9, will be part of the 2.3.2 release.
