### ISSUE TITLE
Tedious query with multiple array elements 

### ISSUE THREAD

**Issue by whiterabbitj** [tediousjs/tedious#709]
Hello I am trying to insert multiple values onto my tedious query from an array. An make a coresponding amounts of calls to my sql server. However, I am not getting the required results. 

In this version only the first value is getting parsed. 

Could you please explain how should I insert different values from my array into the tedious query?

Someone suggested generating an XLM document and parsing it to the query? ( would that be the most easiest workaround this problem?)

```
`function GetJobsToCourseID(index, jobData){
  if((jobData != undefined)&&(jobData != null)){
    //console.log(jobData);
var extrArray = [];
    var newArray = [];
    for(var i = 0 ; i< jobData.length; i++){
        extrArray = jobData[i];
      }

    for (var j=0; j<extrArray.length; j++)
    {

      console.log(extrArray[j]);

      pool.acquire(function (err, connection1111) {
                if (err)
                console.error(err);
          
(function(array1){

requestID = new Request("SELECT IDKey from dbo.Jobz where SubJobFamily = @array1",  function(err, rowCount){

 if (err) {
      console.log(err);
    } else {connection1111.reset(function(err){});
  }
  });

requestID.addParameter('array1', TYPES.VarChar, array1);
requestID.on('row', function(columns) {
    for (var i = 0; i <columns.length;  i++)

    {  
    
      if (columns[i].value == null || columns[i].value == undefined) {
        console.log('NULL');
      } else {  

      console.log(columns, "fffffffffffffffffffffffffffffffffffffffffffffffffffffffff");
     
      }
      
    }

});
  connection1111.execSql(requestID);
  
     }(extrArray[j]));

});
      }
       pool.on('error', function (err) {
            console.error(err);
 });
}}`
```

**Comment by arthurschreiber** [comment]
Hey there! 👋 

I guess the most straightforward solution would be to build the query string dynamically, and have a new parameter for each entry in your array.

The second option would be to use a TVP parameter, but that'd be a bit more advanced.

**Comment by whiterabbitj** [comment]
very cocky... But solved it already adding a connection pool and let parameter in my loop.  thank you for an answer on closed issue though.
