### ISSUE TITLE
SQL 2016

### ISSUE THREAD

**Issue by SteveyPugs** [tediousjs/tedious#718]
I am confused. Is it supported the readme says no but it does connect to 2016 with no issue? So I am curious to get a straight answer.

**Comment by v-suhame** [comment]
Driver does works with SQL Server 2016, but its doesn't support features like Always Encrypted.

**Comment by SteveyPugs** [comment]
Ok. Thanks for the answer @v-suhame. Much appreciated.

**Comment by SteveyPugs** [comment]
Actually for future reference @v-suhame what about 2017? Same story?

**Comment by SteveyPugs** [comment]
@v-suhame I know you also only list that one feature but is there a list of features it won't support beside the above? Let me know thanks.

**Comment by v-suhame** [comment]
Yes, all the other [new features](https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-2016#sql-server-2016-database-engine) of SQL Server 2016 should work without any changes to the driver. Same goes for all the [new features](https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-2017#sql-server-2017-database-engine) in SQL Server 2017, they don't need changes to the driver 😄

**Comment by SteveyPugs** [comment]
Thanks!

**Comment by SteveyPugs** [comment]
Just a note, if you guys don't mind can I do a pull request to have the docs update for this information?

**Comment by v-suhame** [comment]
You are more than welcome to do that 👍
