### ISSUE TITLE
"parameter.type.validate is not a function" when using "geometry" data type

### ISSUE THREAD

**Issue by AlexMesser** [tediousjs/tedious#722]
Hi! I am using node-mssql and trying to save column with geography data type. Node-mssql supports that type (`sql.Geography`) but tedious falls on `validateParameters() ` function.

This is what I trying:

```sql
INSERT INTO "post"("id", "geoType") VALUES (@0, @1)
```
with parameters:
```typescript
[{"value":1,"type":"int","params":[]},
{"value":"POINT (100 100)","type":"geometry","params":[]}]
```
tedious falls with `parameter.type.validate is not a function` error.

I put log before `const value = parameter.type.validate(parameter.value);` code:

```typescript
{ type: 
   { id: 56,
     type: 'INT4',
     name: 'Int',
     declaration: [Function: declaration],
     writeTypeInfo: [Function: writeTypeInfo],
     writeParameterData: [Function: writeParameterData],
     validate: [Function: validate] },
  name: 0,
  value: 1,
  output: false,
  length: undefined,
  precision: undefined,
  scale: undefined }
{ type: { id: 240, type: 'UDTTYPE', name: 'UDT', hasUDTInfo: true },
  name: 1,
  value: 'POINT (100 100)',
  output: false,
  length: undefined,
  precision: undefined,
  scale: undefined }
```
as we see, second type have wrong definition. What am I doing wrong ?

**Comment by v-suhame** [comment]
@AlexMesser tedious doesn't support geography data type, refer http://tediousjs.github.io/tedious/api-datatypes.html 

As per node-mssql [doc ](https://github.com/tediousjs/node-mssql#geography-and-geometry), 
>node-mssql has built-in serializer for Geography and Geometry CLR data types.

It must be converting geography to some data type that tedious supports. Please raise this issue in [node-mssql](https://github.com/tediousjs/node-mssql/issues).

**Comment by AlexMesser** [comment]
Thank you!
