### ISSUE TITLE
nvarchar(max) Issue with Proc Parameter

### ISSUE THREAD

**Issue by RealNateB** [tediousjs/tedious#725]
When attempting to return nvarchar(max) from a stored proc, it limits to 4000. 

Fixed issue in `nvarchar.js`, `resolveLength()` as shown below. I don't know your code base well enough to know if this breaks anything but for my purposes and my checking, it resolved the issue. I assume this would also apply to varchar(max). 

I tried changing .maximumLength to "max" but there are some parts of the code expecting a number there.

```js
  resolveLength: function resolveLength(parameter) {
    if (parameter.length != null) {
      return parameter.length;
    } else if (parameter.value != null) {
      if (Buffer.isBuffer(parameter.value)) {
        return parameter.value.length || 1;
      } else {
        return parameter.value.toString().length || 1;
      }
    } else {
        return "max";
      // return this.maximumLength;
    }
  },
```

**Comment by v-suhame** [comment]
@RealNateB Thanks for reporting the issue, nice catch! This issue will affects all the variable-length data types (nvarchar/varchar/varbainary) returned by `OUTPUT` parameter. We will take deeper look at it :)
