### ISSUE TITLE
BulkLoad Executing in Connecting State

### ISSUE THREAD

**Issue by djb14** [tediousjs/tedious#729]
Following along with this example for bulkLoad : 
http://tediousjs.github.io/tedious/bulk-load.html

Receiving error: Request can only be made in LoggedIn State, not in Connecting state.
Which I know is usually a sign of an incorrect connection configuration.
But when I run  
`connection.on('debug', function(err) { console.log('debug:', err);});` 
I get the following message: 
`debug: State change: Connecting -> SentPrelogin
debug: State change: SentPrelogin -> SentTLSSSLNegotiation
(node:13080) [DEP0064] DeprecationWarning: tls.createSecurePair() is deprecated.
 Please use tls.Socket instead.
debug: TLS negotiated (ECDHE-RSA-AES256-SHA384, TLSv1/SSLv3)
debug: State change: SentTLSSSLNegotiation -> SentLogin7WithStandardLogin
debug: Packet size changed from 4096 to 4096
debug: State change: SentLogin7WithStandardLogin -> LoggedInSendingInitialSql
debug: State change: LoggedInSendingInitialSql -> LoggedIn`

So, it looks like I'm successfully logging in but the bulkLoad operation is occuring before?

**Comment by v-suhame** [comment]
`connection.execBulkLoad(bulkLoad);` should be called after the `connect` event. It is likely that you are calling `execBulkLoad` before connection is established. Can you double check that? 
If that's not the case, share your repo, we will have a look 🙂

**Comment by djb14** [comment]
Thanks so much for the quick response. Below is the basic code I am trying to use:

`var Connection = require('tedious').Connection;
var Request = require('tedious').Request;
var TYPES = require('tedious').TYPES;

var config = {
  userName: 'Username',
  password: 'Password',
  server: 'azure_server',
  options: {
   /* debug: {
      packet: true,
      data: true,
      payload: true,
      token: false,
      log: true
    },*/
    database: 'Database',
    encrypt: true, // for Azure users
  }
};

var connection = new Connection(config);
//connection.on('debug', function(err) { console.log('debug:', err);});

// optional BulkLoad options
var options = { keepNulls: false };
// instantiate - provide the table where you'll be inserting to, options and a callback
var bulkLoad = connection.newBulkLoad('TableName', function (error, rowCount) {
 	console.log('inserted %d rows', rowCount);
  	console.log(error);
});

// setup your columns - always indicate whether the column is nullable
bulkLoad.addColumn('storyId', TYPES.Numeric, { nullable: false });
bulkLoad.addColumn('category', TYPES.NVarChar, { length: 50, nullable: false });
bulkLoad.addColumn('categoryId', TYPES.Numeric, { length: 50, nullable: false });
// add rows
bulkLoad.addRow({ storyId: 7, category: 'hello', categoryId: 12 });
bulkLoad.addRow({ storyId: 23, category: 'world', categoryId: 12  });

// execute
connection.execBulkLoad(bulkLoad);`

**Comment by v-suhame** [comment]
@djb14 All execution should happen after connection is established, i.e execSql()/execSqlBatch()/execBulkLoad()/execute() should be called in the listener of `connect` event , like this,

```node
connection.on('connect', function(err) {
  if (err)
    throw err;
  connection.execBulkLoad(bulkLoad);
});
```

**Comment by v-suhame** [comment]
Hope this issue is resolved, feel free to reopen it if needed.
