### ISSUE TITLE
Are there any plans for a Promise- or async/await-based API?

### ISSUE THREAD

**Issue by goloroden** [tediousjs/tedious#734]
Basically, the title already says it all: Currently, tedious is entirely based on callbacks. Are there any plans to change this to an API that is Promise-based, so that you can use tedious with `async`/`await`?

This would be so awesome 😊

**Comment by Hadis-Fard** [comment]
At the time of writing this comment, we're looking into them, you can track the progress in tediousjs/node-tds-token-stream#1 and #716 😄

**Comment by goloroden** [comment]
Great, thanks a lot 👍

**Comment by v-suhame** [comment]
Sharing the comment made by @arthurschreiber 
>Promises / better async await support is in my long-term list of things to do. The reason I've refrained from touching that subject so for in tedious is that there is still a ton of discussion going on inside the Node.js project itself on how to move forward on better support for these 2 topics.
>
>E.g. very recently, an early version of async iterator support was added to ReadableStream for the next Node.js version (10) - see https://nodejs.org/download/nightly/v10.0.0-nightly20180205d4b605b990/docs/api/stream.html#stream_readable_asynciterator
>
>If possible, I'd rather have us built tedious on top of these core primitives (like streams), and then just absorb the work that is happening in the Node.js core.
