### ISSUE TITLE
Can't resolve 'dns' en react js

### ISSUE THREAD

**Issue by AngelFeu** [tediousjs/tedious#737]
Siempre que ingresa a un modulo con sql pasa esto.
Estoy trabajando desde react js.
Mi servidor sql server es 2017 lo que leí que tedious soporta actualmente.
quizás estoy haciendo mal, ya que leí que se debe hacer desde el lado del servidor, lo que no entiendo porque todos los ejemplos son para llamar desde app.js

Version:
```
{
  "name": "pruebasql",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-scripts": "1.1.4",
    "tedious": "^2.3.1"
  }
}
```

Error:

> Failed to compile
> ./node_modules/tedious/lib/connector.js
> Module not found: Can't resolve 'dns' in 'C:\programacion\pruebasql\node_modules\tedious\lib'

Code:
```
var Connection = require('tedious').Connection;
var Request = require('tedious').Request;
var TYPES = require('tedious').TYPES;

// Create connection to database
var config = {
  userName: 'sa', // update me
  password: 'mypass', // update me
  server: 'localhost',
  options: {
      database: 'mydb'
  }
}
var connection = new Connection(config);

// Attempt to connect and execute queries if connection goes through
connection.on('connect', function(err) {
  if (err) {
    console.log(err);
  } else {
    console.log('Connected');
  }
});
```

**Comment by AngelFeu** [comment]
please give me an example, cant find a good one anywhere. ty!

**Comment by v-suhame** [comment]
This page should help you in getting started, https://docs.microsoft.com/en-us/sql/connect/node-js/node-js-driver-for-sql-server?view=sql-server-2017

**Comment by v-suhame** [comment]
Hope you figured out how it works, feel free to reopen the issue if needed.
