### ISSUE TITLE
Escaping with tedious

### ISSUE THREAD

**Issue by fraross** [tediousjs/tedious#751]
Hi, this is mi query:
INSERT INTO DESCRIZIONE (DESCRIZIONE, FIELD, LANG, IDMONUMENTO) VALUES(@DESC, @FIELD, @LANG, @IDM)

But @DESC is a text with single quotes or multiple quotes and using parameters with this code:
Request.addParameter("DESC", Types.Text, request.payload.descrizione);

It does not escape my text and these quotes are remove, why? How can I solve this?

**Comment by v-suhame** [comment]
`Types.Text` maps to JavaScript type String, so quotes you are using in `addParameter` presents "DESC" as a String. If you want the quotes to be stored, you need to escape them like,
>Request.addParameter('\\'DESC'\\', Types.Text, request.payload.descrizione);

**Comment by v-suhame** [comment]
@fraross Hope this issue is resolved, feel free to open it if not.
