### ISSUE TITLE
version: 2.6.3, datetime data type, getTime() is not defined

### ISSUE THREAD

**Issue by mjodeh** [tediousjs/tedious#774]
when i try to pass a parameter with a datetime data type it gives this error.
The work around I found is like this:
under lib\data-types\datetime.js
from line 29 it should be like this:

if (options.useUTC) {
        var dateTest = new Date(parameter.value);
        days = Math.floor((parameter.value - UTC_EPOCH_DATE.getTime()) / (1000 * 60 * 60 * 24));
        seconds = dateTest.getUTCHours() * 60 * 60;
        seconds += dateTest.getUTCMinutes() * 60;
        seconds += dateTest.getUTCSeconds();
        milliseconds = seconds * 1000 + dateTest.getUTCMilliseconds();
      } else {
        var dateTest = new Date(parameter.value);
        dstDiff = -(dateTest.getTimezoneOffset() - EPOCH_DATE.getTimezoneOffset()) * 60 * 1000;
        days = Math.floor((dateTest.getTime() - EPOCH_DATE.getTime() + dstDiff) / (1000 * 60 * 60 * 24));
        seconds = dateTest.getHours() * 60 * 60;
        seconds += dateTest.getMinutes() * 60;
        seconds += dateTest.getSeconds();
        milliseconds = seconds * 1000 + dateTest.getMilliseconds();
      }
since the value is a number then the functions: getTime(), getUTCHours(),getUTCMinutes(),getUTCSeconds(), getTimezoneOffset(),getHours(),getMinutes(),getSeconds()

are not defined, so the solution i came with is first convert the parameter.value to a Date object and it seems to work fine.

SQL Server 2016

**Comment by chdh** [comment]
Why don't you pass a `Date` object as the parameter value?
It's documented in the [data types page](http://tediousjs.github.io/tedious/api-datatypes.html), that the JavaScript type must be `Date`.

**Comment by mjodeh** [comment]
this is the work around i used instead of modifying the source code, but it would be better if its done on the source code since the object type passed is DateTime.
Thanx.

**Comment by chdh** [comment]
There is no object type `DateTime` in JavaScript, only [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date). For the SQL server data type `DateTime` you have to use the JavaScript type `Date` for the parameter values.

**Comment by Suraiya-Hameed** [comment]
The suggestion above should have solved this issue, feel free to reopen it if needed.
