### ISSUE TITLE
connectionTimeout

### ISSUE THREAD

**Issue by ggazulla** [tediousjs/tedious#778]
How can change default connectionTimeout from 15000ms to more?
I'm trying add connectionTimeout: 90000 to connection options but no way...

Thanks!

**Comment by v-suhame** [comment]
Hey @ggazulla, it is `connectTimeout` and not `connectionTimeout` 😅 If you have used `connectTimeout` and still running into issue, can you share more details like the error stack, debug log and is this Azure Server?

**Comment by ggazulla** [comment]
@v-suhame  Thanks you so much! it works! :)
