### ISSUE TITLE
Random ETIMEDOUT 15000ms error

### ISSUE THREAD

**Issue by Troldefar** [tediousjs/tedious#786]
Doing a simple login electron application through Microsoft Azure however... For most routers my logic works fine, however when i try on specific routers that i need to access i get 

> ConnectionError {message: "Failed to connect to DELETEDSERVERNAME.database.windows.net:1433 in 15000ms", code: "ETIMEOUT", stack: "ConnectionError: Failed to connect to DELETEDSERVERNAME…DELETEDSERVERNAME/node_modules/tedious/lib/connection.js:906:16"}code: "ETIMEOUT"message: "Failed to connect to DELETEDSERVERNAME.database.windows.net:1433 in 15000ms"stack: "ConnectionError: Failed to connect to DELETEDSERVERNAME.database.windows.net:1433 in 15000ms↵ at ConnectionError (/Users/DELETEDSERVERNAME/Desktop/DELETEDSERVERNAME/node_modules/tedious/lib/errors.js:12:12)↵ at Connection.connectTimeout (/Users/DELETEDSERVERNAME/Desktop/DELETEDSERVERNAME/node_modules/tedious/lib/connection.js:936:28)

Tedious config object below

`var config =  {
        userName: 'DELETED',
        password: 'DELETED',
        server: 'DELETED.database.windows.net'
        options: {
           database: 'DELETED', 
           encrypt: true
       }
   }`

**Comment by Suraiya-Hameed** [comment]
Hi @Troldefar, Can you try https://github.com/tediousjs/tedious/pull/769? Looks like this issue is similar to the one reported in #590. 

If you are able to reproduce the issue even after using #769, please share the tedious logs along with info like, how often do you see this error? how did you connect via specific router? which version of driver are you using?

**Comment by Troldefar** [comment]
I managed to work around this by writing actual functional code, instead of that garbage i was producing for - The error was a result of my bad coding :-D Sorry i forgot to write it in here
