### ISSUE TITLE
Having a hard time returning records

### ISSUE THREAD

**Issue by JamesDoe** [tediousjs/tedious#787]
I am having a difficult time understanding why the following code breaks when anything other than columns[0].value is used:

```
             var myReturnObject = [];
             request.on('row', function(columns) {
                let o = {};
                for (let i in columns) {
                    o[columns[i].metadata.colName]=columns[i].value;
                }
                console.log(o);
                myReturnObject.push(columns[0].value);
            });
```

Anything other than "columns[0].value" will fail to push elements into the myReturnObject array. The console instruction will simultaneously fail. I've tried pushing my own objects as well as tedious-produced objects, i.e. columns[0].metadata.colName.

There is no debug or error code; just no elements pushed... not even an empty array.

What is going on here?

Side Note: I can push objects _alongside_ columns[0].value; i.e. "myReturnObject.push(columns[0].value,o)" works...

**Comment by Suraiya-Hameed** [comment]
Hey @JamesDoe, Is your query returning multiple columns? You can console.log `columns` to check that. Also, move `myReturnObject.push(columns[i].value);` inside the `for` loop.

**Comment by JamesDoe** [comment]
Hello @Suraiya-Hameed. Yes, it is returning multiple columns. 

I need to push the object into the array at the end of the ```for``` loop, as each record is represented as an individual object, and each column of the row is a property of the object. If I push into the array during the ```for``` loop, I will lose the grouping.

**Comment by Suraiya-Hameed** [comment]
But by having `myReturnObject.push(columns[0].value);` outside the loop, aren't you pushing just the value of first column every time! 

> Anything other than "columns[0].value" will fail to push elements into the myReturnObject array

Can you also clarify what was the other thing that failed? Can you share the original code that is causing this issue, along with what you are expecting `myReturnObject` to contain and what it actually contains?

**Comment by JamesDoe** [comment]
It's not pushing the first column's value, because ```.on('row',``` fires once for every record/row in a query and the element at the first index of each returned array is an object that contains the value and associated metadata.

```
        pool.acquire(function (err, connection) {
            if (err) { console.error(err); return; }
        
            //use the connection as normal
            let request = new Request(myQuery, function(err, rowCount) {
                if (err) { 
                    callback(err); 
                } else {
                    if ((data.auth === 1) && (rowCount > 1)) { 
                        callback({code:101,descr:'Invalid row count!'}); 
                    } else {
                        callback(null,myReturn); 
                    }
                }
                //release the connection back to the pool when finished
                connection.release();
            });
        
            request.on('row', function(columns) {
                let o = {};
                for (let i in columns) {
                    o[columns[i].metadata.colName]=columns[i].value;
                }
                console.log(o);

                
                myReturn.push(columns[0].value,o);
                // myReturn.push(o);

            });
            
            connection.execSql(request);
        });
```
and my callback is: 

```
function getRows (o) {
    return new Promise((resolve,reject) => {
        db_helper.get(o, (err, row) => {
            if (err) {
                reject(err);
            } else if (row) {
                resolve(row);
            } else {
                reject({code:100,descr:'Invalid row count!'});
            }
        })
    })
}
```

**Comment by Suraiya-Hameed** [comment]
Thanks for sharing the code :) I'm using this minimal, tedious only code for reproducing/understanding your issue, but everything seems to work fine,

```node
var connection = new Connection(config);
connection.on('connect', function(err) {
    executeStatement();
  }
);

function executeStatement() {
  var myReturnObject = [];
  request = new Request("select * from tds_char", function(err, rowCount) {
    console.log(myReturnObject);
    connection.close();
  });

  request.on('row', function(columns) {
    let val = {}
    columns.forEach(function(column) {
      val[column.metadata.colName] = column.value;
    });
    myReturnObject.push(val); 
  });

  connection.execSql(request);
}
```

Schema for the table is 
```SQL
CREATE TABLE [dbo].[tds_char](
	[c1] [char](32),
	[c2] [int] 
) 
```

With 2 rows, the console output I get is
`[ { c1: 'charDataTest                    ', c2: 56 },
  { c1: 'charDataTest                    ', c2: 56 } ]`

It retrieves all the columns and values, can you use this example to explain the issue you are facing?

**Comment by JamesDoe** [comment]
Thank you @Suraiya-Hameed for the assistance. Yersterday, I rewrote the code from scratch and removed some of the error checking:
```
    request.on('row', function(columns) {
        let o = {};
        columns.forEach((a)=>{o[a.metadata.colName]=a.value});
        myReturn.push(o);
    });
```
and
```
var MSSQL = {
    call: function  (o) {
        return new Promise((resolve,reject) => {
            db_helper.get(o, (err, row) => {
                if (err) {
                    reject(err);
                } else if (row) {
                    resolve(row);
                } else {
                    reject({code:100,descr:'Invalid row count!'});
                }
            })
        })
    }
};
```
and I am also now getting all columns and values... I truly don't understand the difference, but rather than compare code-for-code, I'm just going to be thankful that the code is now functioning properly.

Thank you again for your inisight and help!

**Comment by JamesDoe** [comment]
I think the issue was because I was using indexes here:
```
[columns[i].metadata.colName]=columns[i].value;
```
 I realize that columns [0] is the only viable object in each returned row. I'm just not clear as to why the object DID populate with the appropriate keys and values.

**Comment by Suraiya-Hameed** [comment]
Using your for loop actually worked for me, so I'm not sure what went wrong. Glad that you got it working :)
