### ISSUE TITLE
problem with rowCount

### ISSUE THREAD

**Issue by iarash84** [tediousjs/tedious#789]
Hi
I use express.JS and tedious for implementing a web service, but i can't compare row Count in code below with 1 in if statement ??? why ?? can anybody explain me what happened ??

this is my code 
`    const query = `BEGIN
                        IF NOT EXISTS (SELECT * FROM [dbo].[User]
                                        WHERE [userName] = 'MyuserName')
                        BEGIN
                        INSERT INTO [dbo].[User]
                                ([userName]
                                ,[nameAndFamily]
                                ,[premissionLevel]
                                ,[createDateTime])
                            VALUES
                                ('MyuserName'
                                ,'nameAndFamily'
                                ,'premissionLevel'
                                ,'2018-09-05 09:23:10')
                        END
                    END`;

    

    sqlconnection.execSql(new Request(query, 
        function(err, rowCount, rows){
        if(err) {
            res.end(JSON.stringify({status: 'Failed', id: '', token: err.message}));
            }
        })
        .on('doneInProc',function(rowCount, more, rows){
                console.log(typeof rowCount);
                if(rowCount === 1){
                    res.end(JSON.stringify({status: 'Success', id: '', token: ''}));
                }else{
                    res.end(JSON.stringify({status: 'Failed', id: '', token: 'this Username taken before'}));
                } 
            })
        );`

**Comment by Suraiya-Hameed** [comment]
From [tedious docs](http://tediousjs.github.io/tedious/api-request.html#event_done), 
> If you are using execSql then SQL server may treat the multiple calls with the same query as a stored procedure. When this occurs, the doneProc or doneInProc events may be emitted instead. You must handle both events to ensure complete coverage. 
.
Alter your code to listen to both `doneProc` and `doneInProc`, that might fix the issue

**Comment by Hadis-Fard** [comment]
Feel free to reopen the issue, if it persists
