### ISSUE TITLE
Update to Babel 7

### ISSUE THREAD

**Issue by kibertoad** [tediousjs/tedious#791]
New Babel got released recently, providing considerably faster build time and other goodies. Would a PR, updating used version of Babel be accepted?

**Comment by Suraiya-Hameed** [comment]
Yes, a PR would be great 😃

**Comment by kibertoad** [comment]
Right, Babel 7 itself can only be run on Node 6+, so PR can only be merged after https://github.com/tediousjs/tedious/issues/792 is resolved :)
