### ISSUE TITLE
Drop Node 4 support

### ISSUE THREAD

**Issue by kibertoad** [tediousjs/tedious#792]
Official support for Node 4 has ceased a while ago already. If we abolish support for it we could target Node 6 for transpilation, resulting in much more readable and debuggable code, and we could also stop using babel-runtime (which causes https://github.com/babel/babel-loader/issues/152 under some circumstances).

**Comment by Suraiya-Hameed** [comment]
Hey @kibertoad, there is PR https://github.com/tediousjs/tedious/pull/739 for dropping Node 4 support, you can review it and add your suggestions there :)

**Comment by kibertoad** [comment]
@Suraiya-Hameed Doesn't look like there is much to review, it looks like we just need to update the Buffer update PR to resolve conflicts and it should be good to merge :)

**Comment by arthurschreiber** [comment]
#739 was merged and released as `v3.0.0` on the `next` release channel.
