### ISSUE TITLE
Race condition on Request events: 'row' and 'requestCompleted'?

### ISSUE THREAD

**Issue by kunKun-tx** [tediousjs/tedious#793]
First time user here, not sure if this is human error or not.

### **Ver.:**
**Node**: 8. 11.3
**Tedious**: 2.6.4
**Bluebird**: 3.5.2
**DB**: win2012r2 + sqlserver2012
**host**: Debian 9 running in vmware workstation with NAT mode (could this be the issue?)

### **Issue:**
Request's event `row` fires after `requestCompleted` and `done`

### **Expected:**
`row` -> `done`/`doneInProc`/`doneProc` -> `requestCompleted`

### **Code:**
```javascript
    const mssqlConnection = new mssql.Connection(basicConfig)

    const querryRunner = (connection, sql) => {
      const statementComplete = (err, rowCount) => {
        if (err) {
          ctx.logger.warn(err)
        } else {
          if (isDevEnv) console.log(rowCount + ' rows')
        }
      }

      const request = new mssql.Request(sql, statementComplete)
      connection.execSql(request)
      return new Promise((resolve, reject) => {
        const data = []
        request.on('row', columns => {
          data.push(columns)
        })
        request.on('error', reject)
        request.on('requestCompleted', resolve(data))
        request.on('done', resolve(data))
        request.on('doneInProc', resolve(data))
        request.on('doneProc', resolve(data))
      })
    }
    const prepQueryData = (connection) => {
      const sql = 'SELECT 42'
      querryRunner(connection, sql)
        .then(data => {
          console.log(data)
        })
    }

    mssqlConnection.on('connect', err => {
      if (err) ctx.logger.warn(err)
      else {
        if (isDevEnv) console.log('mssql connected')
        prepQueryData(mssqlConnection)
      }
    })
```
I have breakpoints on all ·request.on` listeners and find the `row` events always fires after the others.

**Comment by Suraiya-Hameed** [comment]
@kunKun-tx can you try moving `connection.execSql(request)` inside the promise being returned? The order you see could be the result of adding listeners after calling `execSql`. Perhaps the `row` events are emitted by the driver before the listeners get attached.

**Comment by kunKun-tx** [comment]
@Suraiya-Hameed You are right. After moving `connection.execSql(request)` to the top of the promise now we can get the right order of events firing out as
`done`/`doneInProc`/`doneProc` -> `row` -> `requestCompleted`

Thank you and we can close this issue now.
