### ISSUE TITLE
utf-8 charset support

### ISSUE THREAD

**Issue by siamaksalman** [tediousjs/tedious#807]
Hi tedious team.
Thanks for your awesome library. I'm using it in production and and it's working really well. I'm facing some issues on utf-8 characters which I'm not able to store currently

so if I'm having a stringified JSON like this :
"{\"jsonname\":\"تست فارسی\"}"

I'm getting this on ms sql site:
"{\"jsonname"\:\"3 A'13ج\"}"

Now I notice that the character settings should be configured on ms-sql server but is there anyway to set the characterSet to utf-8 in application connection ? something like this in PHP: 

$db['default'] = array(
	'dsn'	=> '',
	'hostname' => '192.168.1.10',
	'port' => '1433',
	'username' => 'test',
	'password' => 'test',
	'database' => 'mytest',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

**Comment by Suraiya-Hameed** [comment]
Hi @siamaksalman, glad to know that tedious is working for you 😃 There is no option to set characterset during connection. Doesn't sending/retrieving result as `NChar` or `NVarChar` work?

**Comment by siamaksalman** [comment]
Dear @Suraiya-Hameed. Thanks you so much. It worked.
Regards
