### ISSUE TITLE
Bulkload request done

### ISSUE THREAD

**Issue by jackdh** [tediousjs/tedious#808]
Hey

much like the request.on('requestCompleted')...

How can I have a bulkLoad.on('requestCompleted')...

Thanks,

**Comment by Hadis-Fard** [comment]
@jackdh there's no 'requestCompeletd' event in bulkload, you can use its callback 😃

**Comment by jackdh** [comment]
Hey thanks for the reply that seems promising.

Just for reference however I'm not seeing a callback on the

`https://tediousjs.github.io/tedious/api-connection.html#function_execBulkLoad`

Do I need to use the newBulkLoad? And if so how? Thanks!

**Comment by Hadis-Fard** [comment]
You need to use `newBulkLoad` and have the completion code in the callback, then execute it using `execBulkLoad`


```
let conn = new Connection(config);
letoptions = { keepNulls: true };
let bulkload = conn.newBulkLoad('MyTable', options, (err)=>{
     console.log('done');
});
conn.execBulkLoad(bulkload);
```

check this page as well: http://tediousjs.github.io/tedious/bulk-load.html#usage
