### ISSUE TITLE
Issues with reading metadata of existing tables 

### ISSUE THREAD

**Issue by kunzhang1110** [tediousjs/tedious#825]
I was doing a project and encounter some issues in getting table's metadata/schema for the bulkloader. Basically, we had an existing/designed but empty table and we tried to put data in it. My solution was to make a dummy request, like "select top (1)", to get the column's metadata, as follows

```
function getBulkLoad(_table){
  return new Promise((resolve, reject) => {
    var bl;
    // make a dummy request
    let sql = 'SELECT TOP(1) * FROM ' + _table;
    let request = new TediousRequest(
      sql,
      function(err, rowCount, rows){
        if(!err){
          resolve(bl);
        }else{
          reject(err);
        }
      });

    // retrive metadata of the table and set bulkLoad
    request.on('columnMetadata', function (columns) {
      bl = setBulkLoad(columns);
    });

    connection.execSql(request);
  });
}
```

which returns a promise that returns a bulkload on resolve. I think creating the table in the code would have worked but we could not do that for some other reasons.

Also when reading nullable columns with certain types XXX, such as datetime,  the returned object type is XXXN. However, XXXN is somehow not supported in the current version for bulkloading, though can be found in source code. My workaround was to mannually set object type XXXN back to XXX, and set column nullability again for bulkloader, something like

```
    // tedious library read some nullable type abc as abcN; convert abcN back to abcN
    if(dataTypeName.slice(-1)== 'N'){  //if dataType is nullable
      dataTypeName = dataTypeName.slice(0,-1);
    }

    if (NULLABLE_COLUMNS.indexOf(colName) > -1){ //if colname is in NULLABLE_COLUMNS
      bl.addColumn(colName ,TYPES[dataTypeName], {nullable:true});
    }else{
      bl.addColumn(colName ,TYPES[dataTypeName], {nullable:false});
    }
```

I know these are probably some noob's way to handle things :), so can anyone suggest a better way to do it? Thanks.

**Comment by Hadis-Fard** [comment]
@kunzhang1110 this code doesn't seem to use tedious bulkloader correctly (or maybe it's partial code snippet :sweat_smile:), you should create a bulkload object, see the [documentation ](http://tediousjs.github.io/tedious/bulk-load.html) for more info, also you should be able to create table by sending the sql. for the type issue, could you send a working repo?

**Comment by Hadis-Fard** [comment]
@kunzhang1110 could you send and isolated executable repo of the issue? It's time-consuming to go through all your code 😅

**Comment by Hadis-Fard** [comment]
@kunzhang1110 closing this issue, feel free to reopen 😄
