### ISSUE TITLE
the `tdsVersion` option is not working

### ISSUE THREAD

**Issue by tommyfok** [tediousjs/tedious#838]
## the `tdsVersion` option is not working
> help~~~~~~

I am so confused that even if I set tdsVersion to '7_1', tedious still generated SQL statements only supported by SqlServer version 2012(the fetch next statement), which did not match the document description.
![image](https://user-images.githubusercontent.com/3250229/50158335-d2a58880-030e-11e9-9785-ac739c9a7ff3.png)

generated sql example

```sql
select [存货资料].* from [存货资料] offset @p0 rows fetch next @p1 rows only
```

**Comment by Hadis-Fard** [comment]
Hi @tommyfok 👋  it's not clear what's the issue, are you trying to generate SQL Statement? or you're trying to execute it? Would you please send an isolated executable repo of the issue?

**Comment by tommyfok** [comment]
> Hi @tommyfok 👋 it's not clear what's the issue, are you trying to generate SQL Statement? or you're trying to execute it? Would you please send an isolated executable repo of the issue?

I wanted to use KNEX to perform some queries on my SQL Server 2008 database, but the database reported some SQL errors because KNEX generated some SQL statements that SQL Server 2012 only supported such as `select [存货资料].* from [存货资料] offset @p0 rows fetch next @p1 rows only`. The `fetch next` statement is only supported after Sql Server 2012. Even if I set `tdsVersion` option to `7_1` or other any value that written in the document, I get the same sql.

**Comment by arthurschreiber** [comment]
@tommyfok `tdsVersion` allows specifying the version of the TDS protocol to be used. But this has no impact on `knex` (which is a different project), nor does it impact what SQL features are supported on the SQL Server instance.

E.g. you can connect to SQL Server 2016 using TDS 7.1 and still use all the new T-SQL functionality.

I think you need to reach out to the `knex` developer and raise this issue with them, as there's nothing wrong or unexpected in the way `tedious` behaves here. Thanks! ❤️

**Comment by rickysullivan** [comment]
@tommyfok What was your solution? I'm having the same issue.

**Comment by tommyfok** [comment]
> @tommyfok What was your solution? I'm having the same issue.

I gave up and used `knex.raw` instead.
