### ISSUE TITLE
Using windows authentication not working

### ISSUE THREAD

**Issue by jennypho** [tediousjs/tedious#852]
I'm having trouble getting SQL express connected to my application using windows authentication
is there something I'm doing wrong?  
```
const {Request} = require('tedious');
const TYPES = require('tedious').TYPES;
const ConnectionPool = require('tedious-connection-pool');

const poolConfig = {
    min: 1,
    max: 1,
    log: true
};

const config = {
    server: 'localhost',
    userName: 'windowsUsername',
    password: 'password',
    domain: 'US',
    options: {
        port: 1433,
        database: 'Database name'
    }
};

const pool = new ConnectionPool(poolConfig, config);

pool.on('error', (err) => {
    console.log(err);
});




```

**Comment by MichaelSun90** [comment]
Hi Jennypho,
I just took look at your issue. I have tried the exacted config set up for the connection same as yours, but i cannot repro this issue on myside. Just want to double check, what is the exact error message that you got for windows authentication and, what is the version of the tedious-connection-pool that you are currently using? I am using "tedious-connection-pool": "^1.0.5".  Also, if it is possible, can you also share your package.json or your other set ups, so i can try to reporduce the issue with the exact seting of yours. Thanks

Michael

**Comment by jennypho** [comment]
Nevermind got it to work! I just had to change my configuration

```
const config = {
    userName: "username",
    password: "pass",
    server: "servername",
    domain: "US",
    options: {
        instance: "SQLEXPRESS",
        database: "dbname",
        encrypt: false,
        rowCollectionOnDone: true,
        useColumnNames: true
    }
};
```

**Comment by jennypho** [comment]
> Hi Jennypho,
> I just took look at your issue. I have tried the exacted config set up for the connection same as yours, but i cannot repro this issue on myside. Just want to double check, what is the exact error message that you got for windows authentication and, what is the version of the tedious-connection-pool that you are currently using? I am using "tedious-connection-pool": "^1.0.5". Also, if it is possible, can you also share your package.json or your other set ups, so i can try to reporduce the issue with the exact seting of yours. Thanks
> 
> Michael

Thanks!
