### ISSUE TITLE
update supported Nodejs versions to active LTS releases

### ISSUE THREAD

**Issue by jimmont** [tediousjs/tedious#876]
Please update the supported versions of Nodejs to active LTS release lines. In particular tedious version 6.

As of May 2019 [active LTS are](https://github.com/nodejs/Release): **Nodejs version 8 and version 10**.

According to [the survey](https://github.com/tediousjs/tedious/issues/690) this could impact as much as 57% of users as they're reported as using a version older than Nodejs v8.

Changes to the project can follow if and when it makes sense to do so (ie passively).

Reasoning: it doesn't make sense to target unsupported runtimes and older versions of this product can be used as-necessary. Targeting active LTS allows using specific features that improve code quality and testing against specific targets reduces testing cost.

**Comment by arthurschreiber** [comment]
As specified in https://github.com/tediousjs/tedious/blob/master/package.json#L36-L38, tedious currently supports Nodejs versions 6 and up. 6 is the current LTS version until the end of April 2019, and we'll probably keep supporting it until then at least.

Thank you for the heads up, but we'll be staying compatible with 6.x at least to the end of April. There's no rush to kick out support right the moment Nodejs 6.x becomes unsupported. 😄

**Comment by jimmont** [comment]
The suggestion is to support LTS releases. The suggestion is not specific to any version, other than those which are active LTS releases. If adopted it would no longer be necessary to publish specific support other than "active LTS releases" and then update the package content to reflect the active LTS release whenever it is updated. Supporting version 6 of Nodejs would be included until the end of April as you've suggested. It seems realistic and reasonable to limit support to what is explicitly tracked as actively supported in the runtime and not outside of that, hence the suggestion. This appears to be lacking from this project, hence the suggestion. It takes some effort to move to different runtimes and making customers aware of transitions is helpful to them. So your calling out version 6 is actually in conflict with this because it fails to consider that this is within a matter of weeks where a given runtime will no longer be formally supported.

**Comment by arthurschreiber** [comment]
I just opened https://github.com/tediousjs/tedious/pull/905 which will drop support for Node.js 6.x.
