### ISSUE TITLE
Request.pause() does no longer stop memory overflow (regression)

### ISSUE THREAD

**Issue by chdh** [tediousjs/tedious#877]
Up to Tedious 2.6.4 everything works fine, but starting with Tedious 2.7.0 the memory keeps getting filled with data from the SQL server even after `Request.pause()` has been called.

This problem has been reported by @gsamal in a comment to #518, and in tediousjs/node-mssql#832.

I have written a test program that confirms the problem: [testPauseResume.zip](https://github.com/tediousjs/tedious/files/2968441/testPauseResume.zip)

**Comment by arthurschreiber** [comment]
This was fixed via #878.

**Comment by arthurschreiber** [comment]
The fix for this is part of the `6.0.1` release. 🎉
