### ISSUE TITLE
Conversion failed when converting the varchar value '0.6' to data type int.

### ISSUE THREAD

**Issue by AlexanderTunick** [tediousjs/tedious#884]
Hello.
I have stumbled on some issue that I can't figure out how to handle right now.
I have a simple query that works in any SQL tool (in my case DataGrip) and doesn't work with 'mssql' [https://www.npmjs.com/package/mssql] library that uses the tedious driver.

```
Select count(distinct o.PID) as p from dbo.Organization as o
inner join dbo.OrganizationDetail as od
    on od.OrganizationUniqueID = o.OrganizationUniqueID
inner join dbo.PIDXrefLinks as x
    on x.OrganizationUniqueID = o.OrganizationUniqueID
left join dbo.OrganizationSupplementalData as cosd
  on cosd.OrganizationUniqueID = o.OrganizationUniqueID
  and cosd.SupplementalDataTypeId = 11
  and cosd.Descriptor = 'Total Minority'
where o.FileType in ('12')
and (case od.ProfessionalType when '09' then x.CWB_OrganizationClassID else 0 end ) != '8'
and o.DeptName is null
and case(cosd.value between 43 and 45)
```

After running the query receiving this error: 
> RequestError: Conversion failed when converting the varchar value '0.6' to data type int.
>     at handleError (node_modules/mssql/lib/tedious.js:519:15)
>     at Parser.<anonymous> (node_modules/tedious/lib/connection.js:618:16)
>     at Parser.<anonymous> (node_modules/tedious/lib/token/token-stream-parser.js:54:15)
>     at addChunk (node_modules/readable-stream/lib/_stream_readable.js:291:12)
>     at readableAddChunk (node_modules/readable-stream/lib/_stream_readable.js:278:11)
>     at Parser.Readable.push (node_modules/readable-stream/lib/_stream_readable.js:245:10)
>     at Parser.Transform.push (node_modules/readable-stream/lib/_stream_transform.js:148:32)
>     at doneParsing (node_modules/tedious/lib/token/stream-parser.js:110:18)
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/infoerror-token-parser.js:46:5
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/infoerror-token-parser.js:13:19
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:247:9
>     at Parser.awaitData (node_modules/tedious/lib/token/stream-parser.js:144:9)
>     at Parser.readUInt32LE (node_modules/tedious/lib/token/stream-parser.js:244:12)
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/infoerror-token-parser.js:12:90
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:446:11
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:433:9
>     at Parser.awaitData (node_modules/tedious/lib/token/stream-parser.js:144:9)
>     at Parser.readBuffer (node_modules/tedious/lib/token/stream-parser.js:430:12)
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:445:17
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:170:9
>     at Parser.awaitData (node_modules/tedious/lib/token/stream-parser.js:144:9)
>     at Parser.readUInt8 (node_modules/tedious/lib/token/stream-parser.js:167:12)
>     at Parser.readBVarChar (node_modules/tedious/lib/token/stream-parser.js:444:12)
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/infoerror-token-parser.js:11:22
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:446:11
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:433:9
>     at Parser.awaitData (node_modules/tedious/lib/token/stream-parser.js:144:9)
>     at Parser.readBuffer (node_modules/tedious/lib/token/stream-parser.js:430:12)
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:445:17
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:170:9
>     at Parser.awaitData (node_modules/tedious/lib/token/stream-parser.js:144:9)
>     at Parser.readUInt8 (node_modules/tedious/lib/token/stream-parser.js:167:12)
>     at Parser.readBVarChar (node_modules/tedious/lib/token/stream-parser.js:444:12)
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/infoerror-token-parser.js:10:20
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:460:11
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:433:9
>     at Parser.awaitData (node_modules/tedious/lib/token/stream-parser.js:144:9)
>     at Parser.readBuffer (node_modules/tedious/lib/token/stream-parser.js:430:12)
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:459:17
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:203:9
>     at Parser.awaitData (node_modules/tedious/lib/token/stream-parser.js:144:9)
>     at Parser.readUInt16LE (node_modules/tedious/lib/token/stream-parser.js:200:12)
>     at Parser.readUsVarChar (node_modules/tedious/lib/token/stream-parser.js:458:12)
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/infoerror-token-parser.js:9:18
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:170:9
>     at Parser.awaitData (node_modules/tedious/lib/token/stream-parser.js:144:9)
>     at Parser.readUInt8 (node_modules/tedious/lib/token/stream-parser.js:167:12)
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/infoerror-token-parser.js:8:16
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:170:9
>     at Parser.awaitData (node_modules/tedious/lib/token/stream-parser.js:144:9)
>     at Parser.readUInt8 (node_modules/tedious/lib/token/stream-parser.js:167:12)
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/infoerror-token-parser.js:7:14
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:247:9
>     at Parser.awaitData (node_modules/tedious/lib/token/stream-parser.js:144:9)
>     at Parser.readUInt32LE (node_modules/tedious/lib/token/stream-parser.js:244:12)
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/infoerror-token-parser.js:6:12
>     at /Users/alexandertunick/WebstormProjects/bal_mocha-tests/node_modules/tedious/lib/token/stream-parser.js:203:9
>     at Parser.awaitData (node_modules/tedious/lib/token/stream-parser.js:144:9)
>     at Parser.readUInt16LE (node_modules/tedious/lib/token/stream-parser.js:200:12)
>     at parseToken (node_modules/tedious/lib/token/infoerror-token-parser.js:5:10)
>     at Object.errorParser (node_modules/tedious/lib/token/infoerror-token-parser.js:43:3)
>     at Parser.parseTokens (node_modules/tedious/lib/token/stream-parser.js:120:29)
>     at Parser._transform (node_modules/tedious/lib/token/stream-parser.js:95:14)
>     at Parser.Transform._read (node_modules/readable-stream/lib/_stream_transform.js:184:10)
>     at Parser.Transform._write (node_modules/readable-stream/lib/_stream_transform.js:172:83)
>     at doWrite (node_modules/readable-stream/lib/_stream_writable.js:428:64)
>     at writeOrBuffer (node_modules/readable-stream/lib/_stream_writable.js:417:5)
>     at Parser.Writable.write (node_modules/readable-stream/lib/_stream_writable.js:334:11)
>     at Parser.addBuffer (node_modules/tedious/lib/token/token-stream-parser.js:69:26)
>     at Connection.sendDataToTokenStreamParser (node_modules/tedious/lib/connection.js:1179:37)
>     at Connection.data (node_modules/tedious/lib/connection.js:1924:24)
>     at Connection.dispatchEvent (node_modules/tedious/lib/connection.js:1012:38)
>     at MessageIO.<anonymous> (node_modules/tedious/lib/connection.js:888:18)
>     at Message.<anonymous> (node_modules/tedious/lib/message-io.js:57:15)
>     at addChunk (node_modules/readable-stream/lib/_stream_readable.js:291:12)
>     at readableAddChunk (node_modules/readable-stream/lib/_stream_readable.js:278:11)
>     at Message.Readable.push (node_modules/readable-stream/lib/_stream_readable.js:245:10)
>     at Message.Transform.push (node_modules/readable-stream/lib/_stream_transform.js:148:32)
>     at Message.afterTransform (node_modules/readable-stream/lib/_stream_transform.js:91:10)
>     at Message.PassThrough._transform (node_modules/readable-stream/lib/_stream_passthrough.js:46:3)
>     at Message.Transform._read (node_modules/readable-stream/lib/_stream_transform.js:184:10)
>     at Message.Transform._write (node_modules/readable-stream/lib/_stream_transform.js:172:83)
>     at doWrite (node_modules/readable-stream/lib/_stream_writable.js:428:64)
>     at writeOrBuffer (node_modules/readable-stream/lib/_stream_writable.js:417:5)
>     at Message.Writable.write (node_modules/readable-stream/lib/_stream_writable.js:334:11)
>     at Message.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:585:51)
>     at IncomingMessageStream.processBufferedData (node_modules/tedious/lib/incoming-message-stream.js:87:21)
>     at IncomingMessageStream._transform (node_modules/tedious/lib/incoming-message-stream.js:113:12)
>     at IncomingMessageStream.Transform._read (node_modules/readable-stream/lib/_stream_transform.js:184:10)
>     at IncomingMessageStream.Transform._write (node_modules/readable-stream/lib/_stream_transform.js:172:83)
>     at doWrite (node_modules/readable-stream/lib/_stream_writable.js:428:64)
>     at writeOrBuffer (node_modules/readable-stream/lib/_stream_writable.js:417:5)
>     at IncomingMessageStream.Writable.write (node_modules/readable-stream/lib/_stream_writable.js:334:11)
>     at Socket.ondata (_stream_readable.js:666:20)
>     at addChunk (_stream_readable.js:283:12)
>     at readableAddChunk (_stream_readable.js:264:11)
>     at Socket.Readable.push (_stream_readable.js:219:10)
>     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)

**Comment by MichaelSun90** [comment]
Hi @AlexanderTunick 
The query that you provide is too complicated for me to mimic on my side, so I tried a simpler version. 
If I directly call 'select CONVERT(INT, '0.6')' from SQL server management studio, and I got the exact same error on my side. In this case, I think SQL server does not accept convert varchar to an int. I think somewhere from your SQL query triggered a SQL server CONVERT() function call which returned an error like this. 

If you can find a simpler example with the database schema and data which triggered the same error and sends it to me. I could again on my side, see if I can find anything from tedious.

**Comment by AlexanderTunick** [comment]
@MichaelSun90 thank you for your response, I currently just replaced the query using just string instead of query builder "knex" for this test and it works. Don't have much time to figure out with it at the moment. Thank you anyway.
