### ISSUE TITLE
The test with UDL was successful, but I couldn't provide a connection from tedious.

### ISSUE THREAD

**Issue by ridvann** [tediousjs/tedious#892]
Hello,

I've connected with UDL.

<a href="https://ibb.co/C98KYnL"><img src="https://i.ibb.co/C98KYnL/Screenshot-2019-04-16-14-31-28.png" alt="Screenshot-2019-04-16-14-31-28" border="0"></a>

But I couldn't connect with Tedious.

SS:
<a href="https://ibb.co/S7dnsby"><img src="https://i.ibb.co/S7dnsby/Screenshot-2019-04-16-14-31-49.png" alt="Screenshot-2019-04-16-14-31-49" border="0"></a>

Error Code:
```connected to 192.168.1.5:1433
State change: Connecting -> SentPrelogin
State change: SentPrelogin -> SentLogin7WithStandardLogin
BağlanmaConnectionError: Login failed for user 'manimapi'.
State change: SentLogin7WithStandardLogin -> Final
connection to 192.168.1.5:1433 closed
State is already Final
```

I run the code as follows,

```Javascript
var Connection = require('tedious').Connection;
var Request = require('tedious').Request;

var config = {
  server: '192.168.1.5',
  authentication: {
    type: 'default',
    options: {
      userName: 'manimapi',
      password: '12qwaszx_'
    }
  }
  
  ,options: {
    database: 'SISTEST',
    encrypt: false // for Azure users
  }
  
};

var connection = new Connection(config);

connection.on('connect', function(err) {
    // If no error, then good to go...
    console.log("Bağlanma" +err);
    //executeStatement();
  }
);

connection.on('debug', function(text) {
    console.log(text);
  }
);

function executeStatement() {
  request = new Request("select * from TEST", function(err, rowCount) {
    if (err) {
      console.log(err);
    } else {
      console.log(rowCount + ' rows');
    }

    connection.close();
  });

  request.on('row', function(columns) {
    columns.forEach(function(column) {
      if (column.value === null) {
        console.log('NULL');
      } else {
        console.log(column.value);
      }
    });
  });

  request.on('done', function(rowCount, more) {
    console.log(rowCount + ' rows returned');
  });

  // In SQL Server 2000 you may need: connection.execSqlBatch(request);
  connection.execSql(request);
}
```

System Information:
OS: Windows Server 2012 R2 Standart
Nodejs: 6.11.3 x86

Why is the connection not available?

Do you have a comment?

Thanks

**Comment by ridvann** [comment]
I have limited access to the database I tested. But I got a log from system admin.

"Reason: failed open the explicity specified database "XXXX". Client: XXX.XXX.XXX.XX"

I couldn't solve the problem.

**Comment by MichaelSun90** [comment]
Hi @ridvann, you tedious side connection configuration looks correct to me. Could you double check the user that you are using have access to the specific database? From your screenshot, I see that when you test the connection using UDL, you do not provide a database name. This is the only difference I can identify from these to connection methods.

**Comment by ridvann** [comment]
Hi @MichaelSun90,

First of all, thank you for your answer. I'm starting to think it's from user permissions. 
The UDL provides a successful connection, even though the database is specific. I guess there is another situation.
If I solve the problem, I'll add the solution here to help other users.

Thanks

**Comment by ridvann** [comment]
Hi,

I solved the problem. The problem is that the database name that was reported to us was incorrect. It's not a technical mistake, so it's a human error :)

In addition, I have a suggestion that can be added in an additional field where the description of the error exists.

I kept you busy. Excuse me for that.

Thanks

**Comment by MichaelSun90** [comment]
No problem, glad the issue has been resolved.
