### ISSUE TITLE
Big Int gets changed for bulkLoad.addRow

### ISSUE THREAD

**Issue by jianingliu** [tediousjs/tedious#893]
Hi there,

I got this problem while working with very big integers. The testing big integer is "2567435346112343576". It was stored always as a string, and the TediousType I used is BigInt. Then I used the bulkLoad.addRow to bulk insert my data into the database. When I checked the db, it was stored as bigint but the value was changed to 2567435346112343552.

Then I tried to insert the data row by row, and got the following error when adding parameter to the query:
Validation failed for parameter XXXX. Value must be between -9007199254740991 and 9007199254740991, inclusive. For bigger numbers, use VarChar type.

I guess we still aren't able to work around the number limitation of javascript for db inserting?
If that is the case, might need to consider making the bulkload throw an error as well.

**Comment by MichaelSun90** [comment]
Hi @jianingliu 
Unfortunately, the number of limitation of javascript is still a thing. Just verified that why the bulk insert has a different behavior with a single insert statement. On the tedious side, the input validation for writeParameterData under begin type could be improved to throw a similar error as "Validation failed for parameter XXXX. Value must be between -9007199254740991 and 9007199254740991, inclusive. For bigger numbers, use VarChar type." in case of an oversized input integer.

**Comment by IanChokS** [comment]
Hi @jianingliu, as @MichaelSun90 stated above, there's a [number limitation in JavaScript](https://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin). A work around is you can try to convert the number you want to insert into the db as a string. Tedious has a dependency called [jsbi](https://www.npmjs.com/package/jsbi) which can help handle BigInt values. Hopefully this helps. I'll close this issue for now, if the solution provided doesn't work feel free to repoen this issue.
