### ISSUE TITLE
Cannot able to use in function with api

### ISSUE THREAD

**Issue by PrasannaBrabourame** [tediousjs/tedious#897]
Cannot able to get the result on express api call.
```
let callSP = (bookcode) => {
    return new Promise((resolve, reject) => {
        connection.on('connect', (err) => {
            if (err) {
                console.log('connection error:', err);
                reject(err);
            }
            let output = { o_retKey: null, o_errMsg: null, o_retReceiptInfo: null };
            let request = new Request(
                'storedprocedure1',
                (err, rowCount, rows) => {
                    if (err) {
                        console.log('request error:', err);
                        reject(err);
                    } else {
                        console.log(rowCount + " rows(s) returned.", rows);
                        resolve(output); 
                    }
                });
            request.addOutputParameter("param1", TYPES.VarChar, '123');
            request.on('returnValue', (parameterName, value) => {
                console.log('request on returnValue: ' + parameterName + ' = ' + value);
                output[parameterName] = value;
            });
            request.on('doneProc', () => {
                console.log('request doneProc', output);
            });
            connection.execSql(request);
        });
    });
}

app.get('/index', function (req, res) {
    let value = await callSP('JATS_A_201203');
    console.log(value)
})

```

**Comment by MichaelSun90** [comment]
Hi @PrasannaBrabourame, can you provide the error message or the script behavior that you currently get?  From the script that you provide here, I did not find any suspicious place. On the other hand, if you have any reproducing step, that will be extremely helpful.

**Comment by PrasannaBrabourame** [comment]
I am getting the result as undefined and when i keep the break point near resolve. It does not trigger

**Comment by MichaelSun90** [comment]
Hi @PrasannaBrabourame, Do you mean that the 'rows' from the call back function is undefined, and resolve(output) is not triggered? If this is the case, can you try set config.options.rowCollectionOnRequestCompletion to true, then test it again.  There are some other details about these parameters, you can check the tedious Github I/O page: http://tediousjs.github.io/tedious/api-request.html

**Comment by PrasannaBrabourame** [comment]
even after trying this. the same error occurs. @MichaelSun90  connection.on is not triggering on api connection

**Comment by MichaelSun90** [comment]
If connection.on is not triggered, it could be caused by the connection configuration. Can you provide the connection config that you use for creating the connection?

**Comment by PrasannaBrabourame** [comment]
I have used the connect config globally " var connection = new Connection(config);" after using on the particular function it is working perfectly. Thanks for your kind help.
