### ISSUE TITLE
Error handling in bulkLoad

### ISSUE THREAD

**Issue by gsamal** [tediousjs/tedious#900]
I have a question on internal handling of bulk load. 
Does the whole operation, when we execute `execBulkLoad` run in transaction? What will happen if for any reason, some records get failed?

Thanks!

**Comment by MichaelSun90** [comment]
Hi @gsamal, I just did a quick test. The current Tedious logic will catch the error and emit an error event, then the corresponding socket error listener will react to this error event, and throw this error. This transfers the program state to the final state which cleans up the process and closes the connection. Seems it will not continue running the rest of the batch query.

**Comment by gsamal** [comment]
Hi @MichaelSun90, I was hoping there would be a transaction involved. Never really like the fact of partial committing a few rows. Thanks for the clarification though.
