### ISSUE TITLE
when database:"中文"//chinese, login fail

### ISSUE THREAD

**Issue by zhangtingwz** [tediousjs/tedious#902]
```
var connection = new Connection({
    authentication: {
        type: 'default',
        options: {
            userName: 'sa', // it`s right
            password: '**********' // It`s right
        }
    },
    server: '*********',               //it`s right
    options: {
        **database: 'VoluntaryReporting',**          //where it`s chinese like'中文' or other chinese
    }
});
```
excuse me，
my english is pool，
today ，i meet a new problem 
when i set database chinese some like
database:"中文", 
and
my sqlserver really have a database that name is "中文"
but when i use  database: '中文'  tell me connection error:elogin error ,sa can`t not login, 
please may be change the error message thank you ,very much , i find this solution one day

**Comment by MichaelSun90** [comment]
Hi @zhangtingwz,  There are two things that you could check for this issue:
1. which version of Tedious version that you are using. I tested your connection set up on tedious 6.1.1, and I am able to connect. Therefore, it is possible that you are on an earlier version which causes the issue.
This is my set up: { 
  server: "localhost",
  authentication: {
    type: "default",
    options: {
      userName: "sa",
      password: "*************",
    }
  },
  options: {  
    database: '中文',
  }
}; 

2. You can also check whether the database '中文' is created under the login sa. If it is not, then user sa may not able to access the database which causes the issue. 
This is how the database looks like on my side: 
![screen shoot](https://user-images.githubusercontent.com/47126816/58208507-b8931c00-7c99-11e9-8dc7-43edd9b43e30.png)

**Comment by zhangtingwz** [comment]
Hi,@MichaelSun90,
Nice to meet you,
I use npm install Tedious,
Tedious should be 6.1.1, 
then i use change my database as "VoluntaryReporting",
this is my option:
`
var connection = new Connection({
    authentication: {
        type: 'default',
        options: {
            userName: 'sa', // it`s right
            password: '**********' // It`s right
        }
    },
    server: '*********',               //it`s right
    options: {
        database: 'VoluntaryReporting'          
    }
});
`
it`s can be use ,
then  even i delete database,my sa is still can be login ,but  when my database:"仙居审批" can`t login

![image](https://user-images.githubusercontent.com/26179617/58222000-36f9c780-7d47-11e9-83c1-9052b01a272c.png)
![image](https://user-images.githubusercontent.com/26179617/58222010-3eb96c00-7d47-11e9-9f53-857b64dea46e.png)
![image](https://user-images.githubusercontent.com/26179617/58222019-44af4d00-7d47-11e9-8eb0-17d31440fcfc.png)

**Comment by zhangtingwz** [comment]
Hi,@MichaelSun90,
i find why it happen ，because i save js as ANSI，not utf-8 ，it`s my way ,sorry
