### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by Steexyz** [tediousjs/tedious#917]
Hi there,

I've been trying to figure this out for days, I'm still a newbie but I have an Express server trying to display data from a query in my database using Tedious. However, I tryied many things but I'm alway facing this error "cb is not a function". I know it's about the callBack but I really can't figure out. It's a React app with an Express Backend. My connection to the database is working fine, I confirmed it from server.js. Express is also working with the Hello route.

**server.js**

//Définition des modules
const express = require("express"); 
const bodyParser = require('body-parser');
//const ConnectionPool = require ('./serverComponents/connection')
const toDayTickets = require('./serverComponents/toDayTickets')

//On définit notre objet express nommé app
const app = express();
//On se connecte à SQL

/*ConnectionPool.acquire(function(err,connection){
    if (err) {
        console.error(err);        
        return;
    } 
    else{
        console.log('Connected to SQL')
    }
})*/
//Get toDay Tickets
app.get('/api/hello', (req, res) => {
    res.send({ express: 'Have a good day' });
  });
  
app.get('/api/toDayTickets', (res) => {
    var query = "select count(*) from billet"
    toDayTickets(query,function(response){
        res.send(response);
    })
  });
  
//Body Parser
var urlencodedParser = bodyParser.urlencoded({
    extended: true
});
app.use(urlencodedParser);
app.use(bodyParser.json());

//Définition des CORS
app.use(function (req, res, next) {
    res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
    res.setHeader('Access-Control-Allow-Credentials', true);
    next();
});

//Définition et mise en place du port d'écoute
var port = 8000;
app.listen(port, () => console.log(`Listening on port ${port}`));

**app.js**
import React from 'react';
import './App.css';
import { ToDayTicket } from './components/toDayTicket'

export class App extends React.Component {
  constructor(props){
    super(props)
    this.state = {
      numberTicket : '0',
      response : ''
    }
  }
  componentDidMount() {
    
    //GetTicketNumbers
    this.displayNewTicket()
      .then(res => this.setState({ numberTicket: '3'}))
      .catch(err => console.log(err));
     //TEST API 
    this.callApi()
      .then(res => this.setState({ response: res.express }))
      .catch(err => console.log(err));
      /*alert('Component did mount')*/

  }
  componentWillUnmount() {
    //alert('Will unmount')
  }
  componentWillMount() {
    //alert('Will mount')
  }
  callApi = async () => {

    const response = await fetch('/api/hello');
    const body = await response.json();
    if (response.status !== 200) throw Error(body.message);
    return body;
    
  }

  displayNewTicket = async() => {
    const response = await fetch('/api/toDayTickets')
    const body = await response.text();
    if (response.status !== 200) throw Error(body.message);
    return body;
    
   
  }

  render() {
    return (
      <div className="App">
       <header className="App-header">   
          <p>{this.state.response}</p>
          <ToDayTicket numberTicket={this.state.numberTicket}/>
        </header>       
      </div>
    );
  }  
  }

**toDayTicket.js**

var ConnectionPool = require('./connection')
var Request = require('tedious').Request;

function toDayTickets(query,callback) { 
  
  ConnectionPool.acquire(function (err,connection) {     
    if (err) {
      console.error(err)     
      return;
  } 
   var response = ''
   var request = new Request(query,function(err) {
      if (err) {            
        console.error(err)
      }
      });      

      request.on('row', function(columns) {
      columns.forEach(function(column) {
      response = column.value
      callback(null,response);   
      });
    });
  
    console.log('Debug Debug')
    connection.execSql(request);   
  })

}

module.exports = toDayTickets;

**Fullstack**
TypeError: cb is not a function
at Object.writeParameterData (D:\Projects\Statistics\node_modules\tedious\lib\data-types\nvarchar.js:69:5)
at new RpcRequestPayload (D:\Projects\Statistics\node_modules\tedious-connection-pool\node_modules\tedious\lib\rpcrequest-payload.js:95:12)
at Connection.execSql (D:\Projects\Statistics\node_modules\tedious-connection-pool\node_modules\tedious\lib\connection.js:883:58)
at Object.callback (D:\Projects\Statistics\serverComponents\toDayTickets.js:27:16)
at ConnectionPool.setUsed (D:\Projects\Statistics\node_modules\tedious-connection-pool\lib\connection-pool.js:216:12)
at ConnectionPool.acquire (D:\Projects\Statistics\node_modules\tedious-connection-pool\lib\connection-pool.js:201:17)
at toDayTickets (D:\Projects\Statistics\serverComponents\toDayTickets.js:7:18)
at app.get (D:\Projects\Statistics\server.js:27:5)
at Layer.handle [as handle_request] (D:\Projects\Statistics\node_modules\express\lib\router\layer.js:95:5)
at next (D:\Projects\Statistics\node_modules\express\lib\router\route.js:137:13)

**Comment by MichaelSun90** [comment]
Hi @Steexyz, for the 'cb' function issue, there is a change under PR #845 that has been recently merged into master which introduce a 'cb' function for writeParameterData.  To fix this, you could just pull the latest master branch changes to your local should resolve this.

**Comment by Steexyz** [comment]
Well, still no changes. I believe it was already up to date.

**Comment by MichaelSun90** [comment]
Oh, Looks like that tedious-connection-pool has not updated the way that they using the writeParameterData. @Steexyz, can you try to add an empty call back to the places that tedious-connection-pool calls the function? 
For example: 
replace type.writeParameterData(buffer, param, options);
with: type.writeParameterData(buffer, param, options, ()=>{}); 
see if this fix the issue. 

I think you need to do this to all places that call the writeParamerterData inside tedious-connection-pool. Also, if this fix works, I think you may want to also post an issue on tedious-connection-pool to let them know that this function behavior has changed, so they can release a new version.

**Comment by Steexyz** [comment]
Well, I don't find a writeParameterData in connection-pool.js... It seems it didn't receive an update in years. I might just stop using tedious-connection-pool..

**Comment by MichaelSun90** [comment]
Hi @Steexyz , sorry that I may not make this one clear. From your stack trace, there is a line actually marked a function call to the writeParameterData : 
"at new RpcRequestPayload (D:\Projects\Statistics\node_modules\tedious-connection-pool\node_modules\tedious\lib\rpcrequest-payload.js:95:12)"

I think you can try to look into rpcrequest-payload.js line 95 for the function call of writeParameterData
See if you can find it.

**Comment by Steexyz** [comment]
Hmm, I've found : 
   type.writeParameterData(buffer, param, this.options, () => {
      //cb();
    });
I commented it but no changes. this is on line 107.

On line 95, I can only find : 

   if (type.hasPrecision) {
      if (parameter.precision) {
        param.precision = parameter.precision;
      } else if (type.resolvePrecision) {
        param.precision = type.resolvePrecision(parameter);
      } //This is line 95


    }
FULL CONTENT OF FILE : 
"use strict";

const WritableTrackingBuffer = require('./tracking-buffer/writable-tracking-buffer');

const writeAllHeaders = require('./all-headers').writeToTrackingBuffer; // const OPTION = {
//   WITH_RECOMPILE: 0x01,
//   NO_METADATA: 0x02,
//   REUSE_METADATA: 0x04
// };


const STATUS = {
  BY_REF_VALUE: 0x01,
  DEFAULT_VALUE: 0x02
};
/*
  s2.2.6.5
 */

module.exports = class RpcRequestPayload {
  constructor(request, txnDescriptor, options) {
    this.request = request;
    this.procedure = this.request.sqlTextOrProcedure;
    this.options = options;
    this.txnDescriptor = txnDescriptor;
  }

  getData(cb) {
    const buffer = new WritableTrackingBuffer(500);

    if (this.options.tdsVersion >= '7_2') {
      const outstandingRequestCount = 1;
      writeAllHeaders(buffer, this.txnDescriptor, outstandingRequestCount);
    }

    if (typeof this.procedure === 'string') {
      buffer.writeUsVarchar(this.procedure);
    } else {
      buffer.writeUShort(0xFFFF);
      buffer.writeUShort(this.procedure);
    }

    const optionFlags = 0;
    buffer.writeUInt16LE(optionFlags);
    const parameters = this.request.parameters;

    const writeNext = i => {
      if (i >= parameters.length) {
        cb(buffer.data);
        return;
      }

      this._writeParameterData(parameters[i], buffer, () => {
        setImmediate(() => {
          writeNext(i + 1);
        });
      });
    };

    writeNext(0);
  }

  toString(indent) {
    indent || (indent = '');
    return indent + ('RPC Request - ' + this.procedure);
  }

  _writeParameterData(parameter, buffer, cb) {
    buffer.writeBVarchar('@' + parameter.name);
    let statusFlags = 0;

    if (parameter.output) {
      statusFlags |= STATUS.BY_REF_VALUE;
    }

    buffer.writeUInt8(statusFlags);
    const param = {
      value: parameter.value
    };
    const type = parameter.type;

    if ((type.id & 0x30) === 0x20) {
      if (parameter.length) {
        param.length = parameter.length;
      } else if (type.resolveLength) {
        param.length = type.resolveLength(parameter);
      }
    }

    if (type.hasPrecision) {
      if (parameter.precision) {
        param.precision = parameter.precision;
      } else if (type.resolvePrecision) {
        param.precision = type.resolvePrecision(parameter);
      }
    }

    if (type.hasScale) {
      if (parameter.scale) {
        param.scale = parameter.scale;
      } else if (type.resolveScale) {
        param.scale = type.resolveScale(parameter);
      }
    }

    type.writeTypeInfo(buffer, param, this.options);
    type.writeParameterData(buffer, param, this.options, () => {
      //cb();
    });
  }

};

**Comment by Steexyz** [comment]
Nevermind, I figured it out, wasn't in the right file.

It's working now!

TYVM

**Comment by MichaelSun90** [comment]
Hi @Steexyz, Good to know that you figured it out.  Is that ok to close this issue now?

**Comment by Steexyz** [comment]
Yes, you can close! It was really the function from the module within Tedious Connection Pool that was lacking the empty CallBack.

**Comment by notestyle** [comment]
Why didn't you fix this issue on the master branch?
