### ISSUE TITLE
Error running tests when cloning from master

### ISSUE THREAD

**Issue by bengawel** [tediousjs/tedious#943]
Read the pull_request_template.md and ran the tests specified by step 3.
Received an error that there was no file '~/.tedious/test-connection.json'

I could not find anything in the documentation stating this was a required file and could not find anything in the documentation specifying the format of this file.

**Comment by IanChokS** [comment]
Hi @bengawel,

You need the file located in your ~/users/_your_accnt_/.tedious.test-connection.json if you have windows. The JSON should look like this:

```
{
    "config": {
        "server": "localhost",
        "authentication": {
            "type": "default",
            "options": {
                "userName": "your_username",
                "password": "your_password"
            }
        },
        "options": {
            "port": 1433,
            "database": "master"
        }
    }
}
```
Hope this helps!

**Comment by IanChokS** [comment]
> I could not find anything in the documentation stating this was a required file and could not find anything in the documentation specifying the format of this file.

I believe I this specification somewhere in a PR... I'll take a look

**Comment by bengawel** [comment]
Thanks for your help and the quick response!  Unfortunately I'm still not able to get it to work. I created the file and it exists in the correct path but it is not able to read the contents of the file.

It would be nice if this file existed under the test directory so that the path to the file would always be static and the format would be defined.

**Comment by bengawel** [comment]
Actually I just got the test to read the file.  I'm not able pass all of the integrations though, I'm assuming it has something to do with the instance of sql server I have running.  I'm not really sure how to move forward from here, is there any documentation on a recommended setup for sql server to test on?  Or maybe even like a docker image of an instance of sql server or something?

**Comment by IanChok** [comment]
What kind of errors are you getting? A stack trace can be of great help. Also, which integration tests / tests are failing? If you're unable to connect to the sql server, then check through your Microsft SQL Server Management Studio, you can try to [make sure that TCP IP is enabled ](https://www.habaneroconsulting.com/stories/insights/2015/tcpip-is-disabled-by-default-in-microsoft-sql-server-2014) and that [You have the correct port number in your configuration ](https://sqlandme.com/2013/05/01/sql-server-finding-tcp-port-number-sql-instance-is-listening-on/) to check if the server is reachable.

**Comment by bengawel** [comment]
It was the instance of sql server I had running. I ended up using a docker image, and got the integration tests to work. Thanks again for your help!  

Two unit tests are failing related to day light savings, is this expected?

**Comment by IanChokS** [comment]
That's great to hear! Yes the two daylight savings are expected to fail locally due to changes intentionally made in V8: v8/v8@dbdede0 (#767).
