### ISSUE TITLE
Cannot connect to azure database with active directory on aks

### ISSUE THREAD

**Issue by whs-dot-hk** [tediousjs/tedious#946]
I can connect using localhost computer but not aks

aks
connected to [azure-mssql-account].database.windows.net:1433
State change: Connecting -> SentPrelogin
State change: SentPrelogin -> SentTLSSSLNegotiation
TLS negotiated (ECDHE-RSA-AES256-GCM-SHA384, TLSv1.2)
State change: SentTLSSSLNegotiation -> SentLogin7Withfedauth
State change: SentLogin7Withfedauth -> ReRouting
Packet size changed from 4096 to 4096
connection to [azure-mssql-account].database.windows.net:1433 closed
Rerouting to [dns-name].tr9.eastasia1-a.worker.database.windows.net:11129
State change: ReRouting -> Connecting
connected to [azure-mssql-account].database.windows.net:1433
State change: Connecting -> SentPrelogin
State change: SentPrelogin -> SentTLSSSLNegotiation
TLS negotiated (ECDHE-RSA-AES256-GCM-SHA384, TLSv1.2)
State change: SentTLSSSLNegotiation -> SentLogin7Withfedauth
State change: SentLogin7Withfedauth -> Final
connection to [azure-mssql-account].database.windows.net:1433 closed

local
connected to [azure-mssql-account].database.windows.net:1433
State change: Connecting -> SentPrelogin
State change: SentPrelogin -> SentTLSSSLNegotiation
TLS negotiated (ECDHE-RSA-AES256-GCM-SHA384, TLSv1.2)
State change: SentTLSSSLNegotiation -> SentLogin7Withfedauth
State change: SentLogin7Withfedauth -> SentLogin7WithStandardLogin
Packet size changed from 4096 to 4096
State change: SentLogin7WithStandardLogin -> LoggedInSendingInitialSql
State change: LoggedInSendingInitialSql -> LoggedIn

please help

**Comment by IanChokS** [comment]
Hi @whs-dot-hk,

What's your configuration for connecting?

**Comment by whs-dot-hk** [comment]
Hi, here is the code I used

```
const { Connection } = require('tedious');

const config = {
  server: '[azure-mssql-account].database.windows.net',
  authentication: {
    type: 'azure-active-directory-password',
    options: {
      userName: '<active directory user account>',
      password: '<user account password>'
    }
  },
  options: {
    database: '<database name>',
    debug: {
      token: true,
    },
  }
}

const connection = new Connection(config);

connection.on('debug', (message) => console.log(message))
```

**Comment by IanChokS** [comment]
@whs-dot-hk What version of tedious are you currently using? The current version should be v6.3.0

**Comment by whs-dot-hk** [comment]
Hi, looks like this is the code I ran into

https://github.com/Azure/ms-rest-nodeauth/blob/b9f236c3b2dfc66f9d6a9d63a678335f736cc77c/lib/login.ts#L144


The promise resolve in local but reject in aks

**Comment by whs-dot-hk** [comment]
Hi, it was fixed by configuring active directory's firewall

Sorry for the inconvenient

**Comment by IanChokS** [comment]
Hi @whs-dot-hk I'm going to close this issue, feel free to open it again if you encounter the same problem!
