### ISSUE TITLE
TYPES.DateTimeOffset not working as expected

### ISSUE THREAD

**Issue by devdeer-alex** [tediousjs/tedious#965]
I want to insert some rows using bulk. Here is my sample code:

	const timeStamp = '2019-08-02T14:40:21+02:00';
	const config = {
        authentication: {
            options: {
                userName: 'USER',
                password: 'PASS'
            },
            type: 'default'
        },
        server: 'SQLSERVER-ADDRESS',
        options: {
            database: 'DBNAME', 
            encrypt: true,
            useUTC: true
        }
    }
	connection.on('connect', function(err) {
        if (err) {   
            // error during connection establishment             
            context.done(err, null);
        } else {
            const bulkOptions = { 
                keepNulls: true 
            };
            let bulkLoad = connection.newBulkLoad('Orders', bulkOptions, function (err, rowCount) {
                if (err) {
                    log.error(err);                    
                } else {
                    log.info(`Inserted ${rowCount} rows.`);                    
                }
            });
            bulkLoad.addColumn('OrderDate', Types.DateTimeOffset, { scale: 7, nullable: true });
            bulkLoad.addRow({ 	
                OrderDate: new Date(Date.parse(timeStamp)),	
            });
            connection.execBulkLoad(bulkLoad);
        }
	});

The result in SQL server is:

    2019-08-02 12:40:21.0000000 +00:00

This is technically correct but I expected it to be:

    2019-08-02 14:40:21.0000000 +02:00

That is the reason I used `DateTimeOffset` on SQL Server in the first place. Currently I loose the timezone information in SQL Server.

**Comment by MichaelSun90** [comment]
Hi @devdeer-alex ,  you can try to insert the date not as a DateTimeOffset, but as a Varchar type.  Otherwise, on the SQL server-side, it will calculate the time based on your local timezone information. 

You can try to replace your original code with this, and give it a try. See if this helps. 

bulkLoad.addColumn('c1', TYPES.VarChar, { scale: 7, nullable: true });
bulkLoad.addRow({ 	
        c1: timeStamp,	
      });

**Comment by devdeer-alex** [comment]
Hi @MichaelSun90 , thanks for suggesting this. It works if I change my parameter-value to

    2019-08-02 12:30:21 +02:00

as T-SQL expects it.
