### ISSUE TITLE
Request only return latest error message

### ISSUE THREAD

**Issue by irgijs** [tediousjs/tedious#968]
When executing an SQL script which results in multiple errors, tedious only registers the last error on the Request object. This is inconvenient, especially if the last errors refers to the previous error.

**Example**
```
create type test_type as table ( id int, primary key (code) );
- OUTPUT SQL MANAGEMENT STUDIO
-- Msg 1911, Level 16, State 1, Line 1
-- Column name 'code' does not exist in the target table or view.
-- Msg 1750, Level 16, State 0, Line 1
-- Could not create constraint or index. See previous errors.
- OUTPUT TEDIOUS REQUEST
-- RequestError: Could not create constraint or index. See previous errors.
```

The error message event is emitted on the connection for both messages, so this allows us to retrieve all error messages. However, it doesn't feel like this is the correct approach to achieve this as it feels a bit dirty.

The abovementoined can be reproduced by the test script attached.
[tedious-multiple-error-messages.zip](https://github.com/tediousjs/tedious/files/3609836/tedious-multiple-error-messages.zip)

**Comment by IanChokS** [comment]
Hi @irgijs, just to clarify, are you saying that all SQL err messages are emitted for the Connection object, but only the last SQL err message is emitted in the Request object?

**Comment by irgijs** [comment]
@IanChokS Yes, that is indeed what I meant to say.

**Comment by IanChokS** [comment]
@arthurschreiber what do you think about this? I was thinking to add an additional message in the Request error message pointing to the connection.errorMessage for further stack trace for error messages?

**Comment by irgijs** [comment]
@IanChokS Do you have a status update for me? :)

**Comment by arthurschreiber** [comment]
@irgijs Would be adding `errorMessage`/`infoMessage` events to `Request` good enough for you? Then we could emit these events both on the `Connection` as well as on the `Request` object.

**Comment by irgijs** [comment]
@arthurschreiber If the events are still committed software implementing Tedious is responsible for collecting these errors. Isn't it better to add an `errors` array to the `Request` object, containing all the errors raised during the requests? Then we can easily display all the errors that occurred.

**Comment by jeremy-w** [comment]
i encountered this working with knex migrations, where i get told in the error to read a previous error message, but i don't get to see the previous error message.

## sketch of suggested change
the immediate issue in that case looks to be the clobbering of the (singular) request.error when an error gets parsed. a "RequestMultiError" that collects the messages in order as received and otherwise defers to the child errors for details would present a good interactive developer experience in that context, while still allowing programmatic access to all the underlying errors. pseudocode would be roughly:

```js
newError = …
request.error = request.error
  ? (request.error instanceOf RequestMultiError
     ? request.error.errors.push(error)
     : new RequestMultiError(request.error, newError))
  : newError
```

## workarounds
for my immediate needs, i was previously just snooping with Wireshark, then localized the issue and patched in some logs:

```patch
--- a/lib/connection.js	2021-10-06 08:02:02.000000000 -0400
+++ b/lib/connection.js	2021-10-06 07:54:36.000000000 -0400
@@ -1179,7 +1179,9 @@
             error.serverName = token.serverName;
             error.procName = token.procName;
             error.lineNumber = token.lineNumber;
+            console.log('JWS: prev request.error:', {'request.error': request.error})
             request.error = error;
+            console.log('JWS: TEDIOUS: ERROR:', {error})
           }
         }
       } else {
```

**Comment by jeremy-w** [comment]
TIL of AggregateError. Yes, that would be much better than duplicating it in a custom class. :)
--
Jeremy W. Sherman
http://jeremywsherman.com/

**Comment by MichaelSun90** [comment]
Hi @irgijs and @jeremy-w , We have release the new error handling logic in version14.5. If you want, you can take a look.  Also, there are some associated doc provide under our Git IO page . The details can be checked here #1436. Close this for now, and if anything needed, you can open a new issue.
