### ISSUE TITLE
Inserts into varbinary(max) col with FILESTREAM or reads from that column takes 10's of seconds

### ISSUE THREAD

**Issue by sammaniamsam** [tediousjs/tedious#971]
For some reason, inserts into varbinary(max) col with FILESTREAM or reads from that column takes 10's of seconds with tedious. I took the time to trace the bottle neck in my node application back to tedious. I tested the following query using **roughly two 25MB files**.

`select * from documents where file_extension = 'zip'`

**MSSQL Management Studio**

![Screen Shot 2019-09-18 at 1 49 36 PM](https://user-images.githubusercontent.com/16583147/65177178-d2602800-da1b-11e9-89c6-8bbad31b0818.png)

**Chrome Dev Tools**

![Screen Shot 2019-09-18 at 1 53 16 PM](https://user-images.githubusercontent.com/16583147/65177179-d2602800-da1b-11e9-8206-6c0d19666991.png)

**Code snippet (not complete)**

[tedious-snippet.txt](https://github.com/tediousjs/tedious/files/3636518/tedious-snippet.txt)

**Comment by IanChok** [comment]
Hi @sammaniamsam,

Thanks for pointing this out. I think this may be due to how token parsing is implemented in Tedious, namely there's a lot of asynchronous call backs that take up a lot of memory which becomes more so when using varbinary(max) and perhaps varchar(max) as well. We do have a plan to refactor how things are implemented in Tedious to increase performance coming up in the near future. 

What are your thoughts @arthurschreiber, @MichaelSun90 ?

**Comment by IanChokS** [comment]
Hi @sammaniamsam,

Thanks for pointing this out. I think this may be due to how token parsing is implemented in Tedious, namely there's a lot of asynchronous call backs that take up a lot of memory which becomes more so when using varbinary(max) and perhaps varchar(max) as well. We do have a plan to refactor how things are implemented in Tedious to increase performance coming up in the near future. 

What are your thoughts @arthurschreiber, @MichaelSun90 ?

**Comment by IanChokS** [comment]
Hi @sammaniamsam, I am just curious what version of Tedious are you using that causes this performance bottleneck? #1006

**Comment by sammaniamsam** [comment]
@IanChokS I'm using "^5.0.3"

**Comment by IanChokS** [comment]
Ok after sifting through all of the currently open issues, it's clear that performance blockage is a common problem (e.g., #879, #781,#475,#467, #319). Currently we have on our road map things like implementing Always Encrypted feature, [improved data type validation / conversion](https://github.com/tediousjs/tedious/pull/677), [Pluggable authentication providers](https://github.com/tediousjs/tedious/pull/624), and [refactoring current data types](https://github.com/tediousjs/tedious/issues/678). But based on the issues being raised, it seems like this performance block is the most common barrier people are facing when using tedious. I'm discussing with Arthur and the team on what work needs to be prioritized, so if you feel like improving performance is the biggest change you'd like to see, please leave a like or comment your thoughts about how we should move forward. Any feedback would be of great help! 🙇

**Comment by IanChokS** [comment]
#1037

**Comment by IanChokS** [comment]
Hi @sammaniamsam, we've recently merged #1049 and #1044 that hopefully improves performance. Do you mind if you run your benchmark again against the latest master and let us know if you see the an improve in performance from you end? 

Thanks! 🙇

**Comment by sammaniamsam** [comment]
@IanChokS Absolutely! Thank you guys for taking care of this. I look forward to testing the new improvements.

**Comment by sammaniamsam** [comment]
@IanChokS the results are as follows:

Method | Tedious Version | Number of Files | Size | Time to Execute (ms)
-- | -- | -- | -- | --
Read | ^6.3.0 | 1 | 23.33 MB | 2435.834
Read | ^6.3.0 | 2 | 46.66 MB | 5008.435
Read | ^6.3.0 | 3 | 136.5 KB | 329.727
Insert | ^6.3.0 | 2 | 11.9 MB | 4316.95
Insert | ^6.3.0 | 4 | 59 KB | 42.864
Read | ^8.0.1 | 1 | 23.33 MB | 2694.422
Read | ^8.0.1 | 2 | 46.66 MB | 5329.447
Read | ^8.0.1 | 3 | 136.5 KB | 43.969
Insert | ^8.0.1 | 2 | 11.9 MB | 4514.139
Insert | ^8.0.1 | 4 | 59 KB | 40.855

My **console.time** and **console.timeEnd** functions wrap the places where I'm awaiting my promises.
`	console.time("storeDocumentsInBatches");
	await Promise.all(proms);
	console.timeEnd("storeDocumentsInBatches");
`

Let me know if you'd like specific query examples or DB config info.

**Comment by sammaniamsam** [comment]
@IanChokS The results are in the table below. Let me know if you have any questions.

Method | Tedious Version | Number of Files | Size | Time to Execute (ms)
-- | -- | -- | -- | --
Read | ^6.3.0 | 1 | 23.33 MB | 2435.834
Read | ^6.3.0 | 2 | 46.66 MB | 5008.435
Read | ^6.3.0 | 3 | 136.5 KB | 329.727
Insert | ^6.3.0 | 2 | 11.9 MB | 4316.95
Insert | ^6.3.0 | 4 | 59 KB | 42.864
Read | Latest Master | 1 | 23.33 MB | 2771.478
Read | Latest Master | 2 | 46.66 MB | 4877.394
Read | Latest Master | 3 | 136.5 KB | 93.575
Insert | Latest Master | 2 | 11.9 MB | 2535.267
Insert | Latest Master | 4 | 59 KB | 43.886

**Comment by IanChokS** [comment]
That's looking good! It matches our results for inserts. For e.g, memory usage has dropped by half.
![image](https://user-images.githubusercontent.com/53239257/76124871-7f216800-5fb0-11ea-981d-afa186af0a4c.png)
![image](https://user-images.githubusercontent.com/53239257/76124881-82b4ef00-5fb0-11ea-8431-2a08209ee6b3.png)

We'll definitely be looking to increase read time as well in the future 💪
