### ISSUE TITLE
Empty Server Name During TLS Handshake to Sql Server

### ISSUE THREAD

**Issue by ziwa-msft** [tediousjs/tedious#975]
Hi

My name is Mike and I am part of the Azure SQL connectivity team. I recently noticed that a lot of traffic connecting to Sql with Tedious driver do not have server name specified during the TLS handshake. Upon reading up the code a bit I see that the server name was passed by by "
config.server" in [here](https://github.com/tediousjs/tedious/blob/ff17897a99ba292c47ab7325ae45c8fdcc851f10/src/connection.js).

May I know how this could be achieved from the client side? Can they specify empty server name during handshake and then log with the real server name?

Thanks

**Comment by arthurschreiber** [comment]
Heya 👋 

> I recently noticed that a lot of traffic connecting to Sql with Tedious driver do not have server name specified during the TLS handshake.

That's weird. As you can see in

https://github.com/tediousjs/tedious/blob/26ea6b19418978f22f471e742a07ec98acf49e6a/src/message-io.ts#L66-L74

we're passing the servername to the `tls.connect` method, and I'm assuming this would do the correct thing. 🤷‍♂

Could you elaborate a bit more what is going wrong, and what you're expecting to happen instead? Also, is this an issue somehow? Wouldn't clients be unable connect without specifying the hostname in the TLS handshake?

**Comment by ziwa-msft** [comment]
Hi.

Thanks for the reply! The issue is that during the prelogin phase, the client sends us a client hello message to initiate the handshake, and we notice that some of the hello messages do not contain a server name value. 

This will not cause login failures, as we do not validate the server name from client hello messages. I am asking because we are considering a few improvements that will need the server name passed in from clients, and I am baffled by some of these missing values from Tedious drivers.

It is also happening only on a small percentage of successful logins. I would say less than 1%.

**Comment by ziwa-msft** [comment]
To be more specific on my question: Is it possible for the client to configure their Tedious driver so that then send empty server name during the handshake and passes in the real server name after SSL connection for login?

**Comment by arthurschreiber** [comment]
Heya @ziwa-msft,

I checked how TLS connections were established in earlier versions of `tedious`, and I stumbled upon this:

https://github.com/tediousjs/tedious/blob/c5cb405c027a13ac1bd2d1da9dbbb57b8640b141/src/message-io.js#L83-L110

As you can see there, this code uses `tls.createSecurePair`. This method of establishing a tls connection did not allow providing a servername, and I'd imagine that'd explain what you're seeing. This method was used in older versions up to and including `tedious@2.6.3`, starting with `tedious@2.6.4` we switched to `tls.connect` which does allow specifying a servername.

`tedious@2.6.3` was released in July 2018, which would also explain the low number of requests you're seeing. 👍

**Comment by ziwa-msft** [comment]
This is very helpful! Thanks for pinpointing the issue in the old code!
