### ISSUE TITLE
Migration MSSQL to MYSQL 

### ISSUE THREAD

**Issue by shahrukhebiztrait** [tediousjs/tedious#976]
Hello Guys, 

We have implemented the whole project in nodejs using tedious-connection-pool with MSSQL database, Now we want to change the database to MySql due to the AWS cost, so tedious provide MySql support? , do have any east way to migrate MSQL to MySql, please suggest here, is very useful for me. Thank You!

**Comment by arthurschreiber** [comment]
👋 Hey there!

`tedious` does not provide MySQL support, and I doubt it ever will - MySQL and MSSQL are just too different for that to make sense. There are other libraries built on top of `tedious` (e.g. `sequelize`) that provide a generic API across different database systems and try to hide away differences between MySQL and MSSQL, but I've never performed such a database migration and thus can't really give any useful tips. 😞 

I wish best of luck to you and your migration project, and feel free to report back what path and tools you've chosen! 🙇
