### ISSUE TITLE
How to return Key-Value array ? (without metadata )

### ISSUE THREAD

**Issue by glococo** [tediousjs/tedious#978]
Hi,

is there any way to return key-value array instead of sub-object { value:... , metadata: .. }
when using: "rowCollectionOnRequestCompletion" ?

request= new Request("SELECT * FROM my_table", (err,count,rows) => log( rows ) )
sql.execSql( request )

I want rows result to be like this
[ { key:value, key:value },{ key:value, key:value }, ... ]

**Comment by glococo** [comment]
My workaround is

function removeMetaData( arr ) {
  arr.forEach( obj=> Object.keys( obj ).forEach( key=> obj[key] = obj[key].value )  )
  return arr
}
request= new Request("SELECT * FROM my_table", (err,count,rows) => console.log( removeMetaData(rows) ) )
sql.execSql( request )

**Comment by MichaelSun90** [comment]
Hi @glococo 
If you want a key-value pair output, I think this config options will help you:

options.useColumnNames
            A boolean determining whether to return rows as arrays or key-value collections. (default: false).

However, the metadata will still be in the result.

**Comment by IanChokS** [comment]
@glococo Does @MichaelSun90's solution work for you? If not feel free to repoen this issue. Closing it for now.

**Comment by glococo** [comment]
@MichaelSun90 I already using options.useColumnNames= true.

I expect from a SQL connector to return a json format, but in turn I get this with tedious:
 
```
PKIDUSER: { value: 14, metadata: [Object] },
PRIMER: { value: 'TNAMEO                                                                                            ',
      metadata: [Object] },
SEGUNDO: { value: 'QLASTO                           ', metadata: [Object] }
}
```
That's why I still using my workaround.
`arr.forEach( obj=> Object.keys( obj ).forEach( key=> obj[key] = (typeof obj[key].value=='string')?obj[key].value.trim():obj[key].value )  )
`

@IanChokS Why should I need the meta object ? I could be optional, I think. 
Even the blank spaces do not make sense, I end up trimming it.

Cheers

**Comment by IanChokS** [comment]
Hi @glococo, 
Tedious returns column metadata because that is the SQL Server protocol (called TDS) for returning row data:

> Row data MUST be preceded by a description of the column
>names and data types. For more information about how the column names and data types are
>described, see section 2.2.7.4.

Also, from what I am understanding from your question, the `request.on(row, (columns) => {....})` event already returns an array of key-value pairs.

For e.g., if you run the `examples/minimal.js` file, you can see the columns returned is an array of key-value objects:

```
columns:  [
  {
    value: 42,
    metadata: {
      userType: 0,
      flags: 32,
      type: [Object],
      collation: undefined,
      precision: undefined,
      scale: undefined,
      udtInfo: undefined,
      dataLength: undefined,
      schema: undefined,
      colName: '',
      tableName: undefined,
      cryptoMetadata: undefined
    }
  },
  {
    value: 'hello world',
    metadata: {
      userType: 0,
      flags: 32,
      type: [Object],
      collation: [Object],
      precision: undefined,
      scale: undefined,
      udtInfo: undefined,
      dataLength: 11,
      schema: undefined,
      colName: '',
      tableName: undefined,
      cryptoMetadata: undefined
    }
  }
]
```

**Comment by noid2** [comment]
Applying  map-reduce function in returned rows:

```
rows.map(r=>{
      return r.reduce((a,k)=>{
        a[k.metadata.colName]=k.value
        return a
      }
      ,{})
    })
```
