### ISSUE TITLE
Documentation inaccurate for `trustServerCertificate` config value

### ISSUE THREAD

**Issue by FSQuaratiello** [tediousjs/tedious#983]
In the [documentation for `Connection` objects](http://tediousjs.github.io/tedious/api-connection.html#function_newConnection), it states that the default value of the `trustServerCertificate` option is `false`. 

However, [in the actual code](https://github.com/tediousjs/tedious/blob/master/src/connection.js#L245), it appears that this value defaults to `true`. Is there a reason for this inconsistency? The security implications (by default, connections will skip certificate verification, while users of Tedious will be entirely justified in believing that certificate verification is taking place) seem rather significant.

**Comment by IanChokS** [comment]
Hi @FSQuaratiello, thanks for raising this issue! For now I've updated the docs to show that `trustServerCertificate = true` to better reflect the actual default value in Tedious. We will take a deeper look into this issue with possible changes coming soon.
